### ISSUE TITLE
Token contstructor required

### ISSUE THREAD

**Issue by orloffv** [irazasyed/telegram-bot-sdk#1]
public function __construct($token, $async = false, $http_client_handler = null)
$this->accessToken = isset($token) ? $token : getenv(static::BOT_TOKEN_ENV_NAME);

maybe use 
public function __construct($token = null, $async = false, $http_client_handler = null)?

**Comment by irazasyed** [comment]
Thanks for pointing out. Seems like i missed that. Pushing changes now :+1:

**Comment by irazasyed** [comment]
Pushed a patch release - [v0.2.1](https://github.com/irazasyed/telegram-bot-sdk/releases/tag/v0.2.1) and credited!
