### ISSUE TITLE
getMe() returns an empty array

### ISSUE THREAD

**Issue by TheReverend403** [irazasyed/telegram-bot-sdk#100]
Simple enough, using `$this->getTelegram()->getMe()->getId()` in a class extending `Command` produces an empty array.

**Comment by irazasyed** [comment]
That's weird. Can you tell me what version of the library you're using and do you have Async requests turned ON?

**Comment by TheReverend403** [comment]
2.0.0, and yes, I do. I'll try it without and report back.

**Comment by irazasyed** [comment]
That's the problem. Since it's an async request, it makes the call but doesn't wait for the response. What you could do is, `$this->telegram()->setAsyncRequest(false);` before making that request.

**Comment by irazasyed** [comment]
Refer: https://irazasyed.github.io/telegram-bot-sdk/usage/async/
