### ISSUE TITLE
How to send "Playable" video?

### ISSUE THREAD

**Issue by secretwebmaster** [irazasyed/telegram-bot-sdk#1005]
I am using to sendVideo method to send video. The message is successfully sent out but the video seems sending out as document instead of a playable video.  It shows a blank square. When you clicked on the square, it downloads the mp4 file.

My aim is to send out a video that user could play in telegram without downloading.

Here is my code in Controller:
```
 $response = $this->telegram->sendVideo([
     'chat_id' => $chat_id, 
     'video'=> InputFile::create("https://mydomain/myvideo.mp4", 'test.mp4'),
     'width'=>600,
      'height'=>400,
]);
```

Please advise. Thank you

**Comment by ILabiak** [comment]
You have to set supports_streaming option to true. Docs: https://core.telegram.org/bots/api#sendvideo
