### ISSUE TITLE
telegram bot delete group message don't working

### ISSUE THREAD

**Issue by phpmac** [irazasyed/telegram-bot-sdk#1006]
Has anyone encountered the same problem as me? The return was successful. How to solve it without deleting?

**Comment by alies-dev** [comment]
@phpmac 
1) can you pls share a code snippet you used?
2) package version

**Comment by phpmac** [comment]
> @phpmac
> 
> 1. can you pls share a code snippet you used?
> 2. package version

```
        Telegram::deleteMessage([
            'chat_id' => $chat_id,
            'message_id' => $message_ids,
        ]);

```
Thank you very much for your reply.

**Comment by alies-dev** [comment]
@phpmac

```php
Telegram::deleteMessage([
    'chat_id' => $chat_id,
    'message_id' => $message_ids,
]);
```
`message_id` should be an integer, based on `$message_ids` var name, I assume this is an array of IDs (what is wrong), see https://core.telegram.org/bots/api#deletemessage (where you can read other constraints of this method)

**Comment by phpmac** [comment]
it's works,It's my problem.sorry,Thank you for your reply and everyone's efforts for my question.
