### ISSUE TITLE
BUG | HELP

### ISSUE THREAD

**Issue by ShoteeDevs** [irazasyed/telegram-bot-sdk#1008]
![Screenshot_20220912-092957_Termux](https://user-images.githubusercontent.com/113356314/189654442-1617618f-cf83-461b-850c-17a6534757bf.jpg)

Any solution?

**Comment by alies-dev** [comment]
this is depreciation notice, it's not a bug, it doesn't affect how application works. You are free to ignore it or update Laravel version ;)

**Comment by ShoteeDevs** [comment]
> este é um aviso de depreciação, não é um bug, não afeta o funcionamento do aplicativo. Você é livre para ignorá-lo ou atualizar a versão do Laravel ;)

actually i had installed "composer require irazasyed/telegram-bot-sdk ^2.0" so this happened...

**Comment by alies-dev** [comment]
telegram-bot-sdk is outdated version:
<img width="446" alt="image" src="https://user-images.githubusercontent.com/5278175/189664727-8e53dc95-b415-4aea-8cb8-335498ab88a5.png">

it's ok to have deprecations for outdated ones
