### ISSUE TITLE
How to use the method replyWithMessage in a webhook?

### ISSUE THREAD

**Issue by IggorGor** [irazasyed/telegram-bot-sdk#1009]
Hi!

I'm trying to use the replyWithMessage method in my controller, which is used as a webhook. To do this, I added the Answerable trait to the class. But when I try to execute this method, I get an error.

```
class TgBotController extends Controller
{
    use Answerable;

    public function index(Request $request)
    {
        $update = Telegram::commandsHandler(true);
        
        // some code
        
        $this->replyWithMessage([
                    'text' => 'some_text',
        ]);
```

[replyWithMessage] does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method [replyWithMessage] does not exist. at /var/www/some/path/vendor/irazasyed/telegram-bot-sdk/src/Answers/Answerable.php:48)

Tell me, what am I doing wrong? As I understand it, I can respond directly to a request from a webhook

**Comment by YSRoot** [comment]
class TgBotController extends Controller
{
    use Answerable;

    public function index(Request $request)
    {
        $tg = Telegram::bot('your_bot');
        $update = $tg->commandsHandler(true);
        
        $this->setTelegram($tg);
        
        // some code
        
        $this->replyWithMessage([
                    'text' => 'some_text',
        ]);

**Comment by IggorGor** [comment]
Thanks, it works!

**Comment by RaptorialThing** [comment]
for 3 version of telegram-bot-sdk (compitable with Laravel 8) u can use 

class TgController extends Controller
{
   
    use Telegram\Bot\Answers\Answerable;

    public function index(Request $request)
    {
        $update = Telegram::commandsHandler(true); 
    }
}

and 

  $this->replyWithMessage([
                'text' => 'some_text',
    ]);

inside app/Telegram/Commands
for /start app/Telegram/Commands/StartCommand

routes/web
Route::post("/webhook", [\App\Http\Controllers\TgController::class,'index']);
