### ISSUE TITLE
Laravel 5.2 update?

### ISSUE THREAD

**Issue by vadimwe** [irazasyed/telegram-bot-sdk#101]
Problem 1
    - Conclusion: remove laravel/framework v5.2.6
    - Conclusion: don't install laravel/framework v5.2.6
    - Conclusion: don't install laravel/framework v5.2.5
    - Conclusion: don't install laravel/framework v5.2.4
    - Conclusion: don't install laravel/framework v5.2.3
    - Installation request for irazasyed/telegram-bot-sdk ^1.0 -> satisfiable by irazasyed/telegram-bot-sdk[v1.0.0].
    - Conclusion: don't install laravel/framework v5.2.2
    - Conclusion: don't install laravel/framework v5.2.1
    - irazasyed/telegram-bot-sdk v1.0.0 requires illuminate/support 5.0.*|5.1.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.2.0
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.2.0
..........

**Comment by irazasyed** [comment]
Master branch already supports Laravel 5.2. It's pending for release as there has been some major changes due to the latest multi bot support feature.

You could either use the master branch using `3.0.*@dev` or wait for the release.

**Comment by rainbowhat** [comment]
How do i go about installing this?
