### ISSUE TITLE
Telegram\Bot\Api::revokeChatInviteLink(): Return value must be of type

### ISSUE THREAD

**Issue by agoukuaile** [irazasyed/telegram-bot-sdk#1012]
- `irazasyed/telegram-bot-sdk` version: ^3.9
- PHP Version: 8.0
- Laravel Version: 9.19

## Description:

Telegram\Bot\Api::revokeChatInviteLink(): Return value must be of type Telegram\Bot\Objects\ChatInviteLink, array returned {"exception":"[object] (TypeError(code: 0): Telegram\\Bot\\Api::revokeChatInviteLink(): Return value must be of type Telegram\\Bot\\Objects\\ChatInviteLink, array returned at /www/vendor/irazasyed/telegram-bot-sdk/src/Methods/Chat.php:189)

**Comment by alies-dev** [comment]
@agoukuaile 
this issue is [fixed](https://github.com/irazasyed/telegram-bot-sdk/commit/e3219f31b6da983b0d9050cf313ee65d835faf95) on the develop branch but still not released yet.

@irazasyed can we tag a new release please?
