### ISSUE TITLE
[request] https://core.telegram.org/method/messages.sendReaction

### ISSUE THREAD

**Issue by am0nshi** [irazasyed/telegram-bot-sdk#1013]
- `irazasyed/telegram-bot-sdk` version: 3.9.0
- PHP Version: 7.4.0
- Laravel Version: 8.83.25 (optional)

## Description:
There is new functionality in telegram with "reactions". Please see details in link https://core.telegram.org/method/messages.sendReaction

### Stacktrace:
```
N/A
```

## Steps To Reproduce:
Feature request

**Comment by alies-dev** [comment]
@am0nshi 
thanks for the request!

Unfortunately, Bots API doesn't have an access to reactions, the link you shared is API to Telegram clients (not bots).
