### ISSUE TITLE
message_thread_id in sendMessage

### ISSUE THREAD

**Issue by nozzy177** [irazasyed/telegram-bot-sdk#1018]
Telegram update adds topics to organize discussions in large groups. So that the bot can send a message to the topics, the sendMessage method must contain the parameter - message_thread_id. Can I do it now with your library?

**Comment by jonnywilliamson** [comment]
I'll look into this.

**Comment by vdkar** [comment]
I really need this update (read data from telegram api). Since the bot uses this opportunity to notify residents about the presence of light in the house in Ukriane.
