### ISSUE TITLE
Retrieve other information using webhook and command

### ISSUE THREAD

**Issue by alberto-bottarini** [irazasyed/telegram-bot-sdk#102]
Maybe I missed something, but how can I get some other infos (e.g. chat_id) inside my handle method? I have access only to text.

I need to save chat_id on the db to later respond to that chat.

Telegram send to webhook something similar to this:

    array (
      'update_id' => xxxxxxxxxxx,
      'message' => 
      array (
        'message_id' => xxxxxxxxxxx,
        'from' => 
        array (
          'id' => xxxxxxxxxxx,
          'first_name' => 'aaaaaaaaaaa',
          'username' => 'bbbbbbbbb',
        ),
        'chat' => 
        array (
          'id' => xxxxxxxxxxx,
          'first_name' => 'aaaaaaaaaa',
          'username' => 'bbbbbbbbbb',
          'type' => 'private',
        ),
        'date' => 1452166375,
        'text' => '/myCommand',
      ),
    )

why did you hide all information but text for command?

btw: great job, man! :+1:

**Comment by irazasyed** [comment]
Hey!

Commands have access to the updates object, You just need to call `$this->getUpdate()` and you'll get the original Update object.

So for example, You want to access chat id, you'd do something like this:
```php
$chat_id = $this->getUpdate()->getMessage()->getChat()->getId();
```

Thanks!
