### ISSUE TITLE
Command from different bots are merged

### ISSUE THREAD

**Issue by lebalex** [irazasyed/telegram-bot-sdk#1023]
- `irazasyed/telegram-bot-sdk` version: 3.9
- PHP Version: 7.4.20
- Laravel Version: #.#.# (optional)

## Description:
telegram.php
'bots'                         => [
        'supportBot' => [
                        'username'  => 'bot1_bot',
                        'token' => 'api1',
'commands'            => [
                            App\TelegramCommands\ECommand::class,
                            App\TelegramCommands\MeteoCommand::class
                        ],
                    ],
        'testBot' => [
                        'username'  => 'bot2_bot',
                        'token' => 'api2',
                        'commands'            => [
                            App\TelegramCommands\StartCommand::class,
                            App\TelegramCommands\HelpCommand::class,
                        ],
                    ],
]
....

Telegram::bot('testBot')->getCommands() retrun all 4 commands
Telegram::bot('supportBot')->getCommands() retrun all 4 commands

written a command in a telegram (in any of the two), I still get into the class.
### Stacktrace:
```
```

**Comment by alies-dev** [comment]
thanks @lebalex 
it looks like a serious bug. If you just created a project, I would recommend you to use [SDK v4](https://github.com/telegram-bot-sdk/telegram-bot-sdk) -- it has better maintenance

**Comment by irazasyed** [comment]
This is resolved in 3.x branch (will be merged/released soon).
