### ISSUE TITLE
Any examples of usage?

### ISSUE THREAD

**Issue by Aido21** [irazasyed/telegram-bot-sdk#1032]
Hi
it could be very useful for newbies

Regards

**Comment by towoju5** [comment]
it's available on the documentation
@Aido21 You should check it here [Documentation](https://telegram-bot-sdk.readme.io/docs/getting-started)

**Comment by Aido21** [comment]
I'm afraid I have to disagree.
The documentation is outdated and does not have sufficient examples IMHO

**Comment by towoju5** [comment]
You can offer them a hand in updating the docs. That's why it's an open source project I used the same documentation to setup a project yesterday and everything went well.
