### ISSUE TITLE
Upgrade laravel 10 conflict

### ISSUE THREAD

**Issue by PerawatNgoding** [irazasyed/telegram-bot-sdk#1036]
I have try to upgrade my project to laravel 10, but i got error on this package with text require illuminate support 5.8 - 9, i see on this package update is 5.8 - 10 for laravel 10 compability, but its not working.

**Comment by alfiosalanitri** [comment]
Set the version dev-develop in your composer and update.

**Comment by el3wdy** [comment]
> Set the version dev-develop in your composer and update.

i have same problem.

**Comment by el3wdy** [comment]
composer require "irazasyed/telegram-bot-sdk dev-develop"

OR 

    "require": {
        "irazasyed/telegram-bot-sdk": "dev-develop",
    },

**Comment by PerawatNgoding** [comment]
> Set the version dev-develop in your composer and update.

Thank. I solve my issue
`"require": {
    "irazasyed/telegram-bot-sdk": "dev-develop",
},`
