### ISSUE TITLE
Not installed in Laravel 10.1.5

### ISSUE THREAD

**Issue by IggorGor** [irazasyed/telegram-bot-sdk#1037]
- `irazasyed/telegram-bot-sdk` version: 3.9
- PHP Version: 8.1.9
- Laravel Version: 10.1.5 (optional)

## Description:
Hello!

I am installing the telegram-bot-sdk library in Laravel 10.1.5 I'm giving the command:
**composer require irazasyed/telegram-bot-sdk**

I get an error in response:
 _- irazasyed/telegram-bot-sdk v3.9 requires illuminate/support 5.8 - 9 -> found illuminate/support[v5.8.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., 
v9.52.4] but these were not loaded, likely because it conflicts with another require._

Is there any way I can solve this problem?

**Comment by alfiosalanitri** [comment]
[see here](https://github.com/irazasyed/telegram-bot-sdk/issues/1036#issuecomment-1449565333)

**Comment by IggorGor** [comment]
Thanks!

**Comment by ariaieboy** [comment]
@irazasyed can you please tag the recent changes so we can update the package without needing to set the version to `dev-develop`?

**Comment by irazasyed** [comment]
I'm working on `3.x` branch which includes not only Laravel 10 support but several other upgrades/bugfixes applied.

You guys can join the discussion [here](https://github.com/irazasyed/telegram-bot-sdk/discussions/1041) and vote (PHP min. 8 and Laravel 9-10 support).

You're welcome to test and share your feedback. I'll only be able to tag a release once we have some feedback from the community regarding the issues you're facing when trying to upgrade your existing project and if it's stable enough to tag.
