### ISSUE TITLE
Markdown suport

### ISSUE THREAD

**Issue by Alvaroctal** [irazasyed/telegram-bot-sdk#104]
Hi, maybe I haven't seen it, but as far as I have read the code & docs, there is not a method to set the _parse mode_ for example as Markdown, of a Message with [sendMessage](https://core.telegram.org/bots/api#sendmessage).

I have tried `$telegram->sendMessage($group, $message, 'Markdown');` unsuccessfully. But with: 
`https://api.telegram.org/botTOKEN-GOES-HERE/sendMessage?chat_id=CHAT-GOES-HERE&text=*hola*%20_potato_%20[link](https://google.com)&parse_mode=Markdown` works fine.

**Comment by irazasyed** [comment]
Hi, `sendMessage` accepts an array of params. So you need to build the params array and pass it to the method, it'll work.

**Comment by Alvaroctal** [comment]
Ooookay, my version was a bit old and didn't worked with arrays, thank you so much.

**Comment by irazasyed** [comment]
No problem!
