### ISSUE TITLE
laravel 10.0 composer requires irazasyed/telegram-bot-sdk ^3.9.0

### ISSUE THREAD

**Issue by Duch-Nuon** [irazasyed/telegram-bot-sdk#1043]
Problem 1
    - Root composer.json requires irazasyed/telegram-bot-sdk ^3.9.0 -> satisfiable by irazasyed/telegram-bot-sdk[v3.9].
    - irazasyed/telegram-bot-sdk v3.9 requires illuminate/support 5.8 - 9 -> found illuminate/support[v5.8.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.

**Comment by amkatyshev** [comment]
+1

**Comment by nekooee** [comment]
please update your package for Laravel 10
 irazasyed/telegram-bot-sdk[v2.0.0, ..., v2.3.0] require guzzlehttp/guzzle ~6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.8] but it conflicts with your root composer.json require (^7.5).

**Comment by victor-ponamariov** [comment]
+1

**Comment by illiamorkva** [comment]
+1

**Comment by irazasyed** [comment]
Someone with an active project can please try this branch and let me know the issues you're facing or not.

https://github.com/irazasyed/telegram-bot-sdk/tree/3.x

This is compatible with Laravel 10 but also has some underlying dependency packages upgraded due to which there are breaking changes. Need to confirm before I tag a release.

**Comment by ivatutin** [comment]
Laravel Framework 10.4.1

 composer require irazasyed/telegram-bot-sdk ^3.9

  Problem 1
    - Root composer.json requires irazasyed/telegram-bot-sdk ^3.9 -> satisfiable by irazasyed/telegram-bot-sdk[v3.9].
    - irazasyed/telegram-bot-sdk v3.9 requires illuminate/support 5.8 - 9 -> found illuminate/support[v5.8.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.

**Comment by seaklong** [comment]
how to configuration and intergrate telegram-bot-sdk + laravel ?

**Comment by donnyxray** [comment]
Current Laravel Passport requires  "league/oauth2-server": "^8.2", which requires "league/event": "^2.2", which conflicts with telegram-bot-sdk requirement "league/event": "^3.0".

**Comment by irazasyed** [comment]
@donnyxray It's pending merge here: https://github.com/thephpleague/oauth2-server/pull/1308

Maybe request them to merge and tag a release?

Edit: I commented. Maybe show support and upvote there :)

Looks like this is going to be a roadblocker to tag this release.

**Comment by donnyxray** [comment]
Voted.

Note that dev-develop did work for me in Laravel 10, prior to the last commit. Any chance you could tag a prior commit as an intermediate release?

**Comment by irazasyed** [comment]
Released [3.9.1](https://github.com/irazasyed/telegram-bot-sdk/releases/tag/v3.9.1).

3.10 will be on hold for now. Please create a new issue ticket if you face any issues with the latest release.

**Comment by irazasyed** [comment]
[3.10](https://github.com/irazasyed/telegram-bot-sdk/releases/tag/v3.10.0) Released. 

Ended up creating a bunch of polyfill/bridges to make League Event 2 and 3 compatible. 

We'll drop version 2 completely in the next major release.
