### ISSUE TITLE
Suggestion: Add an optional alias array to allow triggers other than the command's name.

### ISSUE THREAD

**Issue by TheReverend403** [irazasyed/telegram-bot-sdk#105]

**Comment by irazasyed** [comment]
Can you elaborate with maybe an example?

**Comment by TheReverend403** [comment]
I'm thinking like...

````
<?php
class EchoCommand extends BaseCommand
{
    protected $description = 'Whatever.';
    protected $name = 'echo';
    protected $aliases = ['test', 'ayy'];

    public function handle($arguments)
    {
        $this->reply('Ayy lmao!');
    }
}
````

And then any of /echo, /test or /ayy will trigger this command.

**Comment by irazasyed** [comment]
Oh okay, Good idea. I'll look into this and implement. Thanks for the suggestion :+1:

**Comment by jonnywilliamson** [comment]
What should happen if an alias matches another "normal" command?

**Comment by TheReverend403** [comment]
I assume the same thing that happens if you try to have two commands with the same name.

**Comment by filipekiss** [comment]
@jonnywilliamson @TheReverend403 I guess we could always try to check for command names first and aliases later. So command names would always take precedence over an alias. This would be very useful. Today I extend the command class as a new command to create an alias. Has anyone made anything regarding this? I'll have a few hours free today, maybe I can take a look at this.

**Comment by irazasyed** [comment]
Added. Will be released in V3 :)

**Comment by zvermafia** [comment]
@irazasyed It would be good if you will add the aliases without the prefix slash too, like below:
```
/new
/n
new
n
```
It's comfy when you work with the custom keyboard and you won't to write text on button like a "/new" instead of "New"...
