### ISSUE TITLE
getting wrong response frpm webhook: 404 not found

### ISSUE THREAD

**Issue by tayyabbashir2224** [irazasyed/telegram-bot-sdk#1059]
### PHP version

5.7

### irazasyed/telegram-bot-sdk version

v3.4.1

### Laravel version (if any)

v8.83.27

### Code To Reproduce the bug

i am getting this error by following the tutorial 
[https://www.xibel-it.eu/setup-telegram-bot-sdk-with-webhook-in-laravel/](url)

{"ok":true,"result":{"url":"https://mybbpk.altervista.org/Nmlpzus6R5EnEO9dPiCQ/webhook","has_custom_certificate":false,"pending_update_count":6,"last_error_date":1681231273,"last_error_message":"Wrong response from the webhook: 404 Not Found","max_connections":40,"ip_address":"172.67.212.132"}}

**Comment by irazasyed** [comment]
Read the error. It says 404 not found. There's a problem with your endpoint.
