### ISSUE TITLE
guzzlehttp/guzzle version

### ISSUE THREAD

**Issue by wking0702** [irazasyed/telegram-bot-sdk#1065]
Drupal 10 has the guzzlehttp/guzzle version ~7.5.0 dependency.
And your library depends on guzzlehttp/guzzle version ^7.4.5...

 
Is it possible to change this dependency?

**Comment by irazasyed** [comment]
What is the issue? That's the minimum version package requires.

**Comment by wking0702** [comment]
Yes, everything is correct. Sorry.
