### ISSUE TITLE
Inline Keyboard web_app

### ISSUE THREAD

**Issue by HydraCoderX** [irazasyed/telegram-bot-sdk#1069]
Hi, 
didnt find anywhere anything about it. But is it possible to open the inapp browser with an inline button?

->row([Keyboard::inlineButton(['text' => 'Book Ads', 'web_app' => 'https://url.com'])]

like this? with the "web_app"  or did i muss something?

Greetings

**Comment by mes01** [comment]
> Hi, didnt find anywhere anything about it. But is it possible to open the inapp browser with an inline button?
> 
> ->row([Keyboard::inlineButton(['text' => 'Book Ads', 'web_app' => 'https://url.com'])]
> 
> like this? with the "web_app" or did i muss something?
> 
> Greetings

```
$inlineLayout = [
    [
        Keyboard::inlineButton([
            'text' => 'Test',
            'web_app' => [
                'url' => 'https://test.ru'
            ]
        ]),
    ]
];

$keyboard = Keyboard::make([
    'inline_keyboard' => $inlineLayout
]);

$this->replyWithMessage([
    'text' => "Text",
    'reply_markup' => $keyboard
]);
```

**Comment by irazasyed** [comment]
```php
$reply_markup = Keyboard::make()
				->inline()
				->row([
					Keyboard::inlineButton([
                        'text' => 'Test',
                        'web_app' => [
                            'url' => 'https://google.com'
                        ]
                    ])
				]);
```
