### ISSUE TITLE
How to implement 'ask', 'secret', 'choice' commands?

### ISSUE THREAD

**Issue by mahefooz** [irazasyed/telegram-bot-sdk#107]
The command example given in documentation is related to replywithMessage, but how to implement question and answer session with bot user?

**Comment by filipekiss** [comment]
As mentioned in issue #90, to actually keep the user inside an specific flow you'll have to record in which step of your flow the user is and handle it on you application. This is not a problem with the SDK nor the Telegram API. This is just something that need to be done on your application rather than as a library feature (at least for now. If telegram changes how they handle message flow this might become available in the future).

**Comment by mahefooz** [comment]
Got your point. We are planning to build something like botfather..where
bot asks a series of questions and user will answer them, then bot get the
things done. Just wondering which feature or module of laravel can help us
achieve this?

**Comment by filipekiss** [comment]
@mahefooz I have a bot that does this. I have a table on a sqlite database that I use to control where the user is. So when the user sends the first message, I create or update a record with the user ID and the next step on the flow base on his message. When I receive another message, I check if that user was in the middle of a series of questions or something and then I use the proper controller/method to handle his response. If there's another step, I update the record with the user id and the new step information. If the user is done, I delete the flow information, so the user is ready to start from the beginning again.

**Comment by mahefooz** [comment]
@filipekiss thanks for the guidance. I think this can be achieved using webhook and laravel controllers, then what is the use of commands feature available in this SDK?

**Comment by filipekiss** [comment]
@mahefooz It's a simpler way to set-up commands so you don't have to parse every message, the SDK will do it for you. :)

**Comment by filipekiss** [comment]
@mahefooz It's a simpler way to set-up commands so you don't have to parse every message, the SDK will do it for you. :)

**Comment by irazasyed** [comment]
What @filipekiss said.
