### ISSUE TITLE
Command is not triggered

### ISSUE THREAD

**Issue by ZnarKhalil** [irazasyed/telegram-bot-sdk#1073]
### PHP version

8.1

### irazasyed/telegram-bot-sdk version

3.11

### Laravel version (if any)

9

### Code To Reproduce the bug

I have set my bot in the config file and registered my start command in the commands section of the bot as the following:
`'mybot' => [
            'username' => env('TELEGRAM_BOT_NAME', 'YOUR_BOT_NAME'),
            'token' => env('TELEGRAM_BOT_TOKEN', 'YOUR-BOT-TOKEN'),
            'certificate_path' => env('TELEGRAM_CERTIFICATE_PATH', 'YOUR-CERTIFICATE-PATH'),
            'webhook_url' => env('TELEGRAM_WEBHOOK_URL', 'YOUR-BOT-WEBHOOK-URL'),
            'commands' => [
//                Acme\Project\Commands\MyTelegramBot\BotCommand::class
                App\Telegram\Commands\StartCommand::class,
            ],
        ],`

Webhook is added to telegram and to the $except array in laravel VerifyCsrfToken middleware, the webhook is working fine but the command is not triggered.
in the webhook handler function i have set an info function to print a message to the laravel log to check if the webhook is working or not and message is logged.

the commandHanlder function is right after the info logging function and yet nothing happend
`$update = Telegram::commandsHandler(true);`

StartCommand:

`  /**
     * @var string Command Name
     */
    protected string $name = 'start';

    /**
     * @var array Command Aliases
     */
    protected array $aliases = ['listcommands'];

    /**
     * @var string Command Description
     */
    protected string $description = 'Start command, Get a list of all commands';

    /**
     * {@inheritdoc}
     */
    public function handle()
    {
        $response = $this->getUpdate();

        $chId = $response['message']['chat']['id'];
        $btn = Telegram\Bot\Keyboard\Keyboard::button([
            'text' => 'Share my phone number',
            'request_contact' => true,
        ]);
        $keyboard = Telegram\Bot\Keyboard\Keyboard::make([
            'keyboard' => [[$btn]],
            'resize_keyboard' => true,
            'one_time_keyboard' => true,
        ]);

        $this->replyWithMessage(['chat_id' => $chId, 'text' => 'We need your phone number for authentication, please press share my phone number', 'reply_markup' => $keyboard]);
    }`

is there any steps i didn't follow?

**Comment by irazasyed** [comment]
You can drop the `chat_id` when using `replyWith*` methods. Debug this by disabling everything and responding with a simple text message and then see what happens.

**Comment by ZnarKhalil** [comment]
Ok, Will try that. but I forgot to mention that the command was working fine before updating to the latest version
