### ISSUE TITLE
Silent breaking change in v3.12

### ISSUE THREAD

**Issue by ariaieboy** [irazasyed/telegram-bot-sdk#1076]
### PHP version

8.2

### irazasyed/telegram-bot-sdk version

3.12

### Laravel version (if any)

10

### Code To Reproduce the bug

In the latest version of the SDK, the base_bot_url const has been changed from `https://api.telegram.org/bot` to `https://api.telegram.org`, and that breaks the applications that use a custom URL as the base bot URL.
The document itself is not updated too.
https://telegram-bot-sdk.com/docs/getting-started/configuration#base-bot-url 
My problem was fixed by removing the `/bot` from my custom base bot URL.

**Comment by irazasyed** [comment]
Thanks for the report. Can you try the latest commit 8a36eef0f9f508977ac0076937f126dd7e761628 and let me know if it works fine for you?

**Comment by ariaieboy** [comment]
> Thanks for the report. Can you try the latest commit [8a36eef](https://github.com/irazasyed/telegram-bot-sdk/commit/8a36eef0f9f508977ac0076937f126dd7e761628) and let me know if it works fine for you?

The API works fine, but the file downloader has a problem.
I've commented on the code here :
https://github.com/irazasyed/telegram-bot-sdk/commit/8a36eef0f9f508977ac0076937f126dd7e761628#r115397195

**Comment by irazasyed** [comment]
I pushed a new commit: https://github.com/irazasyed/telegram-bot-sdk/commit/31a71aef80fd328bfe0084738cc3b51cc49867f4

**Comment by ariaieboy** [comment]
> I pushed a new commit: [31a71ae](https://github.com/irazasyed/telegram-bot-sdk/commit/31a71aef80fd328bfe0084738cc3b51cc49867f4)

This commit works for me just fine.
can you please tag these changes so I can update my projects according to it?

**Comment by irazasyed** [comment]
Done https://github.com/irazasyed/telegram-bot-sdk/releases/tag/v3.13.0
