### ISSUE TITLE
baseBotUrl

### ISSUE THREAD

**Issue by LipeApp** [irazasyed/telegram-bot-sdk#1077]
### PHP version

8.1

### irazasyed/telegram-bot-sdk version

3.13

### Laravel version (if any)

9

### Code To Reproduce the bug

Я использовал свой телеграм басе урл
Мой басе урл https://my.domen.uz/bot выглядело так.
Что теперь, вы добавили функцию который с урл убирает **/bot**  
Почему?

**Comment by irazasyed** [comment]
That is only for file URL. Not for the API endpoints.
