### ISSUE TITLE
TelegramSDKException in GuzzleHttpClient.php line 114:

### ISSUE THREAD

**Issue by realreef** [irazasyed/telegram-bot-sdk#108]
i try with simple code: 

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Telegram;

class TelegramController extends Controller {
      public function postSendMessage(){
    	       $response = Telegram::getMe();

		$botId = $response->getId();
		$firstName = $response->getFirstName();
		$username = $response->getUsername();
		return $response;
       }
}

after i hit this function, gets response : 

TelegramSDKException in GuzzleHttpClient.php line 114:
cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

help for solutions.thx

**Comment by irazasyed** [comment]
You seem to have a problem with your self-signed certificate. You need to upload a proper certificate, have a proper setup of HTTPS for your webhook.

**Comment by hellosaeedalizadeh** [comment]
it is not possible to disable HTTPS for webhook ?

thanks before

**Comment by irazasyed** [comment]
No. It's a strict requirement from Telegram end.

**Comment by hellosaeedalizadeh** [comment]
thank you :)

**Comment by irazasyed** [comment]
@hellosaeedalizadeh You're welcome :)

**Comment by Benyaminrmb** [comment]
so . . . if my website have "https" when we can use it ?
else -> i can`t   . is it not it ?
