### ISSUE TITLE
Empty Message object return on some files

### ISSUE THREAD

**Issue by foremtehan** [irazasyed/telegram-bot-sdk#1082]
### PHP version

8.1

### irazasyed/telegram-bot-sdk version

3

### Laravel version (if any)

10

### Code To Reproduce the bug

1. Download this file (it contain one subtitle file in it)
[example.zip](https://github.com/irazasyed/telegram-bot-sdk/files/11714315/example.zip)

2. unzip it with php: **(its important to unzip it with php)**

```php
$zip= new \ZipArchive();
$zip->open('example.zip');
$zip->extractTo('.');
```

3. Then send it:

```php
$response =  Telegram::sendDocument([
    'chat_id' => CHAT_ID,
    'document' => InputFile::create("The Other Two S02E08 - Pat Gets an Offer to Host \"Tic Tac Toe\".srt")
]);

//$response is an empty Message object!
```

I contacted the Telegram Bot API developer and they said that the request didn't even took place...

**Problem:**

The PHP unzip class extracts and renames the special characters in the filename to another valid character, Which is double quotations in this case. However, the character will still be converted to a double quotation mark, so you have to use quotation marks as I did in the example above.

It should throw an exception, but it silently returns an empty object.

**Comment by irazasyed** [comment]
You could use single quotes? Pre-process to a valid filename supported by Telegram? Not sure what the SDK could do here.
