### ISSUE TITLE
Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\Promise\unwrap()

### ISSUE THREAD

**Issue by Maatify** [irazasyed/telegram-bot-sdk#1086]
### PHP version

8.0 or later

### irazasyed/telegram-bot-sdk version

^3.9

### Code To Reproduce the bug

Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\Promise\unwrap() in vendor\irazasyed\telegram-bot-sdk\src\HttpClients\GuzzleHttpClient.php:50
Stack trace:
#0 [internal function]: Telegram\Bot\HttpClients\GuzzleHttpClient-&gt;__destruct()
#1 {main}
  thrown in 
vendor\irazasyed\telegram-bot-sdk\src\HttpClients\GuzzleHttpClient.php on line 50

### Error stacktrace (if any)

Please Remove __destruct() method 
from 
src\HttpClients\GuzzleHttpClient.php on line 50

**Comment by ershad7** [comment]
+1

**Comment by hellodit** [comment]
hi @irazasyed this bug is not fixed, please fix it. the MR already requested

**Comment by gntlby** [comment]
Hi,
@irazasyed please fix..

**Comment by hakhagmon** [comment]
hot fix

open 
vendor/irazasyed/telegram-bot-sdk/src/HttpClients/GuzzleHttpClient.php

change 
```
   public function __destruct()
    {
        Promise\unwrap (self::$promises);
    }
```

to

```
   public function __destruct()
    {
        Promise\Utils::unwrap (self::$promises);
    }
```

**Comment by dario86** [comment]
> hot fix
> 
> open vendor/irazasyed/telegram-bot-sdk/src/HttpClients/GuzzleHttpClient.php
> 
> change
> 
> ```
>    public function __destruct()
>     {
>         Promise\unwrap (self::$promises);
>     }
> ```
> 
> to
> 
> ```
>    public function __destruct()
>     {
>         Promise\Utils::unwrap (self::$promises);
>     }
> ```

I made a pull request some weeks ago
