### ISSUE TITLE
help to create model and migration for getUpdates

### ISSUE THREAD

**Issue by omidpaydar** [irazasyed/telegram-bot-sdk#109]
hi
First of all tank you for bot sdk.
i recently start use from laravel and have not enough skill.
can i request help me to design model , migration and Eloquent for get updates from telegram?
i want updates thad receive from telegram with all field Reduction one model and save this to database and can work with this model for any Decision.
tanks

**Comment by irazasyed** [comment]
Hi,

You have to do that yourself. Refer Laravel Docs and its quite easy to understand and create one.

You could also use Laravel Generator by Jeffry Way.
