### ISSUE TITLE
The Telegram::getWebhookUpdate() result always empty array []

### ISSUE THREAD

**Issue by untillnesss** [irazasyed/telegram-bot-sdk#1097]
### PHP version

PHP 8.2

### irazasyed/telegram-bot-sdk version

versions : * v3.13.0

### Laravel version (if any)

versions : * v10.25.2

### Code To Reproduce the bug

![image](https://github.com/irazasyed/telegram-bot-sdk/assets/33585758/9cfa5ac3-82be-4c70-aeef-efb7f40e258a)

I have code like the one above, namely the code to run the webhook sent by Telegram, but the result is always an empty array.

![image](https://github.com/irazasyed/telegram-bot-sdk/assets/33585758/3617d331-d2bb-483a-be16-a11ae8b2a111)

**I have checked the Telegram Bot token many times, there is nothing wrong, it is correct, and I have installed the webhook URL properly.**

**Comment by Freezon** [comment]
I had the same problem)
Steps to fix:
1. Require psr-7 requests, from src: https://laravel.com/docs/10.x/requests#psr7-requests
2. Pass request, like this: 
```php
public function __invoke(ServerRequestInterface $request)
{
    $update = Telegram::getWebhookUpdate(request: $request);
}
```

**Comment by riettotek** [comment]
doesnt work anyway. even installing psr7 request interface. nothing at all!!!

**Comment by irazasyed** [comment]
Method signature is `getWebhookUpdate(bool $shouldDispatchEvents = true, ?RequestInterface $request = null)`.

Behind the scene it relies on `file_get_contents('php://input')` to retrieve the REQUEST body sent from Telegram, so you need to use this method directly within your webhook where this gets invoked or if you wish to wrap it inside other classes/methods, then pass the PSR7 Request.
