### ISSUE TITLE
Get Channel Group Members

### ISSUE THREAD

**Issue by RVP04** [irazasyed/telegram-bot-sdk#1098]
### PHP version

8.1.3

### irazasyed/telegram-bot-sdk version

v3.13.0

### Laravel version (if any)

 v10.30.0

### Code To Reproduce the bug

When I try to use the getChatMember or getChatMembers I get 

```
Telegram\ Bot\ Exceptions \ TelegramResponseException

Bad Request: invalid user_id specified

```

I am trying with the code

```
$chatId = 'xxxx';
    return \Telegram\Bot\Laravel\Facades\Telegram::getChatMember(['chat_id' => $chatId]);
```

**Comment by HelplessMan** [comment]
In Telegram doc,`user_id` in the method is required
[getchatmember](https://core.telegram.org/bots/api#getchatmember)


```
$chatId = 'xxxx';
$userId = 123
return \Telegram\Bot\Laravel\Facades\Telegram::getChatMember(['chat_id' => $chatId, 'user_id' => $userId]);
```

**Comment by RVP04** [comment]
I want to all the members from the group not to check whether he is a member

**Comment by HelplessMan** [comment]
> I want to all the members from the group not to check whether he is a member

According to my understanding, telegram-bot-sdk cannot directly obtain all users of the group

**Comment by HelplessMan** [comment]
But, you can use this personal account based on the telegram MTProto protocol to achieve the functions you need [getPwrChat](https://docs.madelineproto.xyz/getPwrChat.html)

**Comment by RVP04** [comment]
I am working on laravel application but I don't whether package is available.

**Comment by irazasyed** [comment]
This is not possible with Bot API
