### ISSUE TITLE
Getting message list of a channel

### ISSUE THREAD

**Issue by art-zhitnik** [irazasyed/telegram-bot-sdk#1107]
### PHP version

7.4

### irazasyed/telegram-bot-sdk version

3.9

### Code To Reproduce the bug

None

### Error stacktrace (if any)

Sorry for posting as a bug, but I don't find any way to ask. My case is to parse some open news channel in telegram.

**Comment by art-zhitnik** [comment]
I hope I can do it with a bot, probably using api method https://core.telegram.org/method/messages.getHistory
How can I make api call with your libriry?

**Comment by irazasyed** [comment]
You're looking at Telegram Core API which is different from Bot API. 

You can't retrieve a channel's message unless your bot is added to your channel with appropriate permissions.
