### ISSUE TITLE
"illuminate/support" 11 support

### ISSUE THREAD

**Issue by Pinnokkio** [irazasyed/telegram-bot-sdk#1110]
### PHP version

8.3.2

### irazasyed/telegram-bot-sdk version

3.13

### Laravel version (if any)

11.0

### Code To Reproduce the bug

Install Laravel 11, run `composer require irazasyed/telegram-bot-sdk`

### Error stacktrace (if any)

Please add `Illuminate/support` v11 (Laravel 11) support

**Comment by irazasyed** [comment]
Added
