### ISSUE TITLE
Use as git submodule without composite

### ISSUE THREAD

**Issue by FerX** [irazasyed/telegram-bot-sdk#112]
how can I use as a git submodule without composite?

**Comment by irazasyed** [comment]
Not sure what you're trying to do. Can you please elaborate?

**Comment by jonnywilliamson** [comment]
>A submodule allows you to keep another Git repository in a subdirectory of your repository. The other repository has its own history, which does not interfere with the history of the current repository. This can be used to have external dependencies such as third party libraries for example.

This SDK doesn't use another git repository in it's directory structure! I've no idea what you're doing (or want to do) either!
