### ISSUE TITLE
Bad Request: Can't parse message text: Expected end tag at byte offset xx

### ISSUE THREAD

**Issue by opilo** [irazasyed/telegram-bot-sdk#113]
I keep getting this error:
``Bad Request: Can't parse message text: Expected end tag at byte offset xx``
``Telegram\Bot\Exceptions\TelegramResponseException``
It happens at line 65 of ``irazasyed/telegram-bot-sdk/src/TelegramResponse.php:65``
Is there something wrong with my application or is it from Telegram side.

Thanks

**Comment by ihoru** [comment]
I think, you passed HTML formatting to parse_mode parameter.
And there is a problem in text.
So it's problem of your code.

**Comment by opilo** [comment]
Yes probably, Thank you
