### ISSUE TITLE
How to add "parse_mode" to replyWithMessage?

### ISSUE THREAD

**Issue by kozi** [irazasyed/telegram-bot-sdk#114]
```
$this->replyWithMessage([            
            'text'       => '<pre>MESSAGE</pre>',
            'parse_mode' => 'HTML'
]);
```
does not work!

**Comment by irazasyed** [comment]
You need to use HTML entities.

> All `<`, `>` and `&` symbols that are not a part of a tag or an HTML entity must be replaced with the corresponding HTML entities (`<`with `&lt;`, `>` with `&gt;` and `&` with `&amp;`).

**Comment by ja-heller** [comment]
Any suggestion where things go wrong?
I've used:

                $this->replyWithMessage([
                'text' => "&lt;pre&gt;MESSAGE&lt;/pre&gt; Enjoy your stay!",
                'parse_mode' => 'HTML']);

Output is like: [https://puu.sh/w5rAu/e0ae70fd8f.png](screenshot)
