### ISSUE TITLE
Proxy configs

### ISSUE THREAD

**Issue by wouerner** [irazasyed/telegram-bot-sdk#115]
Hi,

i need to add proxy to acess external api of telegram.

I try put this in guzzle but not have success.

thanks.

**Comment by irazasyed** [comment]
Hi,

As of now it doesn't support such thing by default but it does support `http_client_handler`, So you can create one and implement `Telegram\Bot\HttpClients\HttpClientInterface` interface, then pass it on. It should work then i believe.

I do not have any plans to add such kinda support for now. So you should try the custom http client handler method for such thing or create a PR.

**Comment by jonnywilliamson** [comment]
Try this:

http://stackoverflow.com/a/34760159/659786

**Comment by irazasyed** [comment]
@jonnywilliamson Looks perfect. Thanks for sharing :+1:
