### ISSUE TITLE
Could you please tag your last commit.

### ISSUE THREAD

**Issue by halaei** [irazasyed/telegram-bot-sdk#118]
When the next release is ready?

**Comment by irazasyed** [comment]
It'll take sometime as i plan to implement events system as well as support multi-bot for non-laravel users. There's also inline bot feature pending.

As of now, I don't have any ETA.

**Comment by jonnywilliamson** [comment]
@halaei 

The last [commit ](https://github.com/irazasyed/telegram-bot-sdk/commit/67d1d0169e747741d981c1a3b2c74efbb4e2533f) was only a document change. There was no changes to any of the code.

Therefore you can use the new disable_notification option already in your own code!
