### ISSUE TITLE
Extending CommandBus to handle step-by-step commands

### ISSUE THREAD

**Issue by nMado** [irazasyed/telegram-bot-sdk#119]
It seems that `Telegram\Bot\Api` doesn't support passing a custom `CommandBus`. I need a way to extend `CommandBus` and let `Api` use mine instead of the built-in one.

I will explain the reason why I need to extend the command bus, so maybe you can suggest me a better currently supported approach.

The reason why I want to have a custom command bus, is to let it trigger some commands even when no command is detected.

This approach is to support step-by-step commands, I have a database table that contains the name of the last command name called by the user `users (telegram_uId, telegram_chatId, last_command)`.

Therefore, the new command bus should look into the `users` table, and see if `last_command` is not null, if it's not null, then it'll pass the update to the corresponding command no matter what type the message is (`text`, `photo`, `video` etc.), except if the message `text` matches the command pattern, and the corresponding class should handle the rest from there.

Another approach to support `step-by-step` commands without extending `CommandBus` is by handling the incoming update after it's handled by the Command bus, like:

```php
$update = Telegram::commandsHandler(true);

// OK, start checking for the last command from db
// if last command is not null, then pass the update to the corresponding command
```

But the downside of this approach is that I cannot know if `Telegram::commandsHandler()` has correctly handled the update, and that causes duplication, because after user send `/start` for example the `last_command` will be saved already. And the second thing, is that I don't know how I can reach `CommandBus#parseCommand()`.

**Comment by irazasyed** [comment]
Work in-progress. Already discussed on PHP Chat and moving this conversation in #90.
