### ISSUE TITLE
creating group programatically.

### ISSUE THREAD

**Issue by DhavalsShah** [irazasyed/telegram-bot-sdk#120]
Can we create the group programatically and add the people to group by default if they have installed our customized telegram service? And how to detect people from regular telegram users to who have not installed our telegram application? Does telegram bot help us to create group and add member by default who have our telegram application?

**Comment by irazasyed** [comment]
No. You can't do that. Telegram Bot API doesn't support that.

**Comment by DhavalsShah** [comment]
Hello irazasyed thanks for the answer. So,can we do the same by using the telegram api? I am asking because GetGems application(Based on Telegram) has already implemented this feature. Automatically we join GetGems advertising group after installing GetGems app and detect user whether user(from contact list) uses thier GetGems application or not. Based on that they invite user.

**Comment by irazasyed** [comment]
Unfortunately, I don't really know as I've never worked with the core API. So i can't really comment on that. You should check their documentation to know more about it. If other apps are able to do it, then maybe it's possible.
