### ISSUE TITLE
commands won't work after adding new commands

### ISSUE THREAD

**Issue by moein-rahimi** [irazasyed/telegram-bot-sdk#122]
hi
i've set webhook and it works just fine, now i would like to add new commands, i've just duplicate the helpcommand.php and edit it by my needs and then i've registered it to command array. but now my command won't work not even the helpcommand.php
this is my registered commands:
````
'commands' => [
         Telegram\Bot\Commands\HelpCommand::class,
         Telegram\Bot\Commands\NewsCommand::class,
    ],
````
and my newscommand.php
````
<?php

namespace Telegram\Bot\Commands;

use Telegram\Bot\Actions;
use Telegram\Bot\Commands\Command;

class NewsCommand extends Command
{
    /**
     * @var string Command Name
     */
    protected $name = "news";

    /**
     * @var string Command Description
     */
    protected $description = "news goes here";

    /**
     * @inheritdoc
     */
    public function handle($arguments)
    {
        // This will send a message using `sendMessage` method behind the scenes to
        // the user/chat id who triggered this command.
        // `replyWith<Message|Photo|Audio|Video|Voice|Document|Sticker|Location|ChatAction>()` all the available methods are dynamically
        // handled when you replace `send<Method>` with `replyWith` and use the same parameters - except chat_id does NOT need to be included in the array.
        $this->replyWithMessage(['text' => 'Hello! Welcome to our bot, Here are our available commands:']);

        // This will update the chat status to typing...
        $this->replyWithChatAction(['action' => Actions::TYPING]);

        // This will prepare a list of available commands and send the user.
        // First, Get an array of all registered commands
        // They'll be in 'command-name' => 'Command Handler Class' format.
        $commands = $this->getTelegram()->getCommands();

        // Build the list
        $response = '';
        foreach ($commands as $name => $command) {
            $response .= sprintf('/%s - %s' . PHP_EOL, $name, $command->getDescription());
        }

        // Reply with the commands list
        $this->replyWithMessage(['text' => $response]);

        // Trigger another command dynamically from within this command
        // When you want to chain multiple commands within one or process the request further.
        // The method supports second parameter arguments which you can optionally pass, By default
        // it'll pass the same arguments that are received for this command originally.
        $this->triggerCommand('subscribe');
    }
}
````
also i've created the newscommand the same directory as the helpcommand

**Comment by jonnywilliamson** [comment]
Was the help command working before you added the new command?

Do you know how to setup POSTMAN (chrome extension) send a manual request to your server?

You'd be able to see what your server replies with if you send it an update, perhaps it's failing on the SSL certificate. Perhaps there's a php syntax error?

Very hard to start debugging until you can see some sort of error message, or you can trace/debug the code as the request gets handled.

Can you find any error logs or server responses?

**Comment by irazasyed** [comment]
First of all, You're not supposed to be editing or storing your app files in the vendor directory.

You have to place it outside somewhere accessible by composer and then register it.

Second, If you notice, the last line in handle is trying to trigger `subscribe` command which based on your code doesn't even exist. So remove that. And like @jonnywilliamson suggested, follow those instructions too.

**Comment by moein-rahimi** [comment]
@irazasyed 
can you make a example for commands path? i placed a command file inside app directory and adressed it like this: 
````         app\News::class,
````
but the project can't found it
````
Command class "app\News" not found! Please make sure the class exists.
````

**Comment by irazasyed** [comment]
You need to learn more about PSR rules before jumping into building bots as without it, you'll have a hard time figuring out things.

I would suggest you to first go through: http://www.php-fig.org/

Especially the autoloading part/namespace.

It should match your namespace. Something like:

```php
App\NewsCommand::class
```

**Comment by moein-rahimi** [comment]
thanks for responding, yes it was cause of my knowledge in autoloading, now the commands works just fine.
thank you

**Comment by irazasyed** [comment]
Cool. You're welcome. Glad it works fine now.

**Comment by alhaitis** [comment]
Salam Syed Irfaq,

 I am very interested about the bot telegram to i hope u can input video in
youtube so can find out how to use the telegram sdk

**Comment by irazasyed** [comment]
@alhaitis WS, I'll think about it. As of now my priority is to get the V3 released with the planned conversational system and other pending things. But anyone can do that though.
