### ISSUE TITLE
When will you add silent mode?

### ISSUE THREAD

**Issue by zvermafia** [irazasyed/telegram-bot-sdk#123]
![2016 03 09-21 28 24](https://cloud.githubusercontent.com/assets/7254584/13642360/f7f737fa-e63d-11e5-8de4-3ca975cac0d2.jpg)
Go to the [page](https://core.telegram.org/bots/api#sendmessage).

**Comment by ihoru** [comment]
@zvermafia you can use it already in version v2.0! And doesn't matter whether it is coded somehow or not.
https://github.com/irazasyed/telegram-bot-sdk/blob/67d1d0169e747741d981c1a3b2c74efbb4e2533f/src/Api.php#L223

**Comment by irazasyed** [comment]
Like @ihoru already mentioned. You can already use it. Since we moved to array params in V2. You don't have to wait for the SDK to be updated. All you have to do is just add it to your params array.

Refer above link.

**Comment by zvermafia** [comment]
Thanks! I got you.
