### ISSUE TITLE
how to handle normal text via command system

### ISSUE THREAD

**Issue by moein-rahimi** [irazasyed/telegram-bot-sdk#126]
hi
I'm using keyboard for my bot and i'd like to handle commands without having the command text in keyboard, i mean i want to use normal text in keyboard but the specific text trigger a command.
for example user send 'latest' via keyboard which is a normal text, and i want to handle it via a command class.

**Comment by irazasyed** [comment]
That is no possible right now out of the box. But i have plans to add a method to trigger a command from outside. You can then use that to trigger the command based on any text or whenever you like.
