### ISSUE TITLE
openshift installation help.

### ISSUE THREAD

**Issue by ropad** [irazasyed/telegram-bot-sdk#127]
Hi I'm planing to use this sdk to create a telegram bot, based on a openshift application. Ufortunately I'm vey inexpert and I need your help for deploying it on openshift. 
Can anyone of you, if already use it on openshift or know how to do it, provide a easy guide for openshift deployment?

**Comment by irazasyed** [comment]
Hey @ropad, I haven't used Openshift before. So I don't think I would be of any help but I'll keep this issue open. Maybe someone has used it before with this SDK.

**Comment by ropad** [comment]
Thank you

**Comment by ropad** [comment]
HI I found a laravel 5 cartridge wich I already installed and inside I found a copmposer.json file, so my question is: If I add "```
require": {
      "irazasyed/telegram-bot-sdk": "^2.0"
```  my system will be ok ?

**Comment by irazasyed** [comment]
No problem :)

Yep, It should. As long as you have composer installed and can run commands.
