### ISSUE TITLE
Error 500 in sharing host

### ISSUE THREAD

**Issue by hamedmoody** [irazasyed/telegram-bot-sdk#128]
Hi this is my code in wordpress plugin for simple send message to chat id. when i open url message has been sent but browser return error 500. this is my code:
```
<?php
/*
 * Plugin Name: Telegram Bot
 */

defined('ABSPATH') || exit;

require( plugin_dir_path(__FILE__) . 'vendor/autoload.php' );
//require( plugin_dir_path(__FILE__) . 'classes/IRCTG_Telegram_Command.php' );

global $irctg_bot;
$irctg_bot = new Telegram\Bot\Api('215756634:AAE7RHTD8cUv-ZSo_MnpqHQBrPo35xE9biQ');

add_action('init', function(){
    global $irctg_bot;
    if(isset($_GET['usetg']) && $_GET['usetg'] == 'ok'){
        try{
            $irctg_bot->sendMessage(array(
                'chat_id' => '76363847', 
                'text' => 'Hello World'
            ));
        } catch (Exception $ex) {

        }
    }
});
```

**Comment by irazasyed** [comment]
Hi, Please post your error log. Without it, Would be hard to tell what's causing that issue.

**Comment by irazasyed** [comment]
What is the PHP version that you're using or your provider is giving you? It needs to be at least PHP5.5.

**Comment by hamedmoody** [comment]
ok my php version is: 5.4.42
have you any way to run with this version of php?

**Comment by irazasyed** [comment]
Just ask your hosting provider to upgrade PHP version. They should be able to assist you. It's so outdated.

**Comment by hamedmoody** [comment]
Thanks
