### ISSUE TITLE
bot api 2.0

### ISSUE THREAD

**Issue by Visionary89** [irazasyed/telegram-bot-sdk#131]
Today came the update 2.0 api. sdk will support it?

**Comment by irazasyed** [comment]
Yes, It'll be supported. I'll look into it and try to add it to V3.0 of this SDK. Thanks for the info.

**Comment by jumong** [comment]
Thank you!

**Comment by thob** [comment]
Hi, you got an ETA for v3?

**Comment by irazasyed** [comment]
@thob No ETA yet but mostly the methods are already implemented, thanks to @jonnywilliamson. The Inline Query Objects are pending which should also be done in a day and the remainder is the multi bot support for standalone users. Once that is done, we should be all set to release.

In the mean time, you can pull the dev-master and test it.

**Comment by irazasyed** [comment]
Quick update, We've made great progress over the last few days. I believe, I can release V3 anytime next week for sure!

We have some major changes, a lot of new & exciting features coming up for you guys!

I'm closing this ticket for now. If you're not on [PHP Chat](https://telegram-bot-sdk.readme.io/blog/join-php-chat-slack-community-for-support), Please do come and join. All the latest updates and on-going development discussions are inside the chat. So you can follow along, give your feedback, test beta, make suggestions, take help and more. Thanks!
