### ISSUE TITLE
Should emoji -> text conversation retain the colon

### ISSUE THREAD

**Issue by jonnywilliamson** [irazasyed/telegram-bot-sdk#138]
Just amazing stuff.

Question:

When **creating** a message that contains an emoji, we use the following syntax:
```php
    $result = $tg->sendMessage([
        'chat_id'      => '<id>',
        'text'         => 'There is so much new stuff, I am so :smile and i am not :cry',
    ]);
```

1st Question, should the syntax single colon -  `:smile`  or  double colon `:smile:` as a lot of other sites use?

When **receiving** a message with an emoji, the emoji parser returns the text without any colons:
eg:
`There is so much new stuff, I am so smile and i am not cry`

Should this be
`There is so much new stuff, I am so :smile and i am not :cry`

Without ever dealing with this before, my initial reaction was to expect to type
`:smile:` when creating a message - and receive `:smile:` in my text when receiving one.

Interested in other views.

**Comment by jonnywilliamson** [comment]
The reason I ask, is that the website http://emoji.muan.co seems to show them all with double colons.

![image](https://cloud.githubusercontent.com/assets/2513663/14580145/334fe45a-03bc-11e6-9b85-3020aba3e5d3.png)

**Comment by irazasyed** [comment]
I think it would make sense, yes!

Also, It'll be easier to check when dealing with parsing as well as reactions, etc. Especially with the buttons.

**Comment by irazasyed** [comment]
Feel free to send a PR if you're available. I'll check into this later. Gotta work on Manager and finish that first.
