### ISSUE TITLE
Can I use this with Lumen?

### ISSUE THREAD

**Issue by LukasMa** [irazasyed/telegram-bot-sdk#149]
Hi,
not an issue, I just wanted to ask if can use the SDK with Lumen. In theory it should work, but at the moment it fails when I try to load the service provider:

`
Type error: Argument 1 passed to Telegram\Bot\Laravel\TelegramServiceProvider::registerTelegram() must be an instance of Illuminate\Contracts\Foundation\Application, instance of Laravel\Lumen\Application given, called in D:\lamp\www\telegram-bot\vendor\irazasyed\telegram-bot-sdk\src\Laravel\TelegramServiceProvider.php on line 43
`

Sure I could try to fix that by making some changes in the source myself, but I don't think thats the best way.
Is there a nice work around to make this work in Lumen?

**Comment by irazasyed** [comment]
Hi,  Support for Lumen is already present in `dev-master`. Please wait for V3 to be released, You'll be able to use it then. If it's urgent, then you can either pull the master copy or refer the changes in service provider and make the changes accordingly in your copy for the time being.
