### ISSUE TITLE
Question about sendMessage

### ISSUE THREAD

**Issue by angelocala94** [irazasyed/telegram-bot-sdk#15]
Anyone know how to break line in telegram messages?

**Comment by irazasyed** [comment]
Just use the standard line break character in PHP.

Example:
```php
$message = "Hello World \n";
$message .= "This will be in new line\n";
$message .= "Final line";

$telegram->sendMessage('CHAT_ID', $message);
```

**Comment by nanangkoesharwanto** [comment]
![screenshot-web telegram org 2016-08-22 00-10-52](https://cloud.githubusercontent.com/assets/11191677/17838660/fd00d26a-67fc-11e6-9305-a26312192eb6.png)

```
$response = $telegram->sendMessage([
	'chat_id' => $chat_id, 
	'text' => 'Success! Your Telegram account with name <b>'.$first_name.' '.$last_name.'</b> has been added into iBridge data!.%0ABack to <a href="https://ibridgeapp.com/home">iBridge</a>',
	 'parse_mode' => 'HTML'
]);
```

Using \n or %0A did not make a new line. any suggestion?

**Comment by turtle-bazon** [comment]
Problem solved?

**Comment by nanangkoesharwanto** [comment]
solved. see here https://github.com/irazasyed/telegram-bot-sdk/issues/227
