### ISSUE TITLE
get webhook information

### ISSUE THREAD

**Issue by moeinrahimi** [irazasyed/telegram-bot-sdk#155]
hi
it may be stupid but i don't know how to retrieve information sent from webhook or getupdates()
should i use this $telegram->getUpdates()->getMessage()->getChat() ?
it's not working ofcourse, can anyone make a example of how access updates information such as chatid or text

**Comment by irazasyed** [comment]
Please refer the docs here: https://telegram-bot-sdk.readme.io/docs/webhook-updates

Also, If you don't have the outgoing webhook setup. Only then you can use the `getUpdates()` method.

So taking getUpdates as an example, it would be:

```php
$updates = $telegram->getUpdates();

// Get's the last update, since the $updates is an array of several update objects.
$update = $updates->recentMessage(); 

$message = $update->getMessage();
$id = $message->getMessageId();
$chat = $message->getChat();
```

Hope that helps. Please go through the docs as well as the collections API of laravel to get an understanding of how things work and the useful methods it offers.
