### ISSUE TITLE
Do you support reply with payload.

### ISSUE THREAD

**Issue by derakoola** [irazasyed/telegram-bot-sdk#156]
Bots that are fast need to send response when they want to send 200 status, Do you support it?
( For more information plz check images )

![photo_2016-04-24_00-56-57](https://cloud.githubusercontent.com/assets/5869562/14763830/955bc64a-09b7-11e6-9ef9-6b3828220745.jpg)

![photo_2016-04-24_00-57-16](https://cloud.githubusercontent.com/assets/5869562/14763831/9803992c-09b7-11e6-998b-484be627b4c0.jpg)

**Comment by irazasyed** [comment]
It's simply a JSON encoded payload of the params and the method name. You can just use the PHP's built-in function to do this when you pass the params array.
