### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by Dohab** [irazasyed/telegram-bot-sdk#16]
Hi,
Can you please explain in details how to install it?
What paths should I work in? is it public_html or root?
No matter what I did, I'm always facing this error:
Fatal error: Class 'Irazasyed\Telegram\Telegram' not found in /home/XXXX/public_html/tele.php on line 5

**Comment by irazasyed** [comment]
Hi,

You need to use [Composer](https://getcomposer.org) to work with this library.

You can use my Telegram Bot Bootstrap [here](https://github.com/irazasyed/telegram-bot-bootstrap) - https://github.com/irazasyed/telegram-bot-bootstrap
