### ISSUE TITLE
Request a training package for Beginners

### ISSUE THREAD

**Issue by BehroozBvk** [irazasyed/telegram-bot-sdk#165]
@irazasyed :+1: 
Hi, I have a question about a simple tutorial teaching as a simple robot from scratch by me like I'm much too confusing.

**Comment by irazasyed** [comment]
Hi @BehroozBvk If i got this right, what you're asking is basically a tutorial and a sample project repo right?

**Comment by BehroozBvk** [comment]
@irazasyed : Hi yes, a typical project Laravel, and this package

**Comment by irazasyed** [comment]
I haven't created one but I do have a plan to create a bootstrap project. Maybe in near future but not right now. Please refer the docs as well as Laravel tutorials and you should be able to understand them easily.

**Comment by ottnorml** [comment]
@irazasyed: Are there any news concerning your plans for a beginners tutorial? I would be interested too. :)

**Comment by irazasyed** [comment]
@ottnorml Yes, I'll have them up once I release v3 which has some major changes. No point in covering v2 now in tutorials. The new version is packed with some great features which I think needs to be highlighted with a proper tutorial. Once I do that, I'll make sure to inform in our Slack channel.

Do join if you've not already joined. Thanks!
