### ISSUE TITLE
The problem of returning empty method getWebhookUpdates() 

### ISSUE THREAD

**Issue by BehroozBvk** [irazasyed/telegram-bot-sdk#167]
> MyCode Controller : 
`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Telegram;
use Input;
use App\Http\Requests;
use Telegram\Bot\Objects\Message;
use Telegram\Bot\Objects\Update;
use Telegram\Bot\Api;
use Telegram\Bot\Commands\Command;

class BotController extends Controller
{ 

    public function getupdate()
    {
    	$telegram = new Api('111111111:AAGWcbJ9xNIP3yJ9rS7QEE4jlqMX5wQhn6c', 'true');
        $telegram->setWebhook(['url' => 'https://Mydomain.com/Telegram/111111111:AAGWcbJ9xNIP3yJ9rS7QEE4jlqMX5wQhn6c/webhook']);
        $update = $telegram->getWebhookUpdates();
        dd($update);
	
    }
}
`

help me !!!

**Comment by irazasyed** [comment]
You need to learn Laravel as well as go through the docs properly. Because the initial setup itself is wrong. Unfortunately, I can't spoon feed, everything is already out there in docs.

**Comment by BehroozBvk** [comment]
Well give you a simple source hard to really ???
