### ISSUE TITLE
Why method getName is not a part of CommandInterface?

### ISSUE THREAD

**Issue by BoShurik** [irazasyed/telegram-bot-sdk#168]
So, we should add this method to interface or make a check for `\Telegram\Bot\Commands\Command` instance

https://github.com/irazasyed/telegram-bot-sdk/blob/master/src/Commands/CommandBus.php#L102

**Comment by irazasyed** [comment]
Feel free to send a PR. I didn't add. But i will later, thanks for bringing that up.
