### ISSUE TITLE
[Todo] Choose between illuminate/cache and doctrine/cache

### ISSUE THREAD

**Issue by tjomamokrenko** [irazasyed/telegram-bot-sdk#172]
To store information about current user conversation (see https://github.com/irazasyed/telegram-bot-sdk/pull/171) we need to choose between these two packages.

I'm for `doctrine/cache` since it's simpler, well-tested and more stable than `illuminate/cache`.

> I think we could've used `illuminate/cache`
> ...
> I'm not quite sure if it's any better because I haven't really used `doctrine/cache` directly. I've only used `illuminate/cache` in Laravel projects.
> The problem with illuminate components is basically when the project is used within some incompatible version of Laravel, then we're forced to update the changes to our project as well as maintain multiple versions just to support Laravel users, which is kinda problem.
> If `doctrine/cache` can support multiple drivers and it's easier, then I don't have any issues going with it.
> ...
> Can we detect the platform and maybe use Laravel's built-in cache and settings when it's being used with Laravel and fallback to `doctrine/cache` for standalone users? That would make things a lot easier.
> — irazasyed

help wanted @irazasyed @jonnywilliamson @ihoru @halaei @BoShurik

**Comment by halaei** [comment]
I have used `illuminate/cache` but not `doctrine/cache`. Sometimes I directly use `predis` as well. I don't feel `illuminate/cache` is complicated or unstable.

**Comment by halaei** [comment]
Do you use cache tag?

**Comment by tjomamokrenko** [comment]
see #171
