### ISSUE TITLE
documentation readme.io 404 writes error

### ISSUE THREAD

**Issue by exileed** [irazasyed/telegram-bot-sdk#179]
https://telegram-bot-sdk.readme.io/docs does not work. Where to get the documentation ?
![2016-05-16_18-29-58](https://cloud.githubusercontent.com/assets/942898/15296156/4503634e-1b94-11e6-9a03-8c19dd89180c.png)

**Comment by irazasyed** [comment]
Seems to work fine for me! Please recheck.

**Comment by exileed** [comment]
Prague does not work, but it works through a VPN
