### ISSUE TITLE
how install?

### ISSUE THREAD

**Issue by reimax** [irazasyed/telegram-bot-sdk#180]
via doc:

root@ubuntu:/telegram2# curl -sS https://getcomposer.org/installer | php
Downloading 1.1.0...

Composer successfully installed to: /telegram2/composer.phar
Use it: php composer.phar
Some settings on your machine may cause stability issues with Composer.
If you encounter issues, try to change the following:

The xdebug extension is loaded, this can slow down Composer a little.
Disabling it when using Composer is recommended.

root@ubuntu:/telegram2# php composer.phar require irazasyed/telegram-bot-sdk ^2.0
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package irazasyed/telegram-bot-sdk No version set (parsed as 1.0.0) is satisfiable by irazasyed/telegram-bot-sdk[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.
root@ubuntu:/telegram2#

**Comment by irazasyed** [comment]
You need to setup a basic PHP project with composer. Once you have that in place, you can then start the installation by following the docs. Please refer them.
