### ISSUE TITLE
Callback, url buttons

### ISSUE THREAD

**Issue by vladimir-yuldashev** [irazasyed/telegram-bot-sdk#183]
Hi

Could not find in documentation how to make callback buttons (https://core.telegram.org/bots/2-0-intro#callback-buttons) or url buttons (https://core.telegram.org/bots/2-0-intro#url-buttons) using this SDK.

Please, provide some information about it.

Thank you

**Comment by irazasyed** [comment]
Hi,

These features are supported in dev-master branch. They're pending to be released in V3 but can be used already.

No docs for now. You'll have to refer the source code or wait until V3 is launched (No ETA).
