### ISSUE TITLE
How can I handle messages without start with '/' ?

### ISSUE THREAD

**Issue by DenisOgr** [irazasyed/telegram-bot-sdk#184]
I want to use messages without command in same string.
For example:
```
I: /newbot
         Bot: ok! type the name of bot
I: testBot
        Bot: Done! Thx, bro.
```

Title of command I will be save in mysql for current chat_id.

Thans, Denis

**Comment by irazasyed** [comment]
You're probably looking at the conversations plugin which is in works. If it's as simple as you've described, then you can simply get updates through webhook and then process them manually without using any commands.

Just check for the string in the message and respond, when the user replies, check if it's a command and if not, then it's your answer. Respond and store it.

**Comment by DenisOgr** [comment]
Thanks, I created fork and add needs actions.
