### ISSUE TITLE
Inline keyboard

### ISSUE THREAD

**Issue by derakoola** [irazasyed/telegram-bot-sdk#186]
Do you support new features like inline-keyboard?

**Comment by aminshafiee048** [comment]
hi guys,
I have the same question, and i know this sdk support inline keyboard but don't know how could handle callback data ? becuse if we use callback_data for inline keyboard did not any thing post to chat!
thanks

**Comment by irazasyed** [comment]
Yep but it's in dev-master, yet to be tagged as V3.

You can either refer the master branch and explore the source code or wait till it's released with the docs written. No ETA though.
