### ISSUE TITLE
sendMessage do not work

### ISSUE THREAD

**Issue by Enelar** [irazasyed/telegram-bot-sdk#187]
Seems like sendMessage stoped working:
try it in docs https://telegram-bot-sdk.readme.io/v2.0/docs/sendmessage

**Comment by irazasyed** [comment]
It seems to work fine, not sure what you're refering to?

**Comment by nerestaren** [comment]
Are you setting a real chat_id? You need that.

To get one, talk to your bot and capture `$message->getChat()->getId()`.

Cheers!

**Comment by Enelar** [comment]
@nerestaren Telegram documentation said that i could use my nickname (offenso) as chatid, but i tried my userid (23572074) too. (Because it equal to chat_id in webhook update).

I also tried `@offenso` and `@23572074`.

**Comment by irazasyed** [comment]
@Enelar You need to set a a valid token by clicking on the green key icon on top right to actually test the API calls.

Like it says in the URL `YOUR_APP_TOKEN` which will be replaced if you add the token. After you add, try it out.

**Comment by Enelar** [comment]
@irazasyed that were un-obvious(maybe we should point on that, with popup maybe?), yep, now it works from documentation.
I am closing issue, because apparently bug is in my code.

Thanks for the assistance.
