### ISSUE TITLE
How to download file?

### ISSUE THREAD

**Issue by DenisOgr** [irazasyed/telegram-bot-sdk#188]
Hi.
I want to download file from user (telegram).
I get file_id from message.document, I can call 
```
use Telegram\Bot\Api;
$telegram = new Api('BOT TOKEN');
$response = $telegram->getFile(['file_id' => 'ABC12345XYZ6789...']);
```
 and get json info for file,
but how  can i download file to my server?

Thanks, Denis.

**Comment by irazasyed** [comment]
Use Guzzle to download it: See this [link](http://guzzle.readthedocs.io/en/latest/request-options.html#sink-option).

**Comment by DenisOgr** [comment]
Thx I know how to download file from link use Guzzle, but I think that you do can this action "from box"
