### ISSUE TITLE
How to send a valid and empty response

### ISSUE THREAD

**Issue by CristianOspina** [irazasyed/telegram-bot-sdk#190]
Hello!
A user has blocked my bot, but there are three pending request. I can not answer that because Telegram returns with: "Bot was blocked by the user".

But Telegram continues to send the request, I guess waiting for a valid response.

How I can reply that I received the message? How from the SDK I can send a valid response without any action?

Regards!

**Comment by irazasyed** [comment]
Just respond with header status code `200` and some text in body like `ok`. Telegram will confirm you accepted the message.

**Comment by CristianOspina** [comment]
Thanks!
Works now!
