### ISSUE TITLE
Copy message from other channel

### ISSUE THREAD

**Issue by ashkufaraz** [irazasyed/telegram-bot-sdk#192]
Hi
Sorry,I have a question about your project(telegram).
Can I get the message channels that I'm not their admin?
I want write a script that read message from other chanel and write to
my chanel.
I can do it?
best regards
thanks

**Comment by irazasyed** [comment]
Hi,

I don't think that's possible. If you're an admin of the channel, only then you can add the bot (I think). Otherwise you wouldn't be able to do that.

I haven't tested this to be sure but i would recommend you try and post your results here as well.
