### ISSUE TITLE
setWebhook doesn't handle certificate errors

### ISSUE THREAD

**Issue by Lohoris** [irazasyed/telegram-bot-sdk#193]
Despite throwing exceptions in case of URL errors, setWebhook silently ignores any certificate error. If you pass an invalid filename, it will just pretend everything's fine, but nothing will work instead.

**Comment by irazasyed** [comment]
Well, If it's invalid, then doesn't Telegram respond with an error message?

The SDK doesn't handle this case.

**Comment by Lohoris** [comment]
It didn't, I just got the empty Message either way.

I bet in this case you could first check if the file exists, and if it doesn't throw an exception, regardless of what the SDK does?

**Comment by jonnywilliamson** [comment]
Fixed with https://github.com/irazasyed/telegram-bot-sdk/pull/222/commits/c8be93f94b6bc2de05efed7bac96d43334ef475f
