### ISSUE TITLE
setWebhook doesn't return a TelegramResponse

### ISSUE THREAD

**Issue by Lohoris** [irazasyed/telegram-bot-sdk#194]
`removeWebhook` correctly returns a `TelegramResponse`, as documented, but `setWebhook` returns an empty `Message`, both in case of success and in case of failure.

This, unless it throws an exception due to a wrong URL.

**Comment by irazasyed** [comment]
I'll have to look into this. Thanks for reporting 👍

**Comment by jonnywilliamson** [comment]
Fixed by 97f3362f450b20e7c0910036c51c0a99fbd44060

**Comment by firegore2** [comment]
how to check if the webhook url is valid?

**Comment by irazasyed** [comment]
@firegore2 Please create a new issue ticket. Thanks.
