### ISSUE TITLE
Dynamic Commands

### ISSUE THREAD

**Issue by yaim** [irazasyed/telegram-bot-sdk#196]
Is there a way to implement dynamic command names such as /show_post_25 and /show_post_100 in the current CommandBus system?

**Comment by irazasyed** [comment]
Not directly but it's doable. You can register one command, then manually trigger it based on incoming messages pattern.

**Comment by yaim** [comment]
Great, thanks! 🙏🏻

**Comment by jonnywilliamson** [comment]
Yeah personally think this is much more suited to commands with arguments

so that your command would be
`/show_post` which you register and then look for any arguments after the command to process

Therefore

`/show_post_25` would become
`/show_post 25` and you would process it that way.

**Comment by yaim** [comment]
@jonnywilliamson I'm agree that this is the more logical way, but does not have a good expreience for the user. Letting user to just click on an hyperlink command is much more easier than asking them to type the whole command and its arguments.

**Comment by jonnywilliamson** [comment]
In that case, using middleware in laravel would be perfect for detecting this!

**Comment by irazasyed** [comment]
We're revisiting this thanks to a new issue ticket and some improvements to the SDK since. If someone lands here, here's how to do this: https://github.com/irazasyed/telegram-bot-sdk/issues/1061#issuecomment-1509436944
