### ISSUE TITLE
Inline mode methods.

### ISSUE THREAD

**Issue by smartdeath** [irazasyed/telegram-bot-sdk#198]
Hi,
Do you have any plan to implement[ inline mode methods ](https://core.telegram.org/bots/api#inline-mode-methods) ?

Thank you .

**Comment by irazasyed** [comment]
Hey @smartdeath,

They're already implemented in master branch. Just not released as the plan was to decouple the whole SDK which is still under works. Been busy, So I couldn't focus on it.

You can pull `3.*@dev` and start using though.

**Comment by joseska** [comment]
Hi. I´m interested in use inline mode too.
 how can i use master branch??
I install 2.0 from documentation "composer require irazasyed/telegram-bot-sdk ^2.0"

Thanks.....

**Comment by smartdeath** [comment]
Good job thank you my friend.

**Comment by joseska** [comment]
How can I install the version that have inline mode??????
Thanks

**Comment by irazasyed** [comment]
@joseska `composer require irazasyed/telegram-bot-sdk 3.*@dev`

**Comment by joseska** [comment]
Thanks..... i will try tomorrow

**Comment by smartdeath** [comment]
Hello @irazasyed How can i use inline keyboard !?

**Comment by irazasyed** [comment]
@smartdeath In case you still haven't figured out yet, refer this comment: https://github.com/irazasyed/telegram-bot-sdk/issues/270#issuecomment-254185680

**Comment by smartdeath** [comment]
Thank you so much

**Comment by maralbe** [comment]
i used this version ->  composer require irazasyed/telegram-bot-sdk 3.*@dev

and since i installed it my php give me error : 
PHP Fatal error:  Maximum execution time of 60 seconds exceeded in /home/maral/Sites/shopBot/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php on line 109

i do'nt know how to fix it.. 
can you help me to solve it?

**Comment by smartdeath** [comment]
@maralbe try it : http://stackoverflow.com/questions/1420249/maximum-execution-time-of-60-seconds-exceeded-error
