### ISSUE TITLE
CallbackQuery

### ISSUE THREAD

**Issue by cjmaximal** [irazasyed/telegram-bot-sdk#203]
Hi!
How do I handle callback query for data send after inline button click?

For ex.:

> User:
>  /start

> Bot:
> Hi!
> inline button "menu"

> User:
> click on inline button "Menu"

What should I do to respond to?

**Comment by sloothword** [comment]
You can read the updates the same way, detect that it is a callback query with `detectType` and process them accordingly. (at least in master, not sure how it worked in 2.0).

**Comment by cjmaximal** [comment]
Thank you!
I thought Callback works the same as the command (write a class, add it to configuration and it works). That is, it is necessary himself handle the callback?

**Comment by sloothword** [comment]
Yeah i am working on something like that.

But currently you have to deal with it yourself.
I would do it maybe like that:
- you get back the `$updates` either from `getUpdates` or `commandsHandler` (idk what you are using right now)
- iterate over these updates and check with `detectType` or `has('callback_query')` if it is a callback
- do whatever you want with it

**Comment by cjmaximal** [comment]
We'll have to use this form.
I use telegram-bot-sdk with laravel 5.2, this solution a little out of style laravel
