### ISSUE TITLE
not work replyWith in callback data with inlinekeyboard 

### ISSUE THREAD

**Issue by Ebi1020** [irazasyed/telegram-bot-sdk#204]
hi, i'm get error in commands :(
[2016-07-08 03:57:48] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getChat() on null' in H:\src\vendor\irazasyed\telegram-bot-sdk\src\Answers\Answerable.php:52

**but** working with edit line 52 to:

if ($this->update->has('message'))
        $chat_id = $this->update->getMessage()->getChat()->getId();
else
        $chat_id = $this->update->getCallbackQuery()->getMessage()['chat']->getId();

**Comment by biakaveron** [comment]
The same issue.

I think it will be better to implement getChat() method for Update object.

**Comment by jonnywilliamson** [comment]
This is because the sdk has an assumption that all Updates passed to this class will be of the `message` type when in fact they can also be `edited_message` type.

We are working on a solution to this.

**Comment by jonnywilliamson** [comment]
Hopefully this should be done shortly.

**Comment by korvin3** [comment]
I have the same problem. My solution:
`$telegram->getCommandBus()->execute('*callbackName*', [], $update->getCallbackQuery());`
Maybe be useful for someone.
