### ISSUE TITLE
how to get text of message 

### ISSUE THREAD

**Issue by alihossein** [irazasyed/telegram-bot-sdk#207]
hi . 
how to I get text of message  send by the user in Telegram  ? which methods ? Example please.
I used this package in Laravel .

**Comment by sloothword** [comment]
It is clearly described in the documentation.
(Get the update, get the message, get the text)

Maybe you can provide the code you already have and then i can help you with the missing pieces.

**Comment by alihossein** [comment]
thanks you @sloothword  . 
i get text and chat_id with this code. 

`$update    =Telegram::getWebhookUpdates();`
`$chat_id   =$update->getMessage()->getChat()->getId();`
`$text=$update->getMessage()->getText();`
