### ISSUE TITLE
Bot building best practice / sample project

### ISSUE THREAD

**Issue by lawrencegs** [irazasyed/telegram-bot-sdk#208]
CMIIW, I feel that building a bot is inherently different to website and API.

I'm wondering if there's a project using this SDK out there that we can take a look to see how we should architect our bot.

**Comment by Tejasvi1** [comment]
Yoo

**Comment by irazasyed** [comment]
As of now, We don't really have any best practices but there are several open source projects that use this SDK.

You can use GitHub search to pull out some results, here's [one](https://github.com/search?utf8=%E2%9C%93&q=filename%3Acomposer.json+irazasyed%2Ftelegram-bot-sdk&type=Code&ref=searchresults).

I might setup a sample project in near future. If I do, it'll be listed ofc.
