### ISSUE TITLE
Need deserialization improvement

### ISSUE THREAD

**Issue by alexsparc** [irazasyed/telegram-bot-sdk#209]
The hash below can not be caught by SDK properly

`{"event":{"update_id":0000000,"edited_message":{"message_id":000,"from":{"id":0000000,"first_name":"alias","username":"uname"},"chat":{"id":0000000,"first_name":"alias","username":"uname","type":"private"},"date":1469563313,"edit_date":1469572794,"text":"newText"}}}`

So all info stored in **edited_message** can not be reached

**Comment by jonnywilliamson** [comment]
This will be fixed shortly.

**Comment by jonnywilliamson** [comment]
Should be fixed with 7d8814a5f6a6ccba09798c4377eff41642324251
