### ISSUE TITLE
Your code has been copied and license violated.

### ISSUE THREAD

**Issue by codninja** [irazasyed/telegram-bot-sdk#21]
Hi,

I came across this repository recently: https://github.com/mgp25/Telegram-Bot-API

And i noticed, the guy copied maximum of your methods/functions including complete documentation and other things and as per your license, It seems like a clear case of violation since he doesn't even bother to give proper credit or follow the license.

I informed him too but he doesn't seem to bother and defends himself.

Just thought I'd give heads up as being a developer myself, I know the value of ones work and time! Also, It's never a good idea to steal someones work and take credits.

**Comment by codninja** [comment]
P.S Here's the issue i had created: https://github.com/mgp25/Telegram-Bot-API/issues/4

**Comment by irazasyed** [comment]
Hi @codninja 

Thanks for reporting. I'll look into the issue and see what i can do about it.

It does seem like he has copied a lot of the code.

**Comment by codninja** [comment]
No problem.

The guy blocked me from the repo and he even went on to delete the links i had posted which showed what he had copied. That's pathetic.

**Comment by jonnywilliamson** [comment]
This author used to be the maintainer of the whatsAPI code base (which he didn't write but took over after "venemous" stopped supporting) which was a hacked Whatsapp api. 

Recently WhatsAPI got a lot of cease and desist messages from whatsapp and they pulled the project all together. Looks like they needed a quick fix to get back into the messaging game and unfairly came here to pilfer. 

That's bad form. :(
