### ISSUE TITLE
Get information from getUpdate()

### ISSUE THREAD

**Issue by scordone** [irazasyed/telegram-bot-sdk#210]
Hey,
Im trying to work with the updates and i can't get any information from the result of getUpdates
for example if i try:
$update = $telegram->getUpdates();
$message = $update->getMessage();
$from = $message->getFrom(); 

y get: Fatal error: Call to a member function getMessage() on a non-object

and the same happends with every method that i tried from update objects.
please help!!
Thanks!!

**Comment by alihossein** [comment]
hi
i use this code for laravel : 
` $this->update =Telegram::getWebhookUpdates();`
 `$this->chat_id=$this->update->getMessage()->getChat()->getId();`
`$this->text   =$this->update->getMessage()->getText();`

**Comment by jonnywilliamson** [comment]
@scordone If you are using `getUpdates()` the there has to be messages/updates waiting for your bot on the telegram server.

That method will then return an ARRAY of UPDATES that you can loop through and deal with as you please.

If you have NO updates and try to call a method on them, you'll get that error: 

Fatal error: Call to a member function getMessage() on a non-object

Are you sure you are getting updates in the first place?

**Comment by djz3r0** [comment]
I have the same problem. I've set up a webhook so there is an update but the `$update = $telegram->getWebhookUpdates();`  is not set.

**Comment by jonnywilliamson** [comment]
I'm finding it hard to debug this with the information provided.

So to absolutely be sure that youve set the webhook properly, goto https://requestb.in/ and create a new request bin. You'll be given a URL like this `http://requestb.in/1kcai4j1?inspect`.

Change it to an https url by adding the s, and then use the `setWebhook` method from the API to set this URL and your new webhook.

Then start sending some messages to your bot. Reload the requestb.in url and you'll see if you have set it correctly.

We can start from there...

**Comment by djz3r0** [comment]
Ofcourse it is not easy to debug this behaivior.

But most of the time all is working fine. So my webhook is working well and it seems the updates from TG are looking in some cases different and can’t be parsed.

 

Von: Jonathan [mailto:notifications@github.com] 
Gesendet: Dienstag, 16. August 2016 15:14
An: irazasyed/telegram-bot-sdk <telegram-bot-sdk@noreply.github.com>
Cc: djz3r0 <yannick.luedemann@gmx.de>; Comment <comment@noreply.github.com>
Betreff: Re: [irazasyed/telegram-bot-sdk] Get information from getUpdate() (#210)

 

I'm finding it hard to debug this with the information provided.

So to absolutely be sure that youve set the webhook properly, goto https://requestb.in/ and create a new request bin. You'll be given a URL like this http://requestb.in/1kcai4j1?inspect.

Change it to an https url by adding the s, and then use the setWebhook method from the API to set this URL and your new webhook.

Then start sending some messages to your bot. Reload the requestb.in url and you'll see if you have set it correctly.

We can start from there...

**Comment by jonnywilliamson** [comment]
@djz3r0 

The recent addition of an `edited_message` message from telegram is probably causing this issue.

At the moment if your bot receives an update from telegram of an `edited_message` the SDK is unable to parse it correctly. Its likely that it's throwing an exception.

At the moment we have a partial fix in the develop branch, and should hopefully have a full fix soon as it's currently under discussion.
