### ISSUE TITLE
'photo' =>  stream?

### ISSUE THREAD

**Issue by Alexufo** [irazasyed/telegram-bot-sdk#211]
Hi, I want resize image before send. But I can past url or local path only. I dont want use temp file.
Is this possible extend? Curl allow send images from stream.

**Comment by irazasyed** [comment]
Not sure I understand what you're looking for but I'll attempt to answer you.

If I got this correct, You're trying to resize the image before it's sent to Telegram right?

In that case, You can use some library to resize the image or an API which can take your image via URL or other method and return you an image link which can then be sent to the end user.

I hope that's what you were looking for. The SDK supports uploading by URL too.

**Comment by Alexufo** [comment]
In my case telegram-bot-sdk install on server with images. Images are big and I want use just like
 
    'photo' => reasize($img);

Inside code without url. Because i dont want create special service  for resize images.

May be add support not only http/ftp or /path and also  data://  or php://memory ?

**Comment by irazasyed** [comment]
You can already pass a resource to it and it'll automatically process it. If it isn't a resource but a URL or path to a file, then it'll handle that as well.

**Comment by Alexufo** [comment]
Have you an example how resources pass?

```
$data = 'iVBORw0KGgoAAAANSUhEUgAAABwAAAASCAMAAAB/2U7WAAAABl'
. 'BMVEUAAAD///+l2Z/dAAAASUlEQVR4XqWQUQoAIAxC2/0vXZDr'
. 'EX4IJTRkb7lobNUStXsB0jIXIAMSsQnWlsV+wULF4Avk9fLq2r'
. '8a5HSE35Q3eO2XP1A1wQkZSgETvDtKdQAAAABJRU5ErkJggg==';
$data = base64_decode($data);

$im = imagecreatefromstring($data);
$response = $this->telegram->sendPhoto([
  'chat_id' => $chatid, 
  'caption' => $model->last_name,
  'photo' => $im, 
  'reply_markup' => $reply_markup
]);						
```
    Bad Request: there is no photo in the request in
