### ISSUE TITLE
getMe not work!!!

### ISSUE THREAD

**Issue by alihossein** [irazasyed/telegram-bot-sdk#212]
hi 
why today getMe method Not Work  for me !!! 
`$info= Telegram::getMe();`
return : 
`User {#258 ▼`
`#items: []`
`}`

**Comment by irazasyed** [comment]
Do you still have this problem?

**Comment by alihossein** [comment]
yes

**Comment by irazasyed** [comment]
- What version of the SDK are you using?
- Did you check to make sure the token is set properly and is valid?

**Comment by alihossein** [comment]
how to see my version of SDK?
token set properly and my bot work fine.
no errors return . only response is : 
return : 
User {#258 ▼
#items: []
}

**Comment by irazasyed** [comment]
Open your `composer.json` file and see the version next to the `irazasyed/telegram-bot-sdk`.

**Comment by alihossein** [comment]
"irazasyed/telegram-bot-sdk": "^2.0",

**Comment by irazasyed** [comment]
Can you try using `3.*@dev`? If you still have the problem?

**Comment by robertnicjoo** [comment]
same issue here `"irazasyed/telegram-bot-sdk": "^3.15",`


```php
$bot = Telegram::getMe();
dd($bot);
```

```bash
Telegram\Bot\Objects\User {#1444 ▼
  #items: []
  #escapeWhenCastingToString: false
}
```
