### ISSUE TITLE
telegram keyboard not showing non English languages chracters?

### ISSUE THREAD

**Issue by sdghafouri** [irazasyed/telegram-bot-sdk#215]
I'm trying to write a telegram bot in Persian which is a non English utf8 language. when I try to send plain text in Persian to my client it works perfectly ok

`    $array = [
"chat_id" => $chat_id,
"text" => $someNonEnglishText
];
$telegram->sendMessage($array);`
but when I try to send keyboard data with the code below it just show some question marks like ???????????????? on my keyboard buttons

`    $reply_markup = $telegram->replyKeyboardMarkup([
  'keyboard' => $someNonEnglishkeyboard, 
  'resize_keyboard' => true, 
  'one_time_keyboard' => true
   ]);
    $telegram->sendMessage([
  'chat_id' => $updates[0]->getMessage()->getChat()->getId(), 
  'text' => $something,
  'reply_markup' => $reply_markup
]);`
an I'm perfectly sure that my bot php file is utf8 by running the following command in terminal file myfile.php whilch I got the answer:
` surveyBot.php: PHP script, UTF-8 Unicode text`

can someone help?

ps:the above code works perfectly fine for English keyboard.

**Comment by irazasyed** [comment]
The SDK doesn't do anything that could cause this issue. It's the Telegram that's doing it.

You should try making a call directly using a GET request and not SDK just to test things and confirm. Unfortunately, I'm not able to get time to test this issue for now. You should also try contacting Telegram bot support and see what they have to say about it.

I'm open for PRs if you think and confirm it's an issue from SDK end. It'll take some time for me to look into it myself and I believe you can't wait (Since you had also sent me an email stating it's urgent).

**Comment by sdghafouri** [comment]
I'm perfectly sure it's a problem of sdk because I test the same text with the regular telegram API and it worked. but anyway thank u for your quick response and your great library. That was the only time I had a problem with your sdk and its always worked for me. I'll try to dig into the code and fix it myself and if not I'll try another way.

**Comment by sdghafouri** [comment]
I'm perfectly sure it's a problem of sdk because I test the same text with the regular telegram API and it worked. but anyway thank u for your quick response and your great library. That was the only time I had a problem with your sdk and its always worked for me. I'll try to dig into the code and fix it myself and if not I'll try another way.
regardsSaeid Ghafouriform Iran

**Comment by irazasyed** [comment]
I see. Feel free to open a Pull Request if you have a fix. It would be much appreciated. Thanks!

**Comment by jonnywilliamson** [comment]
@sdghafouri Have you tried

`$array = [ "chat_id" => $chat_id, "text" => utf8_encode($someNonEnglishText) ]`

I'm wondering if its an encoding issue?

**Comment by manzoorwanijk** [comment]
I have a bot that handles Arabic text very well (see attachment). SDK has no issues. I had once faced similar issues while fetching the Arabic text from Database, then I had to change the encoding of my Database and also the encoding of the database connection object.
![screenshot_20160831-100444](https://cloud.githubusercontent.com/assets/18226415/18116210/6d8f11be-6f63-11e6-82cf-9c9faa2cd539.png)

**Comment by irazasyed** [comment]
@manzoorwanijk Thanks for posting that screenshot.

Since we didn't hear anything from @sdghafouri. I'm closing this issue now.

**Comment by mahdidev13** [comment]
@sdghafouri : hi, i had the same problem. i'm using php. it works fine now just by using function urlencode in php.
