### ISSUE TITLE
How to simply ask 1 question, provide multiple options, and get user response ?

### ISSUE THREAD

**Issue by simkimsia** [irazasyed/telegram-bot-sdk#216]
I am not asking on how to create a question and answer bot which I know requires database.

I am asking for 1 question, 4 options, and look at the response using this SDK.

I have read the documentations and there is no documented way to do something like this clearly for beginners like myself.

I am unable to piece the pieces together. Please advise.

**Comment by irazasyed** [comment]
You can try using [convo](https://github.com/telegram-bot-kit/convo) package for this. It's best suited for you use case.

Please note, The convo package is not yet submitted to packagist but it can be downloaded and used directly as well. It's still WIP package as Laravel support should be added and its related docs too.

The API is likely to change along with the paths and other things. So keep an eye!

**Comment by simkimsia** [comment]
Hi @irazasyed I have looked at the convo package. 

I figured out how to load the convo package without using composer temporarily though long term wise i still prefer to load it using composer.

I am now stuck with looking at the convo example and figuring out how it works with the command examples you have in this repo. https://github.com/telegram-bot-kit/convo/issues/20

Can advise?
