### ISSUE TITLE
Document Update 

### ISSUE THREAD

**Issue by smartdeath** [irazasyed/telegram-bot-sdk#226]
Please update your documentation about using inline mode keyboard !

**Comment by irazasyed** [comment]
@smartdeath It'll be updated when V3 gets released as there are several changes and improvements in this new upcoming release. Thanks!

**Comment by mostafaznv** [comment]
Hi @irazasyed 
thank you for your great package.

v4 is going to be released but the documentation is outdated yet :smile:
