### ISSUE TITLE
new line in sendMessage

### ISSUE THREAD

**Issue by nanangkoesharwanto** [irazasyed/telegram-bot-sdk#227]
![screenshot-web telegram org 2016-08-22 00-10-52](https://cloud.githubusercontent.com/assets/11191677/17840906/ee397a04-683b-11e6-8807-0e5251f2e27a.png)

```
$response = $telegram->sendMessage([
    'chat_id' => $chat_id, 
    'text' => 'Success! Your Telegram account with name <b>'.$first_name.' '.$last_name.'</b> has been added into iBridge data!.%0ABack to <a href="https://ibridgeapp.com/home">iBridge</a>',
    'parse_mode' => 'HTML'
]);
```
Using \n or %0A did not make a new line. any suggestion?

**Comment by tesmojones** [comment]
Please use \n inside double quotation mark ("), not in single quote (')

**Comment by ashfaqtech** [comment]
Please Use %0a for new Line (I try in PHP it's working)

**Comment by Samrat-Saha-Sammy** [comment]
> Please Use %0a for new Line (I try in PHP it's working)

Works fine with GET API request.

**Comment by wolfofficialss** [comment]
> Please Use %0a for new Line (I try in PHP it's working)
 
Any idea for mono text in php?
