### ISSUE TITLE
Telegram Webhook stop sending new updates

### ISSUE THREAD

**Issue by nanangkoesharwanto** [irazasyed/telegram-bot-sdk#228]
I've set a webhook and work well from yesterday until this morning, but on 10.AM, suddenly webhook does not send any update anymore.

Nothing changes on my bot setting and my script.

Then I remove and setwebhook again (https://ibridgeapp.com:443/telegram/callback), suddenly webhook sent me only old updates (data in the morning), not the new updates, even I send new messages to my bot.

I tried several times set-remove webhook, and only old updates comes not the new updates.

Any advice and helps are really help me.

**Comment by nanangkoesharwanto** [comment]
New info:
at 4:59 PM. my bot is working normally again.
I don't know why.

but now, i feel really happy. hope, never get the bot problem again.

**Comment by irazasyed** [comment]
Maybe their servers were down or something.

Telegram sent you old updates because they weren't marked as accepted/read by your server which is done by a simple response with HTTP status code 200. They attempt to send you a few times.

Glad it works fine for you now!
