### ISSUE TITLE
If a /command contains a newline, the bot doesn't receive the message at all

### ISSUE THREAD

**Issue by Lohoris** [irazasyed/telegram-bot-sdk#229]
I've noticed that if the arguments of a `/command` contain a newline, then the bot just doesn't receive anything.

I've searched in my code and wasn't able to find a bug my side. Of course I could be wrong, but it would be much easier if anyone else could test it.

**Comment by manzoorwanijk** [comment]
I have a bot that receives arguments with newline and it works perfectly. What do you mean by 

> the bot just doesn't receive anything

?
May be you need to check your code for handling commands...

**Comment by Lohoris** [comment]
I added the commands using `addCommands` and when users call them, they usually correctly receive the call to the `handle` function.

If there's any newline in the input, the bot still receives the message as a normal message, but the `handle` function apparently doesn't get called.

I've rechecked my code multiple times and I couldn't find any error, but if you confirm that `handle` gets called even if there are newlines in the input, then I'll post it somewhere for verification…

**Comment by Lohoris** [comment]
I've tested it some more, and I confirm this doesn't work.

Calling any /command, if there is any newline in the whole message, the bot will receive the message, but the command callback won't be called.

That is, I call `commandsHandler`, the callback just isn't called at all, but in the returned array I can see the message itself.

I called it twice in a row, once with a newline, once without, and I couldn't notice any particular difference between the two messages.

Looking at the library's source code, I guess the function `processCommand` might be failing the check `if ($message !== null && $message->has('text')) {` for some reason?
Or maybe it's the `handler` function that fails this other check?
```
        $match = $this->parseCommand($message);
        if (!empty($match)) {
```

**Comment by Lohoris** [comment]
I confirm the problem lies within the regexp of `parseCommand`, that receives the correct `$text` and produces an empty `$match` when there's a newline in the input.

**Comment by Lohoris** [comment]
Fixed adding an `s` to the end of the regexp, as otherwise the final `.` doesn't match newlines.

I'll try to fork and submit a pull request.

**Comment by irazasyed** [comment]
@Lohoris Thanks for debugging the issue. If you can send a PR, That would be great and would be appreciated.

If not, Will do it when I get some free time. Thanks!

**Comment by Lohoris** [comment]
I think I've sent it, no problem, and thank you for your great library!
