### ISSUE TITLE
Default command (command not found)

### ISSUE THREAD

**Issue by Bogdaan** [irazasyed/telegram-bot-sdk#232]
Hi, it posible set "default command", or 
determine witch command process current Update object?

Typical case - reply with some text after "unknow command".

UPD. 
Seems for now its impossible, problem:
https://github.com/irazasyed/telegram-bot-sdk/blob/d353035c7ad4729360698ce033426adba07fde30/src/Commands/CommandBus.php#L227

Why it return "Ok", and why default command = "help"?

UPD2.
Second problem:
https://github.com/irazasyed/telegram-bot-sdk/blob/d353035c7ad4729360698ce033426adba07fde30/src/Commands/CommandBus.php#L205

May be better to return object that contains the name of command + Update object?

**Comment by irazasyed** [comment]
Help is the default command, just create a new help command and replace the default register with your own command, it should then start working and responding as per your logic or the default is to just respond the list of available commands.

**Comment by Bogdaan** [comment]
@irazasyed i see that 'help' is default command. But I need to have 2 commands:
* "command not found"
* "help command"

"Command not found" purpose:
1. Try recognize user input by patterns (if not see №2)
2. Display text like "I'm sorry we could not recognize ...."

"Help command" purpose:
1. Show available commands
2. Show short manual

**Comment by irazasyed** [comment]
You can do that inside your Help command.

Inside the help command, check to see if it's a help command and if it's so, then respond with available commands or whatever and if it isn't, then that means it has been triggered because the command was not found in which case you can respond with "command not found" message or whatever message you'd like to send them.

**Comment by jonnywilliamson** [comment]
@Bogdaan 

Here's how I do it for my help command, its exactly what you are after:


```php
<?php

namespace App\Telegram\Bot\commands;

use App\Telegram\Bot\BotCommand;

class help extends BotCommand
{

    /**
     * @var string Command Name
     */
    protected $name = "help";

    /**
     * @var string Command Description
     */
    protected $description = "Need some help? Here's where you'll get some answers.";

    /**
     * @inheritdoc
     */
    public function handle($arguments)
    {
        $update = $this->getUpdate();

        if (starts_with($update->getMessage()->getText(), '/help')) {
                return $this->replyWithMessage(
                    [
                        'text'                     => view('telegramBot.commandHelp')->render(),
                        'disable_web_page_preview' => true,
                    ]);
            }
        }

        //Invalid command.
        return $this->replyWithMessage(
            [
                'text'                     => view('telegramBot.commandInvalid')->render(),
                'disable_web_page_preview' => true,
            ]
        );
    }
}
```

**Comment by Bogdaan** [comment]
@jonnywilliamson thanks for reply, this option is nice.

@irazasyed ok, but this part looks strange:

```
// first run some command
return $this->commands['help']->make($this->telegram, $arguments, $message);

// then again check command name
if (starts_with($update->getMessage()->getText(), '/help')) {
```
And this scheme will remain unchanged?

Anyway i close this issue (because "default command@ is possible), thanks for help.
