### ISSUE TITLE
Bot got banned by the user: Unhandled Exception

### ISSUE THREAD

**Issue by phpfs** [irazasyed/telegram-bot-sdk#234]
Hello!

My Server tried to send a notification today and the whole script crashed because an unhandled exception occurred. Cause: The Bot got banned by the user.

Unfortunately, I can't supply a stack trace. I am using v2.0.0!

How can I prevent my Script from crashing?

Greetings, phpfs

**Comment by phpfs** [comment]
Duplicate #169 

How can I prevent my Script from crashing?

**Comment by irazasyed** [comment]
Hi,

Catch the exception and mark the user as banned if you use database or something to record or black the user.
