### ISSUE TITLE
 require Composer's autoloader

### ISSUE THREAD

**Issue by mobasher92** [irazasyed/telegram-bot-sdk#236]
what does this line mean? 
After installing, you need to require Composer's autoloader if you want to use the library standalone:
require 'vendor/autoload.php';
where should I put this line?

**Comment by mobasher92** [comment]
is there a sample code for telegram bot with laravel so that i can check what's wrong with my code?

**Comment by mobasher92** [comment]
I'v installed a new version of laravel . I mean 5.1 and the $except array was not supported in laravel 5

but now i get this messge : "nothing to publish for tag []" when I run "php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider" after I set the providers and alias array in config file !

**Comment by mobasher92** [comment]
I have copied the config file manually and set the token but when in laravel I want to use "Telegram::...."
it gives me this error : "Class Telegram was not found ..."

how can i fix this?

**Comment by jonnywilliamson** [comment]
Please review the installation steps again carefully.

https://telegram-bot-sdk.readme.io/docs/getting-started

If you are using Laravel, there's no need (ie. you should not) follow the instructions for standalone mode.
