### ISSUE TITLE
Equivalent to BotFather's /setcommands?

### ISSUE THREAD

**Issue by Lohoris** [irazasyed/telegram-bot-sdk#237]
Is there a way using this sdk to trigger BotFather's `/setcommands`?

I add the commands using `addCommand` and they work, but they don't automatically get added to this list, and I couldn't find any way to do it that isn't talking to the BotFather using my main account.

**Comment by jonnywilliamson** [comment]
Not at the moment. It's still a manual process to add it to the bot father. 

I'm sure that @irazasyed would be open to any pull request you make though!

**Comment by irazasyed** [comment]
That can't be done through their API. BotFather itself is a separate bot and there isn't any API that I'm aware of to set commands in that bot.

If a bot can talk to a bot, then maybe we could add methods to send message with `/setcommands` and all the commands that are registered in SDK. Gotta test this!

**Comment by jonnywilliamson** [comment]
![image](https://cloud.githubusercontent.com/assets/2513663/18311167/c464f692-74fa-11e6-93c7-d1e36e53467c.png)


Just remembered. Bots can not talk to bots. From the docs.

**Comment by irazasyed** [comment]
So then this isn't possible!
