### ISSUE TITLE
Laravel 5.3 support

### ISSUE THREAD

**Issue by harrisnl** [irazasyed/telegram-bot-sdk#238]
Laravel 5.3 is not supported out-of-the box.
When installing I get this composer error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for irazasyed/telegram-bot-sdk ^2.0 -> satisfiable by irazasyed/telegram-bot-sdk[v2.0.0].
    - Conclusion: remove laravel/framework v5.3.6
    - Conclusion: don't install laravel/framework v5.3.6
    - irazasyed/telegram-bot-sdk v2.0.0 requires illuminate/support 5.0.*|5.1.*|5.2.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.1.30|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.1.31|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.1.41|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.2.19|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.2.21|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.2.24|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.2.25|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.2.26|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.2.27|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.2.28|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.2.31|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.2.32|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.2.37|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.2.43|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.2.45|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.0.22|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.0.25|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.0.26|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.0.28|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.0.33|don't install laravel/framework v5.3.6
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5.3.6
    - Installation request for laravel/framework (locked at v5.3.6, required as 5.3.*) -> satisfiable by laravel/framework[v5.3.6].

**Comment by irazasyed** [comment]
Laravel 5.3 is supported in `dev-master` branch. You can pull it using: `3.*@dev`.

It's yet to be tagged. Please note, There are some major changes that could break your code. Feel free to open an issue ticket if you face any issues. Thanks!

**Comment by harrisnl** [comment]
Great! thanks for the fast update
