### ISSUE TITLE
Why I cannot get the Firstname of the bot ?

### ISSUE THREAD

**Issue by hndr91** [irazasyed/telegram-bot-sdk#239]
This is my code
```
require 'vendor/autoload.php';
use Telegram\Bot\Api;
$telegram = new Api('MY_API');

$response = $telegram->getMe();

$botId = $response->getId();
echo $botId // this result just fine
$botFirstName = $response->getFirstName();
echo $botFirstName //return 0
$botUname = $response->getUsername();
echo $botUname //return nothing
```
I only able to print bot ID

**Comment by jonnywilliamson** [comment]
The response to a `getMe` request should look like this.

```json
{
    "ok": true,
    "result": {
        "id": 12345678,
        "first_name": "YourBot",
        "username": "YourBot"
    }
}
```

Why don't you see what you get back from the server:
```
require 'vendor/autoload.php';
use Telegram\Bot\Api;
$telegram = new Api('MY_API');

$response = $telegram->getMe();

var_dump($response);  // Or print_r()
```


Post it here and we can continue.

**Comment by hndr91** [comment]
Thanks Jonny, I got every value for id, fistname, and username from server. I have print into json_encode format and look like this

```{ "id": 2301xxxxx, "first_name": "bot first name", "username": "bot_username" }```

**Comment by jonnywilliamson** [comment]
Ok, so you have the data you need, now what happens when you do this:

```
require 'vendor/autoload.php';
use Telegram\Bot\Api;
$telegram = new Api('MY_API');

$result = $telegram->getMe();
$username = $result->getFirstName();

var_dump($username);
```

**Comment by hndr91** [comment]
it result bot's first name, everything just fine

**Comment by jonnywilliamson** [comment]
What version of this API are you using?

Did you install using composer? If so, run this command in the terminal where you have installed it
```
composer info | grep 'irazasyed/telegram-bot-sdk'
```

If you didn't use composer (why not?) run this in the terminal where the file `API.php` resides.

```
cat Api.php | grep 'VERSION'
```

**Comment by jonnywilliamson** [comment]
Excellent. Close the issue when you are happy its all working.

**Comment by hndr91** [comment]
i use v2.0.0 via composer, and everything is fine now. I able to print bot's first name. So, what happend actually ?
Thanks for your help ^^
