### ISSUE TITLE
Logical bug in Laravel ServiceProvider

### ISSUE THREAD

**Issue by morilog** [irazasyed/telegram-bot-sdk#241]
There is a logical bug in Laravel service provider at v2.0, you are register commands before registering Laravel container, so if a command has injected dependencies, those does not resolved and throw exception.

**Comment by jonnywilliamson** [comment]
Already fixed with https://github.com/irazasyed/telegram-bot-sdk/commit/d30613583ebe825283843ffa31257b83d7e447e7



Use the latest dev version if you need this at the moment. Warning there are a lot of BC in the new version.
