### ISSUE TITLE
get chat id 

### ISSUE THREAD

**Issue by mobasher92** [irazasyed/telegram-bot-sdk#242]
this is my code
`
ini_set('display_errors', 1);
	require "/usr/local/src/vendor/autoload.php";
	use Telegram\Bot\Api;

	$telegram = new Api('my_token');
	$fp = fopen("log.txt", "w+");
	
	$updates = $telegram->getWebhookUpdates();
	fputs($fp, sizeof($updates));
	
	foreach ($updates as $update) {
		fputs($fp, "5");
		$chatid = $update->getMessage()->getChat()->getid();
		fputs($fp, "6");
		/*$response = $telegram->sendMessage([
			'chat_id' => $chatid, 
			'text' => 'Hello World'
		]);*/

	}
`
after this line of code: "$chat = $update->getMessage()->getChat();" it does not work and nothing is logged in a file.
can you help me please?

when i remove the webhook the code works fine and send message but with webgook it does not work 
why?

**Comment by jonnywilliamson** [comment]
Could you run this code and show us what gets outputted?

```
$telegram = new Api('my_token');

$updates = $telegram->getWebhookUpdates();

var_dump($updates);
```

**Comment by mobasher92** [comment]
it works fine now. The problem was when you you user getupdates and there is no webhook you get all the updates and it's an array but when you have a webhook you get each update seperately and there is not need to loop through the getwebhookupdates' result

**Comment by jonnywilliamson** [comment]
Yes,

Please watch out when you update to version 3 (when it gets released) as these methods have very slightly changed name.
