### ISSUE TITLE
Add support for InlineKeyboards

### ISSUE THREAD

**Issue by corneyl** [irazasyed/telegram-bot-sdk#244]
It would be nice to have support for inline keyboards, see: https://core.telegram.org/bots/api#inlinekeyboardmarkup

**Comment by irazasyed** [comment]
That is already implemented in our `dev-master` branch. It's just not yet tagged.

You can install it using: `3.*@dev` version.

**Comment by corneyl** [comment]
Ah, great, I used the search function on top but it didn't return any results. I'll check it out!

**Comment by JaoNoctus** [comment]
I did not find the function in the dev version.
