### ISSUE TITLE
Can't use it with Laravel 5.3

### ISSUE THREAD

**Issue by simonardejr** [irazasyed/telegram-bot-sdk#247]
Hi! First, thanks for this awesome package, it really rocks!

But, I'm trying to "composer require irazasyed/telegram-bot-sdk" with a fresh Laravel 5.3 installation and getting this:

Problem 1
    - Installation request for irazasyed/telegram-bot-sdk ^2.0 -> satisfiable by irazasyed/telegram-bot-sdk[v2.0.0].
    - Conclusion: remove laravel/framework v5.3.9
    - Conclusion: don't install laravel/framework v5.3.9
    - irazasyed/telegram-bot-sdk v2.0.0 requires illuminate/support 5.0.*|5.1.*|5.2.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.0.22|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.0.25|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.0.26|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.0.28|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.0.33|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.1.30|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.1.31|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.1.41|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.2.19|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.2.21|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.2.24|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.2.25|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.2.26|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.2.27|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.2.28|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.2.31|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.2.32|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.2.37|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.2.43|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.2.45|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.3.9
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.3.9
    - Installation request for laravel/framework (locked at v5.3.9, required as 5.3.*) -> satisfiable by laravel/framework[v5.3.9].

am I missing something?

thanks and sorry for my bad english :-)

**Comment by irazasyed** [comment]
Thanks for trying this library and for creating this issue ticket.

So the Laravel 5.3 support is available in our `dev-master` branch which can be pulled by using `3.*@dev` version.

Please note, the V3 version has several breaking changes and is pending a release/documentation. So you gotta be careful when using it. Otherwise, It's packed with even more features and works great.

Hope that helps.

P.S. Your English is good. Not bad at all :)

**Comment by simonardejr** [comment]
great! thanks! :-)
