### ISSUE TITLE
Messages are not marked as read if sent with deep linking

### ISSUE THREAD

**Issue by codefuhrer** [irazasyed/telegram-bot-sdk#252]
Pay attention to the blue mark on the left:

![2016-09-26 03-15-44](https://cloud.githubusercontent.com/assets/2178368/18819338/ef92cd22-839f-11e6-9626-0d14edf51f89.png)

Branch dev-master, Laravel 5.3. I'm explicitly sending the HTTP 200 status in my command, but it still makes no sense with deep linking:
```php
public function handle(string $token)
{
    // Function body...

    Telegram::commandsHandler(true);

    return response('OK', 200);
}
```

**Comment by irazasyed** [comment]
That's something you need to talk to Telegram and find out what we can do about it. Because that's not under our control. The 200 status code method simply indicates we got the message and that's how Telegram thinks you accepted the message and won't re-send it but if it's a different behavior for deep-linking, then it's a problem from their end.

Not sure what we can do about it from the SDK unless they give a solution.

**Comment by jonnywilliamson** [comment]
@codefuhrer 

Hi, could someone explain "deep-linking" to me? 

Also, where was that picture taken? From a mobile telegram app or the  desktop client? 

I had previously sent Telegram a feature request asking them for a way for the webhook to get a response from telegram when the user read the message, but as far as I know this hasn't been implemented yet.

**Comment by irazasyed** [comment]
@jonnywilliamson https://core.telegram.org/bots#deep-linking

**Comment by codefuhrer** [comment]
Hi, @jonnywilliamson 

> could someone explain "deep-linking" to me? 

Deep linking means that you're passing some data to the bot along with the start command ([docs](https://core.telegram.org/bots#deep-linking)). 

> where was that picture taken

I'm using Telegram Web.

It turned out that bots don't "read" messages at all - the marking-as-read mechanism is implemented only client-side. Meaning that my problem is actually Telegram Web's bug.

**Comment by jonnywilliamson** [comment]
Thanks for the links/update guys.

Very fancy name for a simple URL!
