### ISSUE TITLE
/help Command not returning anything

### ISSUE THREAD

**Issue by fmcdigital** [irazasyed/telegram-bot-sdk#253]
/help on Bot conversation is not returning anything..

**Comment by jonnywilliamson** [comment]
There is so little information here there is no answer to your statement.

Please provide the steps you've taken, the code you've written and ALL messages/errors etc you have seen.

**Comment by fmcdigital** [comment]
I installed the package on Laravel 5.2, this package is working when sengind messages to Telegram and getUpdates is working too, but about the command /help it doesn't return the message on Telegram chat when typing /help to my Bot..

**Comment by ethangrant** [comment]
Do you have a post route set up like this:

```php
Route::post('/<token>/webhook', function () {
    $update = Telegram::commandsHandler(true);
  
  // Commands handler method returns an Update object.
  // So you can further process $update object 
  // to however you want.
  
    return 'ok';
});
```

Have a read through the documentation

https://telegram-bot-sdk.readme.io/docs/commands-system

**Comment by fmcdigital** [comment]
I read the docs, but I'll need to setup a webhook, and I got no https ssl for this.., but thanks for helping!

**Comment by irazasyed** [comment]
@fmcdigital You can get one SSL from [LetsEncrypt](https://letsencrypt.org/) or use [CloudFlare](https://www.cloudflare.com/), both are free and easy to setup.

Also, You need to register few commands before you can start using the `/help` command as it simply returns the list of registered commands. Nothing else.

Hope that helps. If you have any other issues. Feel free to create another issue, closing this one for now.
