### ISSUE TITLE
Maximum execution time of 180 seconds exceeded in vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php

### ISSUE THREAD

**Issue by decadence** [irazasyed/telegram-bot-sdk#255]
I use Laravel Facade and `irazasyed/telegram-bot-sdk: "^2.0"`

``` php
foreach ($telegram_users as $info) {
            Telegram::setAsyncRequest(true);

            $message = Telegram::sendMessage([
                "chat_id" => $info->chat_id,
                "text" => $message,
                "disable_web_page_preview" => true,
            ]);
}
```

I think it happens when users is more than one (and chat_id can be repeated).

With sync request all is fine.
With async PHP script just hangs.

Error Log:

```
PHP Fatal error:  Maximum execution time of 180 seconds exceeded in vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php on line 163
[28-Sep-2016 15:47:21 Europe/Moscow] PHP Stack trace:
[28-Sep-2016 15:47:21 Europe/Moscow] PHP   1. Telegram\Bot\HttpClients\GuzzleHttpClient->__destruct() vendor\irazasyed\telegram-bot-sdk\src\HttpClients\GuzzleHttpClient.php:0
[28-Sep-2016 15:47:21 Europe/Moscow] PHP   2. GuzzleHttp\Promise\unwrap() vendor\irazasyed\telegram-bot-sdk\src\HttpClients\GuzzleHttpClient.php:57
[28-Sep-2016 15:47:21 Europe/Moscow] PHP   3. GuzzleHttp\Promise\Promise->wait()
...
```

**Comment by Decadence** [comment]
If I use it in Artisan Command it's working ok.

**Comment by irazasyed** [comment]
- How many users are you trying to send this message to?
- What's your tech stack?

Also, You don't have to set `Telegram::setAsyncRequest(true);` before every request in loop. Just set this outside the loop once to apply it for all. It's a global config.

**Comment by Decadence** [comment]
3 users.

What is tech stack?
PHP 5.6, Apache 2.4 + Nginx 1.9

> Also, You don't have to set Telegram::setAsyncRequest(true); before every request in loop
I know. I just use this code in function with params $username, $message, $async = false and call it function for every user. Above code is just simplified version.
