### ISSUE TITLE
v3 any news ?

### ISSUE THREAD

**Issue by sohrabafard** [irazasyed/telegram-bot-sdk#256]

**Comment by irazasyed** [comment]
We were close to the release but the new official changes that were just reported today might delay V3 more or we may just as well release it for now.

In the meantime, you can use the `dev-master` branch already, though.

**Comment by kettari** [comment]
Could you please point me where dev-master branch is available? I don't see it in the list of branches: http://prntscr.com/cq20f0

**Comment by jonnywilliamson** [comment]
It's the development branch now.

https://github.com/irazasyed/telegram-bot-sdk/tree/develop
