### ISSUE TITLE
Get user ID by username?

### ISSUE THREAD

**Issue by cmpex** [irazasyed/telegram-bot-sdk#258]
Mea culpa if this is a dumb question and I'm just not able to read telegram's API correctly.

Is there a way to get a telegram user ID by doing a lookup by their username in a supergroup?

I want the bot to take action on a user by referencing their username like:
/kick @telegram_user

I'm not sure how to do a lookup of that username into the user ID.

Thanks in advance!

**Comment by manzoorwanijk** [comment]
It is not possible to get user object by passing a username.

The [documentation says](https://core.telegram.org/bots/api#kickchatmember) that _user_id_ (Unique identifier of the target user) for **kickChatMember** method has to be of **Integer** Type

**Comment by kettari** [comment]
No lookup is available. 

You have to store somewhere on your side information about users in the channel when they post to the group. Telegram provides in the Message object info about who sent the message, user_id and username (if it exists). You've to grab it and save. 

When /kick is issued, look at your data and kick user by user_id as @manzoorwanijk suggested.
