### ISSUE TITLE
Gaming platform

### ISSUE THREAD

**Issue by misterkek** [irazasyed/telegram-bot-sdk#259]
https://telegram.org/blog/games
https://core.telegram.org/bots/api#games

**Looks pretty good!**

**Comment by irazasyed** [comment]
Yep, We're looking into it.

We may implement all these for V3 or push it to the next version to avoid further delays. Lets see!

**Comment by irazasyed** [comment]
Added support in develop branch: https://github.com/irazasyed/telegram-bot-sdk/commit/d1f5269e052118abd36b3fef3afc900358d4ec2e
