### ISSUE TITLE
Telegram Slow Responding Bot

### ISSUE THREAD

**Issue by EnesShahn** [irazasyed/telegram-bot-sdk#264]
Hi,
soo i've been developing a bot for two weeks and i noticed a problem,
when i send lots of messages to bot at once (like 50 msgs) the script wont execute anymore (for like 1-3 mins depending on how many messages i've sent) .
soo i desided to check and see what causes the lag and i've created another script with only one request which is sendmessage and still same thing happens the script wont execute, i checked my server if there is a heavy load ,but the server runs fine! and i can execute the script manually while the bot lags soo its not a problem from my server . so if anybody has an idia how to fix this problem please help.
i apreciate that.

Regards,
Enes.

**Comment by irazasyed** [comment]
Hi,

Please provide with the following details:

- Your code:
- SDK version:
- PHP version:
- Tech stack (LEMP / LAMP):
- Server type (Shared/VPS/Dedicated):
- RAM:
- Log info (Post log file data):

**Comment by EnesShahn** [comment]
well i tried with a simple lines of code and still same thing happened, here is codes:
`<?php        
define('token', '55555555555:aaaaaaaaassssssssdddddddddwwwwwwqqqqqqqq');
define('url', 'https://api.telegram.org/bot' . token . '/');
$myChat_id = 999887765;
file_get_contents(url.'sendmessage?chat_id='.$myChat_id.'&text=TEST');
?>`
in this test script didnt use SDK.
php version: 5.6.
about Tech stack i am sorry i am new to web developemnt and i am not sure which one i am using.
RAM: 512M , i am pretty sure its not because of ram because when i send lots of messsages i see that only 100-200 MB used and i increased the memory_limit to 512 and still the same problem.
Log info: about this one i dont know do u mean error logs? if so there is no errors .
