### ISSUE TITLE
Wrong response from the webhook: 400 Bad Request

### ISSUE THREAD

**Issue by aminkt** [irazasyed/telegram-bot-sdk#266]
Hi.

I'm recently tried to use webhook to get update from telegram. my program work correctly whit getUpdates().
but when i set webhook i got 

> "Wrong response from the webhook: 400 Bad Request"

 error when try to check status of webhook by getWebhookInfo method.

here is my code:
`$telegram->commandsHandler(true)`
when is used below code in getUpdates mod every thing was fine.
`$telegram->commandsHandler(false)`

And is should say i use https and my ssl is ok.

This is answer of getWebhookInfo to me.
`{
  "ok": true,
  "result": {
    "url": "https://telbit.ir/api/bot/<token>",
    "has_custom_certificate": false,
    "pending_update_count": 13,
    "last_error_date": 1476344420,
    "last_error_message": "Wrong response from the webhook: 400 Bad Request"
  }
}`

**Comment by irazasyed** [comment]
When you get a webhook request, you need to respond with 200 status code or just return 'ok' or something. That gives confirmation to Telegram that your server accepted their update.

**Comment by AntoLuMeju99** [comment]
How to respond with 200 status or return ok?

**Comment by aminkt** [comment]
@AntoLuMeju99 In your webhook route set http status code 200 in all cases.

**Comment by AntoLuMeju99** [comment]
What u mean?

**Comment by Xibel** [comment]
Route::post('/YourSecretPathToTheWebhookURI/webhook', function () {
    $update = Telegram::commandsHandler(true);
    **return 'ok';**
});

**Comment by rowlin** [comment]
Mby ..Csrf verification need turn off for  route

пт, 17 мая 2019 г., 15:33 Xibel <notifications@github.com>:
