### ISSUE TITLE
create custom keywords

### ISSUE THREAD

**Issue by HaMo0n** [irazasyed/telegram-bot-sdk#27]
Hi all.
I want to create a custom keywords for my robot like this pic
https://core.telegram.org/file/811140184/1/5YJxx-rostA/ad3f74094485fb97bd
This custom keywords has a command (/1 or /2 or /3) and has a description.
I want to show description on keywords but when a user tap a button, The command will be send.

**Comment by irazasyed** [comment]
Hey @HaMo0n 

That is not possible. The custom keyboard can't have different value while showing another description.

You have to add support to process slash options like /1 /2 /3 and also the exact description.
