### ISSUE TITLE
send message with inline keyboard

### ISSUE THREAD

**Issue by aminbag** [irazasyed/telegram-bot-sdk#270]
I wanna send message with inline keyboard.
can u help me to do this?

**Comment by irazasyed** [comment]
Do you use with Laravel or without?

**Comment by irazasyed** [comment]
Here's an example on how to use it in 3.x:

```php
use Telegram\Bot\Keyboard\Keyboard;
use Telegram;

$keyboard = Keyboard::make()
    ->inline()
    ->row(
        Keyboard::inlineButton(['text' => 'Test', 'callback_data' => 'data']),
        Keyboard::inlineButton(['text' => 'Btn 2', 'callback_data' => 'data_from_btn2'])
    );

$response = Telegram::sendMessage([
  'chat_id' => 'CHAT_ID', 
  'text' => 'Hello World',
  'reply_markup' => $keyboard
]);

$messageId = $response->getMessageId();
```

The above should work right now but in develop branch, this has been changed too. So you gotta keep an eye when it's released and upgrade your codes.

**Comment by khalilst** [comment]
@irazasyed Can you please tell me us how to update a message with inline keyboard.
I saw for example in @vote bot, clicking at inline button update whole message and its inline keyboard to brand new one.
How they did it? Delete & resend new message with new inline keybord?
Any help appreciated

**Comment by khalilst** [comment]
I guess,  I found the answer. editMessageText is exactly what I'm looking for.
@irazasyed  BTW, thanks for your great work. Waiting for version 3.0 and its documentation.

**Comment by prayogaep** [comment]
i can't fix this error, help :(
<img width="941" alt="image" src="https://user-images.githubusercontent.com/65759432/201464659-3a562e36-cce2-4e8f-b47f-da8828709ae9.png">

**Comment by prayogaep** [comment]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/65759432/201464682-c38ced7f-c2e7-4c7c-aa3d-bbd1180dcd8d.png">
<img width="843" alt="image" src="https://user-images.githubusercontent.com/65759432/201464727-4170991e-3bf6-443a-98e6-b944c5d41317.png">

i can't fix this error , help

**Comment by prayogaep** [comment]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/65759432/201464745-85acf259-8e33-4e8f-b8b6-cee1fda7d6db.png">
<img width="954" alt="image" src="https://user-images.githubusercontent.com/65759432/201464752-99adbb7a-d76a-4234-8c03-f3521099e81a.png">
help me :(

**Comment by prayogaep** [comment]
Method [replyKeyboardMarkup] does not exist.

how to fix this ?
