### ISSUE TITLE
Is it possible to reply with custom message in keyboard?

### ISSUE THREAD

**Issue by Alvaroctal** [irazasyed/telegram-bot-sdk#271]
Hi,

I'm trying to achieve the following..., a bot where firstly I ask for a queue of request, and then it return one of them with a keyboard of 2 options `OK`, `deny`.

```php
$keyboard = [
    ['Nope', 'OK']
];

$reply_markup = $this->telegram->replyKeyboardMarkup([
    'keyboard' => $keyboard, 
    'resize_keyboard' => true, 
    'one_time_keyboard' => true
]);

$this->replyWithMessage(['text' => $response, 'reply_markup' => $reply_markup]);
```

So, my bot currently supports only command input, is there a way to send a custom command on button pressed? I mean, if I press Ok, my telegram client should say:

`/approve <some id>`

thanks in advance.

**Comment by kettari** [comment]
Hi,

Telegram client should send the text on the button — please refer to the documentation: 

> Text of the button. If none of the optional fields are used, it will be sent to the bot as a message when the button is pressed 
[https://core.telegram.org/bots/api#keyboardbutton](url)

So the answer to your question is: No.

But, you can use CallbackQuery to hide the request/reply from the sight of the user. A little bit complicated, though. [https://core.telegram.org/bots/api#callbackquery](url)
