### ISSUE TITLE
Make unexisting methods explicit

### ISSUE THREAD

**Issue by auburus** [irazasyed/telegram-bot-sdk#272]
I'm having trouble trying to understand the purpose of [this line](https://github.com/irazasyed/telegram-bot-sdk/blob/v2.0.0/src/Api.php#L1066)

```php
public function __call($method, $arguments)
    {
        $action = substr($method, 0, 3);
        if ($action === 'get') {
            /* @noinspection PhpUndefinedFunctionInspection */
            $class_name = studly_case(substr($method, 3));
            $class = 'Telegram\Bot\Objects\\'.$class_name;
            $response = $this->post($method, $arguments[0] ?: []);
            if (class_exists($class)) {
                return new $class($response->getDecodedBody());
            }
            return $response;
        }
        return false; // <--- This line right here
    }
```

I propose that if a method is not found, let's throw a `\BadMethodCallException`, or something similar...

PS: Yes, I've had a hard time figuring out why the api wasn't performing as expected, until I figured out I had a typo in a method name and this function was throwing away the error.
Does it break BC?

**Comment by irazasyed** [comment]
The new changes no longer returns false and instead makes an API call (In case there's a new one added but it's not updated in SDK), it'll then return an unknown object. Please check develop branch.
