### ISSUE TITLE
How to send Message twice

### ISSUE THREAD

**Issue by nubotz** [irazasyed/telegram-bot-sdk#273]
Hi there,
I notice that if I use
$telegram->sendMessage();//first time
$telegram->sendMessage();//second time
would only send once.
the response returned from them are same.
Any idea?

Thanks.

**Comment by sloothword** [comment]
It does send twice for me.
Maybe give the whole code snippet?
What method arguments are you using?

Which (exact) version do you have?

**Comment by nubotz** [comment]
```
	case "/report_down":
	case "/report_down".$bot_id:
		$response = $telegram->sendMessage([
			'chat_id'=>$chat_id,
			'text'=>"okok, already reported. Will check what happened..."
			]);
		_log("first_response " . $response);
		$reponse = $telegram->sendMessage([
			'chat_id'=>133535750,
			'text'=>"[$user_first_name][@$username] reported server down."
		]);
		_log("second_response " . $response);
		//file_get_contents($website."/sendMessage?chat_id=133535750&text=[$user_first_name][@$username] reported server down.");
		break;
```

The response I get is this:

> first_response {"message_id":19877,"from":{"id":213916267,"first_name":"YouTube MP3","username":"u2bu_mp3_bot"},"chat":{"id":133535750,"first_name":"Kel","username":"nubotz","type":"private"},"date":1477787905,"text":"okok, already reported. Will check what happened..."}
> second_response {"message_id":19877,"from":{"id":213916267,"first_name":"YouTube MP3","username":"u2bu_mp3_bot"},"chat":{"id":133535750,"first_name":"Kel","username":"nubotz","type":"private"},"date":1477787905,"text":"okok, already reported. Will check what happened..."}
> 

so I use file_get_contents to send the second message at the moment. Any idea? Thanks.

The sdk version I use (I use develop branch):
commit d218787c3dd74f5a41e909b4ed3c8a0a61210665
Merge: 942f989 f243b5f
Author: Syed I.R <syed@lukonet.com>
Date:   Wed Oct 5 23:05:26 2016 +0530
    Merge branch 'develop' of github.com:irazasyed/telegram-bot-sdk into develop

**Comment by sloothword** [comment]
You wrote $reponse once instead of $response.
Correct that and try again :-)

**Comment by irazasyed** [comment]
Good catch @sloothword

**Comment by nubotz** [comment]
@sloothword  Thanks for pointing out the mistake.
However, I corrected the variable name as still get the same result.
```
	case "/report_down":
	case "/report_down".$bot_id:
		$response1 = $telegram->sendMessage([
			'chat_id'=>$chat_id,
			'text'=>"okok, already reported. Will check what happened..."
			]);
		_log("first_response1 " . $response1);
		$response2 = $telegram->sendMessage([
			'chat_id'=>133535750,
			'text'=>"[$user_first_name][@$username] reported server down."
		]);
		_log("second_response2 " . $response2);
		//file_get_contents($website."/sendMessage?chat_id=133535750&text=[$user_first_name][@$username] reported server down.");

		break;
```
The response still the same.
More importantly, since the message is sent to myself. I only got first message in telegram.

**Comment by jonnywilliamson** [comment]
@nubotz Hi there. I think we've found the source of the bug you're experiencing and we're looking into it.

**Comment by nubotz** [comment]
@jonnywilliamson cool. thanks.

**Comment by irazasyed** [comment]
@nubotz Pushed a fix. Please try now. It should work fine.
