### ISSUE TITLE
webhook  URL 

### ISSUE THREAD

**Issue by jijoamt** [irazasyed/telegram-bot-sdk#274]
Can i set the same webhook  URL for multiple bots . Say i have a BOT1 and BOT2 . Can i set example.com/webook  as the webhook url for both these bots. If so how can i know from which bot was the message ?

**Comment by misterkek** [comment]
Why do you want to mix this?

Use **example.com/webhook/bot1.php** for Bot 1 
and 
**example.com/webhook/bot2.php** for Bot 2.

**Comment by jijoamt** [comment]
Just wanted to know, if we can use the same url for 2 bots. WIll telegram allow it

**Comment by irazasyed** [comment]
Telegram will allow it. That's not a problem.

But you need a way to distinguish between your bots. The way I do it is:

`domain.com/{bot}/webhook`

Setup a POST route in Laravel and when a request comes in through, I can then know for which bot it is and pass it on to the bots manager.
