### ISSUE TITLE
How to use InlineQueryResultCachedAudio?

### ISSUE THREAD

**Issue by misterkek** [irazasyed/telegram-bot-sdk#277]
How to use InlineQueryResult**Cached**Audio? 
I'm sent "fileid" to "audio_file_id", but received in bot "Bad Request: AUDIO_CONTENT_TYPE_EMPTY".

```
$i=1;
$result = mysqli_query($db, "SELECT fileid FROM fileid limit ".$next_offset.",10");
$query = array();
while($row = mysqli_fetch_assoc($result)) {
    $query[] = $row;
}
if ($query){
   $next_offset=$next_offset+10;
   foreach ($query as $re) {
      $results[] =  [
      'type'         => 'audio',
      'id'           => "$i",
      'audio_file_id'    => trim($re['fileid']),
      ];
      $i++;
   }
   $params = compact('inline_query_id', 'results', 'next_offset');
}
try{
   $rs = $telegram->answerInlineQuery($params);
} catch(Exception $e){
   $response = $telegram->sendMessage([ 'chat_id' => XXXXXXX, 'text' => $e->getMessage() ]);
}
```

**Comment by misterkek** [comment]
Any ideas?

**Comment by sloothword** [comment]
Could you give me some more details?

Where did you get the `fileid` from? How does this string look like?

Does InlineQueryResultAudio without a cached file work?

**Comment by misterkek** [comment]
> Where did you get the fileid from? 

I had previously sent a file to bot (using method `sendAudio`) to get a `fileid`.

`fileid` looks like 'BQADAwXXXerAAoB_msowy3NdBYckwI'. If I use this `fileid` with `sendAudio`, it works. Example: 

```
foreach ($res as $re) {
                $response = $telegram->sendAudio([ 
                    'chat_id' => 123456, 
                    'audio' => 'BQADAwXXXerAAoB_msowy3NdBYckwI',
                    'performer' => 'example',
                    'title' => 'example',
                    ]);
            }
```

But when I pass this `fileid` in Inline Mode, it doesn't. Example code I wrote in a first message.

**Comment by irazasyed** [comment]
@misterkek Here's how you'd use that:

```php
use Telegram\Bot\Objects\InlineQuery\InlineQueryResultCachedAudio;

// Fluent Example
$results[] = InlineQueryResultCachedAudio::make()
        ->setId(1)
        ->setAudioFileId($audioFileId);

// Params example
$params = [
  'id' => 1,
  'audio_file_id' => $audioFileId,
];

$results[] = InlineQueryResultCachedAudio::make($params);
```

Let me know if you're able to get it and it works?

**Comment by misterkek** [comment]
@irazasyed 
Tried like this:
```
use Telegram\Bot\Objects\InlineQuery\InlineQueryResultCachedAudio;
try{
     $results[] = InlineQueryResultCachedAudio::make()
        ->setId("1")
        ->setAudioFileId("BQADAgADIAkXXXX_mArzR4rXXXXXAI");
     $params = compact('inline_query_id', 'results');
     $rs = $telegram->answerInlineQuery($params);
} catch(Exception $e){
     $telegram->sendMessage([ 'chat_id' => 123123, 'text' => $e->getMessage() ]);
}
```
But I recieved the same error: "Bad Request: AUDIO_CONTENT_TYPE_EMPTY". 

I made `print_r`:

```
Array
(
    [inline_query_id] => 123123123
    [results] => Array
        (
            [0] => Telegram\Bot\Objects\InlineQuery\InlineQueryResultCachedAudio Object
                (
                    [items:protected] => Array
                        (
                            [type] => audio
                            [id] => 1
                            [audio_file_id] => BQXXXXgADIAkXXXX_mArzR4rXXXXwIAI
                        )
                )
        )
)
```

When I tried another type of content `Article` with a code that I used in first message and it works. `print_r` looks:
```
Array
(
    [inline_query_id] => 123123123
    [results] => Array
        (
            [0] => Array
                (
                    [type] => article
                    [id] => 1
                    [title] => Title
                    [message_text] => asdasd
                    [description] => sdf
                )
        )
)
```
It seems that Audio Type has an extra array.

**Comment by irazasyed** [comment]
@misterkek What you're seeing is an output that has not been processed yet. Meaning, before an API call, that data gets properly encoded in json format (As per requirement from Telegram) and then it's sent.

As far as the audio issue is concerned, you need to check whether that audio ID is correct or not, then whether that file still exists on Telegram server, etc.

As far as I know, the IDs do get expired (I might be wrong but some time ago I did notice that happening).

So the best way to debug right now is to send a new valid audio file, get its id and then try it out.
