### ISSUE TITLE
CommandHandler vs file_get_contents

### ISSUE THREAD

**Issue by MostafaQanbaryan** [irazasyed/telegram-bot-sdk#278]
Hello and Thank you for your great works.
When using `$telegram->commandsHandler(true);` I can get **$text** and **$chatId** in my **webhook**. So what's the use of `json_decode(file_get_contents('php://input'),true);` ?

**Comment by irazasyed** [comment]
Hey!

You don't need to use `json_decode(file_get_contents('php://input'),true);` anywhere.

You can either use `$telegram->commandsHandler(true);` if you want the system to handle the commands or use `$telegram->getWebhookUpdate();` (`3.*`).

FYI, `json_decode(file_get_contents('php://input'),true);` is internally used to get data sent by Telegram to your Webhook.

I hope that answers your question.

Thanks!
