### ISSUE TITLE
Making requests when getting updates

### ISSUE THREAD

**Issue by 9px** [irazasyed/telegram-bot-sdk#28]
hi. telegram [recently](https://core.telegram.org/bots/api#making-requests-when-getting-updates) add an ability to perform a request to the telegram Bot API while sending an answer to the webhook.
can you do a simple implement of this feature in your bot?

**Comment by irazasyed** [comment]
Hi,

Can you tell me a real world use case for this?

Also, Are you aware that, you won't get any results when you make such a request?

You could simply use the `sendMessage()` or `replyWithMessage()` (If you're responding from a command). Let me know.

**Comment by 9px** [comment]
>Can you tell me a real world use case for this?

yes. for example for reply a command that received from user.

when a user send a command to robot, server received it in 1 connection.
When we send an answer to the user (for example with `sendMessage` method), this is another connection.
This new telegram bot feature is great. because it save 1 connection :)
so server can process double request simultaneously.

**Comment by irazasyed** [comment]
Here's how that would work (If you're on Laravel):

```php
Route::post('/webhook', function () {
    $update = Telegram::getWebhookUpdates();
    $chat_id = $update->getMessage()->getChat()->getId();

    Telegram::sendChatAction($chat_id, 'typing');

    $method = 'sendMessage';
    $text = 'This is a demo...!';

    $content = http_build_query(compact('method', 'chat_id', 'text'));
    return response($content)
            ->header('Content-Type', 'application/x-www-form-urlencoded');
});
```

I'll think of a way to implement this in the project itself. But in the mean time, You can use the above.

**Comment by jonnywilliamson** [comment]
@9px - Hi! Could you tell why you think the send on reply is so useful? Apart from reducing a connection, it provides no information on wither your message was sent correctly etc.

That seems like a much bigger disadvantage than the benefit you get back!?

I'd love to know what you plan to use this for as I can't think of anything and I'm interested to make sure I'm not missing out!

**Comment by jonnywilliamson** [comment]
@9px Any more info?
