### ISSUE TITLE
Version 2.1 still contains code of 2.0

### ISSUE THREAD

**Issue by georgjaehnig** [irazasyed/telegram-bot-sdk#281]
Hi,

seems like the release for version 2.1 by mistake contains the code of 2.0. All the new `answer` functions are missing and `src/Api.php` contains

    const VERSION = '2.0.0';
 
I've downloaded the code directly from https://github.com/irazasyed/telegram-bot-sdk/releases/tag/v2.1.0

**Comment by irazasyed** [comment]
Hey!

It was released just to support Laravel 5.3. There are no changes in it.

As far as that version update in Api file is concerned, That's a mistake and I'll bump it in next patch but honestly it shouldn't matter.

All the new changes, etc. are in `dev-master` branch which is pending release for V3.

**Comment by georgjaehnig** [comment]
Ah, thanks for the info!

So I only see the branches `master` and `develop` – is `master` the one you mean?

My goal is to use `answerInlineQuery()` and I'm looking for the easiest/best way to do it. Right now, I have manually cloned the Github repo and have the branch `master` checked out. 

And this line which under 2.0 works fine...

    $update = $telegram->getWebhookUpdates();

now throws an error:

    PHP Fatal error:  Class 'League\\Event\\AbstractEvent' not found in /home/ffit/htdocs/ffit/dev/drupal/profiles/serchilo_profile/vendor/irazasyed/telegram-bot-sdk/src/Events/UpdateWasReceived.php on line 10

Did the API change?

**Comment by georgjaehnig** [comment]
Just figured it out myself. A new dependency got added, and I need to put 

    "require": {
        "irazasyed/telegram-bot-sdk": "dev-master"
    }

into my `composer.json`.

**Comment by holtkamp** [comment]
@georgjaehnig so this issue can be closed?

**Comment by georgjaehnig** [comment]
Yes, it can!

**Comment by irazasyed** [comment]
@holtkamp V3 is stuck with a lot of on-going things like pending tests, decoupling (which has been the primary goal and in-progress), docs and some minor tweaks. I don't think I would be able to tag it anytime soon.

That said, You can still pull in using `3.*@dev` but expect several major changes.

**Comment by thegmacv** [comment]
@georgjaehnig @irazasyed  I have the same issue : 

> Fatal error: Class 'League\Event\AbstractEvent' not found in C:\xampp\htdocs\vendor\irazasyed\telegram-bot-sdk\src\Events\UpdateWasReceived.php

I added the following to the `composer.json` but still getting the error above
```
"require": {
    "irazasyed/telegram-bot-sdk": "dev-master"
}
```

I'm using the master branch, Please help asap
