### ISSUE TITLE
problem with setwebhook

### ISSUE THREAD

**Issue by hrzrahimi** [irazasyed/telegram-bot-sdk#282]
hi
I installed the last version, every things work correctly except when I setwebhook.

I set my url in telegram api : 
https://api.telegram.org/bot<token>/setWebHook?url=<secure-url>

when I run this url manually in my browser, route call controller and work correctly. But when I send text to the Bot, route does not call controller and it's stop on the route

I tested all method such as Get, Post, Put and ....

How can I solve this problem ?

**Comment by ItsOnlyMeNL** [comment]
I have set it up in a different controller: routes:

```
Route::get('/api/v1/telegrambot/setwebhook', 'Admin\indexController@setWebhook');
Route::get('/api/v1/telegrambot/unsetwebhook', 'Admin\indexController@unsetWebhook');
```

And the controller with the functions:

```
public function setWebhook()
  {
    $response = Telegram::setWebhook([
      'url' => 'https://my-telegram.url.here/location/to/webhook-link',
    ]);
    dd($response);
  }

  public function unsetWebhook()
  {
    $response = Telegram::removeWebhook();
    dd($response);
  }
```

This works for me.

**Comment by firegore2** [comment]
I have the same problem but I have the version 2.0

**Comment by irazasyed** [comment]
@hrzrahimi Are you trying to set webhook URL to this one: 
```
https://api.telegram.org/bot/setWebHook?url=
```
?

That's not how you setup a webhook. Please refer docs and also see @ItsOnlyMeNL's example.

@firegore2 What problem are you facing? Please create a new issue ticket with more details.
