### ISSUE TITLE
Command to handle incoming location / user / xyz object

### ISSUE THREAD

**Issue by holtkamp** [irazasyed/telegram-bot-sdk#283]
First of all thumbs up for this library, interesting 😄 

I noticed that the current Command handling only [deals with text messages](https://github.com/irazasyed/telegram-bot-sdk/blob/v2.1.0/src/Api.php#L872-L874). It would be nice to also have a Command being handled when a User sends its Location. So instead of using a condition like:```php $message->has('text')```, it might be an idea to use ```php $command->isApplicableForMessage($message) ```

**Comment by jonnywilliamson** [comment]
You are getting slightly confused.

Commands are ALWAYS only "text messages"
![image](https://cloud.githubusercontent.com/assets/2513663/20146219/e65946aa-a69a-11e6-8452-c4eb528ae12c.png)

Processing commands by looking for the text field is the correct way to go.

However you may be talking about UPDATE objects instead. There are only 5 types of UPDATE objects that telegram will send your webserver:

![image](https://cloud.githubusercontent.com/assets/2513663/20146121/91798410-a69a-11e6-914c-f567ac4c9c69.png)

In the case of commands they arrive inside a "message" update object (or even an "edited_message" Update object). An Update object can also contain the Location type of message you want as well....and it just happens to be the "message" update object too.

So what you actually want is an Update Manager that will have a look at inbound Updates and decide what it wants to do when it detects a location, or a video or a audio file etc etc.


I raised this with @irazasyed at the start of this year and he very kindly whipped up this manager class for me which I have used since and it has been wonderful.

I'll leave it here in case it helps someone.


```php
//UpdatesManager.php
//Detects what type of update object we have received, and **IF** we have registered a class to deal with that type of object, sent it to it.

<?php
namespace App\Telegram\Bot\Handlers;

use Telegram\Bot\Objects\Update;

class UpdatesManager
{
    /**
     * @var Update
     */
    protected $update;

    /**
     * @var array Update Handlers
     */
    protected $handlers;
    /**
     * @var string
     */
    protected $botName;

    /**
     * UpdatesManager constructor.
     *
     * @param Update $update
     * @param array  $handlers
     * @param        $botName
     */
    public function __construct(Update $update, array $handlers, $botName)
    {
        $this->update = $update;
        $this->handlers = $handlers;
        $this->botName = $botName;
    }

    /**
     * Invoke appropriate update handler.
     *
     * @return mixed
     */
    public function process()
    {
        $updateType = $this->detectUpdateType();

        if (isset($updateType, $this->handlers[$this->botName][$updateType])) {
            $handler = $this->handlers[$this->botName][$updateType];

            return (new $handler($this->update, $this->botName))->handle();
        }

        return false;
    }

    /**
     * Determine if a given type is the update.
     *
     * @param string $type
     *
     * @return bool
     */
    public function isUpdateType($type)
    {
        if ($this->update->has(strtolower($type))) {
            return true;
        }

        return $this->detectUpdateType() === $type;
    }

    /**
     * Detect Update Type Based on Update Object Provided.
     *
     * @return string
     */
    public function detectUpdateType()
    {
        $types = [
            'message',
            'inline_query',
            'chosen_inline_result',
            'callback_query',
        ];

        return $this->update
            ->keys()
            ->intersect($types)
            ->pop();
    }
}
```


So, for example, if I wanted a class to manage all MESSAGE UPDATE objects, this is a rough idea how it would look  (This class is just pseudo code DO NOT TRY AND USE IT! - you would have to make this the way you want to deal with inbound messages/objects)

```php
<?php

namespace App\Telegram\Bot\Handlers;

class MessageHandler extends Handler
{
    /**
     * If an update object has a class that can process it, send it to the queue
     * for processing.
     *
     * @return bool|mixed
     */
    public function handle()
    {
      $taskName = $this->doStuffWithUpdateObject();

      $this->dispatch((new $taskName())->onQueue('myOutboundQueue'))
    }

    /**
     * Returns the name of the class that will process the update message object
     *
     * @return string
     */
    protected function doStuffWithUpdateObject()
    {
       //Is this object a command?
       // Either process command
       // If not, is it an audio update or a document etc.
      // Do logic for what you want returned etc.
    }

    /**
     * Detects if the Update is a command?
     *
     * @return bool
     */
    protected function isCommand()
    {
        $message = $this->update->getMessage();

        if ($message->has('entities')) {
            foreach ($message->getEntities() as $entity) {
                if ($entity['type'] == 'bot_command' && $entity['offset'] == 0) {
                    return true;
                }
            }
        }

        return false;
    }

    /**
     * Detect Message Type Based on Update Object Provided.
     *
     * @return string
     */
    protected function detectMessageType()
    {
        $types = [
            'text',
            'audio',
            'document',
            'photo',
            'sticker',
            'video',
            'voice',
            'contact',
            'location',
            'venue',
            'new_chat_member',
            'left_chat_member',
            'new_chat_title',
            'new_chat_photo',
            'delete_chat_photo',
            'group_chat_created',
            'supergroup_chat_created',
            'channel_chat_created',
            'migrate_to_chat_id',
            'migrate_from_chat_id',
            'pinned_message',
        ];

        return ucfirst($this->update->getMessage()
            ->keys()
            ->intersect($types)
            ->pop());
    }
}
```


Then in my controller that receives the Update object from Telegram hitting my webhook, I register what handlers I want to use:

```php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Telegram\Bot\BotsManager;
use App\Telegram\Bot\Handlers\UpdatesManager;

class TelegramBotController extends Controller
{
    /**
     * @var BotsManager
     */
    protected $telegram;

    protected $handlers = [
        'mybot' => [
            'message'      => \App\Telegram\Bot\Handlers\MyBot\MessageHandler::class,
//            'inline_query' => \App\Telegram\Bot\Handlers\MyBot\InlineQueryHandler::class,
//            'chosen_inline_result' => \App\Telegram\Bot\Handlers\MyBot\ChosenInlineResultHandler::class,
//            'callback_query'       => \App\Telegram\Bot\Handlers\MyBot\CallbackQueryHandler::class,
// Etc etc
        ],
    ];


    public function __construct(BotsManager $telegram)
    {
        $this->telegram = $telegram;
    }

    /**
     * Processes an inbound post/update from the Telegram servers.
     *
     * @param $bot The bot name in use.
     *
     * @return string
     */
    public function webhook($bot)
    {
        //Get Update Object
        $update = $this->telegram->bot($bot)->getWebhookUpdates();

        //Handle all types of Update Objects if needed.
        (new UpdatesManager($update, $this->handlers, $bot))->process();

        return response('Ok');
    }
}
```


Take your time to go through it, and thank @irazasyed for giving me the bases to start this.

**Comment by holtkamp** [comment]
wow, @jonnywilliamson thanks for the detailed response!

My point was/is: currently the [Api::processCommand()](https://github.com/irazasyed/telegram-bot-sdk/blob/v2.1.0/src/Api.php#L868-L875) determines whether to 'process' a Command, or not. This is done by checking whether the message carries some text. Ok, maybe in Telegram terminology a "Command is always text". 

You are pointing out a way on how to create a _mapping_ between Commands and Handlers (which is a cleaner way, I agree). 

But for simplicity's sake: why not defer the responsibility of "can an incoming message be processed" to the Command itself, _defaulting_ to:

```php
function isApplicableForMessage($message) : bool
{
    return $message->has('text');
}
```

Now when I look at an incoming Location update (a user that sends its location as an 'attachment' to the bot, so no Command style text is involved):

```
object(Telegram\Bot\Objects\Update)#12546 (1) {
  ["items":protected] => array(2) {
    ["update_id"] => int(007)
    ["message"] => object(Telegram\Bot\Objects\Message)#12400 (1) {
      ["items":protected] => array(5) {
        ["message_id"] => int(672)
        ["from"] => object(Telegram\Bot\Objects\User)#12384 (1) {
          ["items":protected] => array(3) {
            ["id"] => int(007)
            ["first_name"] => string(5) "Name"
            ["last_name"] => string(8) "Holtkamp"
          }
        }
        ["chat"] => object(Telegram\Bot\Objects\Chat)#11933 (1) {
          ["items":protected] => array(4) {
            ["id"] => int(007)
            ["first_name"] => string(5) "Name"
            ["last_name"] => string(8) "Holtkamp"
            ["type"] => string(7) "private"
          }
        }
        ["date"] => int(1478725452)
        ["location"] => object(Telegram\Bot\Objects\Location)#12342 (1) {
          ["items":protected] => array(2) {
            ["latitude"] => float(XYZ)
            ["longitude"] => float(XYZ)
          }
        }
      }
    }
  }
}
```

There we can see the ```location``` entry. So in that case a Command dealing with this, could override the default 'matching' function:

```php
function isApplicableForMessage($message) : bool
{
    return $message->has('location');
}
```

I hope this clarifies the idea a bit. A user sends his location to a bot (no actual "/command" involved).

**Comment by irazasyed** [comment]
Why do you need a command to handle location or contact when you're free to process that the way you like it?

I don't see a point of this TBH.

If it's not a command, you can simply process that based on the incoming update which is return by the commandsHandler method. So you can then apply your logic and process the incoming update as you like it.

**Comment by holtkamp** [comment]
>I don't see a point of this TBH.

Well, the point is (from my perspective): to use the CommandHandler to deal with any kind of incoming message, reducing amount of boilerplate code to process the incoming update. 

I would say it is low hanging fruit to realize a very flexible and future proof setup. Now Commands are limited to dealing with text... why hard code this limitation?

As you suggested, currently we process the updates "ourselves" first, then let the CommandHandler kick in and do its trick, feels double...

**Miscommunication?**

>If it's not a command, 

I think I caused some miscommunication because of my interpretation of the concept of Command:

- when using the pure Telegram definition of Command (```/commandTestHere```), ok, than my suggestion is confusing... sorry about that
- when using a more general definition of Command (as typically used on a [CommandBus](http://simplebus.github.io/MessageBus/doc/command_bus.html)), then also Contacts of Location can be handled by such a Command/Handler mechanism. When new concepts are introduced in the future, the mechanism does not have to change...

Well, just my 2 cents 😄

**Comment by mvggit** [comment]
Sorry!
Please understand to me this part:
$this->update->getMessage()
            ->keys()
            ->intersect($types)
            ->pop()
Where getMessage() getting keys method etc.

I have strong error "Call to a member function keys() on null". That is it ?

**Comment by mvggit** [comment]
$message->has('entities') this have problem to. Update can't do has method.

**Comment by firegore2** [comment]
How to get all Entities with the API? 
I try this:

`if($message->has('entities')){
  foreach($message->getEntities() as $entitie){
     $type=$entitie->getType();
  }
}`
