### ISSUE TITLE
Problems with registering commands

### ISSUE THREAD

**Issue by nycooookie** [irazasyed/telegram-bot-sdk#284]
I somehow didn't manage to use the the command system.
What I tried is to put a `StartCommand.php`-File into `App\Http\Commands` and add this path to `telegram.php`: `App\Http\Commands\StartCommand::class`.
But I keep getting `Command class "App\Http\Commands\StartCommand" not found! Please make sure the class exists.`-Errors.
Any suggestions on what I should change?

**Comment by sloothword** [comment]
Did you forget your autoloader?
e.g. `composer dump-autoload`

Otherwise can you call/instantiate the StartCommand outside of the telegram-sdk?

**Comment by irazasyed** [comment]
Please share your StartCommand code!

I wanna make sure the namespace is correct.

**Comment by nycooookie** [comment]
Ahh yes my namespace was wrong, I copied the `vendor`-part mistakenly. And didn't think about `composer dump-autoload` neither...

Thanks @sloothword and @irazasyed !
