### ISSUE TITLE
Using non-default bots

### ISSUE THREAD

**Issue by baspallada** [irazasyed/telegram-bot-sdk#285]
Hello,

Sorry if this is explained in the documentation, but I have been searching for about half an hour and came up with nothing.

I have added a second user in my config/telegram.php, but how can I use it? 

Thank you in advance

**Comment by sloothword** [comment]
Show me how you use your default bot, i show you how to use the other ;-)

no, seriously in Laravel, you just do `Telegram::bot($name)->anything()` instead of `Telegram::anything()`
Otherwise have a look at the `bot()` function in BotsManager

**Comment by baspallada** [comment]
That did it, thank you.
