### ISSUE TITLE
Can I use this library to send broadcast messages?

### ISSUE THREAD

**Issue by endlessdev** [irazasyed/telegram-bot-sdk#287]
Use the questions during the library to write down the issue. Is there a way to send a broadcast message to this library as shown? It appears that there is a formula in the official API.

**Comment by jonnywilliamson** [comment]
If its not in the BOT API then it is not possible


https://core.telegram.org/bots/api

**Comment by endlessdev** [comment]
After adding chat_id to the database, we should use a message to send a message.
Thank you for your commenting.
