### ISSUE TITLE
How to get user location and phone number?

### ISSUE THREAD

**Issue by amirpiri** [irazasyed/telegram-bot-sdk#290]
I need to get user location and phone number but your sdk is not contain any method!

**Comment by sloothword** [comment]
Have you read the API Documentation?
https://core.telegram.org/bots/api/

This chapter contains what you want:
https://core.telegram.org/bots/api/#keyboardbutton

In short:
- Create a button to request location/phone
- User has to click on it
- In the response you get the requested data

**Comment by niksmac** [comment]
@sloothword can you give an example?

**Comment by mtflud** [comment]
This worked for me on V3

```php

        $btn = Keyboard::button([
            'text' => 'Share my phone number',
            'request_contact' => true
        ]);
        $keyboard = Keyboard::make([
            'keyboard' => [[$btn]],
            'resize_keyboard' => true,
            'one_time_keyboard' => true
        ]);
        $response = $telegram->replyWithMessage([
            'text' => 'Blah blah blah',
            'reply_markup' => $keyboard
        ]);
```

**Comment by TheVladMaska** [comment]
how it is looked in node js

**Comment by YuriSS** [comment]
> how it is looked in node js

```
bot.start(ctx => ctx.reply("Blah blah blah", Markup.keyboard([
  { text: "Share my phone number", request_contact: true }
])))

bot.on("contact", ctx => console.log(ctx.message.contact))
```

**Comment by mrTigerFox** [comment]
PHP

$keyboard = [['Share my phone number','request_contact' => true]]; //Клавиатура
			$reply_markup = $telegram->replyKeyboardMarkup([ 'keyboard' => $keyboard, 'resize_keyboard' => true, 'one_time_keyboard' => true]);
			$telegtram->send_Message(['chat_id' => $chat_id, 'text' => "Would you mind sharing your contact with me?", 'reply_markup' => $reply_markup]);
	
Didn't work.
What i did wrong? Explain me please.

**Comment by mrTigerFox** [comment]
correct version is

$reply = 'Отправьте мне свой номер для регистрации';
$keyboard = [ [ ['text'=>'отправить номер','request_contact'=>true,]]];
$reply_markup = $telegram->replyKeyboardMarkup([ 'keyboard' => $keyboard, 'resize_keyboard' => true, 'one_time_keyboard' => true ]);
$telegram->sendMessage([ 'chat_id' => $chat_id, 'text' => $reply, 'reply_markup' => $reply_markup ]);

**Comment by ItSeemsToWork** [comment]
а на Java

**Comment by am0nshi** [comment]
@irazasyed is *contact* command handle normally on php side? Can't find a way how to "catch" phone number on backend part, once client is sent it

**Comment by egin10** [comment]
@am0nshi me too, anyone can "catch" phone number after the user press the button?

**Comment by egin10** [comment]
Hi @mtflud, thank you, your code save me to create the button.

Finally i found how to get the phone number.
I use Laravel 8.

The code below is command to send button and when user press the button, it'll catch the phone number from user after the user click on "share".

PhoneNumberCommand.php
    
    `public function handle()
    {        
        $response = $this->getUpdate();
        $chat_id = $response->getChat()->getId();

        $btn = Keyboard::button([
            'text' => 'Varify',
            'request_contact' => true,
        ]);

        $keyboard = Keyboard::make([
            'keyboard' => [[$btn]],
            'resize_keyboard' => true,
            'one_time_keyboard' => true
        ]);

        return $this->telegram->sendMessage([
            'chat_id' => $chat_id, 
            'text' => 'Please click on Verify and Share.',
            'reply_markup' => $keyboard
        ]);
    }`

ControllerWebhook.php

    `public function commandHandlerWebHook()
    {
        $updates = Telegram::commandsHandler(true);

        $chat_id = $updates->getChat()->getId();

        // Catch Phone Number
        $user_phone = array_key_exists('contact', $updates['message']) ? 
            $updates['message']['contact']['phone_number'] : null;
        $text = 'Phone number : ' . $user_phone;
        if($user_phone) return Telegram::sendMessage(['chat_id' => $chat_id, 'text' => $text]);

        return 'ok';
    }`
    
 It will check if the $updates['message'] has a 'contact' key.
 and It's work for me!

**Comment by ziZily** [comment]
inlineButton dont support request contract?
@egin10

**Comment by Xatta-Trone** [comment]
@egin10 could you please share your whole code? if possible .

**Comment by egin10** [comment]
> @egin10 could you please share your whole code? if possible .

@Xatta-Trone Hi, I wrote article how to implement it. You can find it on link below.
https://egin10.medium.com/cara-mendapatkan-phone-number-user-dengan-bot-telegram-aa0f3f46046f

**Comment by golibjon0226** [comment]
I do not understand above

**Comment by egin10** [comment]
> I do not understand above

You can translate it into English.
