### ISSUE TITLE
Command with uppercase name not detected

### ISSUE THREAD

**Issue by holtkamp** [irazasyed/telegram-bot-sdk#291]
Currently all incoming commands [are made lowercase](https://github.com/irazasyed/telegram-bot-sdk/blob/547f83d8aa0a7e475ae6179f95de5621c300d629/src/Commands/CommandBus.php#L201) before being executed. 

Where is this specified that all commands should be lower case? Can not find anything here: https://core.telegram.org/bots#commands

I got some commands that refer to domain concepts, which use casing:

```
- /Orders (ok /orders might do the job)
- /ServiceProviders (/serviceproviders is not preferred...)
```

**Comment by sloothword** [comment]
I am not sure i catch your intention.

Do you want /Orders and /orders to match two different Commands?
That might seem quite confusing for your users.

Do you have a problem with ignoring case?
A command named `orders` should match `/Orders` without problems (or any other upper/lower-case variant thereof)

Do you need to the original spelling in your Command? I would suggest to just add it as a variable.

**Comment by holtkamp** [comment]
> Do you want /Orders and /orders to match two different Commands?

Well, not necessarily..., but it would be nice that we can use the name ```Orders``` and are not forced to use ```orders```. Likewise, currently the example of the ```ServiceProviders``` Command if it is named lowercase ```serviceproviders```.

When I use the preferred Command name ```ServiceProviders``` and try to invoke it by submitting a text like:

- /serviceproviders
- /serviceProviders
- /ServiceProviders

it will *not* work, which is unexpected behaviour.

> Do you have a problem with ignoring case?

Yes. Our ```/start``` Command lists all available Commands using their name. So this limitation forces me to use ```serviceproviders``` which is not a 'domain concept' which I try to use consistently in our functional and technical documentation. 

>I would suggest to just add it as a variable.

Mmm, what do you mean here?

I think the solution would be to perform lowercase comparison when matching the Command. But **not** require the Command name to be lower case, which is kind of rigorous?

**Rationale**
We try to adopt the ideas of [Domain Driven Design](https://en.wikipedia.org/wiki/Domain-driven_design). In this paradigm the use of a [ubiquitous language](http://martinfowler.com/bliki/UbiquitousLanguage.html) is one of the starting points. When pitching new ideas using Telegram bots to roll out to our users, it would be nice to not deviate from these principles and stick to the naming conventions used in our domain...

**Comment by sloothword** [comment]
Ok i got you.

You want your Command name to be cast to lowercase as well. @irazasyed I guess thats a reasonable request 

As a workaround i suggested having a variable `$domainObject = "ServiceProviders"` in your command class and use this in your /start or /help commands.
You could also override `Command::getName()` with `return strtolower($this->domainObject)` or similar.
I guess you get the idea.

**Comment by holtkamp** [comment]
> I guess you get the idea.

Aah, ok, yeah that is an idea. There is no hurry in this, I was just surprised by the behaviour. 

It seems [```array_change_key_case()```](http://php.net/manual/en/function.array-change-key-case.php) can be used to acquire an array to match the Commands, regardless how they were named 😄

**Comment by irazasyed** [comment]
Interesting discussion. I'll consider this for V3. Adding it to the V3 Project TODO. Thanks!
