### ISSUE TITLE
$message->getPhoto() not working

### ISSUE THREAD

**Issue by nabeghe** [irazasyed/telegram-bot-sdk#292]
Hi dear,
I'm gonna to get received photo File Id and send it again.
```
$photo = $message->getPhoto();
$response = $telegram->sendPhoto([
      'chat_id' => $chat_id,
      'photo' => $photo[0]->getFileId(),
      'caption' => $update->getMessage()->getCaption()
    ]);
```
but getFileId not working
please help, thanks you...

**Comment by irazasyed** [comment]
Hi,

While this is an old issue and I hope you've already resolved it by now.

But if not, feel free to try the below example (Compatible with v3 develop branch):

``` php
$message = $update->getMessage();
if($message !== null && $message->has('photo')) {
    $chat_id = $message->chat->id;
    $photo = $message->photo;

    $response = $this->telegram->sendPhoto()
        ->chatId($chat_id)
        ->photo($photo[0]['file_id'])
        ->caption($message->caption)
        ->getResult();
}
```

If you're using with Laravel. Do check the [telegram-bot-laravel-starter](https://github.com/irazasyed/telegram-bot-laravel-starter).

Closing this ticket as it's quite old. But feel free to comment or create a new one if face any issues. Thanks!
