### ISSUE TITLE
Commands, not starting with /

### ISSUE THREAD

**Issue by sigaev-pro** [irazasyed/telegram-bot-sdk#295]
Hello!

As I read before here, It's possible now to handle commands not starting with /. I'm developing with dev-master branch and I'm not understand how to do it. As for me, it's very usefull to handle keyboard buttons.

**Comment by ItsOnlyMeNL** [comment]
You need to disable the privacy from the bot so it reads everything  and then explode the message text. 😀


--

-verstuurd vanaf mijn iPhone-

**Comment by CORPARU** [comment]
> You need to disable the privacy from the bot so it reads everything and then explode the message text. 
> 
> -verstuurd vanaf mijn iPhone-
> 
> > Op 15 nov. 2016 om 18:55 heeft Vadim Sigaev [notifications@github.com](mailto:notifications@github.com) het volgende geschreven:
> > Hello!
> > As I read before here, It's possible now to handle commands not starting with /. I'm developing with dev-master branch and I'm not understand how to do it. As for me, it's very usefull to handle keyboard buttons.
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.

And there is a code example how to do this?
