### ISSUE TITLE
API 2.0 issue setwebhook gif

### ISSUE THREAD

**Issue by MrFiregore** [irazasyed/telegram-bot-sdk#296]
Yesterday I started to have problems with the API. My bot send to me all the updates that it received. All works fine but when I send to it a gif file, it don't response to me the update.

# **Attach pictures of the responses:**

## __the response when I send a picture__

![img_20161117_021150](https://cloud.githubusercontent.com/assets/23504988/20372544/5204756a-ac6c-11e6-9d45-9eac7711dcb6.jpg)

## __the response when I send a text message__

![img_20161117_021145](https://cloud.githubusercontent.com/assets/23504988/20372572/808a21a0-ac6c-11e6-8463-f9de696f6981.jpg)

## __the response when I send a gif (as you can see don't exist)__

![screenshot_20161117-021004](https://cloud.githubusercontent.com/assets/23504988/20372552/5f10312c-ac6c-11e6-8cb4-d8f54660288e.png)

**Comment by firegore2** [comment]
# **Attach pictures of the responses:**

## __the response when I send a picture__

![img_20161117_021150](https://cloud.githubusercontent.com/assets/23504988/20372544/5204756a-ac6c-11e6-9d45-9eac7711dcb6.jpg)

## __the response when I send a text message__

![img_20161117_021145](https://cloud.githubusercontent.com/assets/23504988/20372572/808a21a0-ac6c-11e6-8463-f9de696f6981.jpg)

## __the response when I send a gif (as you can see don't exist)__

![screenshot_20161117-021004](https://cloud.githubusercontent.com/assets/23504988/20372552/5f10312c-ac6c-11e6-8cb4-d8f54660288e.png)

**Comment by firegore2** [comment]
To solve that I analize the type of mesage with the next code:

```
function data_type($message){
  $type=$message->detectType();
  if ($type=='document') {
    $document=$message->getDocument();
    $mime_type=$document->getMimeType();
    if ($mime_type=='video/mp4') {
      return 'gif';
    }
    else {
      return $mime_type;
    }

  }
  else {
    return $type;
  }
```
