### ISSUE TITLE
Why don't exist the function to delete messages if telegram offer it method?

### ISSUE THREAD

**Issue by firegore2** [irazasyed/telegram-bot-sdk#297]
The API to create an app offer that method. Why don't implement it in the API PHP SDK?
It can help manage our groups or channels (and prevent the spam).
I love your work 😉

![20161117_024335](https://cloud.githubusercontent.com/assets/23504988/20373047/c33e72c8-ac6f-11e6-947a-3759416a0b6e.png)

Extra:
Could you create a method to combine the bot with the client? Others API combine that technique to upload files when her size is more biggest than 50mb.
Thanx for all

**Comment by irazasyed** [comment]
This is not related to the Bot API. So it's not possible. You gotta request to Telegram to support such kinda feature and only then we can implement such thing.

We can't combine 2 APIs into this SDK as that's not what this project is about. Thanks for the suggestion, though.
