### ISSUE TITLE
Please check my fork

### ISSUE THREAD

**Issue by halaei** [irazasyed/telegram-bot-sdk#299]
Hi, it is a while I made a fork of this repository. I try to keep it current. In the case you are interested to merge the changes into this repository or contribute there or something, please kindly take a look at  https://github.com/halaei/telegram-bot

Regards.

**Comment by jonnywilliamson** [comment]
Maybe you could highlight some important changes you have made to your fork?

Anything really cool?

**Comment by halaei** [comment]
Sure.
1. New updates of bot API are tried to be completely covered.
2. Handling relations between objects (e.g. Update has Message and so on)
are a little bit improved.
3. Bug fixes in the way input file params are handled, and support for Http
URLs in input files (will be downoaded by Telegram servers). See
InputFileInterface.
4. Some helpers regarding fetching entities and html of text messages.
5. I also made the package a pure API client. Many features, like command
bus, are removed. Those tasks belongs to a separate package. We had our
private reop for that.
6. Misc. helper/short-cut functions added to some objects, e.g.
Chat::isPrivate(), Update::getRelatedMessage(), Message::getFileId(),
Update::getFrom(), ...

**Comment by exileed** [comment]
In fork no service provider and facade for Laravel

**Comment by halaei** [comment]
Yes. It is still possible to have an API key in .env and then inject API everywhere you need.
However, I think it is good to add some token based connection pool to make consecutive API requests faster. That can be done via Laravel service providers or by adding some static methods and properties to the API class itself.
