### ISSUE TITLE
ReplyKeyboardRemove

### ISSUE THREAD

**Issue by JaoNoctus** [irazasyed/telegram-bot-sdk#300]
Where is this on the api???

https://core.telegram.org/bots/api#replykeyboardremove

**Comment by JaoNoctus** [comment]
Solved.

```php
$reply_markup = json_encode([
    'remove_keyboard' => true,
]);

$telegram->sendMessage([
    // other fields
    'reply_markup' => $reply_markup,
]);
```

**Comment by MrAndreyGAV** [comment]
for SDK >= 3.0

use Telegram\Bot\Keyboard\Keyboard;

...

$reply_markup = Keyboard::remove();

$telegram->sendMessage([
    // other fields
    'reply_markup' => $reply_markup,
]);
