### ISSUE TITLE
Doc's info missing...

### ISSUE THREAD

**Issue by celorodovalho** [irazasyed/telegram-bot-sdk#301]
Hi!

I tried to follow the "Getting Started" from readme.io.
It was all okay until I tried to set the webhook, but not receiving any answer from Telegram.
So I figured I need to assign an "exception" to the CRSF Token for the "/<token>/webhook" route in the App\Http\Middleware\VerifyCsrfToken.

This is important information that should be included in the Laravel documentation part.

**Comment by jonnywilliamson** [comment]
Yes, that would be great. Maybe you could make a PR for @irazasyed ?

**Comment by irazasyed** [comment]
Thanks for reporting. I've added the step [here](https://telegram-bot-sdk.readme.io/v2.0/docs/webhook-updates#section-laravel-important-).
