### ISSUE TITLE
How does the bot know where the server is?

### ISSUE THREAD

**Issue by xtrasmal** [irazasyed/telegram-bot-sdk#304]
Hi there,

I looked around and could not find some base information which is a bit unclear to me.
How does the bot know where my Laravel application is hosted? 

Best regards

**Comment by jonnywilliamson** [comment]
https://core.telegram.org/bots/api#setwebhook

https://core.telegram.org/bots#6-botfather

**Comment by xtrasmal** [comment]
Ok...after some playing around...it all works ;)
