### ISSUE TITLE
Determine preferred language of Telegram device that sends message to bot

### ISSUE THREAD

**Issue by holtkamp** [irazasyed/telegram-bot-sdk#305]
Is there a way to find out what language the user has set as preferred language? Both on my Android device and Mac laptop the application allows a user to set a language. 

For example: 

<img width="507" alt="screen shot 2016-12-03 at 21 56 17" src="https://cloud.githubusercontent.com/assets/776405/20862165/e8a08934-b9a3-11e6-9ba8-865fe9dd9d9f.png">

In order to have a bot respond in the 'proper' language, it would be nice to be aware of this preference.

Could not find anything on the [Telegram Bot API page](https://core.telegram.org/bots/api), so it might not even be supported?

**Comment by jonnywilliamson** [comment]
Yeah, unfortunately that is not supported.

However, there's nothing stopping you from sending them a keyboard when they first make contact with your bot (via /start) that has a list of those languages.

Then when they press the language that applies to them, your bot will receieve that value, and you could store that in the database (etc) for that user.

More long winded but doable.

**Comment by holtkamp** [comment]
>Yeah, unfortunately that is not supported.

Ok, thanks for the confirmation of this limitation of the Telegram Bot API, strange this "obvious" feature is missing... Will try to find out where to submit a feature request for this. For now I will close this issue.

>More long winded but doable.

Indeed, doable, thanks for the suggestion. For now it is not *that* important and probably some day the API will support it 😄 .

**Comment by holtkamp** [comment]
Well, gave it short search, [it seems they use Trello](https://core.telegram.org/tsi/answering_questions#handling-user-suggestions), but [their board](https://trello.com/b/TgdZ0YI6) seems down or at least not publicly accessible (I did sign in into Trello). So I tried [tweeting](https://twitter.com/mennoholtkamp/status/805433543493033984) them, lets wait for that...

**Comment by czare7** [comment]
In the Java API for Telegram there is a method for getting that info.
update.getMessage().getFrom().getLanguageCode();

**Comment by Marko97IT** [comment]
In the type **User** you can use _language_code_ to determinate the language that the user has.
[Telegram Bot API](https://core.telegram.org/bots/api#user)

**Comment by holtkamp** [comment]
@Marko97IT thanks for this update, seems they have added it, nice!

**Comment by objNameGit** [comment]
hello. How does telegram determine language_code ?
i set spanish language on windows version app, but language_code = 'en'.
how it work?

**Comment by holtkamp** [comment]
Not sure, did you try other devices with the Telegram App? A mobile phone, a tablet, etc and test that?

**Comment by objNameGit** [comment]
Yes of course. I tried sending messages from the phone, computer.
I asked to write a message from a man from Mexico, he has a Russian SIM card, but was registered in a telegram in Mexico. Her message had lang_code = 'es'.

On my device andd computer, I changed the telegram interface language to 'en', but my message  had lang_code = 'ru'.
Even if I write in another language (en, it, es, etc) - my language is always defined as lang_code = 'ru'.
I wrote messages from the ip of other countries in another language (en, it, es, etc), all the same lang_code = 'ru'.

The official documentation does not say anything about how this constant is determined.

I need to understand what language to communicate with the user. But not knowing how the lancode is determined, I cannot be sure that this constant is valid.

I may have to use a webhook to send a text entered by the user into the translator and get the language of the text.
But I would not want to complicate the implementation

**Comment by objNameGit** [comment]
Understood.
The value of the lang_code parameter depends on the language of the Telegram application. It doesn't matter which keyboard layout is enabled.
For example:
In Telegram, the default language is Russian.
I am writing a message in English. lang_code = ru

**IMPORTANT:** After changing the language of telegrams, you need to wait 3-7 minutes until the setting is updated on the telegram server (I think so). Because if you write messages immediately after changing the language of the application, it will display the first language.

**Comment by holtkamp** [comment]
Thanks for the research, too bad the documentation does not cover this and it is not easy to get into contact with the Telegram developers to try to add it...

**Comment by begetan** [comment]
@objNameGit 

I found that a telegram app set  language code from the system setting, not from itself language setting

@holtkamp 
[https://core.telegram.org/bots/api-changelog#may-18-2017](https://core.telegram.org/bots/api-changelog#may-18-2017)

> NEW Multilingual Bots
>The User object now may have a language_code field that contains the IETF language tag of the user's language. Thanks to this, your bot can now offer localized responses to users that speak different languages.

**Comment by AndySem1** [comment]
@objNameGit, @begetan, seems like changing the system's language doesn't help. Possibly it takes longer for TG servers to process the changes... Kinda weird

**Comment by AndySem1** [comment]
Nvm. It took about an hour for TG servers to get new device lang data

**Comment by kamikazebr** [comment]
@purpleslash That change was in app or system language? I'll try wait. Kinda bad need wait so much time to make tests. Tyvm!

**Comment by ziZily** [comment]
so how i can get user language in start command?

**Comment by AndySem1** [comment]
@kamikazebr as far as I remember, it was system language settings

@ziZily start command? Didn’t really get that. We were initially discussing how TG server sees TG client language. Please elaborate

**Comment by ziZily** [comment]
@purpleslash
tanx for reply. i have a telegram bot and i want when user send start command we get user language and according user language( language that user select in telegram app) set bot language, heare is my code but dont work because getUpdate dont return language_code.
//
            $update  = $this->getUpdate();
            $message = $update->getMessage();
            $user_lang= $message->getFrom()->language_code;
            if($user_lang=='fa')
                $lang='fa';
            else
                $lang='en';
//

can you help me?

**Comment by SadDarkAngel** [comment]
```

curl -s "https://api.telegram.org/bot<bot_token>/getChatMember" -H "Content-Type: application/json" -d "{\"chat_id\":<chat_id>,\"user_id\":<chat_id>}" | jq -r ".result.user.language_code"
```

**Comment by SadDarkAngel** [comment]
```

curl -s "https://api.telegram.org/bot<bot_token>/getChatMember" -H "Content-Type: application/json" -d "{\"chat_id\":<chat_id>,\"user_id\":<chat_id>}" | jq -r ".result.user.language_code"
```

**Comment by SadDarkAngel** [comment]
```curl -s "https://api.telegram.org/bot<bot_token>/getChatMember" -H "Content-Type: application/json" -d "{\"chat_id\":<chat_id>,\"user_id\":<chat_id>}" | jq -r ".result.user.language_code"```
