### ISSUE TITLE
Documentation for version 3

### ISSUE THREAD

**Issue by dswtech** [irazasyed/telegram-bot-sdk#310]
Where can I see documentation for 3.*@dev version ?

**Comment by seyfer** [comment]
:+1: 
I wanted to create same issue by myself, but have seen this issue before.

`3.*@dev`

**Comment by JaoNoctus** [comment]
+1 @irazasyed

 PLASE DOCS FOR `3.*@dev`

**Comment by holtkamp** [comment]
Lot of references are made to ```3.*@dev```, but I only see a ```develop``` branch, maybe rename it to 3.x to make sure we are talking about the same thing 😄

**Comment by irazasyed** [comment]
No docs yet. Sorry!

But you can check out the newly released Laravel starter to get an idea of how to use the 3.x develop branch. Here you go: https://github.com/irazasyed/telegram-bot-laravel-starter
