### ISSUE TITLE
Handle an inline button click as command

### ISSUE THREAD

**Issue by noisemaker00** [irazasyed/telegram-bot-sdk#312]
How can I handle the response from inline button as a command?
I give you an example:
[ "text" => "Button 1", "callback_data" => "/cmd_for_btn param1 param2" ]

Now when user click on button I want to handle that in the same way as user typing
"/cmd_for_btn param1 param2"

**Comment by FaridAghili** [comment]
Looking forward to it.
It's essential for create effective interactive bots.
