### ISSUE TITLE
Forbidden: Bot was blocked by the user

### ISSUE THREAD

**Issue by ghost** [irazasyed/telegram-bot-sdk#314]
Hello.
Recently I get a lot of this exception:
`[19-Dec-2016 10:25:49 UTC] PHP Fatal error:  Uncaught exception 'Telegram\Bot\Exceptions\TelegramOtherException' with message 'Bad Request: Failed to get HTTP URL content' in /home/public_html/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php:58
Stack trace:
#0 /home/public_html/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(174): Telegram\Bot\Exceptions\TelegramResponseException::create(Object(Telegram\Bot\TelegramResponse))
#1 /home/public_html/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(204): Telegram\Bot\TelegramResponse->makeException()
#2 /home/public_html/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(65): Telegram\Bot\TelegramResponse->decodeBody()
#3 /home/public_html/vendor/irazasyed/telegram-bot-sdk/src/TelegramClie in /home/public_html/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php on line 58
[19-Dec-2016 11:31:12 UTC] PHP Fatal error:  Uncaught exception 'Telegram\Bot\Exceptions\TelegramOtherException' with message 'Forbidden: Bot was blocked by the user' in /home/public_html/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php:58`

And I don't know why! I don't think someone that blocked my bot, Wanted to work with it and sent any message to bot to get response; And then this exception came up.
I have to say that the performance of my server is a little low, But for 2 days my bot didn't respond and all I got was this kind or error, Just times 1000!
So what's the problem here? How can i catch that?

**Comment by mrmrn** [comment]
I have the same error.
Do you could solve the problem mostafa?in my case when a user block the botm my bot fails in a infinite loop and send a message again and again!!

**Comment by MostafaQanbaryan** [comment]
My bot take to long to respond,  And I think in the mean time User get board and block the bot.
The only thing that we can do, Is catching the exception, and move on.
