### ISSUE TITLE
unable to handle exception!

### ISSUE THREAD

**Issue by giovanniciriello** [irazasyed/telegram-bot-sdk#315]
Hi, I got this problem more times using this sdk.
I can't handle exception, for example, if I have an array of user ids and I do smth like this:
`$chat = Telegram::getChat([
     'chat_id' => $this->user_id
]);`
 but if the chat doesn't exist, the whole code interrupts. and I would handle error in a way like this:
```       
       try{
            $chat = Telegram::getChat([
                'chat_id' => $this->user_id
            ]);
        }catch (Exception $e){
            $chat = [
                'first_name' => '',
                'last_name' => '',
                'username' => '',
            ];
        }
```
but the error persist to block the code. I've tryed also with a if - else.
How can i solve it?

**Comment by web2033** [comment]
Hi! Did you find a solution?
