### ISSUE TITLE
install in lumen 5.3

### ISSUE THREAD

**Issue by HASSANDL** [irazasyed/telegram-bot-sdk#316]
Hello, very thanks for this plugin.
how install it in lumen 5.3?

**Comment by obarlas** [comment]
I have found the easiest way to fork or clone the repository and change 
`
use Illuminate\Contracts\Foundation\Application;
`
to
`
use Laravel\Lumen\Application;
`

in TelegramServiceProvider.php

**Comment by irazasyed** [comment]
Use `3.*@dev` version. It'll pull the latest master branch. It has support for Lumen. Please note, the API has some major changes which are yet to be documented but is mostly compatible with 2.0.

**Comment by irazasyed** [comment]
I've added Lumen support for 2.0 as well.
