### ISSUE TITLE
separate Messages and Commands

### ISSUE THREAD

**Issue by nkornushin** [irazasyed/telegram-bot-sdk#318]
In all examples and documentation we can see code for Commands like this:

```
Route::post('/<token>/webhook', function () {
    $update = Telegram::commandsHandler(true);

    $message = $update->getMessage();
    $chatId = $message->getChat()->getId();
    Telegram::sendMessage($chatId, 'Hello World');

    return 'ok';
});
```

But if user will input command, and command will replay some text - we will return 2 message (message from command and "Hello World"). How to break code after execute command?
I made some code:

```
$update = Telegram::commandsHandler(true);
        if(empty($update->getMessage()->getEntities()) || $update->getMessage()->getEntities()[0]['type'] != 'bot_command') {
            $chat_id = $update->getMessage()->getChat()->getId();

            Telegram::sendMessage([
                'chat_id' => $chat_id,
                'text' => "hello"
            ]);
        }
```

**Comment by irazasyed** [comment]
The docs just give an example of how to handle both case scenarios. Your code is good too. Thanks for sharing, I might publish that as an example as well but not at this time.
