### ISSUE TITLE
How use Emoji in version 3.0.x-dev

### ISSUE THREAD

**Issue by BehroozBvk** [irazasyed/telegram-bot-sdk#319]
How can I get a telegram of emoji to the new version for a list and use it in my sendMessage method Please put a code sample. Please copy document 3.0.x- put the two together.

Thank

**Comment by BehroozBvk** [comment]
Does not anyone help?
Who was behind this document Version 3 ?

**Comment by ItsOnlyMeNL** [comment]
What do you mean? You want to send Emoji? If so, i use this to send messages with emojis: 

```
Telegram::sendMessage([
           'chat_id' => $chatId,
           'text' => iconv(mb_detect_encoding($bericht, mb_detect_order(), true), "UTF-8", $bericht),
           'disable_web_page_preview' => 'true'
         ]);
```

You do need to know the code for the emoji you want to send, most of the times i use this table:
http://apps.timwhitlock.info/emoji/tables/unicode

**Comment by BehroozBvk** [comment]
Thank you dear friend, but I use a package of classes is your Emoji
