### ISSUE TITLE
[TODO] Add Emoji Support and Helpers

### ISSUE THREAD

**Issue by irazasyed** [irazasyed/telegram-bot-sdk#32]
Will use this for reference: http://emoji.muan.co/

Add support such that, Simple `:smile:` would automatically map that into appropriate char from this list: https://github.com/muan/emojilib/blob/master/emojis.json

**Comment by benelang** [comment]
+1

**Comment by filipekiss** [comment]
@irazasyed I'll do this.

**Comment by irazasyed** [comment]
@filipekiss Sounds good. Looking forward to your PR.
