### ISSUE TITLE
cURL error 28: Connection timed out after 10000 milliseconds

### ISSUE THREAD

**Issue by manzoorwanijk** [irazasyed/telegram-bot-sdk#321]
Everything was working perfectly till today, but all of a sudden, all of my bots stopped working. Upon debugging, I got this error even for `sendMessage` method.
Any idea?

**Comment by CristianOspina** [comment]
Same here. I have that error when uploading files. Could it be an API?

**Comment by manzoorwanijk** [comment]
It finally came out to be the issue with my server. Fixed now :)

**Comment by jonnywilliamson** [comment]
Please give more details so others finding this thread might be able to save some time!

Thanks.

**Comment by CristianOspina** [comment]
@manzoorwanijk How did you solve it?

**Comment by manzoorwanijk** [comment]
It was a problem with my host server. They fixed it and they don't tell you what they did :)

**Comment by CristianOspina** [comment]
What did you tell them? To see if I tell them the same thing haha.
