### ISSUE TITLE
answerCallbackQuery

### ISSUE THREAD

**Issue by mfiyalka** [irazasyed/telegram-bot-sdk#322]
Hello!

Using the "3.*@dev"

Get error: - Fatal error: Uncaught Telegram\Bot\Exceptions\TelegramOtherException: Bad Request: QUERY_ID_INVALID in /.../vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php on line 58
Help me.

```
$telegram->answerCallbackQuery([
    'callback_query_id' => $callback_query_id,
    'url' => $url
]);
```

**Comment by ItsOnlyMeNL** [comment]
I am seeing the same error from time to time. This is also causing telegram to remove the keyboard from the client's app.

Hopefully someone can help with this :)

**Comment by dvdghe** [comment]
plz help. how can use answerCallbackQuery ?

**Comment by mrmrn** [comment]
when I want to send a photo have the same error with version 2.2
