### ISSUE TITLE
create inline keyboard using irazasyed

### ISSUE THREAD

**Issue by maralbe** [irazasyed/telegram-bot-sdk#323]
i used this version -> composer require irazasyed/telegram-bot-sdk 3.*@dev

and since i installed it,  my php give me error :
PHP Fatal error: Maximum execution time of 60 seconds exceeded in /home/maral/Sites/shopBot/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php on line 109

i do'nt know how to fix it..
can you help me to solve it?

before that, I'd use version '2.1'
and it was OK
but since i wanted to use inline keyboards, so install this version..
and now my bot stop working

**Comment by maralbe** [comment]
before that, I'd use version '2.1'
and it was OK
but since i wanted use inline keyboard, so install this version..
and now my bot stop working

**Comment by Lutick** [comment]
set_time_limit(0);

**Comment by maralbe** [comment]
thanks for your response..
unfortunately i delete this package.. and work with telegram api
and it works for me now
