### ISSUE TITLE
how to check if a message is a reply_to_message?

### ISSUE THREAD

**Issue by firegore2** [irazasyed/telegram-bot-sdk#324]
The API has a method implemented?

**Comment by Sipanatik** [comment]
getUpdates from telegram API ?

**Comment by irazasyed** [comment]
Use `$message->isType('reply_to_message')` method. Check out [here](https://github.com/irazasyed/telegram-bot-sdk/blob/develop/src/Objects/Message.php#L74-L88)

**Comment by firegore2** [comment]
Sorry for request later, already got it with this

**Comment by irazasyed** [comment]
@firegore2 No problem! Glad to know you've already found the solution 👍
