### ISSUE TITLE
Please, add leaveChat method to current 3.*@dev version

### ISSUE THREAD

**Issue by seyfer** [irazasyed/telegram-bot-sdk#325]
[https://core.telegram.org/bots/api#leavechat](https://core.telegram.org/bots/api#leavechat)

This method is very useful for commands like /off or /unsubscribe.

**Comment by seyfer** [comment]
I have changed version to

`"irazasyed/telegram-bot-sdk": "dev-develop"` 

and now it's here.

**Comment by seyfer** [comment]
No, it's not.

New version works in very different way. So, please backport method `leaveChat` to 3.*@dev

**Comment by derakoola** [comment]
@irazasyed When do you publish version 3, please!?

**Comment by jonnywilliamson** [comment]
@seyfer Why do you believe leavechat is not in the dev version?

https://github.com/irazasyed/telegram-bot-sdk/blob/develop/src/Methods/LeaveChat.php

**Comment by seyfer** [comment]
@jonnywilliamson I use a version before Methos in their own directory were introduced. And there is no LeaveChat method.

**Comment by irazasyed** [comment]
Please refer this starter package I just released: https://github.com/irazasyed/telegram-bot-laravel-starter

It has a sample method usage. So you can get an idea on how to use other methods.

**Comment by seyfer** [comment]
@irazasyed you demonstrate there how to use v3.0, but I have asked about port leaveChat back to 2.0.

**Comment by seyfer** [comment]
@irazasyed , @jonnywilliamson so, what about version 2.2 and leaveChat method?
