### ISSUE TITLE
getWebhookUpdates return empty

### ISSUE THREAD

**Issue by v2mgm** [irazasyed/telegram-bot-sdk#328]
after setwebhook, getWebhookUpdates always return empty

`$update = $bot->getWebhookUpdates();
var_dump($update);`

**output:**
> object(Telegram\Bot\Objects\Update)#33 (1) { ["items":protected]=> array(0) { } }

**Comment by irazasyed** [comment]
How are you executing this code?

You can't use that with a GET request. It only works with a POST request and when Telegram sends you an update.

**Comment by v2mgm** [comment]
The problem was on my side ... sorry
