### ISSUE TITLE
command detection

### ISSUE THREAD

**Issue by derakoola** [irazasyed/telegram-bot-sdk#33]
Imagine my username's bot is "something_bot".

when a command receives like that:
/start 
StartCommand triggered.

and when this command receives
/start@something_bot
again StartCommand triggered.

and bug is here:
when
/start@ANOTHER_bot
receives StartCommand triggered, the command is not for my bot.

**Comment by jonnywilliamson** [comment]
@irazasyed 

This is straightforward to fix - would you be happy with another config setting of BOT_NAME ?

**Comment by irazasyed** [comment]
@jonnywilliamson I'm fine with that but since i had plans for #22 multi bot support, We have to think about handling multiple bots and It shouldn't be difficult to implement that.

**Comment by derakoola** [comment]
@jonnywilliamson this is required for multiple Bot!
@irazasyed I am new in github.com, can i extend this package as you?

**Comment by jonnywilliamson** [comment]
Multi bot solution would be a much better fix.

**Comment by irazasyed** [comment]
@derakoola yeah sure you can, just fork the repo and you can make the changes. You can then send a PR.

@jonnywilliamson Yep, I'm working on it today. Will try to push if I'm done!
