### ISSUE TITLE
What about mentions?

### ISSUE THREAD

**Issue by francescomalatesta** [irazasyed/telegram-bot-sdk#330]
Hey there @irazasyed , doing my first steps implementing a bot with Laravel 5.4. Everything works fine btw :)

Just a question about mentions. I've created a couple of commands, extending the `Telegram\Bot\Commands\Command` class. Everything works fine in private chat, then I added my bot to a group.

Tried to call the command via `@botname /command arguments` but the command is not called in any way. 

Are these command classes "included" also when mentioning the bot? :) It could be a really nice feature. If not possible right now, I could help with a PR for it. :)

Let me know!

**Comment by irazasyed** [comment]
Hey @francescomalatesta 

As far as I know, You can call a command by doing `/command@botname arguments` in groups. The SDK supports such calls and will process the command like it does in private.

Please test and let me know if that works!

**Comment by francescomalatesta** [comment]
As not said, it works perfectly, also without any mention. `/command arguments` is enough! Definitely my bad, closing it!

**Comment by irazasyed** [comment]
No problem :)

Thanks for confirming it works! 👍
