### ISSUE TITLE
issue with the method getWebhookInfo

### ISSUE THREAD

**Issue by firegore2** [irazasyed/telegram-bot-sdk#332]
when i try to get the status of the Webhook with that method the API enter on a loop send me differents errors .
This is the code:

```
$bot = new Api("MY_BOT_TOKEN");
$update=$bot->getWebhookUpdates();
$update_status=$bot->getWebhookInfo();
sendMessageBot("WebhookInfo:<br>".arrayToMessage($update_status->getDecodedBody()),my_id,'HTML');
```

> sendMessage Bot is a function that I was created to simplify the send messages myself

> arrayToMessage is a function to transform an array to string

The result of that is the next:
![image](https://cloud.githubusercontent.com/assets/23504988/22408719/b530a474-e67d-11e6-80b3-20019f8d82c0.png)

![image](https://cloud.githubusercontent.com/assets/23504988/22408728/e7e5d7c2-e67d-11e6-934d-b4bebc97dc81.png)

**Comment by irazasyed** [comment]
Do you have a webhook setup?

Because if you do and your server isn't responding to Telegram with a status of 200 or "ok", then the messages get queued and are tried again. So that might be the case.

Need more details and code to debug.

**Comment by irazasyed** [comment]
Actually, you do have a webhook. But like I said, your server needs to respond with status 200. So simply echo like "ok" and Telegram will consider that as message accepted. And you should consider putting that webhook info in a command like "/debug" or something.
