### ISSUE TITLE
Webhook telegram not always responds

### ISSUE THREAD

**Issue by pfloriginale** [irazasyed/telegram-bot-sdk#333]
Hi,
I properly set the webhook and it works but after some times it stop responding.

When i set it, it respond me

`object(Telegram\Bot\Objects\Message)#541 (1) { ["items":protected]=> array(1) { [0]=> bool(true) } }`

Sometimes it responds after minutes... somethimes don't respond...
could anyone tell me where is a problem?

here my setting
`
        Telegram::setWebhook([
          'url' => 'https://svariogroup.com/hubble/public/xxx_webhook',
          'certificate' => 'http://svariogroup.com/hubble/public/xxx.pem'
        ]);`

thanks a lot

**Comment by irazasyed** [comment]
Hey @pfloriginale,

It's totally up to Telegram servers and your server. It's hard to tell where the issue could be.

If your server is slow, out of memory or taking too much time to process something in the background or execute your script?

Try spinning up a droplet powered by [DigitalOcean](https://m.do.co/c/2b0c9f6a7541) (If you don't already use it). I highly recommend their LEMP stack.
