### ISSUE TITLE
Commands strange behaviour

### ISSUE THREAD

**Issue by TheWiseJah** [irazasyed/telegram-bot-sdk#334]
Hi,

I'm using your package to develop a Telegram Bot with Laravel framework.

I'm using the latest version of your package and Laravel 5.4.9 but I've some questions about it.

Following the guide on github:

- I set up the bot token and the async = true in my telegram.php under the config folder.
- I set up a route under my routes file

Route::post('/<token>/help', function () {
    
    $update = Telegram::commandsHandler(true);

    return 'ok';
});

- I've setted in the VerifyCrsfToken Middleware in the $except array the route '<token>/help' 

Now I'm encountering some issues: 

the bot does not reply to the /help command

Googling around I've found this post on github
https://github.com/irazasyed/telegram-bot-sdk/issues/69

If I create a route where I set up the command in the bot

Route::get('/set', function () {
    $res = Telegram::setWebhook([
        'url' => 'https://[botdomain]/<token>/help'
    ]);
    dd($res);

});

the response is true and the bot starts to reply, but this causes one more issue..
Now the bot replies with the help command to any commands I send.

This is strange because with this setup the bot should respond only to the /help command and ignore all others incoming commands

how can I solve this?

Thanks in advance 

Gianluca

**Comment by irazasyed** [comment]
Hi,

That's not how you register commands.

Please refer [ commands system docs](https://telegram-bot-sdk.readme.io/docs/commands-system) fully.

The commands are not registered based on the routes. It has to be done from the config file for Laravel.

Once you create a new command and then register it, it'll then start working as expected.

Hope that helps.

Also, Make sure to go through the webhooks documentation as well.

Thanks!
