### ISSUE TITLE
Telegram bot with Webhook/MySQL

### ISSUE THREAD

**Issue by Mick777fr** [irazasyed/telegram-bot-sdk#335]
Hi,
I'm having a hell to fetch the data get from a MySQL db included into a webhook to Telegram.
Here is my piece of code within my php page:

`$db = mysql_connect("xxxx", "xxxx", "xxxx") or die ('Error');`
`mysql_query("SET NAMES UTF8");`
`mysql_select_db("xxxx",$db);`
`$query ="xxxx ";`
`....`
`$result = mysql_query($query,$db);`
`$max_item = mysql_num_rows($result);`
`....`
`$myrow = mysql_fetch_row($result);`
`$reply .= $myrow[0].", " . $myrow[4].", ".$myrow[1]."\n";`
`....`
`$sendto =API_URL."sendmessage?chat_id=".$chatID."&text=".urlencode($reply);`
`file_get_contents($sendto);`

and...nothing happen. The connection and the SQL query both work properly while accessing directly to the PHP page. But via Telegram...RIEN ! NADA ! ;-{

Any help would be much appreciate.
Merci ;-)

**Comment by irazasyed** [comment]
This does not seem to be related to this SDK. I don't think I could be of any help in that case.

There are missing details as well.

**Comment by sorrow-poetry** [comment]
hi mick
this isnt related to SDK but
the problem is
`file_get_contents($sendto);`
it wont work because it will change the '&'
you need to use curl
[here ](http://php.net/manual/en/book.curl.php)you can read Documentation
and if you use this SDK it will very easy to handle....

**Comment by Mick777fr** [comment]
Thanks Vahid !
