### ISSUE TITLE
problem with config file

### ISSUE THREAD

**Issue by alimrd** [irazasyed/telegram-bot-sdk#338]
when i use

> `php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider"`

the `config/telegram.php` was generated i set 

> `'http_client_handler'` => new \Telegram\Bot\HttpClients\GuzzleHttpClient(new GuzzleHttp\Client(['verify'=>false]))`

and use ` $telegram = new Telegram\Bot\Api();` but config doesn't work and when  i use this 

> `$telegram = new Telegram\Bot\Api(null,null,config('telegram.http_client_handler'));`

it's work!
what's my solution?

**Comment by irazasyed** [comment]
Hi,

What version of the SDK are you using?

**Comment by alimrd** [comment]
last version

**Comment by irazasyed** [comment]
Last stable or dev? Please specify.
