### ISSUE TITLE
Issue with delivery Order 

### ISSUE THREAD

**Issue by LeonAlvarez** [irazasyed/telegram-bot-sdk#340]
Hi, Im using v2.0 with Laravel 5.2 , but im having an issue when I want to send 2 or more message to the same chat_Id . They don't arrive in the order of my code. Even more each time they do in different order. Using Webhook and tried both asycn true and false.

`public function callback(){`
       ` /** @var \Telegram\Bot\Objects\Update $update */`
       ` //$update = Telegram::commandsHandler(true);`
       ` $update = Telegram::getWebhookUpdates();`
       ` $chatId = $update->getMessage()->getChat()->getId();`
        `Telegram::sendMessage([`
          `  'chat_id' => $chatId,`
            `'text' => $chatId`
        `]);`
        `Telegram::sendMessage([`
          `  'chat_id' => $chatId,`
            `'text' => '1'`
        `]);`
        `Telegram::sendMessage([`
           ` 'chat_id' => $chatId,`
            `'text' => '2'`
        `]);`
        `Telegram::sendMessage([`
          `  'chat_id' => $chatId,`
            `'text' => '3'`
        `]);`
        `return 'ok';`
    }`

I have also tried usleep() after each sendMessage() but the only thing that change is the response time for the first message (they arrive close and still wrong order).

**Comment by irazasyed** [comment]
Hi,

Can you try this with the master branch?
