### ISSUE TITLE
error 500 in simple using

### ISSUE THREAD

**Issue by hamedmoody** [irazasyed/telegram-bot-sdk#342]
in https with this code 
![image](https://cloud.githubusercontent.com/assets/9475089/23104339/08831f94-f6e1-11e6-8944-d9e29dc5df6b.png)
i have error 500!
why?

**Comment by irazasyed** [comment]
500 error is with your server. Check to see if everything is right with it. Check the logs.

Need more details to better assist.

**Comment by LeonAlvarez** [comment]
Check your files permissions and Apache/Nginx logs
