### ISSUE TITLE
2.2 stuck on 'pre-release'?

### ISSUE THREAD

**Issue by holtkamp** [irazasyed/telegram-bot-sdk#344]
Not a biggie, but it seems https://github.com/irazasyed/telegram-bot-sdk/releases/tag/v2.2.0 has been marked as pre-release since January 5th 2017, is this 'intended'? Or can we expect an actual release as well 😄 

<img width="755" alt="screen shot 2017-02-27 at 19 28 20" src="https://cloud.githubusercontent.com/assets/776405/23374110/2048c4c4-fd23-11e6-8096-29fded58c207.png">

**Comment by irazasyed** [comment]
Released :)

It wasn't intended. Had planned to test it properly but couldn't. But I got no issues reported anyway. Thanks 👍
