### ISSUE TITLE
Is there any simple example in native PHP?

### ISSUE THREAD

**Issue by behnamazimi** [irazasyed/telegram-bot-sdk#346]
Hi,
Is there any sample by this SDK in PHP, I want to use this but I couldn't config and run in for my Bot.
or Is there any documentation about how should I config this SDK for webhook?

**Comment by sorrow-poetry** [comment]
https://telegram-bot-sdk.readme.io/docs

**Comment by behnamazimi** [comment]
Thanks for your reply, but in this document there is no example about how to config bot or how to send the first request or get updates!
I could not find the relation between classes and objects out. for example what is the HttpClient.
Is it possible to give me simple code that send a request to bot or get updates?

**Comment by irazasyed** [comment]
@behnamazimi Here you go: https://github.com/telegram-bot-kit/standalone-bootstrap

The docs cover both Laravel and Standalone usage. Please check them. Thanks!
