### ISSUE TITLE
version 3

### ISSUE THREAD

**Issue by jsina** [irazasyed/telegram-bot-sdk#351]
Hi there
when will U release version 3?
because I've seen you added some method in Api.php like answerCallbackQuery or editMessage ...etc. but you wouldn't release it yet.
Best

**Comment by irazasyed** [comment]
Hi, No release date yet.

But I just released a starter package for Laravel. So you could get an idea of what has changed.

Here you go: https://github.com/irazasyed/telegram-bot-laravel-starter
