### ISSUE TITLE
Set webHook URL in Laravel

### ISSUE THREAD

**Issue by behnamazimi** [irazasyed/telegram-bot-sdk#352]
I just use this SDK in Laravel, It's not working when I set a route as a webHook URL.
For set a webHook I did this:

In `Route/web.php`:
`Route::post('/hook', 'HookController@index');`

And this is my `index()` method in **HookController**:
```
public function index()
    {
        try {
            $token = 'mytoken';

            $bot = new Api($token);

            $update = new Update($bot->getWebhookUpdates());

            // I get a chat id directly by getupdates before webhook set just for test...
            $bot->sendMessage(['chat_id' => 72457465, 'text' => 'hi']);

        } catch (Exception $e) {
            $bot->sendMessage(['chat_id' => 72457465, 'text' => 'hi']);
        }
    }
```
**Edit:**
And this is the result when I fire getWebhookInfo:
```
{
"ok": true,
"result": {
    "url": "https://myhost.com/hook",
    "has_custom_certificate": false,
    "pending_update_count": 8,
    "last_error_date": 1489482484,
    "last_error_message": "Wrong response from the webhook: 405 Method Not Allowed",
    "max_connections": 40
}
}
```
Am I wrong?

**Comment by irazasyed** [comment]
In Laravel, You don't need to do `new Api` and stuff. That's totally wrong.

Please follow these instructions:
- https://telegram-bot-sdk.readme.io/docs#section-laravel-additional-steps

- https://telegram-bot-sdk.readme.io/docs/webhook-updates (Click on Laravel Tab, next to Standalone in code block):

```php
// Put this inside either the POST route '/<token>/webhook' closure (see below) or 
// whatever Controller is handling your POST route
$updates = Telegram::getWebhookUpdates();

// Example of POST Route:
Route::post('/<token>/webhook', function () {
    $updates = Telegram::getWebhookUpdates();

    return 'ok';
});
```

Then do this: https://telegram-bot-sdk.readme.io/docs/webhook-updates#section-laravel-important-

**Comment by mnr73** [comment]
i have the same problem and i do all step. this is my except

```
protected $except = [
        '/*/webhook',
        '*/webhook',
        'https://subdomin.mydomin.ir/*/webhook',
    ];
```

webhook url is https://subdomin.mydomin.ir/<token>/webhook

but its not work. may its happen for subdomin?

**Comment by blackcat20180000** [comment]
LOL,LOL,LOL

**Comment by leevu712** [comment]
I also use subdomain. But you only use:

```
class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        'xxxxxx/webhook'
    ];
}
```

Route:
`Route::post('xxxxxx/webhook', [TelegramController::class, 'telegramWebhook'])->name('telegram.webhook'); `

And check log file when use hook like:
```
class TelegramController extends Controller
{
      public function telegramWebhook()
      {
             Log::info( "Hook ok" );
      }
}
```
