### ISSUE TITLE
when group changed to super groups

### ISSUE THREAD

**Issue by Roham0010** [irazasyed/telegram-bot-sdk#354]
Hi,
On forwardMessage I had this error:
"Bad Request: group chat was migrated to a supergroup chatc"
but from telegram response it's not a error it's just a response that says group id is changed because group type changed to super group!
Telegram API response was this:

````
Array
(
    [ok] => 
    [error_code] => 400
    [description] => Bad Request: group chat was migrated to a supergroup chat
    [parameters] => Array
        (
            [migrate_to_chat_id] => -1001... #new group id
        )

)
````
so I tryed with new group id and it worked!
And to resolve this in codes I changed this:
`return isset($this->decodedBody['ok']);`
In isError method of TelegramResponse Class to this:
`return isset($this->decodedBody['ok']) && ($this->decodedBody['ok'] === false && !isset($this->decodedBody['parameters']['migrate_to_chat_id']));`
When I get this error I just try the action wtih new group id!

**Comment by jonnywilliamson** [comment]
I'll be back with this project again very shortly (within next 2 weeks...) thanks for this info. I'll add it to the to do list.
