### ISSUE TITLE
Fail to connect via guzzle http

### ISSUE THREAD

**Issue by fadrimerdianto** [irazasyed/telegram-bot-sdk#356]
Hello, Im trying to run my first project on laravel. Before try this package I already create another bot with python and it was running well with localhost. Now I am trying to build a bot with PHP (with this package in laravel 5.4). I try run the smple method getMe(), but it returns with this error by laravel `TelegramSDKException in GuzzleHttpClient.php line 114:
cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).` After Im looking for the answer, I found that this package only can be accessed with secured connection HTTPS. Can I access the bot with localhost in my laravel project? thanks before

**Comment by JuniorZavaleta** [comment]
Hi,

Are you using webhooks?
**If the answer is yes...**

You should use ngrok
https://ngrok.com/

If you are using Homestead, you must add -host-header, see the next link
https://laracasts.com/discuss/channels/servers/homestead-ngrok

When you are running ngrok copy the https link and set your webhook with that

**If the answer is no...**
I don't know xD

**Comment by fadrimerdianto** [comment]
Hi @JuniorZavaleta, thanks for ur advice. Unfortunately i dont use the webhook. And I am still getting that  error 😂

**Comment by irazasyed** [comment]
That issue is because of your cURL setup. Please check that. Also, Like @JuniorZavaleta said, you should consider using ngrok.io to setup a webhook and yes HTTPS is required for working with webhook and it's a requirement from Telegram end.

**Comment by irazasyed** [comment]
Also check out laravel-homestead or valet (If on mac).

**Comment by Kutalia** [comment]
You might need to download [Certificate Authorities certificate store](https://curl.se/docs/caextract.html), place it anywhere on a disk and reference it in your php.ini file:
`curl.cainfo = "C:\path\to\cacert.pem"`
