### ISSUE TITLE
irazasyed/telegram-bot-sdk v2.2.0 requires illuminate/support ~5.0 -> no matching package found.

### ISSUE THREAD

**Issue by aminkt** [irazasyed/telegram-bot-sdk#359]
Hi.
Im using yii2 frame work.
When i run composer update the flowing error occurred:

```
- Installation request for irazasyed/telegram-bot-sdk ^2.0 -> satisfiable by irazasyed/telegram-bot-sdk[v2.2.0].  
- irazasyed/telegram-bot-sdk v2.2.0 requires illuminate/support ~5.0 -> no matching package found. 
```

Please be aware that i don't need laravel at all.

**Comment by irazasyed** [comment]
Hi,

That's weird. I've never encountered such error. Have to look into it.

Perhaps post your composer.json?

And that package is not only to support Laravel but also for things like Collection API and other helper methods this package uses.

**Comment by aminkt** [comment]
About a month ago its work correctly bot now its not.

This is a part of composer.json

```
"minimum-stability": "dev",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "2.0.9",
...
        "irazasyed/telegram-bot-sdk": "dev-master",
...
    },
```

**Comment by irazasyed** [comment]
Can you try again? It seems to be working fine for me as I've tried recently as well. Maybe there was some issue from their end.

**Comment by aminkt** [comment]
I tried. but problem not solved yet.

**Comment by muswanto** [comment]
I have a same problem. Step to reproduce

1. Fresh install laravel via composer (v.5.4.30) and running well after that
2. Install telegram bot sdk via composer (composer require irazasyed/telegram-bot-sdk ^2.0)

**this's the output :** 
composer require irazasyed/telegram-bot-sdk ^2.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for irazasyed/telegram-bot-sdk 2.0 -> satisfiable by irazasyed/telegram-bot-sdk[v2.0.0].
    - Conclusion: remove laravel/framework v5.4.30
    - Conclusion: don't install laravel/framework v5.4.30
    - irazasyed/telegram-bot-sdk v2.0.0 requires illuminate/support 5.0.*|5.1.*|5.2.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.1.30|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.1.31|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.1.41|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.2.19|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.2.21|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.2.24|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.2.25|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.2.26|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.2.27|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.2.28|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.2.31|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.2.32|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.2.37|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.2.43|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.2.45|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.0.22|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.0.25|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.0.26|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.0.28|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.0.33|don't install laravel/framework v5.4.30
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5.4.30
    - Installation request for laravel/framework (locked at v5.4.30, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.30].


Installation failed, reverting ./composer.json to its original content.

**Here's my composer.json**
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}

**Other Information :** 
- PHP 7.0.13
- Laravel 5.4.30
- OS Windows 10 Home Edition

What's things i miss ? Thank u sir... :)

**Comment by yasirdocs** [comment]
@muswanto 
you can see it
https://github.com/irazasyed/telegram-bot-sdk/issues/276

**Comment by yasirdocs** [comment]
use 3.*@dev in composer @muswanto 
you can see it https://github.com/irazasyed/telegram-bot-sdk/issues/276

**Comment by sy04** [comment]
how can i remove my installation ( irazasyed/telegram-bot-sdk ^2.0 )

**Comment by Habtesoft** [comment]
php artisan config:clear
set TELEGRAM_BOT_TOKEN in .env
composer require irazasyed/telegram-bot-sdk ^3.4.1
ps publish conf file with php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider"
