### ISSUE TITLE
how to find user data such as user/chat id when a command is triggered?

### ISSUE THREAD

**Issue by mrmrn** [irazasyed/telegram-bot-sdk#360]
Dear syed irfaq;
I want to know all information about the user who is triggered the command.
as you said in [doc](https://telegram-bot-sdk.readme.io/v2.0/docs/commands-system) command example:

> This will send a message using `sendMessage` method behind the scenes to
        the user/chat id who triggered this command.

how can I have user/chat id?

**Comment by JuniorZavaleta** [comment]
Hi,
On the Command classes I use the next
```
$update  = $this->getUpdate()
$message = $update->getMessage();
$from = $message->getFrom();
$chat = $message->getChat();

$telegram_user = TelegramChat::find($chat->getId());

if (is_null($telegram_user)) {
    if ($chat->getType() == 'private') {
        TelegramChat::create([
            'chat_id'    => $chat->getId(),
            'first_name' => $from->getFirstName(),
            'last_name'  => $from->getLastName(),
            'username'   => $from->getUsername(),
            'type'       => $chat->getType(),
        ]);
```

I hope this help you.

**Comment by mrmrn** [comment]
thank you junior,
`$telegram_user = TelegramChat::find($chat->getId());`

I dont have TelegramChat facade

**Comment by JuniorZavaleta** [comment]
You're welcome. Oh... TelegramChat is my model for manage chats on the db.

**Comment by mrmrn** [comment]
thank you.
I used this 
```
$update  = $this->getUpdate();
$message = $update->getMessage();
$chat = $message->getChat();
chat->getId();
```
and it works. :+1:
