### ISSUE TITLE
I added serviceprovider to lumen but it gaves me There are no commands defined in the "vendor" namespace.

### ISSUE THREAD

**Issue by mrmrn** [irazasyed/telegram-bot-sdk#361]
I want to use this package v2.2  with lumen 5.4.5.
I registerred service provider `$app->register(Telegram\Bot\Laravel\TelegramServiceProvider::class);` then `php artisan vendor:publish` and I have this error:
```
 [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "vendor" namespace.
```

**Comment by irazasyed** [comment]
That is because Lumen doesn't have `vendor:publish` command. A workaround is to also install [larasupport](https://github.com/irazasyed/larasupport).

**Comment by JesterAntik** [comment]
Very good tool! Pls, add info to Getting start documentation.
