### ISSUE TITLE
Authenticate a bot to initiate a chat using API?

### ISSUE THREAD

**Issue by noncototient** [irazasyed/telegram-bot-sdk#362]
Hey,

not an issue but looking for advice. I would like to send scheduled updated to users who signed up for my Laravel app. I've got the bot to work, but having difficulties figuring out a way to authenticate a bot automatically for that user. 

I don't want the user to start the chat with the bot manually and then somehow provide me with their ID, is there a way to authenticate a bot with the customer from API? 

Hope someone knows a way.

**Comment by irazasyed** [comment]
Hey!

You can't automatically do that but what you can do is, have the user click on a link which will prompt them to start talking with your bot. You can also do deep linking and basically have some data sent to your bot initially.

That is good in cases where you have a user signed up already and you'd like to associate their existing user id with their telegram account. Hope that helps!
