### ISSUE TITLE
how to handle Forbidden: bot was blocked by the user?

### ISSUE THREAD

**Issue by mrmrn** [irazasyed/telegram-bot-sdk#363]
hi,
I wrote a bot for connecting 2 people together.
it works fine but when a user block it, the bot cannot do anything. It stick in a loop and send a message continuously to users.
`$data=Telegram::commandsHandler(false);`
when I want above method it gaves me:
`TelegramResponseException in TelegramResponseException.php line 58: Forbidden: bot was blocked by the user`
and it dose not work for any user. not just that user who blocked my bot!!
how can I get rid of this problem?

thanks.

**Comment by mrmrn** [comment]
I  used `Telegram::setAsyncRequest(true)->` before each `sendMessage` method and get rid of this error.
but still I want to know when I have this 403 error to handle error and do something.

**Comment by jonnywilliamson** [comment]
Don't be using the `setAsyncRequest` method unless you REALLY understand what it is and why you need it.

Why don't you just use a simple Try and Catch block and deal with the exception?

This is VERY rough and basic example below.

```php
        try {

            $telegram->sendMessage([
                'chat_id'                  => '<PERSONS_ID>',
                'text'                     => 'Here is some text',
            ]);

        } catch (TelegramResponseException $e) {

            $errorData = $e->getResponseData();

            if ($errorData['ok'] === false) {
                $telegram->sendMessage([
                    'chat_id' => '<ADMINISTRATOR ID>',
                    'text'    => 'There was an error for a user. ' . $errorData['error_code'] . ' ' . $errorData['description'],
                ]);
            }
        }
```


Please let us know if this resolved your problem.

**Comment by mrmrn** [comment]
thank you for the response. it works for me.

**Comment by mohsennrs** [comment]
Hi.Sorry to bring this up again but using try catch doesn't seem to work for me. Although it catches exceptions but my bot encounters a loop all the same. Any suggestions?

**Comment by neel004** [comment]
@mohsennrs  you got any another solution if yes then please let me know i have also been fallen pray to telegram infinite loop

**Comment by mohsennrs** [comment]
@neel004 I got it to work at the time but I'm really not sure how I fixed it, but I think using general Exception class did the job. My code is like this:

      `try{
            $response = $this->telegram->deleteMessage([
                "chat_id" => "chat id",
                "message_id" => "message id"
            ]);
            return $response
        } catch (\Exception $e) {
            return $e;
        }`

**Comment by 20Amir04** [comment]
Hello, i have the same problem. Can you help me?
 I`m a student, and this is my first telegram bot, which I create, I will add my full cod here, becouse I dont understand where I got problem. My classmate click two times on button and my bot was blocked, he doesn`t work, doesn`t send message and an., can you help me fix that?
using System.Linq;
using System;
using System.Globalization;
using System.Xml.Linq;
using Telegram.Bot;
using Telegram.Bot.Types;
using Telegram.Bot.Types.ReplyMarkups;
using System.Threading;
using System.Threading.Tasks.Dataflow;
using Telegram.Bot.Requests;
using System.Data.SqlClient;
using System.Data.SQLite;
using System.Security.Cryptography;

namespace MyApp
{
    internal class Program
    {
        private static long TeacherChatID = 0;
        private const string connectionString = "Data Source= C:\\Users\\Amir\\Desktop\\Телеграм бот\\telegramBot\\telegramBot\\students.db";
        private const string TEXT1 = "Узнать мою тему практики";
        private const string TEXT2 = "Изменить мою тему практики";



        private static HashSet<long> ActiveQuestions = new HashSet<long>();  

        static void Main(string[] args)
        {
                var client = new TelegramBotClient("5938181065:AAGyG4jhHjxzYYXMalHOsWaLZK7sEZmupoA");
            client.StartReceiving(Update, Error);
            Console.ReadLine();
        }

        async static Task Update(ITelegramBotClient botClient, Update update, CancellationToken token)
        {

            var message = update.Message;

            if (message == null)
            {
                return;
            }
           
            if (ActiveQuestions.Contains(message.Chat.Id))
            {
                ActiveQuestions.Remove(message.Chat.Id);
                var OldTopic = GetTopic(message.Chat.FirstName);
                UpdateTopic(message.Text, message.Chat.FirstName);
                await botClient.SendTextMessageAsync(message.Chat.Id, "Ваша тема обновлена!");
                if (TeacherChatID != 0)
                {
                    await botClient.SendTextMessageAsync(TeacherChatID, text: $"Студент {message.Chat.FirstName} изменил тему с {OldTopic} на {message.Text}");
                }     
                return;
            }
            

            if (message.Text.ToLower().Contains("/start"))
            {
                await botClient.SendTextMessageAsync(message.Chat.Id, "Добро пожаловать!");
               // await botClient.SendStickerAsync(message.Chat.Id, sticker: "https://tlgrm.ru/_/stickers/ccd/a8d/ccda8d5d-d492-4393-8bb7-e33f77c24907/1.webp");
                return;
            }

            else if (message.Text.ToLower().Contains("привет") && message.Chat.Username == "UnknownCustomer")
            {
                await botClient.SendTextMessageAsync(message.Chat.Id, "Здравствуйте, Роман Валентинович!");
                TeacherChatID = message.Chat.Id;
                return;
            }

            else if (message.Text.ToLower().Contains("привет"))
            {
                string client = message.Chat.FirstName;

                string[] parse = client.Split("_");

                if (parse.Length != 3)
                {
                    await botClient.SendTextMessageAsync(message.Chat.Id, "Ваше имя не отвечает стандартам практики!");
                    await botClient.SendTextMessageAsync(message.Chat.Id, "Пример: Пупкин_ИВ_ИПЗ110К");
                    return;
                }

                string name = parse[0] + " " + parse[1];
                string group = parse[2];

                await botClient.SendTextMessageAsync(message.Chat.Id, $"Привет, студент группы {group}, {name}!");
                await botClient.SendTextMessageAsync(message.Chat.Id, text: "Выбери действие: ", replyMarkup: GetButtons());

            }

            switch (message.Text)
            {
                case TEXT1:
      
                    await botClient.SendTextMessageAsync(message.Chat.Id, text: "Ваша тема: " + GetTopic(message.Chat.FirstName), replyMarkup: GetButtons());
                    break;
                case TEXT2:
                    if (message.Text == TEXT1 || message.Text == TEXT2)
                    {
                        await botClient.SendTextMessageAsync(message.Chat.Id, "Введите тему!");
                    }
                    await botClient.SendTextMessageAsync(message.Chat.Id, text: "Введите свою новую тему практики: " , replyMarkup: GetButtons());
                    ActiveQuestions.Add(message.Chat.Id);
                    break;
            }
        
        }

        private static IReplyMarkup? GetButtons()
        {
           ReplyKeyboardMarkup replyKeyboardMarkup = new(new[]
                    {
                        new KeyboardButton[] { TEXT1 },
                        new KeyboardButton[] { TEXT2 },
                    })
            {
                ResizeKeyboard = true
            };
            return replyKeyboardMarkup;
        }

        private static void UpdateTopic(string topic, string firstName)
        {
            using var connection = new SQLiteConnection(connectionString);
            connection.Open();
            using var command = connection.CreateCommand();
            command.CommandText = "Update studenti SET Topic = @topic WHERE FirstName= @firstName";
            command.Parameters.AddWithValue("@topic", topic);
            command.Parameters.AddWithValue("@firstName", firstName);
            command.Prepare();
            command.ExecuteNonQuery();
        }

        private static string GetTopic(string firstName)
        {
           using var connection = new SQLiteConnection(connectionString);
            connection.Open();
            using var command = connection.CreateCommand();
            command.CommandText = "Select topic FROM Studenti WHERE FirstName= @firstName";
            command.Parameters.AddWithValue("@firstName", firstName);
            command.Prepare();
            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
               return reader.GetString(0);
            }
            return null;
        }

        
        private static Task Error(ITelegramBotClient arg1, Exception error, CancellationToken arg3)
        {
            Console.WriteLine(error.ToString());
            return Task.CompletedTask;
        }      
    }



    
}
