### ISSUE TITLE
Handling conversations and working with database

### ISSUE THREAD

**Issue by gvmohzibat** [irazasyed/telegram-bot-sdk#364]
Hello.
Does telegram bot sdk support database? How can I handle conversations?
For example I have a command "/contact" which displays the message "Please enter your message:". After that the user should enter the contact message. How can I understand this message?

**Comment by irazasyed** [comment]
The SDK has got nothing to do with how you store the data of your bot. But you're free to use anything to store in or outbound communication between your users and the bot.

In other words, you can use a database yes!

As far as the conversations are concerned, you can use either cache or store in a database the last query of the user and your Q and then accordingly map based on the incoming update.

Take a look at this package: https://github.com/telegram-bot-kit/convo (It's not released and possibly outdated but use it for reference purposes).
