### ISSUE TITLE
Calling command from inline button

### ISSUE THREAD

**Issue by num3r06** [irazasyed/telegram-bot-sdk#365]
It's possible to call a bot command from inline button?
I want to start command /search {parameter} and when the answer server is coming (an array of results) for each element of array i want to prepare a inline button which launch command /detail {ret result[x]}.
With keyboard button it's possible, with inline button i don't know how to use callback_data for my scope
Thx

**Comment by stasusov** [comment]
https://github.com/irazasyed/telegram-bot-sdk/issues/350#issuecomment-288225068
`'callback_data' => '/detail ...'`

**Comment by num3r06** [comment]
ok thx

**Comment by peimansh** [comment]
I have exactly the same problem, 
would you please explain more ?
I could not solve the problem by the explanation provided :(

**Comment by peimansh** [comment]
by the way i'm using telegraf in Node.Js
