### ISSUE TITLE
Method for getting previous Updates based on update_id

### ISSUE THREAD

**Issue by Dilden** [irazasyed/telegram-bot-sdk#366]
Is there a method available (possibly in the Api object) for retrieving previous Update objects based on the update_id when a webhook is set? I'm looking for a way to pull the text from a message 1 or 2 messages back from the current message.

**Comment by irazasyed** [comment]
Nope. There is no way to do that with webhook. The only way to achieve that is by storing every message in your database and then looking up using the new update ID or an internal incremental ID. The API doesn't allow you to lookup based on the ids.

The `getUpdates` method does accept [offset](https://core.telegram.org/bots/api#getupdates) param, but it can only work for the updates that are in the queue and till the message is automatically forgotten. So if you have lets say 10 updates lined up in queue which hasn't been read by your bot yet, only then you can use offset in that case. So yeah, database method is rather much better in your case.

Hope that helps and answers your query!
