### ISSUE TITLE
There is no update when inline button attached

### ISSUE THREAD

**Issue by behnamazimi** [irazasyed/telegram-bot-sdk#368]
When I click on an inline button, there is no updates contains `callback_query` or maybe there is no response from server!

It's my `webhookHandler()` method:

```
public function webhookHandler()
{
    $update = $this->telegram->getWebhookUpdate();

    if ($update->isType('callback_query')) {

        $this->telegram->sendMessage([
            'chat_id' => '<My ID>',
            'text' => $update->callbackQuery->data
        ]);

        return 'Ok';

    } else {
        $keyboard = Keyboard::make()
            ->inline()
            ->row(
                Keyboard::inlineButton([
                    'text' => 'Test Btn',
                    'callback_data' => 'callback_from_testbtn'
                ])
            );

        $this->telegram->sendMessage([
            'chat_id' => '<My ID>',
            'text' => 'Text with inline button',
            'reply_markup' => $keyboard
        ]);
        return 'Ok';
    }
    return 'Ok';
}
```

I really need help! what should I do? 😢

**Edit:**
I also removed webhook and check that by `getupdates` to be sure about server. That was OK and when button attached, the last update contains `callback_query`.

**Comment by irazasyed** [comment]
Let me check this and get back to you.

**Comment by irazasyed** [comment]
I just tested and it seems to be working fine.

Here's the complete code:

Make sure you're importing the keyboard class on top of your file:
```php
use Telegram\Bot\Keyboard\Keyboard;
```

Webhook handler:
```php
public function webhookHandler()
{
        $update = $this->telegram->getWebhookUpdate();

        if ($update->isType('callback_query')) {

            $this->telegram->sendMessage([
                'chat_id' => $update->callbackQuery->from->id,
                'text' => $update->callbackQuery->data
            ]);
        } else {
            $keyboard = Keyboard::make()
                ->inline()
                ->row(
                    Keyboard::inlineButton([
                        'text' => 'Test Btn',
                        'callback_data' => 'callback_from_testbtn'
                    ])
                );

            $this->telegram->sendMessage([
                'chat_id' => $update->getMessage()->chat->id,
                'text' => 'Text with inline button',
                'reply_markup' => $keyboard
            ]);
        }

        return 'Ok';
}
```

Response screenshot:
<img width="630" alt="screen shot 2017-04-04 at 11 26 38 pm" src="https://cloud.githubusercontent.com/assets/1915268/24671157/394196c2-198e-11e7-8a01-7cdf9cf610a7.png">


P.S. There was a delay in response from server because I had my local server off, so had to retry after I turned ON (Hence, 2 mins delay).

**Comment by behnamazimi** [comment]
@irazasyed It's same! Not worked! 
I going to create new project and do every steps carefully again. Maybe that was my mistake! (but I test it in two different project before...)

**Comment by irazasyed** [comment]
@behnamazimi Well, I tested and showed you the working example. There's nothing I can do beyond this, unfortunately! :/

Like I said before, Please check your network connections, your codes, docs and my above code as well. Maybe there has been some mistake somewhere, you never know! 

Also, use IDE if not using already (PHPStorm recommended) as that'll help you track issues while you work.

**Comment by behnamazimi** [comment]
@irazasyed I'm so sorry about that but as I said, I created a new project and set it carefully step by step but it is same, not working! Could  I ask you to check and debug my little project? how I can send it to you?

**Comment by behnamazimi** [comment]
@irazasyed It was so strange!!! I create a new bot and set the hook to it. It worked! 😃🕺🏻🕺🏻🕺🏻... 
You know, It took me a day! pufffffff! 😕

**Comment by irazasyed** [comment]
@behnamazimi No worries, Glad to know it worked finally :)

Next, you can create a repo on Github and push your code there and post a link here. If you want to keep things private, then you can ofc either use Github private and give me access or publish it on GitLab.com (They give private access for free and it's just like Github), you can then invite me to your project. I have same username there as well.

**Comment by hellosaeedalizadeh** [comment]
Thanks dear Syed,
I could get updates from webhook but could not get updates of Call back queries form inline keyboards!
Do you think I have to something special ?
I exactly did the same as you did above in an example! but this method 
$update = $this->telegram->getWebhookUpdate(); 
could not get updates of inline keyboards!
Help please :)

**Comment by behnamazimi** [comment]
@hellosaeedalizadeh Is there any established connection to get data from file or database before checking callback query?
I was faced with this problem in two cases. and to solve first one, I create new bot and set my hook on it. and for solving the second, that occurred because of receiving data from database before call back checking, I put my code after callback checking. and it now work correctly.
Bests.

**Comment by hellosaeedalizadeh** [comment]
@behnamazimi now it works and I have no idea :D because I don't change anything!
I am using with Laravel and I think there is no connection to DB before handling the call back query!

**Comment by mramirghafari** [comment]
@irazasyed 
i have this problem too! 
this is my code but it not working for callback data:
```
public function index(Request $request)
    {
        $sm_update = file_get_contents("php://input");
        File::append('fgc.php', $sm_update.PHP_EOL."<hr>");

        $updates = $this->telegram->getWebhookUpdate();
        $amir = json_decode($updates);
        File::append('gwu.php', $updates.PHP_EOL."<hr>");



if ($updates->isType('callback_query')) {
        $query = $updates->getCallbackQuery();
        $data  = $query->getData();
        $chid = $query->getFrom()->getId();
        $this->telegram->sendMessage([ 'chat_id' => $chid, 'text' => $data]);
    }else {
            $this->telegram->sendMessage([
                'chat_id' => $chid,
                'text' => 'hala hala',
                'reply_markup' => json_encode([
                    'inline_keyboard'=>[
                        [
                            ['text'=>"like❤",'callback_data'=>'1'],
                            ['text'=>"unlike👎",'callback_data'=>'2']
                        ]
                    ]
                ])
            ]);
        }

        return 'Ok';

    }
```

tested on: laravel 5.5, laravel 5.4, laravel 5.3

and all package versions!!!! but it not working for me! :(

my issue:
https://github.com/irazasyed/telegram-bot-sdk/issues/504

**Comment by mramirghafari** [comment]
@behnamazimi @hellosaeedalizadeh 
How is your problem solved?

**Comment by shopnaill** [comment]
> I just tested and it seems to be working fine.
> 
> Here's the complete code:
> 
> Make sure you're importing the keyboard class on top of your file:
> 
> ```
> use Telegram\Bot\Keyboard\Keyboard;
> ```
> 
> Webhook handler:
> 
> ```
> public function webhookHandler()
> {
>         $update = $this->telegram->getWebhookUpdate();
> 
>         if ($update->isType('callback_query')) {
> 
>             $this->telegram->sendMessage([
>                 'chat_id' => $update->callbackQuery->from->id,
>                 'text' => $update->callbackQuery->data
>             ]);
>         } else {
>             $keyboard = Keyboard::make()
>                 ->inline()
>                 ->row(
>                     Keyboard::inlineButton([
>                         'text' => 'Test Btn',
>                         'callback_data' => 'callback_from_testbtn'
>                     ])
>                 );
> 
>             $this->telegram->sendMessage([
>                 'chat_id' => $update->getMessage()->chat->id,
>                 'text' => 'Text with inline button',
>                 'reply_markup' => $keyboard
>             ]);
>         }
> 
>         return 'Ok';
> }
> ```
> 
> Response screenshot:
> <img alt="screen shot 2017-04-04 at 11 26 38 pm" width="630" src="https://cloud.githubusercontent.com/assets/1915268/24671157/394196c2-198e-11e7-8a01-7cdf9cf610a7.png">
> 
> P.S. There was a delay in response from server because I had my local server off, so had to retry after I turned ON (Hence, 2 mins delay).

Thanks, you solved my problem :)
