### ISSUE TITLE
how to use stickers as a command?

### ISSUE THREAD

**Issue by mrmrn** [irazasyed/telegram-bot-sdk#369]
I want to use a reply markup such as:
`['/stop','✊']`
and when user click on ✊ I want to fire a command.
but I can not write a controller for it. I mean `✊Command.php` can not be exist.
also I am ok with /stop but I want to get rid of / and have a clean markup such as:
`['stop','✊']` or even better `['👋','✊']`.

**Comment by irazasyed** [comment]
Just check if the sticker or text equals to a specific emoji that you're looking for and then trigger the command using the [triggerCommand](https://github.com/irazasyed/telegram-bot-sdk/blob/develop/src/Traits/CommandsHandler.php#L96-L107) method (Available in v3.x dev).
