### ISSUE TITLE
Can't register commands

### ISSUE THREAD

**Issue by vmohir** [irazasyed/telegram-bot-sdk#372]
Hi, I have some problems with composer and registering commands.
I was able to add Help commands by adding this code to webhook.php:
`$telegram->addCommand(Telegram\Bot\Commands\HelpCommand::class);
$update = $telegram->commandsHandler(true);`

Now I want to add a custom command to my bot. I have a file in Commands/ContactCommand.php. And I have this lines to composer.json in root folder:
`{
	"require": {
		"irazasyed/telegram-bot-sdk": "^2.0"
	},
	"autoload": {
		"psr-4": {
			"CustomCommands\\": "Commands/"
		}
	}
}
`
Then I added this line to webhook.php:
`$telegram->addCommand(CustomCommands\ContactCommand::class);`

But now the bot doesn't work. when I comment the last line, the bot works properly.
What am I doing wrong?

**Comment by irazasyed** [comment]
@gvmohzibat Hi,

Make sure the following:
- You've set the namespace in `ContactCommand.php` same as you've registered in `composer.json` file.
- Fire `$ composer dump-autoload` command once to make sure composer loads your file. 

If after doing the above, it still doesn't work. Then please post your `webhook.php` and the `ContactCommand.php` full code.

**Comment by gvmohzibat** [comment]
@irazasyed Thanks for your reply.
I'm not sure how I should set the namespace :\

ContactCommand.php:
```php
<?php
namespace Telegram\Bot\Commands;
class ContactCommand extends Command
{
	protected $name = 'contact';
	protected $description = 'contact command';

	public function handle($arguments)
	{
		$this->replyWithMessage('text');
	}
}
```
webhook.php:
```php
<?php
// requirements
require 'vendor/autoload.php';
use Telegram\Bot\Api;

// connecting
$telegram = new Api('TOKEN');

// get user message
$updates = $telegram->getWebhookUpdates();
$chat_id = (int) $updates->getMessage()->getChat()->getId();
$text = $updates->getMessage()->getText();

$telegram->addCommand(Telegram\Bot\Commands\HelpCommand::class);
$telegram->addCommand(CustomCommands\ContactCommand::class);
$update = $telegram->commandsHandler(true);

$telegram->sendMessage([
  'chat_id' => $chat_id,
  'text' => $text
]);

?>
```

composer.json:
```json
{
	"require": {
		"irazasyed/telegram-bot-sdk": "^2.0"
	},
	"autoload": {
		"psr-4": {
			"CustomCommands\\": "Commands/"
		}
	}
}
```

And btw! I have another question. How can I see the errors like 'nycooookie' in [this topic](https://github.com/irazasyed/telegram-bot-sdk/issues/284) ?

**Comment by irazasyed** [comment]
Update your `ContactCommand.php` with:

```php
<?php

namespace CustomCommands;

class ContactCommand extends Command
{
...
```

Notice the namespace above? That's same as the one you've set in your composer file and should always match.

**Comment by irazasyed** [comment]
As far as seeing the errors are concerned, That normally happens when there's an error and you execute the script, it'll automatically throw the error. However, You can log errors to file + use try/catch to catch any exception.

Also, You should see if debugging and display error is disabled on your dev/production env. That'll prevent from displaying errors as well.

**Comment by gvmohzibat** [comment]
I've used namespace CustomCommands; before and I tried it again now but it still doesn't work.
You can see my files here:
https://github.com/gvmohzibat/phptelegrambottest

**Comment by irazasyed** [comment]
Did you run `$ composer dump-autoload` after updating the namespace?

**Comment by gvmohzibat** [comment]
Yes I did!

**Comment by denyskorkh** [comment]
Hello! I have similar problem, please help! Did everything described in this topic but did not help
