### ISSUE TITLE
support for inline keyboards

### ISSUE THREAD

**Issue by gvmohzibat** [irazasyed/telegram-bot-sdk#373]
Hi.
Does Telegram-bot-sdk support [inline keyboards](https://core.telegram.org/bots/api#inlinekeyboardmarkup)?

I'm not able to create one.
this is my code:
```php
$keyboard = [
	    ['7', '8', '9'],
	    ['4', '5', '6'],
	    ['1', '2', '3'],
	         ['0']
	];
/*	this code works:
        $reply_markup = $telegram->replyKeyboardMarkup([
		'keyboard' => $keyboard, 
		'resize_keyboard' => true, 
		'one_time_keyboard' => true
	]);
*/

// but this does not:
	$keyboard_markup = Telegram\Bot\Keyboard\Keyboard::make([
		'keyboard' => $keyboard, 
		'resize_keyboard' => true, 
		'one_time_keyboard' => true
	]);
	$keyboard_markup->inline();

	$telegram->sendMessage([
	  'chat_id' => 92454,
	  'text' => $text,
	  'reply_markup' => $reply_markup
	]);
```

**Comment by irazasyed** [comment]
Hey!

Please refer this [comment](https://github.com/irazasyed/telegram-bot-sdk/issues/368#issuecomment-291581829).

**Comment by gvmohzibat** [comment]
Thanks. solved.
My problem was with the version of telegram-bot-sdk. In installation part of [documentation](https://telegram-bot-sdk.readme.io/docs), it's said to use this command:

> composer require irazasyed/telegram-bot-sdk ^2.0

but this version doesn't support keyboards so I changed my composer.json file to this:

``` json
{
    "require": {
        "irazasyed/telegram-bot-sdk": "master-dev"
    }
}
```
