### ISSUE TITLE
how to handle new user join and left super groups

### ISSUE THREAD

**Issue by R30na** [irazasyed/telegram-bot-sdk#377]
I have a bot which is doing some calculations on ["message"]["text"]
when a user joins and left the group the webhookInfo page gives 500 server error 
how can I handle the join and left actions. 

I also tried to check this but is doesnt work.

`$updates = Telegram::getWebhookUpdates();
        $response = json_decode($updates, true);
if($response["message"]["new_chat_participant"]["id"] || $response["message"]["left_chat_participant"]["id"]){
return 'ok';
}
`

**Comment by king-11** [comment]
@mehr30na any solution you got on this I am also facing the same issue whenever user the leaves the bot webhook fails

**Comment by R30na** [comment]
Sorry really can not remember as it was long time ago. But now there are couple of good Bot implementations for Node.js out there you can try them if you are about to build a new one.
