### ISSUE TITLE
Check if webhook url is valid

### ISSUE THREAD

**Issue by MrFiregore** [irazasyed/telegram-bot-sdk#378]
how to check if the webhook url is valid?

**Comment by hellosaeedalizadeh** [comment]
Call this by GET : 

https://api.telegram.org/bot<bot_token>/getWebhookInfo

**Comment by firegore2** [comment]
with getWebhookInfo only catch the info of the updates recibed, don't catch the info of the server side. For example, if I put this:
`$bot->setWebhook(['url'=>'https://google.es/']);`
the response of the server's Telegram said Ok : true
