### ISSUE TITLE
Which method is use to send messages?

### ISSUE THREAD

**Issue by Ham3D** [irazasyed/telegram-bot-sdk#38]
Hello
i recently had a bug , i suppose this sdk use Get method to send text messaged to telegram api, right ?
when i try to send a big message a message pops up about :
{"<html>\r\n<head><title>414_Request-URI_Too_Large<\/title><\/head>\r\n<body_bgcolor":"\"white\">\r\n<center><h1>414 Request-URI Too Large<\/h1><\/center>\r\n<hr><center>nginx\/1.6.2<\/center>\r\n<\/body>\r\n<\/html>\r\n"}
is there a way to use Post instead of Get ?

**Comment by jonnywilliamson** [comment]
Good point. I wondered about this a few months ago.

@irazasyed - any reason why we use GET requests instead of POST requests when connecting to the telegram server?

I had a look and try to change the normal GET to POST in the code, but I wasn't sure how to set the parameters to `application/x-www-form-urlencoded` so I wasn't successful.

**Comment by jonnywilliamson** [comment]
Actually I just worked it out.

If we change the `$this->get` to a `$this->post` in any of the send methods on the API, we have to add a `form_params` to the parameters.

This could be refactored, but a quick hack at the moment would look like this:


```php
// Api.php

    /**
     * Send text messages.
     *
     * @link https://core.telegram.org/bots/api#sendmessage
     *
     * @param int    $chat_id
     * @param string $text
     * @param bool   $disable_web_page_preview
     * @param int    $reply_to_message_id
     * @param string $reply_markup
     *
     * @return Message
     */
    public function sendMessage(
        $chat_id,
        $text,
        $disable_web_page_preview = false,
        $reply_to_message_id = null,
        $reply_markup = null
    ) {
        $params = compact('chat_id', 'text', 'disable_web_page_preview', 'reply_to_message_id', 'reply_markup');
        $response = $this->post('sendMessage', ['form_params' => $params]);

        return new Message($response->getDecodedBody());
    }
```

**Comment by Ham3D** [comment]
it seems working , send a Pr

**Comment by irazasyed** [comment]
Please open a new PR and I can merge it. I won't be able to work on this until this month end. So either someone send a PR or please wait. Thanks!!

**Comment by jonnywilliamson** [comment]
https://github.com/irazasyed/telegram-bot-sdk/pull/40 Refers
