### ISSUE TITLE
How to create Command class for handling chat message without "/" prefix?

### ISSUE THREAD

**Issue by galo4kin** [irazasyed/telegram-bot-sdk#381]
How to create Command class (i.e., class ProfileCommand extends Command) for handling a chat message without "/" prefix (i.e., "My profile" user message)

**Comment by irazasyed** [comment]
You can't do that right now but a workaround is to detect the text and manually trigger the command using the `triggerCommand` method after registering the command.

**Comment by galo4kin** [comment]
Sorry. This code don't work on router/web.php script if chat message not equal '/start':
`$telegram = new \Telegram\Bot\Api;`
`$telegram->addCommand(new App\Http\Commands\Start);`
`$telegram->commandsHandler(true);`

If user write '/start' message this code work fine

Class App\Http\Commands\Start have protected property $name = "start";

**Comment by galo4kin** [comment]
If user send message 'My profile' method \Telegram\Bot\Commands\CommandBus::parseCommand returned empty $matches and everybody command did't execute

**Comment by jonnywilliamson** [comment]
@galo4kin You cannot expect the command to fire if it does not match a command.

Commands by they definition start with a "/", that's what the documents state.
https://core.telegram.org/bots#commands


If YOU want to search every text message your bot receives for a special "key word" then you should do that. After the commandHandler is done processing an inbound update for a command (which starts with a /) it RETURNS the update object.

You can then search the update yourself for the "key word" and then do whatever you would like at this stage. The code below probably doesn't work, but it's just an outline of what you need to do.

```
$telegram = new \Telegram\Bot\Api;
$telegram->addCommand(new App\Http\Commands\Start);

//If the Update contains a message with a command (eg /start), the command handler will detect it and match it to a command class, in this example "Start"
$update = $telegram->commandsHandler(true);

// If it does not have a command in it, the commandsHandler will just return the Update
// Instead now you can do what you want here with the $update and trigger a command if you need to
if(preg_match('%start%', $update->getMessage()->getText()){
   $telegram->triggerCommand('start', $update)
}

```

**Comment by galo4kin** [comment]
Thanx. But this code don't work. Class `\Telegram\Bot\Api` don't have `triggerCommand` method. I can add this method or change line:
`$telegram->triggerCommand('start', $update)` 
to:
`$telegram->getCommandBus()->execute('start', '', $update);` – it's work.

Thax for your support!

**Comment by dadwic** [comment]
`$telegram->getCommandBus()->execute('start', [], $update);`

**Comment by tesenvit** [comment]
what am I doing wrong?
use:
- Laravel 5.5
- "irazasyed/telegram-bot-sdk": "dev-develop"
- webhook

my code
```
public function webhookHandler()
{
    $update = $this->telegram->commandsHandler(true);
    $this->telegram->triggerCommand('myCommand',$update);
}
```
this does not work =(

**Comment by rtfmfm** [comment]
Hello! I'm trying to achieve the same, but I do not know where to add this check if the update does not have a command? Could you tell me, please?

I have the commands working very well, but I want to add the ability the bot to reply without a command.

Best regards!
