### ISSUE TITLE
Problem in use parse_mode

### ISSUE THREAD

**Issue by BangShut** [irazasyed/telegram-bot-sdk#382]
I want to use the phone, but I'm wrong. What is the reason?

**Bad Request: unsupported parse_mode**
` 
 $response = $telegram->sendMessage([
            'chat_id' => 13,
            'parse_mode' =>'<code>inline fixed-width code</code>',
        ]);
`

**Comment by irazasyed** [comment]
`parse_mode` can only have either `HTML` or `Markdown` as it's value.

Example:
```php
$response = $telegram->sendMessage([ 
    'chat_id' => 13,
    'parse_mode' => 'HTML',
    'text' =>'<code>inline fixed-width code</code>'
]);
```
