### ISSUE TITLE
What is the advantages and disadvantages of Asynchronous Requests?

### ISSUE THREAD

**Issue by behnamazimi** [irazasyed/telegram-bot-sdk#386]
What is the Asynchronous Requests exactly means? Why should or should not set it True? or When is it necessary to set True or False?
Is there any relation between Asynchronous Requests and pending update count?

**Comment by jonnywilliamson** [comment]
Means you can send many requests faster, however because you do not wait for reply from telegram you have no idea if Telegram actually read/processed your request.

Personally I don't think its a great idea. But I'm sure others who want to send an insane amount of texts might find it useful.

**Comment by behnamazimi** [comment]
Thanks for your reply.
So I think it's useless in bot's that depends on a hook and server response!
