### ISSUE TITLE
Handling pending updates

### ISSUE THREAD

**Issue by hellosaeedalizadeh** [irazasyed/telegram-bot-sdk#389]
I have a problem with this when I have an error from webhook Telegram add the request to pending updates list but when my webhook works fine again I could not empty the pending updates and bot after fill the pending updates list about 40 will blocked by telegram!

"pending_update_count":9,
"last_error_date":1494444307,
"last_error_message":"Wrong response from the webhook: 500 Internal Server Error",
"max_connections":40

anyone could help me please ? how could i handle pending updates?

thanks before

**Comment by sefidpardazesh** [comment]
i have same problem!!
can you solve that???

**Comment by hellosaeedalizadeh** [comment]
@sefidpardazesh for me it was because of some other post which forwarded to my bot for example from Channels, as I could not handle the structure of data my webhook return 500 error and when you respond error back to telegram it will put the request on a queue and pendding updates will count, the only way to prevent this is to respond with status 200 and telegram think you handled the request!

**Comment by AntoLuMeju99** [comment]
how to respond with status 200?

**Comment by ds-ivanenko** [comment]
@saeedalzdh 
answer, please!!!!
How to respond with status 200? 
I have same problem and can't resolved it!!!

**Comment by irazasyed** [comment]
You'll have to return a simple response with header status code 200. It could just be echoing some text like `Ok` and if you have properly set up your tech stack, then the default status code should automatically be applied.
