### ISSUE TITLE
problem with send photo

### ISSUE THREAD

**Issue by iMohammadd** [irazasyed/telegram-bot-sdk#394]
hello
i want send photo stored on my server bot getting error:

> CouldNotUploadInputFile in CouldNotUploadInputFile.php line 29: Filename not provided for http://domain.com/XXXXX.jpg. Remote or Resource file uploads require a filename. Refer Docs for more information.

my code:
`$this->telegram->sendPhoto([
            'chat_id'=>'XXXXXX',
            'photo'=>'http://domain.com/XXXXX.jpg'
 ]);`

**Comment by firegore2** [comment]
Did you try using https url?

**Comment by iMohammadd** [comment]
@firegore2
yes

**Comment by jonnywilliamson** [comment]
Latest version (develop branch) must use an `InputFile` object when sending ANY files.

```
    \Telegram::bot('sdk')->sendPhoto([
        'chat_id' => '',
        'photo'   => InputFile::create($resourceOrFile, $filename),
        'caption' => '',
    ]);
```
