### ISSUE TITLE
deleteMessage Method is not working!

### ISSUE THREAD

**Issue by mehr30na** [irazasyed/telegram-bot-sdk#405]
according to this link we can delete messages by this method:
https://core.telegram.org/bots/api#deletemessage
but how we can do it in Laravel? with this method it is not working: 
`Telegram::deleteMessage([
                                'chat_id' => $message["chat"]["id"],
                                'message_id' => $message["message_id"]
                            ]);`

**Comment by irazasyed** [comment]
Use the `dev-develop` branch for this method.

**Comment by mehr30na** [comment]
please provide me with the sample.

**Comment by bekaproger** [comment]
In order to be able to delete message just open Api.php file in src folder of the package and convert post method into pubilc method on line 946. Now you can use it :

**Comment by trolllik** [comment]
> In order to be able to delete message just open Api.php file in src folder of the package and convert post method into pubilc method on line 946. Now you can use it :
> $telegram->post('deleteMessage', array $params);

thanks ! now working. ad this in Api.php:
`public function deleteMessage(array $params)
    {
        $response = $this->post('deleteMessage', $params);
        return new Message($response->getDecodedBody());
    } 

`
and use it  $telegram->deleteMessage(array $params);
