### ISSUE TITLE
How to manage multiple bots and create dynamic config for use?

### ISSUE THREAD

**Issue by BehroozBvk** [irazasyed/telegram-bot-sdk#407]
Hi, I want to design a system that can handle multiple bots. The question here is how to have a dynamic file configuration.ex : App / telegram.php

Why should a submission be created and initialized for each bot. If you need to manage the settings manually in the current state. 

Thank you for helping me.

**Comment by irazasyed** [comment]
@BehroozBvk Check out the dev-develop branch. The SDK already supports multiple bots ;)

It's just not tagged but if you read the source code, you'll understand.

**Comment by BehroozBvk** [comment]
Yes, I understand, but I want to know how to add several bots in the app / telegram.php file dynamically and automatically.

And that there is another way, for example: a function for connecting your boat

**Comment by BehroozBvk** [comment]
Someone does not answer?

**Comment by glenwell** [comment]
Seems like there's still no answer two years later. I believe it would require a slight edit of the `BotsManager.php` file. However, I bet this would involve a lot of extending of classes.


```
/**
     * Make a dynamic bot instance.
     *
     * @param string $name
     *
     * @return Api
     */
    protected function makeDynamicBot($params): Api
    {
        $telegram = new Api(
            $params['token'],
            $params['async_requests'],
            $params['http_client_handler']
        );

        // Check if DI needs to be enabled for Commands
        if ($params['resolve_command_dependencies'] && isset($this->container)) {
            $telegram->setContainer($this->container);
        }

        $commands = $params['command'];
        $commands = $this->parseBotCommands($commands);

        // Register Commands
        $telegram->addCommands($commands);

        return $telegram;
    }
```
