### ISSUE TITLE
Constant error on every request

### ISSUE THREAD

**Issue by ingria** [irazasyed/telegram-bot-sdk#411]
Hi, I'm receiving this error from any request:

```
production.ERROR: Telegram\Bot\Exceptions\TelegramOtherException: 
Forbidden: bot was blocked by the user in /vendor/irazasyed/telegram-bot-sdk
/src/Exceptions/TelegramResponseException.php:58
```

The bot was not blocked by the users, and the error appeared about a week ago (suddenly, no code changes were made. Now I have gigabytes of error logs, full of this error.

What can it be?

**Comment by codefuhrer** [comment]
UPD: even if I don't use your lib's methods, I'm still getting that exception.

```
// StartCommand.php:

$url = 'https://api.telegram.org/bot' . $token . '/sendMessage?' . http_build_query([
    'chat_id' => 1111...1111,
    'text' => 'Test',
]);

file_get_contents($url);
```

Throws

Telegram\Bot\Exceptions\TelegramResponseException: Forbidden: bot was blocked by the user in /vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php:58

**Comment by codefuhrer** [comment]
Resolved. I was storing the bot token in .env, and because of some mysterious reason env('BOT_TOKEN') began returning `null`.

You should add the appropriate exception message, because I was confused by the "bot was blocked by the user" error.

**Comment by jonnywilliamson** [comment]
Fairly sure this is caught with the new tests in ver 3.
