### ISSUE TITLE
I got error in laravel 5.2 when using command handler!

### ISSUE THREAD

**Issue by amirpiri** [irazasyed/telegram-bot-sdk#412]
`public function webhook(Request $request)
    {
        Log::info($request);
        
        $update = Telegram::commandsHandler(true);
	
        // Commands handler method returns an Update object.
        // So you can further process $update object 
        // to however you want.

        Log::info($update);
        
        return 'ok';
    }`

 Telegram\Bot\Exceptions\TelegramOtherException: Not Found in /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php:58
Stack trace:
#0 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(174): Telegram\Bot\Exceptions\TelegramResponseException::create(Object(Telegram\Bot\TelegramResponse))
#1 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(204): Telegram\Bot\TelegramResponse->makeException()
#2 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(65): Telegram\Bot\TelegramResponse->decodeBody()
#3 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/TelegramClient.php(138): Telegram\Bot\TelegramResponse->__construct(Object(Telegram\Bot\TelegramRequest), Object(GuzzleHttp\Psr7\Response))
#4 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/TelegramClient.php(119): Telegram\Bot\TelegramClient->getResponse(Object(Telegram\Bot\TelegramRequest), Object(GuzzleHttp\Psr7\Response))
#5 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Api.php(1014): Telegram\Bot\TelegramClient->sendRequest(Object(Telegram\Bot\TelegramRequest))
#6 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Api.php(957): Telegram\Bot\Api->sendRequest('POST', 'sendMessage', Array)
#7 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Api.php(303): Telegram\Bot\Api->post('sendMessage', Array)
#8 [internal function]: Telegram\Bot\Api->sendMessage(Array)
#9 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Commands/Command.php(192): call_user_func_array(Array, Array)
#10 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Commands/HelpCommand.php(32): Telegram\Bot\Commands\Command->__call('replyWithMessag...', Array)
#11 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Commands/Command.php(149): Telegram\Bot\Commands\HelpCommand->handle('')
#12 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Commands/CommandBus.php(195): Telegram\Bot\Commands\Command->make(Object(Telegram\Bot\Api), '', Object(Telegram\Bot\Objects\Update))
#13 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Commands/CommandBus.php(157): Telegram\Bot\Commands\CommandBus->execute('help', '', Object(Telegram\Bot\Objects\Update))
#14 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Api.php(873): Telegram\Bot\Commands\CommandBus->handler('/help', Object(Telegram\Bot\Objects\Update))
#15 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Api.php(839): Telegram\Bot\Api->processCommand(Object(Telegram\Bot\Objects\Update))
#16 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Telegram\Bot\Api->commandsHandler(true)
#17 /usr/share/nginx/html/tbot/app/Http/Controllers/TelegramBotController.php(28): Illuminate\Support\Facades\Facade::__callStatic('commandsHandler', Array)
#18 [internal function]: App\Http\Controllers\TelegramBotController->webhook(Object(Illuminate\Http\Request))
#19 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)
#20 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('webhook', Array)
#21 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\TelegramBotController), Object(Illuminate\Routing\Route), 'webhook')
#22 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\TelegramBotController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'webhook')
#28 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'webhook')
#29 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#30 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#46 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#48 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#51 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#53 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#55 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#56 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#57 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#58 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#59 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#60 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#61 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#64 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#68 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#69 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#70 /usr/share/nginx/html/tbot/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#71 {main}

Next Telegram\Bot\Exceptions\TelegramResponseException: Not Found in /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php:58
Stack trace:
#0 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(174): Telegram\Bot\Exceptions\TelegramResponseException::create(Object(Telegram\Bot\TelegramResponse))
#1 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(204): Telegram\Bot\TelegramResponse->makeException()
#2 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(65): Telegram\Bot\TelegramResponse->decodeBody()
#3 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/TelegramClient.php(138): Telegram\Bot\TelegramResponse->__construct(Object(Telegram\Bot\TelegramRequest), Object(GuzzleHttp\Psr7\Response))
#4 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/TelegramClient.php(119): Telegram\Bot\TelegramClient->getResponse(Object(Telegram\Bot\TelegramRequest), Object(GuzzleHttp\Psr7\Response))
#5 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Api.php(1014): Telegram\Bot\TelegramClient->sendRequest(Object(Telegram\Bot\TelegramRequest))
#6 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Api.php(957): Telegram\Bot\Api->sendRequest('POST', 'sendMessage', Array)
#7 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Api.php(303): Telegram\Bot\Api->post('sendMessage', Array)
#8 [internal function]: Telegram\Bot\Api->sendMessage(Array)
#9 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Commands/Command.php(192): call_user_func_array(Array, Array)
#10 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Commands/HelpCommand.php(32): Telegram\Bot\Commands\Command->__call('replyWithMessag...', Array)
#11 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Commands/Command.php(149): Telegram\Bot\Commands\HelpCommand->handle('')
#12 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Commands/CommandBus.php(195): Telegram\Bot\Commands\Command->make(Object(Telegram\Bot\Api), '', Object(Telegram\Bot\Objects\Update))
#13 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Commands/CommandBus.php(157): Telegram\Bot\Commands\CommandBus->execute('help', '', Object(Telegram\Bot\Objects\Update))
#14 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Api.php(873): Telegram\Bot\Commands\CommandBus->handler('/help', Object(Telegram\Bot\Objects\Update))
#15 /usr/share/nginx/html/tbot/vendor/irazasyed/telegram-bot-sdk/src/Api.php(839): Telegram\Bot\Api->processCommand(Object(Telegram\Bot\Objects\Update))
#16 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Telegram\Bot\Api->commandsHandler(true)
#17 /usr/share/nginx/html/tbot/app/Http/Controllers/TelegramBotController.php(28): Illuminate\Support\Facades\Facade::__callStatic('commandsHandler', Array)
#18 [internal function]: App\Http\Controllers\TelegramBotController->webhook(Object(Illuminate\Http\Request))
#19 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)
#20 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('webhook', Array)
#21 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\TelegramBotController), Object(Illuminate\Routing\Route), 'webhook')
#22 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\TelegramBotController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'webhook')
#28 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'webhook')
#29 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#30 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#46 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#48 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#51 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#53 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#55 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#56 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#57 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#58 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#59 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#60 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#61 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#64 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#68 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#69 /usr/share/nginx/html/tbot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#70 /usr/share/nginx/html/tbot/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#71 {main}

**Comment by rishatsharafiev** [comment]
I had the same error
First, i've updated telegram-bot-sdk to version 2.2
Second, i had mistake in env variable `TELEGRAM_BOT_TOKEN`.
Check out it.
Good luck!
