### ISSUE TITLE
Delete chat message

### ISSUE THREAD

**Issue by wp-src** [irazasyed/telegram-bot-sdk#416]
Hi, i use dev-develop branch, but i can not find any way to delete a message.
Please show me an example of deleting a message in dev-develop version of api.
Thanks.

**Comment by kooroshh** [comment]
this package doesn't support new bot updates , however you can implement it by adding the function to 
https://github.com/irazasyed/telegram-bot-sdk/blob/master/src/Api.php

**Comment by mehr30na** [comment]
Hii, How to delete the messages send by bot itself??. I can not the message_id sent by bot itself.

**Comment by mrTigerFox** [comment]
store it by sending

**Comment by irazasyed** [comment]
You can use `deleteMessage` method to remove the message provided you have the chat and message id. You can refer the method [here](https://github.com/irazasyed/telegram-bot-sdk/blob/develop/src/Methods/EditMessage.php#L199-L234).
