### ISSUE TITLE
Could not get command arguments

### ISSUE THREAD

**Issue by adifaidz** [irazasyed/telegram-bot-sdk#417]
Hi, I'm using the telegram-bot-sdk-starter project to create my bot (using dev-develop version). I'm trying to get my command's arguments but I couldn't.

The message I send through telegram is ` /locate arg1` but I keep getting `array (
  0 => '',
) `  when I call getArguments in the command class.

It was working before (Started the project around May, I think), and I mistakenly updated the package. Was there any changes to the way how it works? Because now when I try to remove and reinstall the package, it still doesn't work.

Also, now this line in the starter project doesn't work anymore
```php
$response = $this->telegram->setWebhook()
            ->url($url)
            ->getResult();
```

Now I need to do this. Is this the intended way to do it now?
```php
$response = $this->telegram->setWebhook(['url' => $url]);
```

**Comment by IronGhost63** [comment]
https://telegram-bot-sdk.readme.io/docs/commands-system

I am not sure if command code in starter project look the same as in doc. But if it does, just all $arguments.

if you have more than one arguments, you need to use explode() to split string by yourself.

**Comment by jonnywilliamson** [comment]
Warning new command system argument detection code is being written at the moment. The docs are (will be) out of date.

Keep an eye on the tests and the commits on the develop branch

**Comment by makuser** [comment]
Any update on this?

**Comment by adifaidz** [comment]
Idk if this has been resolved but in case not,  I used this (Not saying what I'm doing is the way):

Created a base class with handle method eg: BaseCommand

```php
    public function handle(){
        $update = $this->getUpdate();
        $this->parseArguments($update);
    }

    /**
     * Serves as a temporary fix for getting arguments
     * @param  Update $update   Telegram Update object
     * @return bool             Returns true for success and false for failure
     */
    protected function parseArguments(Update $update){
        $args = (explode(' ', $update->getMessage()->getText())); //
        unset($args[0]);
        $args = array_values($args);

        return $this->arguments = !empty($args) ? $args : [];
    }
```
Then just call `parent::handle()` in the class extending it eg: CalculateCommand

```php
    public function handle(){
        parent::handle();
    }
```

**Comment by eric2100** [comment]
Use version 3.0.0
Can not find the argument value

**Comment by dekron** [comment]
I also can't get an argument in the 3.0.0 version

I sent command /set 123

`public function handle()
  {
    $arguments = $this->getArguments();
    Log::debug($arguments);`

local.DEBUG: array (
)

**Comment by Xibel** [comment]
Update to version 3.1 and define your $pattern like:

protected $pattern = '{myargument}';

See #735 for more information.
