### ISSUE TITLE
how to create inline button for share message

### ISSUE THREAD

**Issue by miladr0** [irazasyed/telegram-bot-sdk#419]
telegram has a bot it's name is @like you can create vote with that bot.
![1](https://user-images.githubusercontent.com/6761526/28594826-9896c06e-71a6-11e7-92c2-80a5f3c1f7fe.PNG)

my problem is with share button. how can i share, created voting message so other user can like or dislike
it.
@like bot give me blew string for sharing.how can i acheve that.
![2](https://user-images.githubusercontent.com/6761526/28594930-f83f59b8-71a6-11e7-97c5-a72a2801d9a4.PNG)

**Comment by Zhambul** [comment]
Use switch_inline_query in inline_keyboard

**Comment by erfanhemmati** [comment]
@Zhambul how i can use it?

**Comment by sjomurodov** [comment]
[Awesome Telegram Bot](https://i.stack.imgur.com/WqTGU.jpg)
