### ISSUE TITLE
[request] SendPhoto from URL

### ISSUE THREAD

**Issue by aleritty** [irazasyed/telegram-bot-sdk#42]
Actually your API support only the official method (upload a local file OR reference a file_id).

But automatically handling URL (so submitting as multipart data) can be really useful.

Thank you for your work!!

**Comment by irazasyed** [comment]
Well, We could add support for that but you could simply use built-in PHP functions like `file_get_contents` and pass on the image URL, then the response to the sendPhoto method.

But thanks for the suggestion though. I'll consider this before the next release and see if we can implement it.

**Comment by jonnywilliamson** [comment]
+1

**Comment by azizbek8434** [comment]
hi, i couldn't sent photo using this api methods
```
$response = Telegram::sendPhoto([
  'chat_id' => 'CHAT_ID', 
  'photo' => 'path/to/photo.jpg', 
	'caption' => 'Some caption'
]);
```

>and this is json data and image path

![default](https://user-images.githubusercontent.com/36416819/49513723-bf78ce80-f8b3-11e8-9030-373c1f3bffb9.png)

> and this is my code
```
    protected function getProducts($chat_id,$category_slug,$manager_slug,$lang='en'){
    $products = file_get_contents('https://test.com/api/products?manager='.$manager_slug.'&category='.$category_slug);
        $data = json_decode($products,true);
        foreach($data['data'] as $product){
        Telegram::sendPhoto([
            'chat_id' => $chat_id,
            'photo' => 'https://test.com/public'.$product['image'],
            'caption' => $product['name']
        ]);
    }
```
please help me, thanks in advance..
