### ISSUE TITLE
Using telegram to send message to phone numbers

### ISSUE THREAD

**Issue by nenaeneto** [irazasyed/telegram-bot-sdk#425]
Good morning, I'm using in my telegram chatbot project. I need to create messaging for a list of phone numbers. The registration I have is just a phone number, not ID. I can not solve this problem. If anyone can help me. Thanks

**Comment by mikerockett** [comment]
That is not possible through bots. You cannot even send a message directly to a user via their username.

**Comment by jonnywilliamson** [comment]
@nenaeneto Sorry this will NEVER be possible.

You must get your users to contact YOUR bot first. When then contact your bot (normally by clicking the start button on their phones when they open a chat with it), your system will receive an update message.

In this message will be that users telegram_id. You will have to save/link each users telegram_id with a phone number (if you want to), or just save their telegram_id for later use.

You can then send messages to your users, by using their telegram_id. This avoids you being able to spam people without them ever having contacted you in the first place.

Hope that helps.

**Comment by happykala** [comment]
There is a way to do it. add phone number to your contacts and then you will got their userid, send message to userid. I notice the tool can send messages to phone numbers, you can try a test.https://chromewebstore.google.com/detail/teleplus-multi-accounts-s/ihopneheidomphlibjllfheciogojmbk
