### ISSUE TITLE
Use deleteWebhook to remove, not setWebhook

### ISSUE THREAD

**Issue by mikerockett** [irazasyed/telegram-bot-sdk#427]
Telegram's API allows for the use of [`deleteWebhook`](https://core.telegram.org/bots/api#deletewebhook).

**Comment by jonnywilliamson** [comment]
Hi @mikerockett 

That's currently available in the dev branch for this library

https://github.com/irazasyed/telegram-bot-sdk/blob/develop/src/Methods/Update.php#L103-L113

**Comment by mikerockett** [comment]
Ah, great stuff, thank you!

**Comment by mikerockett** [comment]
Is the dev branch stable enough for use as yet?

**Comment by jonnywilliamson** [comment]
Personally I've been using it for months. No issues at all.
