### ISSUE TITLE
Inlile keyboard+callback_query=status bar Loading

### ISSUE THREAD

**Issue by rodendron** [irazasyed/telegram-bot-sdk#431]
Can you tell me, why when i click on my inline keyboard button, i see "Loading..." status in the top of the chat. 
But SendMessage function already sent message correct.
Sometimes show's time of this status is 10-15 sec. Sometimes i do not see it.
How i can hide this?
Regards

**Comment by tondogiro** [comment]
Can you send some code? It seems you have written something like `sendChatAction`

**Comment by rodendron** [comment]
I think, that is mistake of all Telegram or only my connection or phone. And sometimes i see the same "Loading" bar string from all bots who has inline keyboard.
I think, i can close issue.
My code is:
           $reply = "Press button Start";
           $inline_button = array('text' => 'Press start', 'callback_data' => '/start'); 
           $keyboard = [[$inline_button]];
           $keyboard = array("inline_keyboard" => $keyboard);
           $replyMarkup = json_encode($keyboard);
           $telegram->sendMessage([ 'chat_id' => $chat_id, 'parse_mode'=> 'HTML', 'text' => $reply, 'reply_markup' => $replyMarkup ]);

**Comment by alihesari** [comment]
@rodendron Thank you, You saved my time.
