### ISSUE TITLE
Laravel: No Responce

### ISSUE THREAD

**Issue by JBird608** [irazasyed/telegram-bot-sdk#432]
Hi all, 

I have been trying to get this package to work for a little time now, so far I have been able to publish a message to Telegram, however I am unable to get a responce from anything.

I have a controller set up for the two different types of request `TelegramController`. 

```PHP
<?php

namespace App\Http\Controllers;

use Telegram\Bot\Api;
use Telegram\Bot\Laravel\Facades\Telegram;

class TelegramController extends Controller
{

    public function without()
    {

        $telegram = new Api(env('TELEGRAM_BOT_TOKEN'));

        $response = $telegram->getMe();

        return $response;
    }

    public function with()
    {

        $response = Telegram::getMe();

        $botId = $response->getId();
        $firstName = $response->getFirstName();
        $username = $response->getUsername();

        return $response;
    }
}
```

When calling the method `without` I get the JSON responce, however if I call the `with` I get nothing. 

Does anyone know how to solve this problem so I can use the Facade? 

Cheers, Joe.

**Comment by amahag** [comment]
Hi Joe, 
It's because you have set Asynchronous request true in telegram.php in config folder. So Telegram::getMe() will call the request but doesn't wait to receive a response from the server. so you will face a free response.

**Comment by irazasyed** [comment]
Hi,

Please refer this project: https://github.com/irazasyed/telegram-bot-laravel-starter

You don't have to initialize the `Api` class if you set up the service provider in your `app.php` file and then set bot token in `.env` file.
