### ISSUE TITLE
Too many Request : retry after .. | (telegram bot Limit)

### ISSUE THREAD

**Issue by mahdiahmadi73** [irazasyed/telegram-bot-sdk#433]
hi
 i create bot that send some messae to some user .but each time i send message  i get this exception :
  
  Next Telegram\Bot\Exceptions\TelegramResponseException: Too Many Requests: retry after 283 in 
  /home/mahdi/PhpstormProjects/first/vendor/irazasyed/telegram-bot -
  sdk/src/Exceptions/TelegramResponseException.php:58
 i know problem comes from telegram limit (429) that bot cant send more than 30 message per secnd or 1 message to user per second .
i use sleep(2) or sleep(3) between my code but problem still exist 
my question is :
1-how to handle the exception and before occured .
2-how to get response code (exception) after sendMessage.
3-is it good idea to use Laravel Job  this problem (send message to user) ? and how
please send some example code or documention

@irazasyed

**Comment by sautchenkov** [comment]
Telegram also has limit 20 messages per minute to one user.

**Comment by ragsfdc** [comment]
I too am facing the same problem.. I tried below code snippet still did not work.  I tried with telegram.error.TimedOut but that also didnt help out. Anyone pls help

try:
        for k,v in dictOfitems.items():
        bot.send_message(chat_id=group_id,text=f'{k} :: On {v}')
except telegram.error.RetryAfter as e:
         sleep(45)
         bot.send_message(chat_id=group_id,text=f'{k} :: On {v}')
