### ISSUE TITLE
getCallBackQuery method does not exists.

### ISSUE THREAD

**Issue by tondogiro** [irazasyed/telegram-bot-sdk#434]
Hi everyone... 
I have a problem that seems to be a common problem... but I have not found a workly solution :(

I have an inline button but I do not receive any update when I click it...

I let you see my code...

First of all I added this line to the composer:
`"irazasyed/telegram-bot-sdk": "^2.2"` (before was 2.0 but due to the error I tryed to change it with 2.2)

Then I set my Webhooks and then I have done a execute.php page: 
```
require_once('vendor/autoload.php');

use Telegram\Bot\Api; //there are no other "use"

$telegram = new Api(TelegramConfig::BOT_TOKEN);

$request = $telegram->getWebhookUpdates();

if ($telegram->isMessageType('text', $request))
{
    //If I write a command, I go here and everything works propery
}
else
{
    // I expected to go here if I clicked an inline button, but not.....
}
```

When I click an inline button `$request` is null so I get an error when I do the if....
Another strange thing to me is that when I write the code the intellisense do not let me see the method `getCallbackQuery` in the request...

`$telegram->getCallbackQuery()` .. It seems `getCallbackQuery` does not exists.... 

Who can help me... is 4 days I am trying to solve by me this problem but with no success...
Thank you

**EDIT**
I have discovered a thing strange to me... 
if I print the request encoded I see it

```
$response = $telegram->sendMessage([
    'chat_id' => myChatId,
    'text' => json_encode($request)
]);
```
In this way I see the json

but when I do, 2 lines later
`$telegram->isMessageType('text', $request)`
I get this error: 

> PHP Fatal error:  Uncaught Error: Call to a member function has() on null in /app/vendor/irazasyed/telegram-bot-sdk/src/Api.php:891
> 
> Stack trace:
> #0 /app/execute.php(20): Telegram\Bot\Api->isMessageType('text', NULL)

it seems request is null

**EDIT 2 **
I have navigated inside `Update.php` and I see:

```
/**
 * Class Update.
 *
 *
 * @method int      getUpdateId()   The update's unique identifier. Update identifiers start from a certain positive number and increase sequentially.
 * @method Message  getMessage()    (Optional). New incoming message of any kind - text, photo, sticker, etc.
 */
```

But in github the fille seems to be differente and seems to have the calback too:

```
/**
 * Class Update.
 *
 *
 * @method int                  getUpdateId()               The update's unique identifier. Update identifiers start from a certain positive number and increase sequentially.
 * @method Message              getMessage()                (Optional). New incoming message of any kind - text, photo, sticker, etc.
 * @method EditedMessage        getEditedMessage()          (Optional). New version of a message that is known to the bot and was edited.
 * @method InlineQuery          getInlineQuery()            (Optional). New incoming inline query.
 * @method ChosenInlineResult   getChosenInlineResult()     (Optional). A result of an inline query that was chosen by the user and sent to their chat partner.
 * @method CallbackQuery        getCallbackQuery()          (Optional). Incoming callback query.
 *
 * @link https://core.telegram.org/bots/api#update
 */
```

**Comment by salvokt** [comment]
Ciao,ce un modo per contattarti oltre questo?

**Comment by fcoedno** [comment]
I have also noted this issue with the Update.php Class. Not sure why the version 2.2 is not updated in the release. Anyway, you can do the following:

    require_once('vendor/autoload.php');

    use Telegram\Bot\Api; //there are no other "use"

    $telegram = new Api(TelegramConfig::BOT_TOKEN);

    $update = $telegram->getWebhookUpdates();

    if ($update->getMessage() !== NULL)
    {
        // You have here a message (be it text, sticker, whaterver)
    }
    else
    {
        $callbackQuery = $update->getCallbackQuery();
        if ( $callbackQuery !== NULL ) {
            // You can use now callbackQuery
            // Get the callbackQuery data with:
            $data = $callbackQuery->getData();
        }
    }
