### ISSUE TITLE
update sdk

### ISSUE THREAD

**Issue by Buheda** [irazasyed/telegram-bot-sdk#435]
Hi. Thanks for SDK.
Could you please update this SDK with the newest methods in the TELEGRAM API ?

**Comment by irazasyed** [comment]
Hi, I'm working on it!

**Comment by jonnywilliamson** [comment]
Yeah, will try and get around to this when I can too.

**Comment by DJafari** [comment]
@irazasyed can i known when coming update ?

**Comment by dzatona** [comment]
@irazasyed sendContact is not working. Is it a bug or we're should wait for an update?

**Comment by mehdikhody** [comment]
use this.
https://github.com/botstan/API

**Comment by irazasyed** [comment]
@mehdikhody Please stop spamming this repo with your promotional messages!
