### ISSUE TITLE
Get user id (chat id) in command class

### ISSUE THREAD

**Issue by sharuman** [irazasyed/telegram-bot-sdk#436]
Hi,
how can I access to the user id within a **command class**?
Suppose I need to make a query to my database in the _HelpCommand.php_ class using the user id. How can I achieve this? I've already tried using _$GLOBALS [user_id]_ (which I set in index.php) but it's not working: 
> PHP Notice:  Undefined index: user_id
That's very strange. What am I missing?

**Comment by holtkamp** [comment]
uhm... **are** there userIds? I believe only chatId's and phoneNumbers are involved. By default you would use the chatId. If you want to 'match' the user with an existing user in your database, you need the phoneNumber. The user has specifically "share" the phonenumber with your bot. Then you should be able to lookup your user in your database and store the chatId for future reference...

**Comment by irazasyed** [comment]
Hi,

Just use `$this->getUpdate();` to retrieve the original update object and you can then fetch the user id or any other data.
