### ISSUE TITLE
Get user and group sender of command

### ISSUE THREAD

**Issue by Alvaroctal** [irazasyed/telegram-bot-sdk#44]
Hi, 

As far as I have read, it's not possible to get the group or the user from which a command has been sent, it would be useful for "private" bots, or user systems.

what do you think?

**Comment by jonnywilliamson** [comment]
Hi,

I'm not sure I follow what you mean.

When a command is issued by a user in a channel (say a group chat) this update object is sent to your webserver for processing.

As you can see it has the details of the user that sent it AND the name of the chat it was sent in.

Is this not what you are looking for?

```
(
    [update_id] => 304090973
    [message] => Array
        (
            [message_id] => 2733
            [from] => Array
                (
                    [id] => 12443287
                    [first_name] => FirstName
                    [last_name] => LastName
                    [username] => username
                )

            [chat] => Array
                (
                    [id] => -20301211
                    [title] => Chat Title
                )

            [date] => 1444162469
            [text] => /somecommand@botname
        )

)

```

**Comment by Alvaroctal** [comment]
Yeah, telegram sends all that into to the web-hook, but I would like that info accesible from inside a Command class.
