### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by holtkamp** [irazasyed/telegram-bot-sdk#441]
Looking at https://github.com/irazasyed/telegram-bot-sdk/releases it has been a while since a new release was tagged, forcing users to rely on the `master` branche. This is not a huge problem, but forces users to inspect updates as done by composer, for example today:

```
  - Updating irazasyed/telegram-bot-sdk dev-master (32d56bd => b445b62):  Checking out b445b62166dfdd838909f693e0b75511e60587ad
    Pulling in changes:
      b445b62 - Syed Irfaq R. ⚡️: Merge pull request #439 from imanghafoori1/master
      9c4bf8f - Iman: Flatten the code
```

Whould it be an idea to tag the current master branch as a new version?

**Comment by irazasyed** [comment]
Current `master` branch is very outdated and a lot has been changed since the last version + `develop` branch.

So tagging a release with `master` branch isn't ideal and going forward, `develop` branch is going to be merged over `master` once a few more things and tests are done.

**Comment by holtkamp** [comment]
ok, thanks for the information on this
