### ISSUE TITLE
New feature proposal

### ISSUE THREAD

**Issue by imanghafoori1** [irazasyed/telegram-bot-sdk#449]
web.php
```php
Route::telegramWebHook('someControler@someMethod');
// or
Route::telegramWebHook(function(){

   // some php code here...
});
```

The hook url goes in config file.
config/telegram.php : 
```
'mybot' => [
            'username' => 'TelegramBot',
            'web_hook_url' => 'bot<some-token>/webhook',  
            'token'    => env('TELEGRAM_BOT_TOKEN', 'YOUR-BOT-TOKEN'),
            'commands' => [
                //Acme\Project\Commands\MyTelegramBot\BotCommand::class
            ],
        ],
```

**Comment by irazasyed** [comment]
What's the benefit? You can just use one dedicated post route for all your bots.

**Comment by imanghafoori1** [comment]
Some people use the same laravel app serve both reqular website and a bot.
The bot is an assistant for the web app. so the web.php gets crowded.

**Comment by irazasyed** [comment]
You can use `routes/api.php` for this then. I do the same thing and here's how it works:

```php
Route::post('/telegram/{bot}/{token}/webhook', 'BotController@webhook')->name('bot-webhook');

// Ex:
// https://domain.com/api/telegram/mybot/12345/webhook
```

```php
class BotController extends Controller
{
    /**
     * Webhook Handler
     *
     * @param $bot
     *
     * @return string
     */
    public function webhook($bot)
    {
        Telegram::bot($bot)->commandsHandler(true);

        return 'Ok';
    }
}
```

**Comment by irazasyed** [comment]
And here's my `setWebhook` method.

```php
/**
 * Set Webhook
 *
 * @param $bot
 *
 * @return string
 */
public function setWebhook($bot)
{
    $token = Telegram::getBotConfig($bot)['token'];
    $webhook = route('bot-webhook', ['name' => $bot, 'token' => $token]);

    Telegram::bot($bot)->setWebhook([ 'url' => $webhook]);

    return 'Done!';
}
```

**Comment by imanghafoori1** [comment]
All bots using the same controller method...
I think the should have their own controller because the want to do their own thing...
```php
Route::telegramBot('my_bot1', 'botController1@handle');

Route::telegramBot('my_bot2', 'botController2@handle');
```
each bot is now free to do it's own thing in it's dedicated controller...

**Comment by irazasyed** [comment]
You can already do that using the post routes. Just create a new one for each bot and its own controller. Totally up to you and flexible. I don't this we need another route method for this as it'll likely confuse people and restrictions with the webhook path and other options. Thanks for the proposal, though.
