### ISSUE TITLE
how to get messages that is not command

### ISSUE THREAD

**Issue by derakoola** [irazasyed/telegram-bot-sdk#45]
How to get messages that is not command in command mode?! 
@irazasyed

**Comment by irazasyed** [comment]
You mean to say, You want to handle normal messages that don't start with a slash?

Like a simple text message `hello world`?

You can normally do that and don't need to create a command class.

**Comment by derakoola** [comment]
@irazasyed 
Yes, that is my issue.

I have a route like this:
`// Laravel
Route::post('/<token>/webhook', function () {
    Telegram::commandsHandler(true);

    return 'ok';
});`

Now I want to get user feedback directly, I don't want to add another route and...

Is it possible?

**Comment by irazasyed** [comment]
Yes, That's possible!

The command handler function returns update object, So if it's not a command and simply a message. It'll return the update object which you can then use it and process accordingly.

Example:
```php
Route::post('/<token>/webhook', function () {
    $update = Telegram::commandsHandler(true);

    $message = $update->getMessage();
    $chatId = $message->getChat()->getId();
    Telegram::sendMessage($chatId, 'Hello World');

    return 'ok';
});
```

**Comment by derakoola** [comment]
Good.
