### ISSUE TITLE
Class TelegramServiceProvider not found

### ISSUE THREAD

**Issue by shaludama** [irazasyed/telegram-bot-sdk#461]
hello
i'm new in Laravel!

when trying to run 
`php artisan vendor:publish`

got the error Class 'Telegram\Bot\Laravel\TelegramServiceProvider' not found

what's the problem?
thanks

**Comment by irazasyed** [comment]
It's possible you haven't installed this SDK using composer properly and just added the service provider to the config? Please check! Reinstall if required.
