### ISSUE TITLE
Callback and Inline query button loadings

### ISSUE THREAD

**Issue by yongkylie** [irazasyed/telegram-bot-sdk#462]
Here is my code :
```
$keyboard = Keyboard::make()
	->inline()
	->row(
		Keyboard::inlineButton(['text' => 'Button 1', 'callback_data' => 'this is button 1']),
		Keyboard::inlineButton(['text' => 'Button 2', 'callback_data' => 'this is another button being pressed'])
	);

$response = Telegram::sendMessage([
	'chat_id' => $some_chat_id, 
	'text' => 'Voila! Here come buttons you requested!',
	'reply_markup' => $keyboard
]);
```

The button works flawlessly, but if i press it, it keep showing loading for 5-15 seconds even the process have been completed.
Any help would be appreciated. Cheers!

**Comment by sautchenkov** [comment]
I receive this behavior only in Android Telegram client. Where you receive this @yongkylie ?

**Comment by yongkylie** [comment]
@sautchenkov Android Telegram client too. I don't know how it affects for iOS phone. But it may confuse some people.

**Comment by sautchenkov** [comment]
@yongkylie I did tests and web, ios and desktop clients don't have this behavior. I think this is Android Client specific problem. 

I also have this problem and will search some solution.

**Comment by bagaiev** [comment]
Hello, we have the same issue on Mac OS client. Any hints on possible reason would be very useful.

**Comment by jonnywilliamson** [comment]
Sorry, are you guys using

https://core.telegram.org/bots/api#answercallbackquery


![image](https://user-images.githubusercontent.com/2513663/31772302-26f776f0-b4d7-11e7-9417-b54ac03cf9de.png)


You MUST reply to an inbound callback query. Even if it doesn't need to tell the user anything.

**Comment by jonnywilliamson** [comment]
Sorry I should clarify.

You MUST return a answerCallbackQuery to the user even if you're not going to display anything. See the highlighted text for the warning.

![image](https://user-images.githubusercontent.com/2513663/31773273-24eec8f6-b4da-11e7-8bfc-8cc8261881a1.png)

**Comment by jonnywilliamson** [comment]
@yongkylie  @sautchenkov @bagaiev 

No feedback guys?

**Comment by sautchenkov** [comment]
I resolve my problem with loading with using this code: 
```
 $query = $update->getCallbackQuery();
 $this->callback_id = $query->getId();

Telegram::answerCallbackQuery([
            'callback_query_id' => $this->callback_id
        ]);
```
Thanks @jonnywilliamson

**Comment by wedhasmara** [comment]
@sautchenkov what is $update variable? Would you like to show the code above that?

**Comment by sautchenkov** [comment]
Hi! @wedhasmara I updated my code above.

**Comment by wedhasmara** [comment]
Oh I see. Thank you so much @sautchenkov

**Comment by yongkylie** [comment]
@jonnywilliamson I should be more careful and read through all the docs before opening an issue I guess. Works pretty well with @sautchenkov code. Thanks a bunch guys! :)

**Comment by Mirzapulatov** [comment]
I used guzzle for bot-sdk 2.2
`public static function answerCallbackQuery($callback_query_id)
    {
        $client = new Client();
        $client->request('GET', config('telegram.api_url') . config('telegram.bot_token') . '/answerCallbackQuery?callback_query_id='.$callback_query_id);
    }`

**Comment by karjok** [comment]
@jonnywilliamson thanks sir. I never see thats message before when i open the documentation. It working properly.

**Comment by Qvei** [comment]
Guys, how about if i need editMessageText after receiving callback_data? 
What if my bot work's mostly with editMessageText? I must to send editMessageText and right after that send answerCallbackQuery? How you guys do this properly?
I have switch case function and every case use editMessageText method...
Sorry for my bad english.
