### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by shadowgroundz** [irazasyed/telegram-bot-sdk#464]
Hello, I am a beginner who wants to develop a telegram bot using the SDK you created. To use webhook, do I have to use self-signed certificate?

**Comment by jonnywilliamson** [comment]
I use homestead and vagrant to set up a test development server. Then ngrok provides access from the telegram server when it wants to send me an update.

When I used this setup there was no requirement for me to send a send-signed certificate.

Your mileage may vary.

**Comment by irazasyed** [comment]
@shadowgroundz You can either use a self-signed certificate or use one of the following options (Easier alternates):

# Development
- [Ngrok](https://ngrok.com/)

# Production
- [CloudFlare](https://www.cloudflare.com/)
- [LetsEncrypt](https://letsencrypt.org/)
