### ISSUE TITLE
GetChatMembersCount bug

### ISSUE THREAD

**Issue by weijinnx** [irazasyed/telegram-bot-sdk#466]
[Laravel 5.5]
So, when I use Telegram::getChatMembersCount([chat_id => id]) - I get a stream, but it needs to return integer (number of members). That is not only bug, I tested getChatAdministrators - the same. Any suggestions why?

**Comment by jonnywilliamson** [comment]
This is all fixed in the develop branch.

https://github.com/irazasyed/telegram-bot-sdk/blob/develop/src/Methods/Chat.php#L191-L194

Add `->getResults()` to the end of the method in `Api.php` if you need an emergency fix.

**Comment by weijinnx** [comment]
@jonnywilliamson thanks! I just updated the package to master branch. Now it works. But I think, you need to release this version.
