### ISSUE TITLE
getFile

### ISSUE THREAD

**Issue by derakoola** [irazasyed/telegram-bot-sdk#47]
$telegram = new Api(config('telegram.bot_token'));
$files = $telegram->getFile($fileId);

make error below:
```Argument 3 passed to Telegram\Bot\Api::sendRequest() must be of the type array, string given, called in .../vendor/irazasyed/telegram-bot-sdk/src/Api.php on line 715 and defined```

**Comment by jonnywilliamson** [comment]
What version of the script are you using?

Line 715 has nothing to do with Api::sendRequest() in the latest commit.
https://github.com/irazasyed/telegram-bot-sdk/blob/master/src/Api.php#L715



The `getFile()` method does NOT exist in the v1.0.0 release.
https://github.com/irazasyed/telegram-bot-sdk/blob/v1.0.0/src/Api.php#L715

You must use the latest files for this to work.

**Comment by derakoola** [comment]
@jonnywilliamson 

I use version ^1.0
latest stable version.

**Comment by jonnywilliamson** [comment]
So therefore you cannot use the `getfFile()` method.

**Comment by derakoola** [comment]
@jonnywilliamson
Witch version has this method?

**Comment by jonnywilliamson** [comment]
Did you not read my message above?

Officially this commit had the feature added: https://github.com/irazasyed/telegram-bot-sdk/commit/002633187bb9abd5a1b103b916a5e2bee2d2cdfa

Just use the latest files or this in your composer.json

`composer require irazasyed/telegram-bot-sdk dev-master`

**Comment by derakoola** [comment]
@jonnywilliamson 
Thanks.
