### ISSUE TITLE
cURL error 7

### ISSUE THREAD

**Issue by abolfazlmohajeri** [irazasyed/telegram-bot-sdk#472]
hi i wanted to set webhook but i got error how can i solve this issue?
 (1/1) TelegramSDKException
cURL error 7: Failed to connect to api.telegram.org port 443: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by sautchenkov** [comment]
Try to do `ping  api.telegram.org` maybe you have some network issues.

**Comment by abolfazlmohajeri** [comment]
@sautchenkov thanks for your respond.
Yes the problem was from host provider and it solved.

**Comment by masami6871** [comment]
> I had this problem,
> It is for filtering in iran, You should be use with vpn

im using vpn .  but i have this problem yet.  
i am confused

**Comment by saeedadmin** [comment]
> > I had this problem,
> > It is for filtering in iran, You should be use with vpn
> 
> im using vpn . but i have this problem yet. i am confused

I am Iranian and I have exactly the same problem
