### ISSUE TITLE
error when using webhook

### ISSUE THREAD

**Issue by maximilianb8** [irazasyed/telegram-bot-sdk#48]
Hi,
i've a problem with the telegram-bot-sdk.
When i activate webhook i've the following error in my php:
Fatal error: Call to a member function has() on a non-object in Api.php on line 681
The code is:
        $message = $update->getMessage();
        if ($message->has('text')) 

I've PHP Version 5.5.9.
Thank you.
Massimiliano

**Comment by alexsoft** [comment]
It is because message is not an object. Because of the fact that onner relationships of update are not initialized. I've already created a PR #49 for fixing that.

**Comment by irazasyed** [comment]
@maximilianb8 Can you please post your webhook specific codes?

I just tested and it works just fine.

@alexsoft The objects are initialized as soon as you call `get<Object>()`, So if you do `getMessage()`, behind the scene it would automatically initialize the object. I just tested it again and everything works fine as expected.
