### ISSUE TITLE
multibot with BotsManager

### ISSUE THREAD

**Issue by cruim** [irazasyed/telegram-bot-sdk#481]
I add [https://github.com/irazasyed/telegram-bot-sdk/blob/master/src/BotsManager.php](url) BotsManager class.  Add in telegram.php 

`return [

    'default' => 'common',
    'manager' => 'second',

    'bots' => [
        'common' => [
            'username'  => 'MyTelegramBot',
            'token' => env('TELEGRAM_BOT_TOKEN'),
            'commands' => [
//                Acme\Project\Commands\MyTelegramBot\BotCommand::class
            ],
        ],
        'second' => [
            'username'  => 'MySecondBot',
            'token' => env('TELEGRAM_MANAGER_BOT_TOKEN'),
        ],
    ],`
Create instance of this class in webhook for second bot
`$config = file(__DIR__.'/../../../config/telegram.php');
        $bots_manager= new BotsManager($config);`

What I must do next that message for second bot is correctly processed?

**Comment by cruim** [comment]
I add this `$bots_manager= new BotsManager($config);` $config look like [I](http://joxi.ru/v29neVXtG9dYaA) try to call `$bots_manager = $bots_manager->bot('second'); `Return error Bot [second] not configured.

**Comment by FayzullaKhodja** [comment]
I have same error

**Comment by cruim** [comment]
look at comments on this post. I fix it with it.
