### ISSUE TITLE
How to add a new method in the package due to the update of the telegram

### ISSUE THREAD

**Issue by BehroozBvk** [irazasyed/telegram-bot-sdk#483]
Hello
How can I add new methods in the updated telegram api to the package myself? For example, the `video_note `.too long to update the package's new version.

**Comment by BehroozBvk** [comment]
No one has a comment?

**Comment by jonnywilliamson** [comment]
Use the develop branch. All methods are there including the very latest.

**Comment by jonnywilliamson** [comment]
Ah looks like that method was missing.

https://github.com/irazasyed/telegram-bot-sdk/pull/489 will fix it when it gets merged.

**Comment by BehroozBvk** [comment]
tanks
