### ISSUE TITLE
Cannot use Telegram\Bot\Objects\Message as Message because the name is already in use

### ISSUE THREAD

**Issue by hadikmsh** [irazasyed/telegram-bot-sdk#484]
Hi
i use this package (dev version) with laravel 5.5 and it work without any problem in local host but when i want to use it on the server i got this error:
Cannot use Telegram\Bot\Objects\Message as Message because the name is already in use.
irazasyed/telegram-bot-sdk/src/Methods/Payments.php on line 5.

how can i fix it?

**Comment by BehroozBvk** [comment]
I also have this problem but the problem was solved by commenting `Telegram \ Bot \ Objects \ Message`

**Comment by ahmadbadpey** [comment]
I had same problem and when commented `Telegram \ Bot \ Objects \ Message` in `payments.php` file now I got this error  : 
`Declaration of App\Commands\StartCommand::handle($arguments) must be compatible with Telegram\Bot\Commands\Command::handle()`
