### ISSUE TITLE
Update "Getting Started" in the Documentation

### ISSUE THREAD

**Issue by BehzadV** [irazasyed/telegram-bot-sdk#486]
Hi and thanks for this great job you have done,

I think the `composer require irazasyed/telegram-bot-sdk ^2.0` part of the "Getting Started" documentation needs updating; because the 2.0 version doesn't support versions of `illuminate/support` higher than 5.2.7.
And that causes installation problems when attempting to install on latest versions of Laravel (5.5.19 to be specific).

Thanks

**Comment by irazasyed** [comment]
Hey! Thanks for the feedback.

The entire documentation needs to be updated as the SDK has gotten major changes since version 2.0.

It's on the to-do list but won't be able to do it until the 3.0 is stable.

Thanks!
