### ISSUE TITLE
How do you get the invite link from a chat?

### ISSUE THREAD

**Issue by reense** [irazasyed/telegram-bot-sdk#487]
Hello everyone, 

The official docs suggest that I should be getting an invite_link per channel.

![screen shot 2017-10-30 at 16 56 16](https://user-images.githubusercontent.com/3921273/32180830-4aac6410-bd93-11e7-9eef-123958733576.png)

Does anyone know why this isn't coming back in the ```getUpdates()``` ?
Is there any way of retrieving the invite_link?

Pardon me if this is a stupid question, but I couldn't find anything about this in the docs.

**Comment by jonnywilliamson** [comment]
Seems like this is a bug on Telegrams side.

I could only get it to work with the following:

1) the group is a channel or supergroup.
2) The bot was an admin
3) The channel actually had an invite link created in the settings for it.
![image](https://user-images.githubusercontent.com/2513663/32201896-2801e6ae-bdd1-11e7-90c2-0bfffcc70063.png)

4) I had to run the new method https://core.telegram.org/bots/api#exportchatinvitelink `exportChatInviteLink` ONCE for the channel/group.


Then, once all that was done, everytime I called `->getChat()` it WOULD return an `invite_link`
![image](https://user-images.githubusercontent.com/2513663/32201890-203cfe04-bdd1-11e7-8448-911499af3133.png)



Perhaps not all those steps are needed. But thats what I did to make it work. The SDK supports the information, it just wasnt sent until all those things had been done.

**Comment by reense** [comment]
Thanks! That fixed my problem.

Closing.

**Comment by silasoli** [comment]
> Seems like this is a bug on Telegrams side.
> 
> I could only get it to work with the following:
> 
> 1. the group is a channel or supergroup.
> 2. The bot was an admin
> 3. The channel actually had an invite link created in the settings for it.
>    ![image](https://user-images.githubusercontent.com/2513663/32201896-2801e6ae-bdd1-11e7-90c2-0bfffcc70063.png)
> 4. I had to run the new method https://core.telegram.org/bots/api#exportchatinvitelink `exportChatInviteLink` ONCE for the channel/group.
> 
> Then, once all that was done, everytime I called `->getChat()` it WOULD return an `invite_link` ![image](https://user-images.githubusercontent.com/2513663/32201890-203cfe04-bdd1-11e7-8448-911499af3133.png)
> 
> Perhaps not all those steps are needed. But thats what I did to make it work. The SDK supports the information, it just wasnt sent until all those things had been done.

Man, yes, I'm here in 2024 and thanking you for that, I hope you have a lot of success in your life
