### ISSUE TITLE
Laravel 5.5: Telegram Class doesn't exist

### ISSUE THREAD

**Issue by gyula21** [irazasyed/telegram-bot-sdk#488]
I have two project where I want to use this SDK. One is Laravel 5.4 the second is Laravel 5.5.
With Laravel 5.4 the message sending goes smoothly, but with the Laravel 5.5 I got the following error:
![telegram](https://user-images.githubusercontent.com/3487559/32190053-d5bf2b46-bdac-11e7-80cc-f3eadfd390b8.png)
What can be the problem?

**Comment by irazasyed** [comment]
What version of the SDK are you using?

**Comment by jonnywilliamson** [comment]
![image](https://user-images.githubusercontent.com/2513663/32200615-7bd935e0-bdca-11e7-819d-932142a4112b.png)


Have just installed a 100% new copy of Laravel 5.5, and the latest commit on dev-develop 

`composer require irazasyed/telegram-bot-sdk dev-develop`

And the SDK is working fine. Sending messages with no errors at all.

Can you check your code again?

**Comment by aso824** [comment]
Did you enabled facade? If not, you can't use `Telegram::` methods.
