### ISSUE TITLE
Connection timeout (Telegram/Curl/Guzzle) - Change timeout not working

### ISSUE THREAD

**Issue by rubenvl2** [irazasyed/telegram-bot-sdk#495]
#Hi, 

Since few days ago I'm getting several:
local.ERROR: Telegram\Bot\Exceptions\TelegramSDKException: cURL error 28: Connection timed out after 10001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/.../vendor/irazasyed/telegram-bot-sdk/src/HttpClients/GuzzleHttpClient.php:114

I search online and found another post with this:  https://github.com/irazasyed/telegram-bot-sdk/issues/130 

I know the connectivity issues can come from the ISP, Telegram, etc... but anyway I wanted to increase that Time Out. 

I tried using the command to increase timeout like you showed, but in any case worked, is always 10s. And I didn't find on the documentation where to use it. 

My implementation now that does not work:

Telegram::setTimeout(30);

            try{
                $response = Telegram::setTimeout(30)->sendMessage([
                    'chat_id' => $chat_id,
                    'parse_mode'=>'html',
                    'text' => $message,
                    'http_client_timeout'         => 40,
                    'http_client_connect_timeout' => 30,
                ]);
            } catch (\Telegram\Bot\Exceptions\TelegramResponseException $e) {
                $errorData = $e->getResponseData();
            }

as you see I tried to put the timeout in 3 places, but in any of them worked out. 

How can I setup more timeout ? 

THANKS!

**Comment by rishatsharafiev** [comment]
Hi, you can patch library here `vendor/irazasyed/telegram-bot-sdk/src/HttpClients/GuzzleHttpClient.php`.

**Comment by rubenvl2** [comment]
Hi thanks. I also added that in case that the try catch fails, do a second try. Usually, if fails on the first, will work on the second, but makes sending messages to slow, so need to move it to a queue. 

Thanks!
