### ISSUE TITLE
Method [replyKeyboardMarkup] does not exist ?

### ISSUE THREAD

**Issue by BehroozBvk** [irazasyed/telegram-bot-sdk#497]
Hi , I use the develop version and I want to create a response, but with the following error, I can:
`[2017-11-08 00:06:47] local.ERROR: Method [replyKeyboardMarkup] does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method [replyKeyboardMarkup] does not exist. at C:\\xampp\\htdocs\
eservitionBot\\vendor\\irazasyed\\telegram-bot-sdk\\src\\Api.php:98)`

Mycode : 
```
$keyboard = [
                    ['test1','test1','test1']
                ];
                $reply_markup = Telegram::replyKeyboardMarkup([
                    'keyboard' => $keyboard,
                    'resize_keyboard' => true,
                    'one_time_keyboard' => true
                ]);

                Telegram::sendPhoto([
                    'chat_id' => $chat_id,
                    'photo' => 'AgADBAADMakxGy85YFOiekhnRNtSr1od-hkABPvv-7v-92YinTgCAAEC',
                    'caption' =>   'hi',
                    'reply_markup' => $reply_markup
                ]);```

Is this method defined in this version?

**Comment by BehroozBvk** [comment]
Someone has no suggestion?

**Comment by BehroozBvk** [comment]
The problem solved by adding the following code in the Api.php file has been resolved.

`public function replyKeyboardMarkup(array $params)
    {
        return Keyboard::make($params);
    }`

Why is the patch upgraded this way irregularly instead of getting better?

**Comment by slev-ua** [comment]
> Telegram::replyKeyboardMarkup is deprecated! Use Telegram\Bot\Keyboard\Keyboard::make(array $params = []) instead.
> To be removed in next major version.

Why not use
`$reply_markup = Keyboard::make($params)`
directly?

**Comment by milad-jfr** [comment]
> 
> 
> > Telegram::replyKeyboardMarkup is deprecated! Use Telegram\Bot\Keyboard\Keyboard::make(array $params = []) instead.
> > To be removed in next major version.
> 
> Why not use
> `$reply_markup = Keyboard::make($params);`
> directly?

is more information available about this ? can i find related information from Telegram documents ?

**Comment by MahbodHastam** [comment]
Actually the `replyKeyboardMarkup` is deprecated so what you will use now is use `Telegram\Bot\Keyboard\Keyboard` and then
```
$reply_markup = Keyboard::make([
    'keyboard' => $keyboard, 
    'resize_keyboard' => true, 
    'one_time_keyboard' => true
]); 
```

**Comment by Itsmaqsud** [comment]
@MahbodHastam where to get the documentation for v 3.0?(
Without documentation, like a blind person!

**Comment by milad-jfr** [comment]
its a little weird about this package. 
The Developer providing ver 2 on website and docs are for ver 2 . then it passed more than one year from that version and now developers use ver 3 ( dev version ) because of outdated live version(v2).
so everyone looks for ver 3 docs on the web ! , and it seems The Developer does not have any plan for Update !

**Comment by Itsmaqsud** [comment]
> its a little weird about this package.
> Developer providing ver 2 on website and docs are for ver 2 . then it passed more than one year from that version and now developers use ver 3 ( dev version ) because of outdated live version(v2).
> so everyone looks for ver 3 docs on the web ! , and it seems The Developer does not have any plan for Update !

I spoke with the developer, he has already developed version 4.0! Soon plans to make a release, I hope with the documentation :) LMAO

**Comment by Xibel** [comment]
Yes, 4.0 will be released with documentation and tutorials.

**Comment by dmdevelops** [comment]
А сроки кто то называл какие то? А то вообще печаль без доки нормальной

**Comment by paulvales** [comment]
> А сроки кто то называл какие то? А то вообще печаль без доки нормальной

Товарищ) вы нашли альтернативное решение или продолжили использовать эту либу?

**Comment by shokanshi** [comment]
Any updates on the updated documentation? A year has passed.

**Comment by ZekiJohn** [comment]
please update the documentation.
