### ISSUE TITLE
How Make Inline-Keyboard Dynamicly

### ISSUE THREAD

**Issue by DeviceSt15i** [irazasyed/telegram-bot-sdk#501]
i have Some Forms 
and i get they with this query 
      $names = DB::Table('forms')->where('status', 'active')->get();
but idont know How To make button For each One 
can u help me ?

**Comment by Adizbek** [comment]
Are you talking about this?      

        $names = ["One", "two", "three"];
        $keyboard = [];

        foreach ($names as $name) {
            $keyboard[] = [$name];
        }

        $reply_markup = Telegram::replyKeyboardMarkup([
            'keyboard' => $keyboard,
            'resize_keyboard' => true,
            'one_time_keyboard' => true
        ]);


        $this->replyWithMessage(['text' => 'Keyboard. 👍👍👍👍👍', 'reply_markup' => $reply_markup]);

![image](https://user-images.githubusercontent.com/10253982/33079351-310f5e16-cef7-11e7-96c4-18acbd05f200.png)
