### ISSUE TITLE
Implement sending albums method

### ISSUE THREAD

**Issue by flaksp** [irazasyed/telegram-bot-sdk#502]
The new message type is album: https://telegram.org/blog/albums-saved-messages

Documentation for new method: https://core.telegram.org/bots/api#sendmediagroup

**Comment by jonnywilliamson** [comment]
Its just released this morning. Give us a little bit of time to implement! 😂

**Comment by mehdikhody** [comment]
Use this.
https://github.com/botstan/API#inputmedia

**Comment by amediateam** [comment]
Is it supported now?

**Comment by 7KiLL** [comment]
`public function sendMediaGroup()
    {
        $media[0] = [
            'type' => 'photo',
            'media'=> 'URL1'
        ];
        $media[1] = [
            'type' => 'photo',
            'media'=> 'URL2'
        ];

        $json = json_encode($media);

        $params = [
            'chat_id' => <CHAT_ID>,
            'media' => $json
        ];
        $url = 'https://api.telegram.org/bot<YOUR_TOKEN>/sendMediaGroup?';
        $url = $url.http_build_query($params);
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_exec($ch);
        curl_close($ch);
    }`

Fast implementation.

**Comment by halaei** [comment]
For sendMediaGroup() support, there is a need to refactor the way this package handle files. I have done that in my fork, but the fork is deviated from this one and I don't think it can be easily merged, because I removed some features as well.

```php
$telegram->sendMediaGroup([
            'chat_id' => getenv('CHAT_ID'),
            'media' => [
                new InputMedia([
                    'type' => 'photo',
                    'media' => fopen(__DIR__.'/files/photo1.png', 'rb'),
                    'caption' => 'Test 1',
                ]),
                new InputMedia([
                    'type' => 'photo',
                    'media' => fopen(__DIR__.'/files/photo2.png', 'rb'),
                    'caption' => 'Test 2'
                ]),
            ],
        ]);
```
If you are still interested, please check https://github.com/halaei/telegram-bot

**Comment by NikiforovAlexandr** [comment]
```
$api->sendMediaGroup([
    'chat_id' => -1,
    'media' => json_encode([
        [
            'type' => 'photo',
            'media' => 'attach://file1.jpg'
        ],
        [
            'type' => 'photo',
            'media' => 'attach://file2.jpg'
        ]
    ]),
    'file1.jpg'=> InputFile::create('./file1.jpg'),
    'file2.jpg'=> InputFile::create('./file2.jpg'),
]);
```
