### ISSUE TITLE
how to send keyboard only without reply

### ISSUE THREAD

**Issue by alainbelez** [irazasyed/telegram-bot-sdk#506]
currently i send the keyboard using

    $keyboard = [
        ['/getcurrentprice'],
        ['/addpricenotify'],
        ['/removepricenotify']
    ];

    $reply_markup = $this->telegram->replyKeyboardMarkup([
        'keyboard' => $keyboard, 
        'resize_keyboard' => true, 
        'one_time_keyboard' => true,
    ]);

    $this->telegram->sendMessage([
        'chat_id' => '-------------', 
        'text' => 'test',
        'reply_markup' => $reply_markup
    ]);

and the result is

![image](https://user-images.githubusercontent.com/6648110/33161586-69f78d8e-d05f-11e7-982e-aca99b50874e.png)

how do you send keyboard only without the "reply" like this (without the red box above)?

![image](https://user-images.githubusercontent.com/6648110/33161593-739fd1b6-d05f-11e7-9aed-8959b185cb96.png)

**Comment by zvermafia** [comment]
I think it is impossible.
