### ISSUE TITLE
Is it possible to send 2 or more sequent messages (async)?

### ISSUE THREAD

**Issue by victor-ponamariov** [irazasyed/telegram-bot-sdk#509]
Hi there, great package! :)

Is it possible to send, say, one text message and one location message, so that it is guaranteed that they will be delivered one after another?

Something like analogue for DB::transaction :)

**Comment by jonnywilliamson** [comment]
Unless you're sending messages via async, every message I've ever sent has always arrived in sequence.

So just send the
Text message
Location Message

in that order in your script.

**Comment by victor-ponamariov** [comment]
Indeed... thanks :)
