### ISSUE TITLE
email from telegram

### ISSUE THREAD

**Issue by derk371** [irazasyed/telegram-bot-sdk#512]
First, sory for my bad english!
Hi, can someone help me with sending email from telegram?
Is it real? Can u give me some examples?

**Comment by jonnywilliamson** [comment]
Telegram only sends telegram messages to other telegram users.

If you wish you could use a telegram bot that listens for a command from another telegram user, and THEN sends an email...but that is not part of the code in this project. You would have to code that feature yourself on your own webserver,
