### ISSUE TITLE
Delete the messages sent by bot itself after a time.

### ISSUE THREAD

**Issue by mehr30na** [irazasyed/telegram-bot-sdk#513]
Hii, How to delete the messages sent by bot sendMessage() ??. 
I can not get the message_id sent by bot itself.

**Comment by zvermafia** [comment]
Can we see what do you do to get message ID?

**Comment by irazasyed** [comment]
When you send the message, Telegram responds with the Message object. Save the ID into your database or whatever storage method you prefer to store the ID and then you can remove it easily.

Please post your code if you're unsure, So we can help you out.

**Comment by mehr30na** [comment]
very good thank you for your answer
