### ISSUE TITLE
Bad Request: message is too long

### ISSUE THREAD

**Issue by husseinmirzaki** [irazasyed/telegram-bot-sdk#514]
When php reaches this line :
$api->commandsHandler( false );
the Telegram \ Bot \ Exceptions \ TelegramResponseException (400) exception will be thrown
what is the problem ?
Am i doing sth wrong ?

**Comment by zvermafia** [comment]
Maybe, what do you try to send (can we see the message text)?

**Comment by husseinmirzaki** [comment]
my bad
I was trying to extend the whole package and the command handler didn't work.
I gave up on that.
tnx for response
