### ISSUE TITLE
I can't get async request promises

### ISSUE THREAD

**Issue by kemerovo-man** [irazasyed/telegram-bot-sdk#515]
Hello! I want to send async sendMessage. I need to know message_id. But I can't.
GuzzleHttpClient.php send method:
$response = $this->getClient()->requestAsync($method, $url, $options);
            if ($isAsyncRequest) {
                self::$promises[] = $response;
            } else {
                $response = $response->wait();
            }
and
 public function __destruct()
    {
        Promise\unwrap(self::$promises);
    }

How to get promises?

**Comment by firegore2** [comment]
same question
