### ISSUE TITLE
Bot as admin channel

### ISSUE THREAD

**Issue by derakoola** [irazasyed/telegram-bot-sdk#52]
Do you support this?!
"Bot as admin channel"
@irazasyed

**Comment by irazasyed** [comment]
What do you mean? Can you please explain?

**Comment by derakoola** [comment]
According to this:
https://core.telegram.org/bots/api#recent-changes

My question is not true.

After adding bot to channel admin you can send message to channel by bot!
Just we have to replace ```@chat_username``` to chat_id.
Thanks.

**Comment by irazasyed** [comment]
You can use `@channel_username` in place of `chat_id` its supported in master branch. Just not tagged yet.

**Comment by pedrodonis** [comment]
With API de Telegram Bot, I need join new members and delete members whit my bot.
is this possible?
