### ISSUE TITLE
PHP Fatal error in simple use

### ISSUE THREAD

**Issue by ghost** [irazasyed/telegram-bot-sdk#531]
PHP Fatal error:  Uncaught Telegram\Bot\Exceptions\TelegramOtherException: Not Found in /home/android/bot/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php:58
Stack trace:
#0 /home/android/bot/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(174): Telegram\Bot\Exceptions\TelegramResponseException::create(Object(Telegram\Bot\TelegramResponse))
#1 /home/android/bot/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(204): Telegram\Bot\TelegramResponse->makeException()
#2 /home/android/bot/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(65): Telegram\Bot\TelegramResponse->decodeBody()
#3 /home/android/bot/vendor/irazasyed/telegram-bot-sdk/src/TelegramClient.php(138): Telegram\Bot\TelegramResponse->__construct(Object(Telegram\Bot\TelegramRequest), Object(GuzzleHttp\Psr7\Response))
#4 /home/android/bot/vendor/irazasyed/telegram-bot-sdk/src/TelegramClient.php(119): Telegram\Bot\TelegramClient->getResponse(Object(Telegram\Bot\TelegramRequest), Object(GuzzleHttp\Psr7\Response))
 in /home/android/bot/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php on line 58

when use simple code of API it show me this error

**Comment by rishatsharafiev** [comment]
I had the same error
First, i've updated telegram-bot-sdk to version 2.2
Second, i had mistake in env variable `TELEGRAM_BOT_TOKEN`.
Check out it.
Good luck!
