### ISSUE TITLE
commandsHandler : how to check that Command was fired

### ISSUE THREAD

**Issue by j1exus** [irazasyed/telegram-bot-sdk#532]
Hi!
Is there a way to check that command was fired with commandsHandler(true)?
commandsHandler returns Update and I would like to have some check that any of registered Commands was fired or not.
Thanks!
I'm using irazasyed/telegram-bot-sdk 3.0

**Comment by SmirnovMaxim** [comment]
@j1exus, 
https://github.com/irazasyed/telegram-bot-sdk/blob/master/src/Commands/CommandBus.php#L42

**Comment by j1exus** [comment]
Thanks for you reply. But I need to check current message to know is there a concidence with registered command or not. Is there a way to check that the command from current message was fired?
For example, I have
$ update = commandsHandler (true);

it always returns Update object. But if any of the registered commands was fired I do not need Update object for further processing. I need null to make like

if (! $ update) {
return 'ok';
}
..do some code

or something like $ update-> wasFired (): boolean to check if command was fired

Thanks!

**Comment by jonnywilliamson** [comment]
Why not just have your base command class fire an event every time the handle method is run. Then listen for that event. 

https://github.com/irazasyed/telegram-bot-sdk/blob/develop/src/Commands/Command.php#L191


The update object is more or less immutable and is not going to be able to tell you if the text in the update object matched a command in your config file. That will be for you to decide how you want to "detect" that.

**Comment by j1exus** [comment]
Hi! Thanks for your answer and idea. I'll focus on it
