### ISSUE TITLE
Support multi-byte encoding

### ISSUE THREAD

**Issue by iqdoctor** [irazasyed/telegram-bot-sdk#535]
The `\Telegram\Bot\Commands\CommandBus::parseCommand` method uses the `substr()` function, which causes the entities to be incorrectly extracted from the message if the Uft-8 encoding is used.

Instead, the function `mb_substr()` should be used.

I also found two more similar uses of `substr()` in methods: `\Telegram\Bot\Commands\Command::cutTextBetween` and `\Telegram\Bot\Commands\Command::cutTextFrom`

It is also necessary to replace `substr()` usage with `mb_substr()`.

**Comment by jonnywilliamson** [comment]
I don't see any problem with that. Put a PR in and lets see if the tests all pass etc. 👍
