### ISSUE TITLE
awaiting response sign on inline button

### ISSUE THREAD

**Issue by cruim** [irazasyed/telegram-bot-sdk#537]
Hi! I use `"irazasyed/telegram-bot-sdk": "3.*@dev"`. When I click on inlineKeyboard there is sign of awainting [http://joxi.ru/8An9DjpFqPwzP2](url), after return response.  There is my inlineKeyboard code `$reply_markup = Keyboard::make()
                    ->inline()
                    ->row(Keyboard::inlineButton(['text' => '🔗 Go to site', 'url' => 'https://cru.im']))
                    ->row(Keyboard::inlineButton(['text' => '🖇 Bind account', 'callback_data' => 'Bind account']))
                    ->row(Keyboard::inlineButton(['text' => '🌐 Select language', 'callback_data' => 'Select language']))
                    ->row(Keyboard::inlineButton(['text' => '💱 Cross-currency', 'callback_data' => 'Cross-currency']));
                $send_messge = new SendMessageController();
                $send_messge->sendMessage($chatid, '⚙ Help ', $bot_name, $reply_markup);`
 This problem only on inlineKeyboard, replyKeyboardMarkup works fine. Thanks

**Comment by Amegatron** [comment]
You should always send "answerCallbackQuery" even if no reply is intended.

**Comment by cruim** [comment]
@Amegatron Could show some example of answerCallbackQuery? Nothing to see in other issues. Thanks.

**Comment by Amegatron** [comment]
@cruim It could look like this in your callback handler:
```php
$telegram->answerCallbackQuery([
    'callback_query_id' => $update->getCallbackQuery()->getId(),
]);
```
This is an empty reply, meaning that the waiting sign on the inline button will disappear.
Also see [official api docs](https://core.telegram.org/bots/api#answercallbackquery) for this method and other possible parameters.

**Comment by cruim** [comment]
@Amegatron  I do this
`$id = $request['callback_query']['id'];
$keyboard = new KeyboardController();
                $keyboard->selectLanguage($chatid, $bot_name);
                try{

                    $message = new SendMessageController();
                    $message->sendMessage($chatid,$id,$bot_name);
                    $telegram = new Api();
                    $telegram->answerCallbackQuery([
                        'callback_query_id' => $id,
                    ]);
                }
                catch (\Exception $e)
                {
                    $message = new SendMessageController();
                    $message->sendMessage($chatid,$e->getMessage(),$bot_name);
                }`
I get in message `$id`(from `try`) but from block catch I get error `Bad Request: QUERYIDINVALID`
