### ISSUE TITLE
Inline keyboard

### ISSUE THREAD

**Issue by b10585** [irazasyed/telegram-bot-sdk#538]
Hey. Could you help me. I'm trying add inline button with URL to message. In client button dosn't show. Why ?        

```
 $keyboard = Keyboard::make()
              ->inline()
              ->row(
                  Keyboard::inlineButton(['text' => 'Test', 'url' => 'https://www.google.com'])
              );

            $response = Telegram::sendMessage([
              'chat_id' => '-XXXXXXXX',
              'text' => 'To ticket № '. $comment->ticket_id .' added comment',
              'reply_markup' => $keyboard
            ]);
```

**Comment by CORPARU** [comment]
> Hey. Could you help me. I'm trying add inline button with URL to message. In client button dosn't show. Why ?
> 
> ```
>  $keyboard = Keyboard::make()
>               ->inline()
>               ->row(
>                   Keyboard::inlineButton(['text' => 'Test', 'url' => 'https://www.google.com'])
>               );
> 
>             $response = Telegram::sendMessage([
>               'chat_id' => '-XXXXXXXX',
>               'text' => 'To ticket № '. $comment->ticket_id .' added comment',
>               'reply_markup' => $keyboard
>             ]);
> ```

$url_arr[0]['text']='Text URL';
$url_arr[0]['url']='https://www.google.com';

$telegram_user = \Telegram::getWebhookUpdates()['message'];

$response = \Telegram::sendMessage([
            'chat_id' => $telegram_user['from']['id'], 
            'text' => 'Test text:',
            'parse_mode'=>'html',
            'reply_markup'=>json_encode(['inline_keyboard'=>array($url_arr)])
        ]);

**Comment by baxranoff** [comment]
how get $url_arr[0]['callback_query'] value ?

**Comment by rubenvl2** [comment]
@CORPARU Thanks! I attach an example with callback data  I did based in your solution. Thanks!! :) 

        $url_arr[0]['text']='message to show';
        $url_arr[0]['callback_data']='code_to_send';


        $response = $telegram->sendMessage([
            'chat_id' => $chatId, 
            'text' => $message,
            'reply_markup' => json_encode(['inline_keyboard'=>array($url_arr)])
          ]);
