### ISSUE TITLE
How to get "ok": true status from response?

### ISSUE THREAD

**Issue by salarBahador** [irazasyed/telegram-bot-sdk#539]
Hi! tnx for the awesome SDK.
My problem is when I use telegrams bot API it returns the "ok": true status in the first line of response. but with SDK it skips the first line and shows the rest. how can I get the status of the response? to know that if sending the message was ok or it returns an error. any help would be appreciated.

Here is the response I get when I use telegram API:

```
{
    "ok": true,
    "result": {
        "message_id": 1,
        "from": {
            "id": 12345678,
            "first_name": "YourBot",
            "username": "YourBot"
        },
        "chat": {
            "id": 1234567890,
            "first_name": "John",
            "last_name": "Doe",
            "username": "JohnDoe",
            "type": "private"
        },
        "date": 1459958199,
        "text": "Hello from Bot!"
    }
}
```

and here is the SDK response:

  ```
  "result": {
        "message_id": 1,
        "from": {
            "id": 12345678,
            "first_name": "YourBot",
            "username": "YourBot"
        },
        "chat": {
            "id": 1234567890,
            "first_name": "John",
            "last_name": "Doe",
            "username": "JohnDoe",
            "type": "private"
        },
        "date": 1459958199,
        "text": "Hello from Bot!"
    }

```

**Comment by irazasyed** [comment]
Hey!

Use the try/catch to catch the exception library throws when there's an error in sending your message or performing any API calls and if it's okay, then you'll get a message object returned in case of `sendMessage` method.

Hope that helps!
