### ISSUE TITLE
Bad Request: type of file mismatch

### ISSUE THREAD

**Issue by pooriajahedi** [irazasyed/telegram-bot-sdk#541]
I can't send Document.
`(2/2) TelegramResponseException
Bad Request: type of file mismatch`

**Comment by farhad321** [comment]
I have this problem.

**Comment by sMojganAlavi** [comment]
hi, if you want to send file with file_id , you can see 2 file_id in getUpdate request, and you must choose second file_id for send_document or sendDocument . Both work for me
