### ISSUE TITLE
Not found error in laravel 5.5

### ISSUE THREAD

**Issue by salamat1307** [irazasyed/telegram-bot-sdk#546]
When I check my chat_id I have following error.
<img width="867" alt="2018-03-24 16 12 02" src="https://user-images.githubusercontent.com/30227583/37863309-1c41c194-2f7e-11e8-964e-ded05471a2a7.png">

How can fix it?

**Comment by rishatsharafiev** [comment]
I had the same error
First, i've updated telegram-bot-sdk to version 2.2
Second, i had mistake in env variable.
Good luck!
