### ISSUE TITLE
callback query not work.

### ISSUE THREAD

**Issue by aliqasemzadeh** [irazasyed/telegram-bot-sdk#547]
Hello,
        $update = Telegram::commandsHandler(true);
        $message = $update->getMessage();

        if($message->text == "/start") {
            $keyboard = Keyboard::make()
                ->forceReply()
                ->row(Keyboard::inlineButton(['text' => '#ثبت نام و فعال سازی', 'callback_data' => 'register']), Keyboard::inlineButton(['text' => '#پرداخت مبلغ آزاد', 'callback_data' => 'free_pay']));
                Telegram::sendMessage([
                    'chat_id' => $message->chat->id,
                    'text' => 'سلام لطفا نسبت به فعال سازی اشتراک خود اقدام کنید.',
                    'reply_markup' => $keyboard
            ]);
        }

        $response = Telegram::sendMessage([
            'chat_id' => $message->chat->id,
            'text' => serialize($message),
        ]);

        return 'Ok';

but I didn't get callback.

**Comment by Amegatron** [comment]
You should call `->inline()` on keyboard to make it inline.
```
$keyboard = Keyboard::make()->inline();
$keyboard->row(/* ... */);
```

**Comment by AGhasemzadeh** [comment]
No, In webhook when I try to get button only I get text not call_back.
