### ISSUE TITLE
give a delay to webhook response

### ISSUE THREAD

**Issue by zhorahmatt** [irazasyed/telegram-bot-sdk#548]
Hai.
I have successfully setup webhook on my web application, but i got a problem when typing some keyword, telegram response many times when using webhook. is there any solution like give a delay on my controller or something in order to not get many response from telegram webhook. 

This is my sample of my code
`$telegram` = new Api(env('TELEGRAM_BOT_TOKEN'));
$fromid = $req['message']['from']['id'];
$chatid = $req['message']['chat']['id'];
$text = $req['message']['text']; // get the user sent text
$name = $req['message']['from']['first_name'];
$sendMessage = $telegram->sendMessage([
            "chat_id"  => $chatid,
            "text"  => 'Hai '.$text.', Welcome',
]);`

* I am using Laravel

**Comment by jhivan** [comment]
If you don't respond with http 200 statu code, telegram api server thinks something is wrong with your bot and repeats every few seconds. you can do something like this:

```
        $sendMessage = $telegram->sendMessage([
            "chat_id" => $chatid,
            "text" => 'Hai '.$text.', Welcome',
        ]);

        if ($response->getMessageId()) {
            return response('', 200);
        }
```

**Comment by zhorahmatt** [comment]
thanks @jhivan. it definitely true. it should add respond http 200 in every request of your process.
