### ISSUE TITLE
pinChatMessage

### ISSUE THREAD

**Issue by decadence** [irazasyed/telegram-bot-sdk#550]
Is there any chance to send custom command. For example I need send [pinChatMessage](https://core.telegram.org/bots/api#pinchatmessage) command but API has no this method and `sendRequest` method is `protected`.

**Comment by sabinico** [comment]
Hello @decadence, I have the same problem.
Did you found the way to do it without modifing the SDK?

Thank you

**Comment by decadence** [comment]
Hello. No :( I just closed issue due to inactivity.

**Comment by sabinico** [comment]
Well I found a possible solution, without modifing vendor files, maybe this can help you and others.

`
$params = ['chat_id' => -1001348827745, 'message_id' => 600];
        $tg_client  = new TelegramClient();
        $tg_request = new TelegramRequest(Telegram::getAccessToken(), "POST", "pinChatMessage", ['form_params' => $params]);
        $response = $tg_client->sendRequest($tg_request);
`
