### ISSUE TITLE
Laravel 401 error

### ISSUE THREAD

**Issue by trollsk1n** [irazasyed/telegram-bot-sdk#555]
laravel version: 5.6.*
telegram-bot-sdk version: ^2.0

hi, i get a 401 error every time when i get run bot. 
error :
`[2018-04-11 16:34:27] local.ERROR: Unauthorized {"exception":"[object] (Telegram\\Bot\\Exceptions\\TelegramResponseException(code: 401): Unauthorized at /var/www/html/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php:58, Telegram\\Bot\\Exceptions\\TelegramOtherException(code: 401): Unauthorized at /var/www/html/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php:58)`

telegram returned in '/getwebhookinfo' `{
    "ok": true,
    "result": {
        "url": "https://mysite.com/api/bot-token/telegrambot",
        "has_custom_certificate": false,
        "pending_update_count": 9,
        "last_error_date": 1523430194,
        "last_error_message": "Wrong response from the webhook: 500 Internal Server Error",
        "max_connections": 40
    }
}`
i excepted webhook url from `app\middleware\verifycsrftoken`,

**Comment by trollsk1n** [comment]
I found a solution, it's error with cyrillic 'C' in bot-token. Please close this issue

**Comment by ayousefidev** [comment]
i have error like this 

laravel version: 5.4.*
telegram-bot-sdk version: ^2.0
