### ISSUE TITLE
How Get response from user??

### ISSUE THREAD

**Issue by zamhirabeta** [irazasyed/telegram-bot-sdk#559]
i will create a register form that contain full name, phone number, age ...!
whit this "request()->input('message.text')" code get text but i don't know how set a dialog between bot and user, until user answer all the question of form.
plaese hellp me!

**Comment by gelinger777** [comment]
I am interested also about this @zamhirabeta . Did you managed to do that?

**Comment by gelinger777** [comment]
@irazasyed  closed as completed? :)

**Comment by irazasyed** [comment]
@gelinger777 That's the default. Closed all old issues for now.

P.S. You should look at caching chat sessions and responding accordingly to achieve what you're looking for.
