### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by FyZzyss** [irazasyed/telegram-bot-sdk#560]
PHP Fatal error:  Uncaught Telegram\Bot\Exceptions\TelegramOtherException: Unauthorized in /app/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php:58
and 
/app/vendor/irazasyed/telegram-bot-sdk/src/Api.php(1014): Telegram\Bot\Tin /app/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php on line 58
"GET /favicon.ico HTTP/1.1" 500 - "-"
nothing changed in library...

**Comment by FyZzyss** [comment]
![screenshot_11](https://user-images.githubusercontent.com/38393787/38784159-aef0dbd4-4116-11e8-9705-282d8c41bb1e.png)

**Comment by yongkylie** [comment]
Can you show more of your code?
