### ISSUE TITLE
Connect to Telegram API throuth socks5 proxy

### ISSUE THREAD

**Issue by faustoFF** [irazasyed/telegram-bot-sdk#563]
Is it posible to connect to Telegram API throuth socks5 proxy?

**Comment by faustoFF** [comment]
Find solution. Code example:

```
use Telegram\Bot\HttpClients\GuzzleHttpClient;
use GuzzleHttp\Client;

$client = new GuzzleHttpClient(new Client(['proxy' => 'socks5h://user:pass@example.com:1080']));
$telegram = new Api($this->token, false, $client);
```

**Comment by ZAZmaster** [comment]
@faustoFF haw about webhooks?

**Comment by faustoFF** [comment]
@ZAZmaster can you put more details in your question?

**Comment by seddighi78** [comment]
How can I use the proxy for webhook?

**Comment by faustoFF** [comment]
@seddighi78 i think its not possible. Сorrect me if I'm wrong. You can use proxy for outgoing request to TG API, but not for incomming.

**Comment by seddighi78** [comment]
Is there any way to proxy the incoming?

**Comment by faustoFF** [comment]
@seddighi78 you can run you webhook frontend on some host and just forward request to you webhook backend endpoint.

**Comment by seddighi78** [comment]
Could you please give me some example or documentation?

**Comment by faustoFF** [comment]
@seddighi78 just google "nginx proxy telegram webhook" or similar. First link in search results: https://gist.github.com/L11R/c4710307ff77936ac1ce1d1bbfa61834

**Comment by seddighi78** [comment]
Thank you sir.

**Comment by Plutonium244** [comment]
> Is there any way to proxy the incoming?
@seddighi78 You can use NGrok. 
download, launch, set webhook to NGrok's https tunnel, enjoy. 
In addition, NGrok has fine inspect page, you can see all your bugs there. http://127.0.0.1:4040/inspect/http
