### ISSUE TITLE
 Notification in the laravel queue

### ISSUE THREAD

**Issue by dormadekhin** [irazasyed/telegram-bot-sdk#565]
I'll describe the situation in detail:
the project on laravel, with the help of the supervisor utility, is launched and monitored by the process that executes the artisan command
Created a notification channel in telegraphs using your package
During the execution of the team's artisan, at the necessary condition, an event is triggered, which is placed in the queue. The event handler already calls the bot notification to the user.
The problem is that the notification is not sent from the event handler, noticed that if you simply execute the code of the handler from the event queue, then the notifications come in normally.
There are no mistakes in the logs, how can you solve this problem?

**Comment by ItsOnlyMeNL** [comment]
I am wondering the same. I have something that needs to be executed in background after sending a message to the bot.  

When i read the actions that need to be done from the database i want to send a message to the sender, but this does not seem to work when done with a laravel queue:work.  When running the somewhat same code as a artisan command it does send a message to the user.

When having the queue call the artisan command it does not send a message to the user.. 

any idea why it would not send out messages to the user if its being ran with a queue?

**Comment by Xibel** [comment]
What queue connection do you use? Database?

Make sure that you clear all cache after changing the config/queue.php file with:

```
php artisan cache:clear
php artisan config:cache
```

Restart the worker with:

`php artisan queue:restart`

If this does not help please show us your Job code and an example of calling that Job.
