### ISSUE TITLE
Respond to inline queries and private messages

### ISSUE THREAD

**Issue by brytey2k** [irazasyed/telegram-bot-sdk#572]
I am building a bot which I want to respond to commands. However, I want it to be able to respond to inline queries like "How are you doing?" which may be sent from a group or a private chat with the bot. 

I am looking through the documentation but I cant find anything like that?
Any help will be appreciated

**Comment by holtkamp** [comment]
@brytey2k maybe this is easier to adopt: https://botman.io/2.0/nlp

**Comment by CORPARU** [comment]
Also looking for the implementation of this SDK (irazasyed/telegram-bot-sdk) as a normal dialogue with the bot, without commands.  

`Route::group(['prefix'=>'bot'], function() {
	Route::match(['get','post'],'/telegram', function(){
		app('App\Http\Controllers\Backend\TelegramController')->webhook();

		return 'ok';
	});`

`namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Telegram;
use App\TelegramUser;

class TelegramController extends Controller
{
    public function webhook(){

    	$telegram = Telegram::getWebhookUpdates()['message'];

    	if(!TelegramUser::find($telegram['from']['id'])) {
    		TelegramUser::create(json_decode($telegram['from'], true));
    	}

    	$update = Telegram::commandsHandler(true);
    }
}
`

I think that here you can somehow replace this request "$update = Telegram::commandsHandler(true);" and redirect to a separate controller messages that do not contain supporting commands
