### ISSUE TITLE
$response->getMessageId() return null

### ISSUE THREAD

**Issue by dormadekhin** [irazasyed/telegram-bot-sdk#573]
I can not get the result of sending a message:

```
 $response  = Telegram::sendMessage([
           'chat_id' => $chat_id,
           'text' => 'test',
       ]) ;
  dump($response->getMessageId());
```

result:
`null`
I'm using Laravel 5.6

**Comment by Logicbloke** [comment]
$response["message_id"] works for me, but I'm not using Laravel.

**Comment by yongkylie** [comment]
you can try

`$response->getMessage()->getMessageId()`

**Comment by eric2100** [comment]
> I can not get the result of sending a message:
> 
> ```
>  $response  = Telegram::sendMessage([
>            'chat_id' => $chat_id,
>            'text' => 'test',
>        ]) ;
>   dump($response->getMessageId());
> ```
> 
> result:
> `null`
> I'm using Laravel 5.6

me too.
i try 
`$response->getMessage()->getMessageId()`
result:
null

laravel 6, irazasyed/telegram-bot-sdk master

**Comment by eric2100** [comment]
> @eric2100 Could you show `$response` content?

After I reinstalled the kit, it was normal and I didn't know how to solve it.
thank you.

**Comment by yongkylie** [comment]
I am closing this issue. Feel free to open this issue again if the problem still occurs.
I suggest you to use `dev-develop` branch since it's more updated. But it's still yet to be documented.
