### ISSUE TITLE
Bad Request: can't parse entities

### ISSUE THREAD

**Issue by axd** [irazasyed/telegram-bot-sdk#581]
`[2018-08-08 15:27:09] development.ERROR: exception 'Telegram\Bot\Exceptions\TelegramOtherException' with message 'Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 70' in /public_html/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php:58`

I just found this Exception when using command on "reply" option in Telegram, I don't know exactly what the error is.

**Comment by fiatjaf** [comment]
Probably means you have invalid Markdown (or HTML?). Telegram's Markdown parser isn't very smart.

**Comment by jonnywilliamson** [comment]
Can you post the data/json payload that was received by the webhook?
