### ISSUE TITLE
Composer update get v2.2.0: is it right?

### ISSUE THREAD

**Issue by ciu8** [irazasyed/telegram-bot-sdk#582]
Hi, i like this sdk and my issue is not on the code, the code works very well!

I include the sdk as a dependency in my project's using composer:
`"require": {
    "irazasyed/telegram-bot-sdk": "^2.0"
  },`
How it's possible that the last commit on v.2.2.0 (hash 2824278370b231dfc9172104db8acc23fc5ade94) is on Jan '17 and the last commit on master is on March '18?

I cannot use a lot of new amazing stuff  like inline query methods :(

Best Regards and tahnks a lot for this great SDK!

**Comment by yongkylie** [comment]
I used the "3.0.x-dev" version to get the newest features. It is still under (slow) development by now.
