### ISSUE TITLE
getCallbackQuery() not exist

### ISSUE THREAD

**Issue by kafkiansky** [irazasyed/telegram-bot-sdk#591]
Hello there. I am exploring examples about processing callback_data using inline keyboard and have noticed that many examples are using method getCallbackQuery(). I have 3 versions of this library and there is no such method. Can you please explain me how can I get data via callback_data? This example  also doesn't work:

$output = json_decode(file_get_contents('php://input'), TRUE);
$callback_query = $output['callback_query'];
$data = $callback_query['data'];

**Comment by yongkylie** [comment]
What version of the library you currently using?

**Comment by kafkiansky** [comment]
> What version of the library you currently using?

now i'm using 3.0 version and method getCallbackQuery() exist, but I still can't get the value
of callback_data. i do so 
`$this->getWebhookUpdate()->getCallbackQuery()->getData();`

**Comment by yongkylie** [comment]
It's working fine for my app. Maybe is it because of the typo? I think you should use `getWebhookUpdates()` instead of `getWebhookUpdate`.

Here is a code I use, and it's working fine:
```
$update = $this->getWebhookUpdates();
$callback_query = $update->getCallbackQuery()->getData();
```

**Comment by kafkiansky** [comment]
> It's working fine for my app. Maybe is it because of the typo? I think you should use `getWebhookUpdates()` instead of `getWebhookUpdate`.
> 
> Here is a code I use, and it's working fine:
> 
> ```
> $update = $this->getWebhookUpdates();
> $callback_query = $update->getCallbackQuery()->getData();
> ```

getWebhookUpdates() is deprecated in this version

**Comment by kafkiansky** [comment]
> It's working fine for my app. Maybe is it because of the typo? I think you should use `getWebhookUpdates()` instead of `getWebhookUpdate`.
> 
> Here is a code I use, and it's working fine:
> 
> ```
> $update = $this->getWebhookUpdates();
> $callback_query = $update->getCallbackQuery()->getData();
> ```

show your composer.json, please

**Comment by yongkylie** [comment]
Here are the version I use `"irazasyed/telegram-bot-sdk": "3.0.x-dev"`

**Comment by kafkiansky** [comment]
> Here are the version I use `"irazasyed/telegram-bot-sdk": "3.0.x-dev"`

thanks!

**Comment by kafkiansky** [comment]
> irazasyed/telegram-bot-sdk": "3.0.x-dev

Sorry, but in this version `getWebhoohUpdates()` is also deprecated

**Comment by yongkylie** [comment]
I used to debug my code (to view at the results of the webhook values) by sending it to my Telegram via user_id.

```
$update = Telegram::bot($bot_name)->getWebhookUpdates();
$reponse = $this->sendMessage([
	'chat_id' => 'your_telegram_chat_id,
	text' => json_encode($update),
]);
```

Hope that helps.

**Comment by kafkiansky** [comment]
> I used to debug my code (to view at the results of the webhook values) by sending it to my Telegram via user_id.
> 
> ```
> $update = $this->getWebhookUpdates();
> $reponse = $this->sendMessage([
> 	'chat_id' => 'your_telegram_chat_id,
> 	text' => json_encode($update),
> ]);
> ```
> Hope that helps.

thanks, i will try.
