### ISSUE TITLE
sendInvoice

### ISSUE THREAD

**Issue by valeriy-efimov** [irazasyed/telegram-bot-sdk#592]
How to send this ? [https://core.telegram.org/bots/api#sendinvoice](url)

**Comment by yongkylie** [comment]
What version are you using? sendInvoice is supported in the develop branch.
You can install the develop branch by running version `3.0-dev`.

**Comment by valeriy-efimov** [comment]
@yongkylie After the update, I saw it and already use it, thanks!

**Comment by yongkylie** [comment]
@valeriy-efimov Great! If it's already solved, feel free to close the issue.

Cheers!
