### ISSUE TITLE
setWebHook returns Message instead of the documented response

### ISSUE THREAD

**Issue by LBreda** [irazasyed/telegram-bot-sdk#598]
Hi, I'm using the 2.2 version.

SetWebHook returns a Message instead of the documented TelegramResponse, so that `Telegram::setWebHook->getDecodedBody()` returns `null` instead of something like:

`{
    "ok": true,
    "result": true,
    "description": "Webhook was set"
}`

**Comment by yongkylie** [comment]
Is it possible for you to use the `3.0-dev` version? Because version 2 is quite outdated now. We are working on the docs right now and it's coming anytime soon. I'd glad to help you do the transition to version `3.0-dev`.

**Comment by LBreda** [comment]
Tried to switch to 3.0. Now `setWebHook` returns a boolean instead of a `TelegramResponse`.

**Comment by yongkylie** [comment]
@LBreda yes, the `version 2` SDK return `TelegramResponse` as response. But, the `version 3-dev` follows the same response that written in official docs [setWebhook](https://core.telegram.org/bots/api#setwebhook) which return a boolean.

There are some breaking changes that follows with `3.0-dev` version.
Hope that helps!

**Comment by LBreda** [comment]
Thanks, I'll have a look and ask if I can't do something. Is there a draft of the new docs?

**Comment by yongkylie** [comment]
@LBreda there's a draft, but it's only available for contributors at the moment. But it's already around the corner and will be released soon.
