### ISSUE TITLE
cant get chat_id in group

### ISSUE THREAD

**Issue by usergao** [irazasyed/telegram-bot-sdk#601]
when i use ：
`$chat_id = $message->getChat()->id;`

the $chat_id i get is a negative number, like ：
`"chat": {
            "id": -285536364,
            "title": "groupName",
            "type": "group",
            "all_members_are_administrators": true
        }`

when i use the id in the chat object to call Chat functions, like getChatMembersCount(), everytime i got null, am i use the wrong id ? somebody know why pls tell me , thank you very much.

**Comment by usergao** [comment]
i just want validate someone is in my group , so i need get the chat_id to call getChatMember(), but the chat_id i get is a negetive number , is this normal?

**Comment by usergao** [comment]
i konw why now , thank you , @yongkylie

**Comment by yongkylie** [comment]
@usergao can you explain why? This might help other user when facing the same problem.

Thankyou.

**Comment by usergao** [comment]
the way i get chat_id is right , but i use wrong param to call getChatMembersCount(), i should use 
$this->telegram to call the function like the code below
![image](https://user-images.githubusercontent.com/19534860/47562531-5798a500-d951-11e8-82e6-1c2d683ec383.png)
