### ISSUE TITLE
The CommandBus singleton is not automatically instantiated in all cases in Laravel

### ISSUE THREAD

**Issue by bdteo** [irazasyed/telegram-bot-sdk#602]
So here is what happens:

# Bug 1

```
use Telegram\Bot\Api as TelegramBotApi;

$api = (new TelegramBotApi('1234:token'));
$api->getCommands();

```
`=> []` (We fail to reproduce the expected behaviour according to the documentation)

Running the following after the above at the same runtime:

```
Telegram::bot();
$api->getCommands();
```
`=> [
     "help" => Telegram\Bot\Commands\HelpCommand {#instance of the HelpCommand},
   ]
` (After calling Telegram::bot() we observe the expected behaviour now) 

Reading the documentation I expected that global commands will be automatically registered and they are registered only in some cases. They are only registered when you use the BotsManager singleton (i.e Telegram::bot($botName)).

# Bug 2 - related bug

The other awesomely awkward thing is that the CommandBus is a singleton, too.
It is not such a big pain, most of the times you will handle a single bot per runtime.

Imho the CommandBus should be managed so that every \Api instance has its own CommandBus singleton. 

_However, the obvious is that sharing the CommandBus makes it hard to handle multiple different bots at the same runtime. What can be done as a workaround will be purely hacking around the SDK._

----

_It is not that big deal since it is a rare scenario to initiate mass message sending to multiple bots at the same runtime. However, it sucks._

# Conclusion
Having these two bugs together makes it very possible for unexpected behaviour to come up.
For example:
- You register the HelpCommand manually using $api->apiCommands();
- In other place in your application you call Telegram:bot();
- This results in a TelegramSdkException - the CommandBus for some funky reason is shared and you are registering the same commands multiple times; 

_Global commands should be registered even if an \Api instance is created manually at runtime, not only via the BotManager singleton. (Why are they global otherwise ?)_

_There are many scenarios when using just the configuration file is not flexible enough._ Creating \Api instances manually seems to be poorly tested (excluding the scenario with the inflexible BotManager singleton and it's configuration file).

_It should be possible to handle multiple bots at the same runtime._ Now doing this requires major workarounding and ugly stuff.

**Comment by irazasyed** [comment]
This should've been resolved in `4.x` when it's released. Appreciate your detailed bug report, tho.
