### ISSUE TITLE
this package is not working for me

### ISSUE THREAD

**Issue by behzadcym** [irazasyed/telegram-bot-sdk#607]
Hi 
I want to use this package to manage my bot but I have a few problems:
when I want to get my bot's info,updates,etc,either I get an empty array or timeout error.
But when I use Postman to get bot's information,it works absolutely fine!
The next problem is when I want to set webhook, I get this error:
Undefined index: result
which refers to this method:
getResult()
in:
vendor\irazasyed\telegram-bot-sdk\src\TelegramResponse.php

**Comment by behzadcym** [comment]
Any suggestions??

**Comment by behzadcym** [comment]
Thank you people! You guys are amazing !! :|

**Comment by yongkylie** [comment]
@behzadcym What version of the SDK are you currently use? Could you provide snippets of your code?
