### ISSUE TITLE
Undocumented features

### ISSUE THREAD

**Issue by bdteo** [irazasyed/telegram-bot-sdk#608]
See `setPattern()` in `Telegram\Bot\Commands\Command`.

There is absolutely no documentation on it.
It is obviously used like `protected $pattern = '{userUid}--{taskUid}';` in your own class that inherits `Command`.

However, for it to become obvious you have to read the source code.

**Comment by yongkylie** [comment]
Hey, @bdteo! That's right, the documentation of v3 and everything about Command System is still WIP.
