### ISSUE TITLE
hi, i couldn't sent photo using this api methods

### ISSUE THREAD

**Issue by azizbek8434** [irazasyed/telegram-bot-sdk#612]
```
$response = Telegram::sendPhoto([
  'chat_id' => 'CHAT_ID', 
  'photo' => 'path/to/photo.jpg', 
	'caption' => 'Some caption'
]);
```

>and this is json data and image path

![default](https://user-images.githubusercontent.com/36416819/49513723-bf78ce80-f8b3-11e8-9030-373c1f3bffb9.png)

> and this is my code
```
    protected function getProducts($chat_id,$category_slug,$manager_slug,$lang='en'){
    $products = file_get_contents('https://test.com/api/products?manager='.$manager_slug.'&category='.$category_slug);
        $data = json_decode($products,true);
        foreach($data['data'] as $product){
        Telegram::sendPhoto([
            'chat_id' => $chat_id,
            'photo' => 'https://test.com/public'.$product['image'],
            'caption' => $product['name']
        ]);
    }
```
please help me, thanks in advance..

_Originally posted by @azizbek8434 in https://github.com/irazasyed/telegram-bot-sdk/issues/42#issuecomment-444471887_

**Comment by vperminov** [comment]
I send picture like that
`  Telegram::sendPhoto([
            'chat_id' => $chat_id,
            'photo' => InputFile::create('https://test.com/public'.$product['image'], $imageName),
            'caption' => $product['name']
        ]);`

**Comment by azizbek8434** [comment]
the result looks like this code
```
            Telegram::sendPhoto([
                'chat_id' => $chat_id,
                'photo' => InputFile::create('https://test.com/public/storage/products/ananas_5bbcf4b89fa9b.jpg', 'ananas_5bbcf4b89fa9b.jpg'),
                'caption' => 'some text'
            ]);
```

OK in this case, which namespace do I need to include?

**Comment by vperminov** [comment]
```
use Telegram\Bot\FileUpload\InputFile;
```

**Comment by azizbek8434** [comment]
It works, thank you very much.
