### ISSUE TITLE
How to disable autorespond with /help command

### ISSUE THREAD

**Issue by Xibel** [irazasyed/telegram-bot-sdk#615]
Thank you for this SDK. It works great. I have a working Laravel (with Webhook) implementation following your documentation and the Laravel examples.

I have one issue with the command implementation. If a /foo is send and the command is not recognized (registered) the bot always answers with the default /help command. This feature is documented like this:

_If a command is not registered but the user fires one (Lets say an invalid command), By default the system will look for a help command if its registered and if yes, then it'll be triggered. So the default help command class if you were to use would respond the user with the available list of commands with description._

How can I disable this?

I would like my bot to answer only to known (registered) commands. If an unknown command is send then the bot should not answer anything. Please advise.

**Comment by jonnywilliamson** [comment]
Untested but commenting out this line in the laravel config file for the SDK should do the trick I think.

https://github.com/irazasyed/telegram-bot-sdk/blob/master/src/Laravel/config/telegram.php#L113

**Comment by Xibel** [comment]
That doesn't work. I tried that already by accident. 
The HelpCommand is called somewhere from the vendor base code. I think it is this place: https://github.com/irazasyed/telegram-bot-sdk/blob/2.0/src/Commands/CommandBus.php#L196

I don't want to change the vendor code at all. But I think this should then be a feature request to remove this behavior. Some option in the config\telegram.php file.

**Comment by imknight** [comment]
plus one on this and it seems like after nearly 6 months still not changing?

**Comment by Xibel** [comment]
The developer seems to abandoned this project. But maybe there are two options to overcome this behaviour:

1. Override the vendor class. (In Laravel this is possible). Use Google to find out;
2. Create your own HelpCommand file and change its behaviour. I am only responding to chatusers I know in my application.

**Comment by irazasyed** [comment]
@Xibel It's already implemented [here](https://github.com/irazasyed/telegram-bot-sdk/blob/master/src/Laravel/config/telegram.php#L113).

It's 3.0 with major changes that haven't been documented. So you gotta explore.

The project has not been abandoned, just been extremely busy so unable to give time to it right now but I will definitely push updates and document when I get some time. Besides, It's mostly the documentation that is missing from v3.0.

**Comment by imknight** [comment]
@irazasyed I think is slightly different from this issue, you can config it with your own helper class but the behaviour issue is the help command becomes the fallback command as well. So when user enter any command that never registers, the help command will be responded.

**Comment by Xibel** [comment]
@imknight Yes, and that is why I implemented my own HelpCommand and respond to users that my app knows and sending known helper commands. You could also implement your own HelpCommand which will not respond to any unknown commands. Check if the Command is only a /help command and respond only on that.

@irazasyed Good to hear you are still there. We will manage somehow :)

**Comment by imknight** [comment]
oh ok, didn't think of check the command in the help command, thanks for pointing out.

**Comment by mambaur** [comment]
try to comment help command in config/telegram.php
```

'commands' => [
        // Telegram\Bot\Commands\HelpCommand::class,
 ],
```
