### ISSUE TITLE
How to answer callback query?

### ISSUE THREAD

**Issue by ghost** [irazasyed/telegram-bot-sdk#616]
Here is my buttons:

        $keyboard = Keyboard::make()
 
           ->inline()

            ->row(
                Keyboard::inlineButton([
                    'text'          => '🇺🇦 українська',
                    'callback_data' => json_encode(['a' => 'firstLang', 'lang' => 'ua']),
                ]),
                Keyboard::inlineButton([
                    'text'          => '🇷🇺 русский',
                    'callback_data' => json_encode(['a' => 'firstLang', 'lang' => 'ru']),
                ]),
                Keyboard::inlineButton([
                    'text'          => '🇺🇸 english',
                    'callback_data' => json_encode(['a' => 'firstLang', 'lang' => 'en']),
                ])
            );

I handle them this way:
  
        $update = Telegram::getWebhookUpdates(); // todo check why is it deprecated
        $isCallback = $update->detectType() === 'callback_query';

        if ($isCallback) {

            $chatId = $update['callback_query']['message']['chat']['id'];

But how can I answer callback query?

**Comment by yongkylie** [comment]
What version of the SDK are you currently using? Are you using it in Laravel?

Based on your code , you just need simply call `answerCallbackQuery()` inside your `if`

If you're using develop version of the SDK:
```
Telegram::answerCallbackQuery([
    'callback_query_id' => $update->getId(),
    'cache_time' => 1
]);
```

If using v2:
```
Telegram::answerCallbackQuery([
    'callback_query_id' => $update['callback_query']['id'],
    'cache_time' => 1
]);
```

**Comment by RaptorialThing** [comment]
I`m handle CallbackQuery this way in laravel controller (php-telegram-sdk version 4):
```
if ($update->objectType() === 'callback_query') {
// example code; $update->getRelatedObject()->data // get callback data
}

// send message with button, callback data
 $keyboard = new Telegram\Bot\Keyboard\Keyboard(['resize_keyboard'=>true,'one_time_keyboard'=>true]);
 $keyboard->inline();
 $button = Telegram\Bot\Keyboard\Keyboard::inlineButton(['text'=>'button text','callback_data'=>'sample data']);
 $keyboard->row($button);              

Telegram::sendMessage([
                        "text"=>"Question for button message", "chat_id" => $update->getMessage()->chat->id,                     
                        "reply_markup"=>$keyboard
                      ]);

//better use  reply function 
$this->replyWithMessage
```
