### ISSUE TITLE
Error during install package in laravel

### ISSUE THREAD

**Issue by masami6871** [irazasyed/telegram-bot-sdk#620]
Hi.  i'm using laravel 5.6 and 5.7 . when i want to  install this package with laravel  i  see this error : 

> C:\Users\Masami\Desktop\project\telegram>composer require irazasyed/telegram-bot-sdk ^2.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

 > Problem 1
    - Installation request for irazasyed/telegram-bot-sdk 2.0 -> satisfiable by irazasyed/telegram-bot-sdk[v2.0.0].
    - Conclusion: remove laravel/framework v5.7.20
    - Conclusion: don't install laravel/framework v5.7.20
    - irazasyed/telegram-bot-sdk v2.0.0 requires illuminate/support 5.0.*|5.1.*|5.2.* -> satisfiable by illuminate/support[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - illuminate/support 5.2.x-dev conflicts with laravel/framework[v5.7.20].
    - illuminate/support v5.2.43 conflicts with laravel/framework[v5.7.20].
    - illuminate/support v5.2.45 conflicts with laravel/framework[v5.7.20].
    - don't install illuminate/support 5.1.x-dev|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.1.30|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.1.31|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.1.41|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.2.19|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.2.21|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.2.24|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.2.25|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.2.26|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.2.27|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.2.28|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.2.31|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.2.32|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.2.37|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.7.20
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.0.22|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.0.25|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.0.26|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.0.28|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.0.33|don't install laravel/framework v5.7.20
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5.7.20
    - Installation request for laravel/framework (locked at v5.7.20, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.20].

> Installation failed, reverting ./composer.json to its original content.

but when i remove ^v2 from end of 
composer require irazasyed/telegram-bot-sdk ^2.0
that package will be install with ^v3 .  but dont work .  i confused .  please help me .

**Comment by yongkylie** [comment]
Hi, @masami6871 ! Please try `dev-develop` version, since the v3.0 is still under development.

Hope that helps!

**Comment by masami6871** [comment]
Thanks , i install that with ^2.*dev

But now i have this error :


cURL error 7: Failed to connect to api.telegram.org port 443: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

We live in iran,and telegram is filter here.but i use of ultrasurf and freegate. But these cant resolve this problem.do you have any suggestion ?

**Comment by Habtesoft** [comment]
php artisan config:clear //del ./bootstrap/cache/* if you'll got error
set TELEGRAM_BOT_TOKEN in .env
composer require irazasyed/telegram-bot-sdk ^3.4.1
ps publish conf file with php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider"
