### ISSUE TITLE
"cURL error 6: Could not resolve host: api.telegram.org (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"

### ISSUE THREAD

**Issue by darvishiyan-mahdi** [irazasyed/telegram-bot-sdk#626]
hi i am developing telegram bot with your package
and i reach this error 
"cURL error 6: Could not resolve host: api.telegram.org (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"
what do you think is the problems?

**Comment by chatlovely** [comment]
it seems that your host could not to connect to telegram . if you use that host in iran you must know that Iran ban telegram . if you use another host country  then you must talk to your hosting provider .
