### ISSUE TITLE
Telegram\Bot\Exceptions\TelegramResponseException Not Found

### ISSUE THREAD

**Issue by sunthree74** [irazasyed/telegram-bot-sdk#627]
why i had this error when i use version 3.0?

**Comment by BehzadV** [comment]
I had the same issue, delete your `Config/telegram.php` file and republish the config file and then edit it to your liking. Take note of the env usage. I hope this solves your problem.

**Comment by smahdis** [comment]
I have the same issue. Removing config/telegram.php and republishing it doesn't resolve the issue. 

Any ideas?

(I hide the url in the photo)

![image](https://github.com/irazasyed/telegram-bot-sdk/assets/13297454/28783f72-198a-4a77-9a40-97a5d951c0e8)
