### ISSUE TITLE
Usage of commands

### ISSUE THREAD

**Issue by kiarash3tar** [irazasyed/telegram-bot-sdk#63]
Hi;
Thanks for this cool program. :+1: 
I used your startCommand sample code in a file named `startCommand` and saved this into commands folder.
Either I did write `$telegram->commandsHandler(true);`

But

When I use `/start` command in my telegram app, nothing gonna happen.

This is my webhook file structure.

***Note :*** <small>The commented lines was tested.</small>
<pre>
require 'vendor/autoload.php';

use Telegram\Bot\Api;

$telegram = new Api('123456:AASxty3ydXux3yeCYEobGNFDefzT-fLUZXE');

$telegram->commandsHandler(true);

//$startCommand = new \Telegram\Bot\Commands\startCommand;

//$startCommand->handle('');

//\Telegram\Bot\Commands\startCommand::handle('');
</pre>

Would you please tell me where's my fault and misunderstanding?

**Thanks in advance**

**Comment by irazasyed** [comment]
Hi,

You need to register the command before it can handle for you.

Ex:
```php
$telegram->addCommand(Telegram\Bot\Commands\HelpCommand::class);
```

Please refer the guide here: https://irazasyed.github.io/telegram-bot-sdk/usage/commands/

**Comment by kiarash3tar** [comment]
Thanks for quick reply.
I read all guide step by step.

would you please show me a working example?
Is my code structure correct?
and 
Should I use register command in same file with webHook?

**Comment by irazasyed** [comment]
Here's the full example based on your code:

```php
require 'vendor/autoload.php';

use Telegram\Bot\Api;

$telegram = new Api('<token>');

$telegram->addCommand(Vendor\App\Commands\StartCommand::class);

$telegram->commandsHandler(true);
```

Commands handler could be anywhere but before that is triggered, the commands should be already registered. Its up to you where you place them. Same file or any other, as long as the command is registered before and then included in webhook file, that's fine too.

**Comment by irazasyed** [comment]
If you were to split it, It could be done something like this (It's a roughly written example):

**Command:**
```php
<?php //   Vendor/App/Commands/StartCommand.php

require 'vendor/autoload.php';

namespace Vendor\App\Commands;

use Telegram\Bot\Commands\Command;

class StartCommand extends Command
{
    /**
     * @var string Command Name
     */
    protected $name = "start";

    /**
     * @var string Command Description
     */
    protected $description = "Start Command to get you started";

    /**
     * @{inheritdoc}
     */
    public function handle($arguments)
    {
        $this->replyWithMessage('Hello! Welcome to our bot');
    }
}
```
**Bootstrap:**
```php
<?php // bootstrap.php
require 'vendor/autoload.php';

use Telegram\Bot\Api;

$telegram = new Api('<token>');

$telegram->addCommand(Vendor\App\Commands\StartCommand::class);
```

**Register Webhook:**
```php
<?php // register-webhook.php

require 'bootstrap.php';

$response = $telegram->setWebhook('https://domain.com/webhook.php'); 
// It is recommended you add some sort of token like security to confirm the request is actually coming from Telegram.

...
```

**Webhook:**
```php
<?php // webhook.php

// Use some sort of security here, 
// Maybe like a token to confirm the request is actually from Telegram.

require 'bootstrap.php';

$telegram->commandsHandler(true);

return "Okay";
```

**Comment by kiarash3tar** [comment]
Thanks for your guide.
Well, I'll get error 500 Internal server error when I want to register commands using this structure.

Other methods work fine, for example I checked `getAccessToken` and  `getMe`.
Would you please help me with this?

**Comment by irazasyed** [comment]
You gotta debug!

- Are you registering the namespace in your composer.json?
- Is your class name and path correct?

**Comment by kiarash3tar** [comment]
No, I didn't manipulate `composer.json` file. In fact I'm newbie to use composer and just read instalation guide in getcomposer.com and installed it.
What should I add to?
Is this the place that you mean?
<pre>
"autoload": {
    "psr-4": {
      "Telegram\\Bot\\": "src/"
    }
  },
</pre> 

And is this a right way?
<pre>
  "autoload": {
    "psr-4": {
      "Telegram\\Bot\\": "src/",
      "Vendor\\App\\Commands\\" : "src/Commands/"
    }
  },
</pre>

**Comment by irazasyed** [comment]
Well, Then i would highly recommend you first learn composer and a few other things before jumping into developing bots as this is not really for beginners.

**Comment by kiarash3tar** [comment]
I'm not saying I'm newbie to php programming.
I'm good in development.
What a few thing?
I'll read more about composer. Thanks for comment.

**Comment by irazasyed** [comment]
I see. Learn things like PSR rules, Namespace, Composer, Dependency Management, Autoloader, etc.

Here are few links to get started:
http://www.php-fig.org/
http://www.phptherightway.com/
