### ISSUE TITLE
$update = Telegram::getWebhookUpdates(); returns empty

### ISSUE THREAD

**Issue by Emperor577** [irazasyed/telegram-bot-sdk#631]
please explain me the problem. Why `Telegram::getWebhookUpdates()` return empty. Here is my blade where i call this method
![image](https://user-images.githubusercontent.com/42857664/53550154-d8fa8100-3b57-11e9-932f-f69d9510ced7.png)

and here is my route
![image](https://user-images.githubusercontent.com/42857664/53550229-0b0be300-3b58-11e9-9497-1d73110b335d.png)

and here is my controller
![image](https://user-images.githubusercontent.com/42857664/53550276-24ad2a80-3b58-11e9-8a30-1c10518c61d3.png)

and finaly the result
![image](https://user-images.githubusercontent.com/42857664/53550308-37276400-3b58-11e9-84f0-578bc0d66783.png)

please help me

**Comment by Xibel** [comment]
What are you exactly trying to do?

Setting a webhook tells Telegram API where to deliver any incomming message to your webhook. So you will only receive messages when someone will send something to your bot. You can't GET the messages by calling a webhookupdates method in a form.

To get messages when you want to call them you need 'long polling' with the getUpdates() method. No need for Webhook. So unset webhook and use getUpdates() method.

**Comment by Emperor577** [comment]
if i use `getUpdates()` i should alwayse send requerst to telegram to get updates right?

**Comment by Emperor577** [comment]
> if i use `getUpdates()` i should alwayse send requerst to telegram to get updates right?

**Comment by Emperor577** [comment]
> What are you exactly trying to do?
> 
> Setting a webhook tells Telegram API where to deliver any incomming message to your webhook. So you will only receive messages when someone will send something to your bot. You can't GET the messages by calling a webhookupdates method in a form.
> 
> To get messages when you want to call them you need 'long polling' with the getUpdates() method. No need for Webhook. So unset webhook and use getUpdates() method.

okay if i use this method `getUpdates()` i should send request always to telegram to get updates right?

**Comment by Xibel** [comment]
Yes, Telegram will queue all the messages and with getUpdates() you will pull all the messages that are in queue (long polling). With Webhook, Telegram will send you every message as soon as it gets to them.

The only thing you need is tell Telegram your webhook url so they can deliver the messages to you. On your side you only need a route to receive the messages. No blade thing needed. 

Please look at issue #628 for my solution how to setup your route and some testcode to confirm you are receiving messages via webhook.
