### ISSUE TITLE
How to change BASE_BOT_URL value?

### ISSUE THREAD

**Issue by AmirrezaNasiri** [irazasyed/telegram-bot-sdk#632]
I know it looks odd to change `BASE_BOT_URL` value of Telegram Bot API which presents in `Telegram\Bot\TelegramClient` class. However, since Telegram is filtered in our country, we're going to proxy incoming and outgoing requests through another URL.   
So in short, how should we really change `BASE_BOT_URL` constant value? or is there other non-breaking way to change HTTP client's one?

**Comment by CodingJediKnight** [comment]
But it's not the best option. If you are using config cache - it will broke. Because your config file will be not serializable. We can't instantiate class in config, so how we can use 'http_client_handler' better way?

**Comment by AmirrezaNasiri** [comment]
Sorry for late reply. I've done this by overriding original class with new one I've created. Here are the steps:

1- Make a copy of `irazasyed/telegram-bot-sdk/src/TelegramClient.php` to somewhere in your app (Like `app/vendor-override/TelegramClient.php`).
2- Make your changes to the file (in this case, `BASE_BOT_URL`). Don't touch namespace or class name at all since we're overriding it.
3- Make sure `app/vendor-override` is included in `composer.json` file like this:
```
"autoload": {
        ...
        "classmap": [
            ...,
            "app/vendor-override"
        ]
    },
```
4- Now our file and the original one will conflict since they have same namespace and class name. We need to exclude original file from composer dump. To do this, simply change your `composer.json` file like this:
```
"autoload": {
        ...
        "exclude-from-classmap": [
            ...,
            "vendor\\irazasyed\\telegram-bot-sdk\\src\\TelegramClient.php"
        ]
    },
```

This is not a bad solution. However I doubt if we can somehow inherit original class file instead of copying it's content since it may cause conflicts upon package upgrade.

**Comment by SirousFakhri** [comment]
> Sorry for late reply. I've done this by overriding original class with new one I've created. Here are the steps:
> 
> 1- Make a copy of `irazasyed/telegram-bot-sdk/src/TelegramClient.php` to somewhere in your app (Like `app/vendor-override/TelegramClient.php`).
> 2- Make your changes to the file (in this case, `BASE_BOT_URL`). Don't touch namespace or class name at all since we're overriding it.
> 3- Make sure `app/vendor-override` is included in `composer.json` file like this:
> 
> ```
> "autoload": {
>         ...
>         "classmap": [
>             ...,
>             "app/vendor-override"
>         ]
>     },
> ```
> 
> 4- Now our file and the original one will conflict since they have same namespace and class name. We need to exclude original file from composer dump. To do this, simply change your `composer.json` file like this:
> 
> ```
> "autoload": {
>         ...
>         "exclude-from-classmap": [
>             ...,
>             "vendor\\irazasyed\\telegram-bot-sdk\\src\\TelegramClient.php"
>         ]
>     },
> ```
> 
> 5- You may need to run `composer dump-autoload` to make changes effective.
> 
> This is not a bad solution. However I doubt if we can somehow inherit original class file instead of copying it's content since it may cause conflicts upon package upgrade.

well, thanks, dude. same issue here and I wonder what was changes exactly on BASE_BOT_URL?

**Comment by AmirrezaNasiri** [comment]
@sirosfakhri I needed this for [Telegram Web Bridge](https://github.com/AmirrezaNasiri/telegram-web-bridge) since sending direct requests for Telegram and receiving its callbacks are blocked in Iran.

**Comment by wfjsw** [comment]
Guess this worth a reopen and refactor since Telegram allows Bot API self-hosting since 5.0.
