### ISSUE TITLE
Dynamically inlineButtons

### ISSUE THREAD

**Issue by Speakkk** [irazasyed/telegram-bot-sdk#641]
Hello, sorry for my english. How can i make dynamically row inlineButtons?

i use v3, not Laravel

Like this:

    foreach($specialisations as  $value){
        $keyboard = Keyboard::make()->inline();
        $keyboard->row(Keyboard::inlineButton([
            'text'          => $value['specialisation'],
            'callback_data' => $value['href'],
        ]));
It returns only last button.
Thank you.

**Comment by Speakkk** [comment]
Sorry, it was
    $keyboard = Keyboard::make()->inline();
    foreach($specialisations as  $value){
    $keyboard->row(Keyboard::inlineButton([
        'text'          => $value['specialisation'],
        'callback_data' => $value['href'],
    ]));

I couldn't see buttons cuz of restriction number of buttons.. It was 210

**Comment by Speakkk** [comment]
Btw, look at this

i wanna to have buttons in one row, how can i do loop inside row()?
foreach($pagination as $value){
        Keyboard::inlineButton(['text' => $value['text'], 'callback_data' => $value['callback_data']]);
    }
    $keyboard->row($variable);
    return $keyboard;

**Comment by LanKing** [comment]
Hi! You can help yourself if you will look into code (vendor/irazasyed/telegram-bot-sdk/src/Keyboard/Keyboard.php : public function row(...$buttons): Keyboard

Here you can see what arguments row() method uses: ...buttons

If we google: php three dots, we can find https://lornajane.net/posts/2014/php-5-6-and-the-splat-operator

So, all that you need is to create array of your buttons first, and after that creare your ->row(...$myArray)
