### ISSUE TITLE
How to upload video and use it using file_id after that

### ISSUE THREAD

**Issue by LanKing** [irazasyed/telegram-bot-sdk#644]
Broked my mind, can you give any sample?

**Comment by LanKing** [comment]
Somebody, help please

**Comment by 0ee** [comment]
`$telegram->sendVideo([`
`'chat_id'                  => 'your chat id',`
`'video'                    => $up->message->video->fileId,`
`'caption'=>                   $up->message->caption,`
`'caption_entities'                 => $up->message->caption_entities,`
`'disable_web_page_preview' => true,`
`]);`
