### ISSUE TITLE
triggerCommand failed on v3.0.0

### ISSUE THREAD

**Issue by smskin** [irazasyed/telegram-bot-sdk#649]
Laravel v5.8.17.
telegram-bot-sdk v.3.0.0

Method triggerCommand('help',$update) return exception "Call to a member function filter() on null".
![image](https://user-images.githubusercontent.com/3227797/57952794-e7566e80-78f6-11e9-825a-de80e17af5c7.png)
![image](https://user-images.githubusercontent.com/3227797/57952809-f2110380-78f6-11e9-898f-b2c9ad8f398f.png)

$update not empty. 
![image](https://user-images.githubusercontent.com/3227797/57952650-829b1400-78f6-11e9-9669-7ac13fc9f0e7.png)

**Comment by romikzo** [comment]
+1 same problem

**Comment by frasagal** [comment]
same problem!!

**Comment by tanogalego** [comment]
Still happening :/

**Comment by irazasyed** [comment]
Fixed #733
