### ISSUE TITLE
Forbidden: bot was blocked by the user

### ISSUE THREAD

**Issue by rizkanns** [irazasyed/telegram-bot-sdk#651]
first, i used to using this send notification message just fine.
i dont know what i've done until it shows this error message
strangely even it shows this error message but actually work in telegram, but still cant figure out why it is showing this error message.
how to fix these? what did i do wrong? i tried to revoke bot telegram, but still showing this error message

**Comment by zaplachinsky** [comment]
@rizkanns It means that user blocked (stopped) your bot in Telegram and not able to receive further messages anymore.

![photo_2019-06-29_22-15-29](https://user-images.githubusercontent.com/20682149/60388515-6d9bce00-9abb-11e9-8fa8-14fa8e0d7b39.jpg)

**Comment by yongkylie** [comment]
Issue closed due to inactivity. Feel free to open the issue if there's further discussions.
