### ISSUE TITLE
The project is abandoned?

### ISSUE THREAD

**Issue by celorodovalho** [irazasyed/telegram-bot-sdk#655]
Has been a long time that I didn't see any update or any reply to the issues.
There are any plans update it?

**Comment by irazasyed** [comment]
Please check the `develop` branch. It was recently updated with the latest changes. Thanks to @jonnywilliamson.

Project is not really abandoned, it's just that I've been very busy. I have plans to make some major changes including proper async functionality based on reactphp but it'll take sometime before I can get back to this. Until then, I'm open to adding anyone that is willing to contribute to the project and help us maintain it.
