### ISSUE TITLE
Bot is answering command in middle of text

### ISSUE THREAD

**Issue by celorodovalho** [irazasyed/telegram-bot-sdk#656]
When I try to just mention a command, like:
```
This is the /new command, use it to create new posts
```
So the bot answers me like I have used the /new command in chat interface.

Do you know how to avoid it?
I'm using the version ^3.0.

**Comment by yongkylie** [comment]
Are you using `commandsHandler` trait to handle commands? If yes, then the current version couldn't avoid that kind of use case.

Other way to handle it is not using `commandsHandler` trait and directly check if `update` format received from Telegram's server match to the format you wanted via `getWebhookUpdate` trait.

Hope that helps.

**Comment by yongkylie** [comment]
Issue closed due to inactivity. Feel free to open the issue if there's further discussions.
