### ISSUE TITLE
Class 'App\Http\Controllers\Telegram' not found

### ISSUE THREAD

**Issue by moein-rahimi** [irazasyed/telegram-bot-sdk#67]
Hi I did just like here:https://irazasyed.github.io/telegram-bot-sdk/
but i get this error class not found.
my code look like this:
  public function index()
    {
       
        
        // Laravel
$response = Telegram::getMe();
return $response;
    }

**Comment by irazasyed** [comment]
Hi,

Please check/do the following:
1. You've the set Facade in `config/app.php` properly.
2. Do `composer dump-autoload`

**Comment by moein-rahimi** [comment]
thanks for quick reply!
it was just a \ !
must add a \ before Telegram
$response = \Telegram::getMe();

**Comment by irazasyed** [comment]
You're welcome!
