### ISSUE TITLE
Telegram Api Url from env variable

### ISSUE THREAD

**Issue by 2618094** [irazasyed/telegram-bot-sdk#677]
Hello!
Due to the blocking of the telegram in Russia, I would like to be able to set the API URL through the environment variable or in any other way to change it.
Make a proxy by nginx is the easiest way to bypass the block, but your project does not allow changes.
Thank you!

**Comment by irazasyed** [comment]
Hey!

Thanks for the suggestion. We'll explore this idea for future releases.

It's an interesting use case and I'm aware of Telegram blocks in some places.

As a workaround for now, perhaps you can host your bot outside your country and that shouldn't cause any issues in API usage then.

Thanks!

**Comment by 2618094** [comment]
This case is not for hosting, its important for local develop :) 
I can make system proxy for this, but change the api url more simplier.
Thank you for answer!
PS: Maybe someone will be useful nginx config for simple proxy
```
server {
        *SERVER_SETTINGS*
        location /telegram_proxy/ {
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass https://api.telegram.org/;
                client_max_body_size 100M;
        }
}
```
