### ISSUE TITLE
Laravel 6 PHP 7.3  studly_case

### ISSUE THREAD

**Issue by eok8177** [irazasyed/telegram-bot-sdk#679]
Call to undefined function Telegram\Bot\Commands\studly_case()
at  vendor/irazasyed/telegram-bot-sdk/src/Commands/Command.php:182

I can temporary fix: 
```
use Illuminate\Support\Str;
$reply_name = Str::studly(substr($method, 9));
```
But it`s not normal

**Comment by irazasyed** [comment]
This has already been updated in `dev-develop` branch. You can use that if you'd like.

**Comment by autowp** [comment]
But BC break in dev-develop: Command::handle($arguments) signature changed
