### ISSUE TITLE
There is any method for Get Reply message ?

### ISSUE THREAD

**Issue by chatlovely** [irazasyed/telegram-bot-sdk#680]
Hi 
I want to know that is there any method like isType('callback_query') for checking ReplyMessages ?
i want to know that user Reply my specified message or not . how can i check that ?

**Comment by irazasyed** [comment]
Hey!

Yes, we do have `isType()` method. Please refer [this](https://github.com/irazasyed/telegram-bot-sdk/blob/develop/src/Objects/Update.php#L66-L80).

**Comment by chatlovely** [comment]
Sorry but there are no Replymessage in $Types variable . 
how can i find type of message is reply ?

**Comment by irazasyed** [comment]
Are you trying to build a conversational bot? I'm not sure I get what you're up to?

You can use `isType('callback_query')` to figure out if its a callback query update type.

**Comment by chatlovely** [comment]
Please tell me explain to you that what i want to do :
i have a reply markup keyboard with some option , one of option is call "Request"
when user click on Request option bot say to him that please reply this message and said us what you need . 
until now i detect option with callback_query .

from now : user reply last message and write something . i want to know how can i detect that user reply to this message via telegram and send something . then i save this message and request title to database via laravel code . 
do you know what i want now ?
