### ISSUE TITLE
Hyper link problem with USSD codes

### ISSUE THREAD

**Issue by MonoAmir** [irazasyed/telegram-bot-sdk#684]
*141# appears as text without link

`$text = '<a href="tel:*141#"> *141# </a> vs <a href="google.com"> *142# </a>';
	$url= "https://api.telegram.org/bot".$token."/sendMessage?chat_id=".$chat_id."&text=".urlencode($text)."&parse_mode=HTML";`

**Comment by irazasyed** [comment]
This doesn't seem to be related to this SDK.
