### ISSUE TITLE
How change delay time of callbackQuery clocks?

### ISSUE THREAD

**Issue by PsagnatAF** [irazasyed/telegram-bot-sdk#690]
How can i minimize long pending of clocks display?
![Снимок экрана от 2019-11-11 17-00-44](https://user-images.githubusercontent.com/29681906/68598018-9ccd3d80-04a6-11ea-8b3d-8a0a98c48c52.png)

**Comment by yongkylie** [comment]
You need to implement `answerCallbackQuery` after processing the callback. What it does is tell Telegram server that you already answer or process the callback. https://github.com/irazasyed/telegram-bot-sdk/blob/develop/src/Methods/Query.php#L48
