### ISSUE TITLE
is version 3 stable or not

### ISSUE THREAD

**Issue by Mdhesari** [irazasyed/telegram-bot-sdk#692]
Hey, I'm using version 3 of the SDK, and have problems on using keyboards.

There is no good documentation on version 3 and in readme.io it's only version 2.

If there is a good source code that use this SDK, I appreciate if you share it with me.

thanks.

**Comment by yongkylie** [comment]
Hi @Mdhesari, it's not stable yet but you may consider to upgrade since there's some new features in the v3. The documentation for v3 is still in progress.

Also if you use the SDK frequently please consider joining our Telegram group at https://t.me/PHPChatCo
