### ISSUE TITLE
Problem with sendMessage and Webhook with Laravel

### ISSUE THREAD

**Issue by ValleyInforge** [irazasyed/telegram-bot-sdk#696]
Hello, my bot not work.
I did setWebhook with success. getMe work and also getWebhookInfo.

I try this for send message when the bot receives one but it not work.

My route:
![Schermata 2019-12-15 alle 18 14 48](https://user-images.githubusercontent.com/14810958/70866247-a8a99500-1f67-11ea-8e47-1c4b7137bf7e.png)

My Controller:
![Schermata 2019-12-15 alle 18 15 47](https://user-images.githubusercontent.com/14810958/70866253-ac3d1c00-1f67-11ea-9d0c-cbefab108298.png)

Thanks for help

**Comment by Ronhul** [comment]
Are you sure your code is right?
I see you are trying to fetch $chat_id from uninitialized $result.
Also please consider that $update came with a Webhooks is translated to an object. So you should get chat id like $update->getMessage()->getChat()->getId()

**Comment by ValleyInforge** [comment]
It works perfectly, It was a long day yesterday for me eheh. 
Thank you very much!

public function test()
    {
        $updates = Telegram::getWebhookUpdates();
        $chat_id = $updates->getMessage()->getChat()->getId();

        $response = Telegram::sendMessage([
            'chat_id' => $chat_id,
            'text' => 'Hello',
        ]);
    }
