### ISSUE TITLE
REQUEST: Nested Entities

### ISSUE THREAD

**Issue by jonnywilliamson** [irazasyed/telegram-bot-sdk#700]
Would anyone have an example of how a nested entity looks when an update object is received?

At the moment I can only find example of multi entities per update, not NESTED entities. To add the feature to the latest API 4.5, I would like to have a proper sample to test code against. Then I can add it to https://github.com/irazasyed/telegram-bot-sdk/pull/699

At the moment, multiple entities per update look something like this:
```json
{
	"update_id": 79107515,
	"message": {
		"message_id": 9906,
		"from": {
			"id": 99999999,
			"is_bot": false,
			"first_name": "Jonathan",
			"last_name": "Williamson",
			"username": "",
			"language_code": "en"
		},
		"chat": {
			"id": 99999999,
			"first_name": "Jonathan",
			"last_name": "Williamson",
			"username": "",
			"type": "private"
		},
		"date": 1578044613,
		"text": "These are multiple entities https://github.com",
		"entities": [
			{
				"offset": 0,
				"length": 5,
				"type": "italic"
			},
			{
				"offset": 10,
				"length": 8,
				"type": "bold"
			},
			{
				"offset": 28,
				"length": 18,
				"type": "url"
			}
		]
	}
}
```

Anyone have anything similar for the nested option?

Thank you

**Comment by jonnywilliamson** [comment]
Bump!!

**Comment by MrFiregore** [comment]
+1
