### ISSUE TITLE
Minimum PHP version

### ISSUE THREAD

**Issue by jonnywilliamson** [irazasyed/telegram-bot-sdk#701]
@irazasyed Hey! Happy new year,

If we're going to require > php 7.2 in composer.json, should we not also remove the travis CI checks for php versions below that?

**Comment by irazasyed** [comment]
@jonnywilliamson Thanks and Happy New Year to you as well :)

Sure thing, no point in testing below the required versions.

**Comment by irazasyed** [comment]
I’ve switched to Github Actions to run tests with appropriate PHP and Laravel versions to test against.
