### ISSUE TITLE
No Laravel... how to add telegram provider?

### ISSUE THREAD

**Issue by venkycc** [irazasyed/telegram-bot-sdk#703]
Hello Guys!

Thanks a million for this stuff!!!

If I don't use Laravel, I guess I can still use this SDK. Where and how do I define 'Telegram'  => Telegram\Bot\Laravel\Facades\Telegram::class ?

I installed the sdk via composer

Thanks in advance

**Comment by michelmelo** [comment]
@venkycc hi
my app.php
providers:
 Telegram\Bot\Laravel\TelegramServiceProvider::class,

aliases:
 'Telegram' => Telegram\Bot\Laravel\Facades\Telegram::class,

**Comment by venkycc** [comment]
I got the following reply in an email but don't see it here

> @venkycc hi
> my app.php
> providers:
> Telegram\Bot\Laravel\TelegramServiceProvider::class,
> 
> aliases:
> 'Telegram' => Telegram\Bot\Laravel\Facades\Telegram::class,

app.php only gets installed if I use Laravel. Can i use this SDK if I don't install Laravel please? What all do I need to do if I don't use Laravel? I don't want to use it...many reasons. I have other Apps without laravel and want to integrate telegram bots 

Thanks again!

**Comment by leoleoasd** [comment]
You don't need to register that service provider if you aren't using laravel.

**Comment by irazasyed** [comment]
Like @leoleoasd mentioned, you don't have to register the service provider or facade if you don't use this SDK within Laravel.
