### ISSUE TITLE
Send message from Laravel Job

### ISSUE THREAD

**Issue by asshaposhnikov** [irazasyed/telegram-bot-sdk#706]
Hi, respect to you for Telegram Bot SDK.
Hi, I installed the latest version of your package today in Laravel. Created a job to send messages through the telegram bot.
Got an error. Moreover, messages from the usual Laravel controller are sent successfully. 
Here are the details.

` namespace App\Jobs; `

`use Illuminate\Bus\Queueable;`
`use Illuminate\Contracts\Queue\ShouldQueue;`
`use Illuminate\Foundation\Bus\Dispatchable;`
`use Illuminate\Queue\InteractsWithQueue;`
`use Illuminate\Queue\SerializesModels;`

`use Telegram;`
`use Telegram\Bot\Api;`
`use Shapoapps\MultibotDriver\ShapoappsMultibotDriver;`

`class SendTelegramBotAdminMessage implements ShouldQueue`
` { `
    `use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;`

    protected $data;

    public function __construct($data)
    {
        $this->data = $data;
    }

    public function handle()
    {
        ShapoappsMultibotDriver::SetCurrentBotByInternalID($this->data['bot_internal_id']);

        $response = Telegram::sendMessage([
             'chat_id' => $this->data['recepient_telegram_id'], 
            'text' => $this->data['message_text'] 
        ]); 
   ` } ` 
 ` } ` 

Error code in laravel log:

` [2020-01-20 10:34:33] local.ERROR: Class 'Telegram' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Telegram' not found at /var/www/twilio_responder/laravel/app/Jobs/SendTelegramBotAdminMessage.php:34)
[stacktrace] `
` #0 [internal function]: App\\Jobs\\SendTelegramBotAdminMessage->handle() `
` #1 /var/www/twilio_responder/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array() `
` #2 /var/www/twilio_responder/laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}() `

**Comment by asshaposhnikov** [comment]
Problem finded and solved, if you use `supervisor` for laravel queue manage. After each commit run in bash ` sudo supervisorctl reread && sudo supervisorctl restart all` , otherwise old laravel Job files version work (without your changes in commit)

**Comment by jonnywilliamson** [comment]
No need to touch supervisor

From laravel docs (https://laravel.com/docs/6.x/queues):

![image](https://user-images.githubusercontent.com/2513663/72749331-a7e0d000-3bb1-11ea-91d3-4fb6a6b7f1c7.png)


![image](https://user-images.githubusercontent.com/2513663/72749372-c3e47180-3bb1-11ea-8e77-a32fb68309d2.png)

**Comment by asshaposhnikov** [comment]
> No need to touch supervisor
> 
> From laravel docs (https://laravel.com/docs/6.x/queues):
> 
> ![image](https://user-images.githubusercontent.com/2513663/72749331-a7e0d000-3bb1-11ea-91d3-4fb6a6b7f1c7.png)
> 
> ![image](https://user-images.githubusercontent.com/2513663/72749372-c3e47180-3bb1-11ea-8e77-a32fb68309d2.png)

Thx, supervisor restart - work fine. I add supervisor restart/reread commands to post commit script (clear laravel caches, restart supervisor).
