### ISSUE TITLE
 Bots have stopped working 2/7/2020

### ISSUE THREAD

**Issue by antonr45** [irazasyed/telegram-bot-sdk#711]
Dear comunity,
all my Telegram bots have stopped working on different hostings 2/7/2020

Linux version 3.10.0-862.14.4.el7.x86_64
PHP 7.1.33

Can you kindly help me?

My code is below:

``` include('/usr/local/bin/vendor/autoload.php');
    use Telegram\Bot\Api; 

    $telegram = new Api('*token*'); 
    $result = $telegram -> getWebhookUpdates(); 
    
    $text = $result["message"]["text"]; 
    $chat_id = $result["message"]["chat"]["id"]; 
    $name = $result["message"]["from"]["username"]; 
$keyboard = []; 

    if($text){
         if ($text == "/start") {
			 $reply = "Text1";
            $reply_markup = $telegram->replyKeyboardMarkup([ 'keyboard' => $keyboard, 'resize_keyboard' => true, 'one_time_keyboard' => false ]);
            $telegram->sendMessage([ 'chat_id' => $chat_id, 'text' => $reply, 'reply_markup' => $reply_markup ]);
        }elseif ($text == "/help") {
            $reply = "Text2";
            $telegram->sendMessage([ 'chat_id' => $chat_id, 'text' => $reply ]);
		}
	}else{
    	$telegram->sendMessage([ 'chat_id' => $chat_id, 'text' => "Text3" ]);
    }

**Comment by irazasyed** [comment]
What version of SDK are you using?

The dev aka 3.0 version requires minimum PHP 7.2.

Further, Send a test message and output the response from the `sendMessage` method. It should have the error message if it isn't successful or the Message object if successful. Maybe your bots have been banned for some reason, there could be network/firewall issues, etc.

**Comment by antonr45** [comment]
I have ver 2.3.0
And actually I have error:
'''Fatal error: Uncaught Telegram\Bot\Exceptions\TelegramSDKException: cURL error 35: Network file descriptor is not connected (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /usr/local/bin/vendor/irazasyed/telegram-bot-sdk/src/HttpClients/GuzzleHttpClient.php:114 Stack trace: #0 /usr/local/bin/vendor/irazasyed/telegram-bot-sdk/src/TelegramClient.php(117): Telegram\Bot\HttpClients\GuzzleHttpClient->send('https://api.tel...', 'POST', Array, Array, 60, false, 10) #1 /usr/local/bin/vendor/irazasyed/telegram-bot-sdk/src/Api.php(1014): Telegram\Bot\TelegramClient->sendRequest(Object(Telegram\Bot\TelegramRequest)) #2 /usr/local/bin/vendor/irazasyed/telegram-bot-sdk/src/Api.php(957): Telegram\Bot\Api->sendRequest('POST', 'sendMessage', Array) #3 /usr/local/bin/vendor/irazasyed/telegram-bot-sdk/src/Api.php(303): Telegram\Bot\Api->post('sendMessage', Array) #4 /home/bitrix/www/bots/telegram/index.php(7): Telegram\Bot\Api->sendMessage(Array) #5 {main} thrown in /usr/local/bin/vendor/irazasyed/telegram-bot-sdk/src/HttpClients/GuzzleHttpClient.php on line 114

**Comment by irazasyed** [comment]
Yes, that seems like network issues within your server. Nothing we can do. Closing this for now. Should there be any issues related to the SDK, feel free to create a new issue.
