### ISSUE TITLE
Call to undefined function Telegram\\Bot\\Commands\\studly_case() - Lumen

### ISSUE THREAD

**Issue by NakatoTeshika** [irazasyed/telegram-bot-sdk#712]
Hello, I have problem with Command class, when I am using REPLYWITH, it is give me error like `{main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function Telegram\\Bot\\Commands\\studly_case() at /var/www/vendor/irazasyed/telegram-bot-sdk/src/Commands/Command.php:182)
[stacktrace]` I have version of Lumen 6.3.4 and sdk bot 2.3

**Comment by chorry** [comment]
studly_case is a dependency from Laravel O_O

**Comment by irazasyed** [comment]
Lumen doesn't have those helpers. Please use this SDK in Laravel.
