### ISSUE TITLE
Issue: ❓ Support Question

### ISSUE THREAD

**Issue by Theolodewijk** [irazasyed/telegram-bot-sdk#713]
I tray to get some info bot Telegram don't reply support tickets!

Can you help me with Telegram. so that I am sent in the right direction.

I work for a government organization and we have a weekly exercise, now I would like to simplify this with, for example, a poll or something else where if someone responds to that I get a feedback via the telegram API.

I want to use PHP for this but see many options on the Telegram website https://core.telegram.org/bots/samples#php but now which one is and is not suitable for this and there is a little explanation somewhere how to find it tackles this?

https://telegram.org/blog/polls-2-0-vmq

Greetings Theo

**Comment by Xibel** [comment]
Hoi Theo, what are you exactly searching for? Do you need specific support for a problem building your product or do you need a programmer to build your product?

How experienced are you with programming in PHP?
Do you want to use a framework like Laravel to implement your Telegram bot?
How far are you implementing your solution?

If it is easier to write in Dutch, please do so.

**Comment by Theolodewijk** [comment]
Hoi Xibel, de bedoeling is dat ik het zelf maak maar wil graag een stap voor zijn voor ik elke beschikbare PHP API versie ga proberen.

Mijn ervaring met PHP is goed dat is verder geen probleem, ik maak het in mijn eigen bestaande systeem.

Op dit moment heb ik alleen nog maar gebruik gemaakt van de telegram API mogelijkheden om berichten en foto's te plaatsen maar het doel dat ik nu wil bereiken is; we hebben welke week een oefening waarbij via WhatsApp aan wordt gegeven wie wel en niet mee doet met een duimpje, nu wil ik hiervan een telegram groep maken die wekelijks een bericht plaatst met twee of drie buttons waar ze op kunnen drukken en dat dit met de API van telegram uitgewisseld kan worden en verwerken in mijn database om te vertalen naar een oefenschema.

Telegram heeft hiervoor meerdere PHP libraries alleen ben ik er niet uit welke hiervoor het beste aansluit met dergelijke mogelijkheden?

**Comment by Xibel** [comment]
Hoi Theo,

Het maakt volgens mij niet zo veel uit welke je gebruikt. Zeker niet als je native php gaat gebruiken. 
Ik heb ervaring opgedaan met twee verschillende bibliotheken. De eerste is van Longman en dat is de originele Telegram Bot heb ik begrepen. Deze heb ik gebruikt bij een native php project. Deze versie maakt wel een complete set aan tabellen aan en zal alle correspondentie loggen in de database. Hij is dus heel uitgebreid. Houd gebruikers, chats, etc bij. Misschien wel iets te veel voor een bot met collega's. Zie https://github.com/php-telegram-bot/core

Daarna ben ik overgestapt naar een PHP Framework en wel Laravel. Daarin maak ik gebruik van https://github.com/irazasyed/telegram-bot-sdk. en wel versie 3.0. Niet zo goed gedocumenteerd als 2.0 maar werkt hetzelfde als de Telegram core en andere bot's. De API endpoints zijn overal hetzelfde. Het gaat meer om de functionaliteiten eromheen. In beide versies gebruik ik Webhooks zodat ik realtime meldingen binnenkrijg en ze niet reactief hoef op te halen. 

Bij wat jij schrijft kan je eigenlijk elke versie gebruiken. Je zal nog steeds zelf wat moeten programmeren met de binnenkomende meldingen in PHP. Maak je gebruik van een Framework zoals Laravel of programmeer je native?

**Comment by Theolodewijk** [comment]
Hoi Xibel,

Dank je wel voor je reactie, dan ga ik me verdiepen in die van Longman, ik programmeer native gericht op specifieke platformen en of doeleinden.

Maak in sommige gevallen ook wel gebruik van Laravel maar niet in dit geval.
