### ISSUE TITLE
Wrong response from the webhook: 405 Method Not Allowed

### ISSUE THREAD

**Issue by ds-ivanenko** [irazasyed/telegram-bot-sdk#719]
Hello everybody!

**I am using Laravel Framework 6.14.0**

I successfully set webhook.
After that, I check the information **_https://api.telegram.org/botMY_CORRECT_TOKEN/getWebhookInfo_** and I have no errors.
But after sending a message to the bot and when checking **_getWebhookInfo_** after that, I get such a message

```
{
   "ok":true,
   "result":{
      "url":"<MY_CORRECT_URL>",
      "has_custom_certificate":false,
      "pending_update_count":10,
      "last_error_date":1583501702,
      "last_error_message":"Wrong response from the webhook: 405 Method Not Allowed",
      "max_connections":40
   }
}

```

At the same time, I successfully send messages to the bot with **sendMessage() function**

```
$response = \Telegram::sendMessage ([
            'chat_id' => '<MY_CORRECT_CHAT_ID>',
            'text' => 'Hello World',
        ]);
```

But the commands do not work for me. I send the **"/help"** command and nothing happens.
Tell me why I get the error **"Wrong response from the webhook: 405 Method Not Allowed"** and **why my Bot does not respond to commands**?

Thanks so much for the answers !!!!
I have already spent a lot of time solving this problem!

**Comment by Xibel** [comment]
Hi, you need to do a couple of things to be able to receive and respond to a command. Using a webhook means Telegram will POST json messages to Laravel. POST needs a CSRF token and since Telegram does not know about your Laravel requirements is does not include a CSRF token. So you need to add the webhook url to the CSRF exclusion list. Therefore it is also important to make your webhook url impossible to guess for external users. Use something like a 32 bit string with random characters.

To add your CSRF exclusion open App\Http\Middleware\VerifyCsrfToken.php and the following code:
```
protected $except = [
        '/<Your_Random_Characters_for_webhook>/webhook/',
    ];
```

Next, you need to edit the /config/telegram.php and write down all the commands in the 'commands' section. Make sure you point the path to the right command file. Example:

```
'bots'                         => [
        'default' => [
            'username'            => env('TELEGRAM_BOT_NAME', 'YOUR_BOT_NAME'),
            'token'               => env('TELEGRAM_BOT_TOKEN', 'YOUR-BOT-TOKEN'),
            'certificate_path'    => env('TELEGRAM_CERTIFICATE_PATH', 'YOUR-CERTIFICATE-PATH'),
            'webhook_url'         => env('TELEGRAM_WEBHOOK_URL', 'YOUR-BOT-WEBHOOK-URL'),
            'commands'            => [
                App\Telegram\Commands\HelpCommand::class,
                App\Telegram\Commands\StartCommand::class,
            ],
        ],
    ],
```
In App\Telegram\Commands you need to have a HelpCommand.php with something like this:

```
<?php

namespace App\Telegram\Commands;

use Telegram\Bot\Commands\Command;
use Telegram;

/**
 * Class HelpCommand.
 */
class HelpCommand extends Command
{
    /**
     * @var string Command Name
     */
    protected $name = 'help';

    /**
     * @var array Command Aliases
     */
    protected $aliases = ['listcommands'];

    /**
     * @var string Command Description
     */
    protected $description = 'Help command, Get a list of all commands';

    /**
     * {@inheritdoc}
     */
    public function handle($arguments)
    
    {
            $text = 'Hello, thanks for visiting me.'.chr(10).chr(10);
            $text .= 'I am the help command'.chr(10);
            
            $this->replyWithMessage(compact('text'));
    }
}
```
That should be it. By the way this information and code examples are based on Laravel 6+ and Telegram  Bot SDK ^3.0.

**Comment by ds-ivanenko** [comment]
**Thank you very much for the answer!!!**

I upgraded to **Laravel 7.1.0.**
Reinstalled _**telegram-bot-sdk**_ like this

`composer require irazasyed/telegram-bot-sdk`

I received a message that I have installed this version of the SDK

`Using version ^ 3.0 for irazasyed / telegram-bot-sdk`

I again did all the steps to configure the SDK. But I get the same error.
**Messages are sent, but Bot commands do not work.**

The SSL certificate installs Let's Encrypt.

In the file **App\Http\Middleware\VerifyCsrfToken.php** added this:

```
class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        '/<MY-BOT-TOKEN>/webhook/',
    ];
}
```


**But I still get the error "Wrong response from the webhook: 405 Method Not Allowed".**((((((((((((((((

**Comment by ds-ivanenko** [comment]
Webhook is set to the root of the site. 
I mean here:
https://my-domain.com/

**Comment by Xibel** [comment]
What does your Laravel.log say? Do you see any error's in there?

You can manually test your webhook by sending a POST message to your webhook url. Check the documentation:
https://core.telegram.org/bots/webhooks#testing-your-bot-with-updates

But check your laravel.log first to see if there any exceptions logged.

**Comment by Xibel** [comment]
One more thing. The Handle method in the HelpCommand.php file needs an argument like so:

public function handle(**$arguments**). I updated the earlier response because it was missing in the example code. Please check that also.

**Comment by Xibel** [comment]
And now with version 3.1 the $argument needs to be removed.

**Comment by irazasyed** [comment]
What does your webhook route look like? Please share the code. Seems like there's no POST route. 

@Xibel Thanks for helping around.

**Comment by Milad-jfr** [comment]
> What does your webhook route look like? Please share the code. Seems like there's no POST route.
> 
Hello , 
I have this situation on my webhook : 

{"ok":true,"result":{"url":"https://siteurl.site/6901110433:AAG7dFaB2ktvZ9nWVETGg4I20ObVcbhIJDU/webhook","has_custom_certificate":false,"pending_update_count":58,"last_error_date":1698503113,"last_error_message":"Wrong response from the webhook: 500 Internal Server Error","max_connections":40,"ip_address":"IP"}}

I use POST route but i receive this error when call the route : 
The GET method is not supported for route <token>/webhook. Supported methods: POST.

My route structure is : 
Route::post('/'.env("TELEGRAM_BOT_TOKEN") .'/webhook', [TelegramController::class, 'webhook']);
