### ISSUE TITLE
Deprecation Notice: Class Telegram\Bot\Objects\ResponseParameters in Laravel 5.8

### ISSUE THREAD

**Issue by mmeidyfachreza** [irazasyed/telegram-bot-sdk#725]
Hello , i have a problem when i try to composer update, it show the errors below:
`Deprecation Notice: Class Telegram\Bot\Objects\ResponseParameters located in D:/web project/backend/laravel/5.8/Implementation-Application/vendor/irazasyed/telegram-bot-sdk/src\Exceptions\ResponseParameters.php does not comply with psr-4 autoloading standard. It will not 
autoload anymore in Composer v2.0. in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201`

Laravel 5.8
telegram-bot-sdk 3.0
composer 1.10.1
PHP 7.4.3

**Comment by Xibel** [comment]
Hi,

Where did you get the file 'ResponseParameters.php' from? It is not part of the Telegram-Bot-SDK 3.0. There is no such file. This file was in a previous version. Could you remove your vendor map completely and run the command: composer install

This should rebuild your vendor map including the telegram-bot-sdk folder. ResponseParameters.php should not be there.

**Comment by zeyad82** [comment]
> Hi,
> 
> Where did you get the file 'ResponseParameters.php' from? It is not part of the Telegram-Bot-SDK 3.0. There is no such file. This file was in a previous version. Could you remove your vendor map completely and run the command: composer install
> 
> This should rebuild your vendor map including the telegram-bot-sdk folder. ResponseParameters.php should not be there.

Hi!
Actually, the file is part of 3.0.0! For some reason commit "Fix "Warning: Ambiguous class resolution" on composer install" in pull request  #610 is not present in tag 3.0.0!

![image](https://user-images.githubusercontent.com/16030521/78997004-79d6b080-7b4e-11ea-8080-29e172ec479b.png)

**Comment by ChristophWurst** [comment]
Same issue here (for https://github.com/nextcloud/twofactor_gateway)

```
Deprecation Notice: Class Telegram\Bot\Objects\ResponseParameters located in ./vendor/irazasyed/telegram-bot-sdk/src/Exceptions/ResponseParameters.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

```
$ composer show irazasyed/telegram-bot-sdk
name     : irazasyed/telegram-bot-sdk
descrip. : The Unofficial Telegram Bot API PHP SDK
keywords : laravel, laravel telegram, telegram, telegram bot, telegram bot api, telegram php, telegram sdk
versions : * v3.0.0
type     : library
license  : BSD 3-Clause "New" or "Revised" License (BSD-3-Clause) (OSI approved) https://spdx.org/licenses/BSD-3-Clause.html#licenseText
homepage : https://github.com/irazasyed/telegram-bot-sdk
source   : [git] https://github.com/irazasyed/telegram-bot-sdk.git fc452f11a6509616f26e279ad36339e1b9032472
dist     : [zip] https://api.github.com/repos/irazasyed/telegram-bot-sdk/zipball/fc452f11a6509616f26e279ad36339e1b9032472 fc452f11a6509616f26e279ad36339e1b9032472
path     : /home/christoph/workspace/nextcloud/apps/twofactor_gateway/vendor/irazasyed/telegram-bot-sdk
names    : irazasyed/telegram-bot-sdk

autoload
psr-4
Telegram\Bot\ => src/

requires
guzzlehttp/guzzle ~6.1
guzzlehttp/psr7 ~1.3
illuminate/support ~5.1
league/event ^2.1
php ^7.0

requires (dev)
phpunit/phpunit ^6.1

suggests
illuminate/container Hold dependencies to be injected in commands constructors
irazasyed/larasupport Allows you to use any Laravel Package in Lumen by adding support!
```

**Comment by irazasyed** [comment]
Hi,

I've just tagged a minor release with this bugfix.

Sorry for the delay.

Thanks!
