### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by nehasharma1997** [irazasyed/telegram-bot-sdk#728]
Laravel Framework 6.18.3
Package : 2.3.0

I used `composer require irazasyed/telegram-bot-sdk ^2.0` to install. It install package successfully. Then i run `php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider"` it give error `Unable to locate publishable resources.`

I also try to manually copy config file to config/telegram.php, but I get `Target class [telegram] does not exist.` when try to use Telegram class.

I also try to re-install the `telegram-bot-sdk`, but with no luck.

Stacktrace :

`Target class [telegram] does not exist. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [telegram] does not exist. at /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:805)
[stacktrace]
#0 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build()
#1 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve()
#2 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve()
#3 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make()
#4 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(1245): Illuminate\\Foundation\\Application->make()
#5 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(198): Illuminate\\Container\\Container->offsetGet()
#6 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(166): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance()
#7 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(255): `

**Comment by shahzodkudratov** [comment]
Hello. I have same issue

**Comment by shahzodkudratov** [comment]
@nehasharma1997 i solved this by doing following:
copy: `vendor/irazasyed/telegram-bot-sdk/src/Laravel/config/telegram.php` to `config/telegram.php`
add: `App\Providers\TelegramServiceProvider::class,` in file `config/app.php`

after that use `app('telegram')->getMe();` in the code.

path to facade: `Telegram\Bot\Laravel\Facades\Telegram`

**Comment by irazasyed** [comment]
Please use the `dev-develop` version (v3).
