### ISSUE TITLE
keyboard doesn't work!

### ISSUE THREAD

**Issue by derakoola** [irazasyed/telegram-bot-sdk#73]
```$keyboard = $telegram->replyKeyboardMarkup([['test']]);```
```$params = [```
```         'chat_id' => $chatId,```
            ```'text' => $text,```
          ```  'reply_markup' => $keyboard,```
```
 ];
```
```return $telegram->sendMessage($params);```

keyboard dose not work!

**Comment by irazasyed** [comment]
What version of the SDK are you using?

The params have been changed in `master` branch which is not a stable branch. Please refer this: https://github.com/irazasyed/telegram-bot-sdk/blob/master/src/Api.php#L736-L762

**Comment by derakoola** [comment]
I use master branch!

Can you help me?!
Witch branch is stable now and how can I find it myself(witch branch is stable).

**Comment by irazasyed** [comment]
You need to use tagged version in production. Currently, It would be `^1.0`.

**Comment by derakoola** [comment]
Dose version ```^1.0``` support ```getFile()``` !?

**Comment by irazasyed** [comment]
Nope! It doesn't. Once v2 is released, You'll get all those methods along with other things that have been implemented and or in works.

I don't recommend using master branch but if you still want it, You can ofc use it. But keep in mind, It has breaking changes and it'll be constantly updated with various changes as we commit.

As for your keyboard issue, just refer the doc block in the URL i gave you. It should work fine then.

**Comment by derakoola** [comment]
ok, problem solved.
Thanks for your description.

**Comment by irazasyed** [comment]
Great. No problem!
