### ISSUE TITLE
getwebhookupdate work with postman just

### ISSUE THREAD

**Issue by Walaa1994** [irazasyed/telegram-bot-sdk#732]
Hello,
I'm using irazasyed:dev-master
work on local server xampp and using ngrok to get https url

I have a problem with getting updates by getwebhookupdate method, noting that it is work successfully when i test with postman, Whereas when I send text from Telegram I don't get response from bot.
Also an important note that the commandsHandler is working successfully and the bot response automatic.

and this is my rout code:
`Route::post('/webhook', 'BotController@webhookHandler');`

and this is my webhookHandler code:
`   public function webhookHandler()
    {
        $update=$this->telegram->commandsHandler(true);
        try{
            $update=$this->telegram->getWebhookUpdate();
            $message=$update[0]['message']['text'];
            $chat_id=$update[0]['message']['chat']['id'];
            $this->telegram->sendMessage(['chat_id'=>$chat_id,'text'=>"Hello"]);
            return 'ok';
        }catch (\Exception $e ){
            var_dump($e->getMessage());
        }
    }`

and this is the result of setting webhook:
{"ok":true,"result":{"url":"https://d7eae21b.ngrok.io/SawaBot/public/webhook","has_custom_certificate":false,"pending_update_count":0,"max_connections":40}}

I hope to help solve this problem or suggest any way to detect the error
Best Regards

**Comment by torvicv** [comment]
you are right. I am same problem.
