### ISSUE TITLE
Arguments for command

### ISSUE THREAD

**Issue by assada** [irazasyed/telegram-bot-sdk#735]
**Version** 3.1.0

**Command:**
```php
class TestCommand extends Command
{
    /**
     * @var string Command Name
     */
    protected $name = 'test';

    /** @var string Command Argument Pattern */
    protected $pattern = '{id} {status}';

	public function handle() {
		$args = $this->getArguments();
		Log::debug($args)
	}
}
```

**Telegram message:** `/test 1 status`

**Actual result:** `[]` (*empty array*). 

**Related:**
https://github.com/irazasyed/telegram-bot-sdk/issues/417#issuecomment-503832815
https://github.com/irazasyed/telegram-bot-sdk/issues/716

**Comment by Xibel** [comment]
Version 3.2.0? Where did you get that from?

With version 3.1 I can confirm it is working.

I send out: '/test 123 WorksLikeACharm' and got the following in return from my TestCommand:

![Telegram_image](https://user-images.githubusercontent.com/5270541/79803477-5ab3fc00-8362-11ea-8c40-8acf4c69dc13.png)

Show us your complete command code for test, please.

**Comment by assada** [comment]
I made a mistake. Of course 3.1

My test command:
```php
<?php

declare(strict_types=1);

namespace App\Telegram\Command;


/**
 * Class TestCommand
 *
 * @package App\Telegram\Command
 */
class TestCommand extends \Telegram\Bot\Commands\Command
{
    /**
     * @var string Command Name
     */
    protected $name = 'test';

    /**
     * @var string Command Argument Pattern
     */
    protected $pattern = '{id?} {status?}';

    /**
     * @var array Command Aliases
     */
    protected $aliases = ['t'];

    /**
     * @var string Command Description
     */
    protected $description = 'Test Command';

    /**
     * @inheritDoc
     */
    public function handle()
    {
        $this->replyWithMessage(
            [
                'text' => '`' . json_encode($this->getArguments()) . '`',
                'parse_mode' => 'markdown'
            ]
        );
    }
}
```


result:
![image](https://user-images.githubusercontent.com/1472664/79804500-d5821480-836c-11ea-9a9f-9f11962455a2.png)

laravel: 7.3.0

```
bash-5.0# php -v
PHP 7.4.4 (cli) (built: Mar 24 2020 01:34:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies
```

web.php:
```php
Route::post('/{token}/webhook', 'TelegramController@webhook')->name('telegram.webhook');
```

TestController.php:
```php
class TelegramController extends Controller
{
    /**
     * @return string
     */
    public function webhook(): string
    {
        $update = Telegram::commandsHandler(true);

        return 'ok';
    }
}
```

![image](https://user-images.githubusercontent.com/1472664/79804920-addf7c00-836d-11ea-971e-7b959a504663.png)

**Comment by Xibel** [comment]
Remove the ? in '{id} {status}'

And /storage/logs/laravel.log should mention some error's. Check that log also.

Did you add your webhook url to the CSRF exclusion array?

**Comment by assada** [comment]
![image](https://user-images.githubusercontent.com/1472664/79805178-3bbb6700-836e-11ea-8842-07b21501aa89.png)
Logs empty after removing `?`

Commands fully working. Issue only with `getArguments`.

**Comment by Xibel** [comment]
Try this TestCommand code:

```
<?php

namespace App\Telegram\Commands;

use Telegram\Bot\Commands\Command;
use Telegram;

use Log;

/**
 * Class TestCommand.
 */
class TestCommand extends Command
{
    /**
     * @var string Command Name
     */
    protected $name = 'test';

    /**
     * @var array Command Aliases
     */
    protected $aliases = ['testcommands'];

    /**
     * @var string Command Description
     */
    protected $description = 'Test command, to test arguments';

    /**
     * @var string Command Pattern
     */
    protected $pattern = '{id} {status}';

    /**
     * {@inheritdoc}
     */
    public function handle()
    
    {
        $args = $this->getArguments();
        Log::debug($args);


        $response = $this->getUpdate();

        $text = 'Hey stranger, thanks for visiting me.'.chr(10).chr(10);
        $text .= 'You send me a test command with following arguments:'.chr(10).chr(10);
        $text .= 'ID: '.$args['id'].chr(10);
        $text .= 'Status: '.$args['status'].chr(10).chr(10);
        $text .= 'Keep up the good work!'.chr(10);
        
        $this->replyWithMessage(compact('text'));

    }
}
```

**Comment by assada** [comment]
```
Undefined index: id
```

Because the `$this->getArguments()` is empty

**Comment by Xibel** [comment]
I see you are using a controller (TelegramController@webhook) to handle the incoming request. Maybe setting the commands up without a controller? I see many users with inline, callback and arguments issues while using a controller setup. I have no experience with using a controller way so I am not sure if this is the problem but for troubleshooting refer back to a direct approach with the commandsHandler in your routes file.

In your routes file add this:
Route::post('/<your webhook uri>/webhook/', function () {
    $update = Telegram::commandsHandler(true);
});

For more information about how to set this up from scratch see https://www.xibel-it.eu/setup-telegram-bot-sdk-with-webhook-in-laravel/

**Comment by assada** [comment]
Looks like the main issue with generated regex `%/test(?:@.+?bot)?\s+?(?P<id>[^ ]++)\s+?(?P<status>[^ ]++)%si` in https://github.com/irazasyed/telegram-bot-sdk/blob/develop/src/Commands/Command.php#L254

**Comment by Xibel** [comment]
Still does not explains why on my side it works.

**Comment by assada** [comment]
Lol!

![image](https://user-images.githubusercontent.com/1472664/79807101-a53d7480-8372-11ea-8e64-8f1adc1c6095.png)

Please forgive me for taking your time! I just forgot to add arguments to the message!

**Comment by Xibel** [comment]
Lol. Nice that you solved it! At lease we build up some knowledge in this issue. Goodluck!

**Comment by etas34** [comment]
hi,
i executed the same commands and it works,

but when i send /test it gives error,

how can i send a info message if user doesnt type argument?

pls answer

**Comment by kklysenko** [comment]
@Xibel Hi! Is it possible to find words that start with a specific character?
kinda, '{$label}'
/test $value => ['label' => 'value']
/test value => []
