### ISSUE TITLE
How to handle Command through callback_data?

### ISSUE THREAD

**Issue by TDarkCoder** [irazasyed/telegram-bot-sdk#736]
composer.json

`"irazasyed/telegram-bot-sdk": "^3.0"`

I want to handle **/keyboard** command through callback_data, called by replyKeyboardMarkup in CallbackCommand.php:

    protected $name = 'callback';
    protected $description = 'This command is used to handle callback';

    public function handle($arguments){

        $inline_keyboard[] = [
            [
                'text' =>'Handle keyboard Command',
                'callback_data' => '/keyboard'
            ]
        ];

        $reply_markup = Telegram::replyKeyboardMarkup([
            'inline_keyboard' => $inline_keyboard,
            'resize_keyboard' => true
        ]);

        $update = Telegram::getWebhookUpdates();

        $text = 'This is just a text-message';

        Telegram::sendMessage([
            'chat_id' => $update['message']['from']['id'],
            'text' => $text,
            'reply_markup' => $reply_markup
        ]);

    }

But when I press on the button, nothing happens, the only thing I see is what is shown in image below:

![Безымянный](https://user-images.githubusercontent.com/56731393/79857682-96dd7000-83e7-11ea-8390-97c43c8e78f0.png)

Please, show me, if I missed something in my code. 
Thanks in advance!

**Comment by assada** [comment]
Actually question is "How i can handle callback requests?".
In my case i am using simple keyboard instead inline mod to avoid callback_query handling(because I did not find a way to do this) 

![image](https://user-images.githubusercontent.com/1472664/79905074-6107ae00-841e-11ea-9a69-2d774dafd288.png)

But this way sucks

**Comment by Omyshev** [comment]
Используй это, тебе нужно получить **Callback_data**  

```
$result = $telegram->getWebhookUpdates();
  $result = json_decode($result, True);
//======== CallBackQuery =============================
  $callback_data = $result['callback_query']['data'];
  $callback_id = $result['callback_query']['message']['chat']['id'];
  $callback_message_id = $result['callback_query']['message']['message_id'];
```
Inline: 
```
switch ($text) { 
  case '/inline':
  $reply = 'Easy Random Bot';
      
       $keyboard = Keyboard::make()->inline()
      ->row(
        Keyboard::inlineButton(['text' => 'Start','callback_data' => '/random']),
      );

      $telegram->sendMessage([
        'chat_id' => $chat_id,
        'text' => $reply,
        'reply_markup' => $keyboard,
        'parse_mode' => 'markdown',
         ]);
         break;
}
```
Обработка callback
```
switch ($callback_data){

    case '/random':
    $num = rand(5, 15);
    $reply = 'Niumber: '.$num ;
    $keyboard = Keyboard::make()->inline()
    ->row(
      Keyboard::inlineButton(['text' => 'One more?','callback_data' => '/random']),
    );
       $telegram->editMessageText([
        'chat_id' => $callback_id,
        'message_id' => $callback_message_id,
        'text' => $reply,
        'reply_markup' => $keyboard,
        'parse_mode' => 'markdown',
         ]);
    
      break;
}
```

**Comment by foremtehan** [comment]
version 3 have a lot of issue.

**Comment by faustoFF** [comment]
@assada, alternatively you can create modified `Telegram\Bot\Objects\Update` object (with text from callback_query data) and pass it to `execute()`. Very hacky, but works for me.

```php
$updates = Telegram::commandsHandler(false);

foreach ($updates as $update) {
    if ($update->isType('callback_query')) {
        $rawResponse = $update->getRawResponse();

        $callbackQueryId = $rawResponse['callback_query']['id'];

        $rawResponse['message'] = $rawResponse['callback_query']['message'];
        $rawResponse['message']['text'] = $rawResponse['callback_query']['data'];
        unset($rawResponse['callback_query']);

        Telegram::getCommandBus()->execute(
            ltrim(explode(' ', $rawResponse['message']['text'])[0], '/'),
            new Update($rawResponse),
            []
        );

        Telegram::answerCallbackQuery(['callback_query_id' => $callbackQueryId]);
    }
}
```
