### ISSUE TITLE
utf-8 !!!

### ISSUE THREAD

**Issue by derakoola** [irazasyed/telegram-bot-sdk#74]
I get this error for many times:

```
Telegram\Bot\Exceptions\TelegramResponseException
[Error]: Bad Request: text must be in utf-8
```

request:
```
{"update_id":1111,"message":{"message_id":1111,"from":{"id":1111,"first_name":"xxx"},"chat":{"id":1111,"first_name":"xxx","type":"private"},"date":1449401679,"text":"1. \u06a9\u0627\u0646\u0627\u0644"}}
```

I provide this by keyboard, if you choose one of buttons, it return this error and if you push the same button again it works!

This error just did not occur on version ```1.0```

**Comment by irazasyed** [comment]
That error is directly from Telegram. It has got nothing to do with the library AFAIK.

Can you re-check with `v1.0` with same keyboard and everything else?

**Comment by derakoola** [comment]
I have 3 bots!
@allStoreBot
@leitnerBot
@nowArzBot
@partnerLookBot

all bots work correctly except the first one!
I checked everything that i think may cause it! I have no idea now!

It's strange! because it works if you touch the same keyboard twice!

![img_2015-12-06 15 44 38](https://cloud.githubusercontent.com/assets/5869562/11613279/4d9927fc-9c30-11e5-959e-6a9067806def.jpg)

**Comment by irazasyed** [comment]
Maybe try with another Telegram client? Like iOS/Desktop? It could also be a bug with their client.

**Comment by derakoola** [comment]
Error in devices:
Telegram Desktop mac OSX: yes
Telegram Desktop Windows: yes
Telegram android: yes

Telegram IOS: not yet!

**Comment by irazasyed** [comment]
Ahan! Report this to Telegram Bot Support, So they can fix this issue across all their clients.

**Comment by derakoola** [comment]
OK, Thanks.

**Comment by derakoola** [comment]
I could find it!

filter text before sending it by:
```$text = iconv("UTF-8", "UTF-8//IGNORE", $text),```

**Comment by jonnywilliamson** [comment]
Please give an example of what message failed BEFORE you filtered it through `iconv()`.

Does this only apply to normal text messages?

Will it also fail if used as a caption for an image or a video?

Thank you.

**Comment by jonnywilliamson** [comment]
I don't think you've got the right solution to your problem.

The docs state:
>If you append the string //TRANSLIT to out_charset transliteration is activated. This means that when a character can't be represented in the target charset, it can be approximated through one or several similarly looking characters. If you append the string //IGNORE, characters that cannot be represented in the target charset are silently discarded. Otherwise, E_NOTICE is generated and the function will return FALSE.

So in your case you are passing a string to the function that you want converted to UTF-8.

However you're telling the function that the input string is UTF-8 already but that it is to DROP any characters that are invalid.

Surely the message text you are trying to send is now missing characters?

**Comment by derakoola** [comment]
@jonnywilliamson 
for normal text it works fine.

I had some info that filled by users and users used abnormal letters.

I prefer to delete abnormal letters rather that translate it.

**Comment by jonnywilliamson** [comment]
And have you tested if the same issue happens if you add those characters to image/video captions? 

That would be another place that text might need to be filtered.

**Comment by derakoola** [comment]
@jonnywilliamson 

no, I don't test in for caption of images! also I think videos don't have a caption!

and also I can't find that letters!
I scaned it myself and I can't detect abnormal letters!
but when I used ```$text = iconv("UTF-8", "UTF-8//IGNORE", $text);```` everything be OK.

**Comment by jonnywilliamson** [comment]
![image](https://cloud.githubusercontent.com/assets/2513663/11809160/cf3bb99e-a31c-11e5-839f-68de1d062053.png)

**Comment by derakoola** [comment]
@jonnywilliamson 
You right. 👍
