### ISSUE TITLE
Webhook called repeatedly - how to stop?

### ISSUE THREAD

**Issue by pfloriginale** [irazasyed/telegram-bot-sdk#740]
telegram call my webhook continuously.. do you know why and how I could stop it?

```
//Retrieve 
    $updates = Telegram::getWebhookUpdates();
   


    //Switch 1
    $some_check= (strtolower(substr($updates['message']['text'],0,9))  == 'etichetta') ? true : false;
    if($some_check){
       // some of my internal code here...
       return;
    }



    //Switch 2    
    if(substr($updates['message']['text'],0,6) == "/start"){
      // some of my internal code here...
        
      return redirect('/profilo');
    }
    else{

      // some of my internal code here...

    }


return response()->json(["status" => "success"]);
```

**Comment by KielD-01** [comment]
First of all, fo with commands instead of checking manually.
Then, set up an accessible webhook URL. 
If You had a queue of failing webhooks - then they will pass and queue stops.

**Comment by irazasyed** [comment]
You need to respond to Telegram with a success message (status code 2xx) every time you get an incoming webhook update to acknowledge you've received the update. I see you're doing that at the end but before that, there's also some code that is returning a redirect request or returning null which is invalid.

If you don't confirm, then Telegram will make several repeated attempts by sending the same update thinking you didn't receive it.
