### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by suadikhasen** [irazasyed/telegram-bot-sdk#741]
How can I make pagination using inline keyboard ?

**Comment by KielD-01** [comment]
@suadikhasen You can do the main array with the data and last two buttons for the pagination.
After You click on the button, You need to check for the `callback_data`.
For example, You need to have:

```php5
$keyboard = [
    'inline_keyboard' => [
        [
             ['text' => 'Song 1', 'callback_data' => '/get_song song_1']
        ],
        [
             ['text' => 'Song 2', 'callback_data' => '/get_song song_2']
        ],
        [
             ['text' => 'Song 3', 'callback_data' => '/get_song song_3']
        ],
        [
             ['text' => '<', 'callback_data' => '/get_song page_3'],
             ['text' => '>', 'callback_data' => '/get_song page_5'],
        ]
    ]
];
        
$markup = new Keyboard($keyboard);
```

Then, You need to regex Your argument:
- Song : `/song_(\d+)/`
- Pagination : `/page_(\d+)/`

And after, You need to check for one of them if it matches a pattern.
And if it's (e.g. page) - You need to get next, or prev, page for the content.
And if it matches a song - then You need to drop content as a message to a chat.

I hope, this helps.
