### ISSUE TITLE
Webhook Is working but return 500 Internal Server Error and Pending Update Count

### ISSUE THREAD

**Issue by senzlord** [irazasyed/telegram-bot-sdk#742]
"has_custom_certificate": false,
"pending_update_count": 16,
"last_error_date": 1588586418,
"last_error_message": "Wrong response from the webhook: 500 Internal Server Error",
"max_connections": 40

return from getWebhookInfo

$updates = Telegram::getWebhookUpdates();

$chatId = $updates["message"]["chat"]["id"];
$message = $updates["message"]["text"];

if (strpos($message, "/start") === 0) {
    $msg = "Welcome to My Bot!!! ";
    $response = Telegram::sendMessage([
           'chat_id' => $chatId,
           'text' => $msg
    ]);
    return response('ok', 200);
}
return response('ok,200);

i already use response status 200...

On ngrok
![image](https://user-images.githubusercontent.com/22251174/80955556-b2a23680-8e29-11ea-96ff-ad4ebe62a0ed.png)

**Comment by Xibel** [comment]
Please check for debugging your webhook the following article: https://www.xibel-it.eu/debug-telegram-bot-sdk-with-webhook-in-laravel/

**Comment by KielD-01** [comment]
@senzlord Check Your `storage/logs/laravel.log` log file for the exceptions caught from the webhook.
Then, You would be able to resolve Your issue.
Just watch Your exception stack.

I hope, this helps.

**Comment by PunyFlash** [comment]
There are some exceptions in your app. You should `try` - `catch` over your update handling process. In this case, the webhook will return the success status, so your updates will be sent once even if an exception happens. I also may recommend a library, where you can turn off Telegram's API HTTP exceptions by passing a related config value - [westacks/telebot](https://github.com/westacks/telebot)
