### ISSUE TITLE
Wrong doc for POST /webhook

### ISSUE THREAD

**Issue by pooriamo** [irazasyed/telegram-bot-sdk#744]
Hi

The doc says to put this in routes:

```
Route::post('/<token>/webhook', function () {
    $updates = Telegram::getWebhookUpdates();

    return 'ok';
});
```

I did the same but the bot failed to reply to commands. But I found something else in the comments of the issues which used `Telegram::commandsHandler(true);` instead, and it's working now. 

Are the docs incorrect?

**Comment by KielD-01** [comment]
@pooriamo It's not mandatory to put that construction into the routes.
You can also do the next one:

```php5
// routes.php
Route::post('/web-hook', [WebHookController::class, 'hook'])
    ->name('tg.wh');

// WebHookController.php

class WebHookController extends Controller
{
    public function hook()
    {
        /** @var Update $update */
        $update = Telegram::commandsHandler(true);
    }
}

```

I use this example for my project and it works just fine.
I hope this helps.
