### ISSUE TITLE
Where is the sendPoll method?

### ISSUE THREAD

**Issue by SuperSpe** [irazasyed/telegram-bot-sdk#745]
I need to dynamically create a poll but I cannot see the sendPoll method.
The guides says that all methods are supported...
Thanks

**Comment by Omyshev** [comment]
Sending a poll works fine.
However, if you send messages to a private chat (chat with the user, then the polling data will be only inside the chat), I used the forwardig message of a polling message for this.

`$question = 'Requered';`
     ` $options = ['First','Two'];`
    `  $telegram->sendPoll([`
       ` 'chat_id' => $chat_id, //Required`
       ` 'question' => $question, //Required`
       ` 'options' => $options, //Required`
       ` 'is_anonymous' => false, //Optional (true / false)`
     `    ]);`

> I used the forwardig message
`$groupid = '-99999999999999'; //getChat`
`$post_number = '2'; //Post with Pool`
` $telegram->forwardMessage([`
 ` 'chat_id' => $chat_id, //Required`
 ` 'from_chat_id' => $groupid, //Required`
`  'message_id' => $post_number, //Required`
`  ]);`

**Comment by KielD-01** [comment]
@SuperSpe If You would like to send a Poll, You need to use `Telegram` Facade or an `Api` class to be able to send a Polls.
Please, check [this](https://github.com/irazasyed/telegram-bot-sdk/issues/777#issuecomment-683108900) issue.
It has all needed information for You for how to send a Poll.

Hope, this helps.

**Comment by KielD-01** [comment]
@irazasyed I think, that this one can be closed due to blatancy.
