### ISSUE TITLE
Handling conversations?

### ISSUE THREAD

**Issue by dasturchiuz** [irazasyed/telegram-bot-sdk#746]
Hello.
How can I handle conversations?
For example I have a command "/contact" which displays the message "Please enter your message:". After that the user should enter the contact message. How can I understand this message?

**Comment by suadikhasen** [comment]
Use database or cache to store status of a user I am currently use database 
Feel free to ask again

**Comment by KielD-01** [comment]
@dasturchiuz I advise You to go with the next way:

- Create Chat model
- Create Chat observer
- Add an observer after the chat has been created
- Cache all the chat_id's into the cache
- After the request comes, check the cache, if chat already exists and create if not

This would make Your database feel well/better and less load on that.
I hope, this helps.
