### ISSUE TITLE
Required "token" not supplied in config even its already there

### ISSUE THREAD

**Issue by nizam27391** [irazasyed/telegram-bot-sdk#747]
Hi.

![image](https://user-images.githubusercontent.com/6505952/81884437-7d84a980-95ca-11ea-8ec4-9b18813bf189.png)

I received the error like the above. However I have the token both in the config and also in .env as TELEGRAM_BOT_TOKEN.

I'm using Laravel and already cleared the cache and config. 

Thanks in advance for the help. :)

**Comment by KielD-01** [comment]
@nizam27391 Looks like You are trying to instantiate `new Api()` with no token passed.
If You are not passing the token it will try to get the token from the file of `.env`, where the default `TELEGRAM_BOT_TOKEN` variable may be placed with the appropriate token.
But, looks like You are missing it.

It's possible to auto-resolve if You have set all the needed webhooks, which has been described in the `conf/telegram.php` file. But all those would be within the specified route, which would be handling and update with `Telegram::commandsHandler(true)`;

I hope, this helps.

**Comment by zloadmin** [comment]
I had the same error when I used Redis for queue and cache. When back to files and sync - all work.
