### ISSUE TITLE
Add support for sending photos via file_id in MediaGroups

### ISSUE THREAD

**Issue by BoBRoID** [irazasyed/telegram-bot-sdk#748]
Hello there!
I want to store some photos sent me by users, and share them with him later. I tried a lot of ways and this is my best solution to do that:

                

                $media = array_map(function($fileId) {
                    return ['type' => 'photo', 'media' => $fileId];
                }, $images);

                Telegram::sendMediaGroup(['media' => json_encode($media)]);`

but, unfortunately, I can't send request in this way from the box because of validator. I propose to make one little change to allow send files in this way: in the `Http` trait in the `uploadFile` method add check for the json. Check my fork for details.

maybee I miss something from documentation, and there exists other way to send files via telegramId?

**Comment by jonnywilliamson** [comment]
All this will be taken care of very shortly. We are in midst of big announcement. Hopefully only a very short time until we can do that.

I hope you can wait until then!

**Comment by PunyFlash** [comment]
See https://github.com/westacks/telebot library

**Comment by topconvert** [comment]
Hello!
When will there be an update to resolve this issue?

**Comment by YSRoot** [comment]
https://github.com/irazasyed/telegram-bot-sdk/pull/1014
in this pr this case solved
