### ISSUE TITLE
Set thumbnail for video not working

### ISSUE THREAD

**Issue by foremtehan** [irazasyed/telegram-bot-sdk#749]
Hello, i want to set thumbnail with sendVideo method but it ignore by telegram:

```php
$tg->sendVideo([
    'chat_id' => 'CHATID',
    'video' => 'file_idstring',
    'thumb' => InputFile::create(public_path('img.jpg')) //image is jpg and less than 320p/200kb
]);
```

Also tried without `InputFile` class by it not working anyone can help me

**Comment by KielD-01** [comment]
@foremtehan Please, be aware of the next thing, which has been described in the [Official Documentation of the Telegram Bot API](https://core.telegram.org/bots/api#sendvideo) for the `sendVideo` method:

<img width="794" alt="Screen Shot 2020-08-29 at 1 47 00 PM" src="https://user-images.githubusercontent.com/10153164/91635105-43ff6f00-e9fe-11ea-8e2b-2d6e7798de70.png">

I hope, this helps.

**Comment by KielD-01** [comment]
@irazasyed We can close this, as this issue is not related to the package and more about the Telegram.
