### ISSUE TITLE
Doesn't work certificate SSL

### ISSUE THREAD

**Issue by DeeSouza** [irazasyed/telegram-bot-sdk#751]
Laravel 5.8
SDK 3.1
My domain is HTTP, not HTTPS.

Error:

cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

My telegram.php config:

`'token' => env('TELEGRAM_BOT_TOKEN', 'YOUR-BOT-TOKEN'),`
`'certificate_path'    => env('TELEGRAM_CERTIFICATE_PATH', storage_path('cacert.pem')),`

But, doesn't work.

**Comment by KielD-01** [comment]
@DeeSouza You can't use self-signed certs for this.
Plus - this is [cURL](https://curl.haxx.se/libcurl/c/libcurl-errors.html) issue with Your cert and not package.

Besides, if You are using Laravel, or any other framework, You can use:
- Laravel Valet ([Mac OS X](https://github.com/laravel/valet) / [Linux](https://github.com/cpriego/valet-linux)/ [Windows](https://github.com/cretueusebiu/valet-windows))
- [ngrok](https://ngrok.com/)

Using one of this tools (Valet using ngrok to share, so it's up what to use) will allow You to share Your project over HTTPS.
You just need to type `valet share` or `ngrok http 80` from the root of the project (if You have Valet or ngrok installed) and there You go - You will get all needed URL's to set up a webhook:

<img width="629" alt="Screen Shot 2020-08-29 at 1 30 03 PM" src="https://user-images.githubusercontent.com/10153164/91634819-fd107a00-e9fb-11ea-97f6-086d6d6bc0db.png">

If that won't work - then set the webhook manually.
Or, You can create a command like below:

```php5
use GuzzleHttp\Client;
use Illuminate\Console\Command;

class SetBotsWebHookCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'tg:wh';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Set Telegram Webhook';

    protected $setWebHookUrl = 'https://api.telegram.org/bot%s/setWebhook?url=%s';

    protected $deleteWebHookUrl = 'https://api.telegram.org/bot%s/deleteWebhook';

    protected $http;

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
        $this->http = new Client();
    }

    /**
     * Execute the console command.
     *
     * @return void
     */
    public function handle()
    {
        array_map(function ($bot) {
            $setWebhook = sprintf(
                $this->setWebHookUrl,
                $bot['token'],
                route($bot['webhook_url'])
            );

            $deleteWebhook = sprintf(
                $this->deleteWebHookUrl,
                $bot['token']
            );

            $this->http->get($deleteWebhook);
            $this->http->get($setWebhook);

        }, config('telegram.bots'));
    }
}
```

I hope, this would help You solving this issue.

**Comment by KielD-01** [comment]
@irazasyed I think, that this can be closed due to unrelated issue.
