### ISSUE TITLE
setAsyncRequest(true)->editMessageCaption($params) Not working

### ISSUE THREAD

**Issue by foremtehan** [irazasyed/telegram-bot-sdk#752]
version : 3.1.0

When i do `setAsyncRequest(true)->editMessageCaption($params)` for channel's posts my server doesnt response and i dont know what is  happing behind the scenes but when i remove the `setAsyncRequest` it would work

**Comment by KielD-01** [comment]
@foremtehan yesterday, I had a try to test `setAsyncRequest` method, and it works fine.

Check for:
- Is Your server up and running
- You have set correct WebHook URL
- WebHook URL is HTTPS and not HTTP as the webhooks works only with Secure Schema
- Your WebHook has been set up

Also, I suggest trying to remove and install the webhook again.
If someone also has got Your key - it possible, that Your webhooks have been removed.
 
I hope, this helps.

**Comment by foremtehan** [comment]
You've test the `setAsyncRequest(true)->editMessageCaption($params)` and it worked for you ?
