### ISSUE TITLE
Set proxy

### ISSUE THREAD

**Issue by yelyas20** [irazasyed/telegram-bot-sdk#753]
Telegram service is filtered in our country. Is there a way to set a proxy to send and receive requests in config file?
In the Laravel env file, I set HTTP_PROXY variable that solved my problem, but I want only telegram requests pass through a proxy.

**Comment by KielD-01** [comment]
@irazasyed is this something we consider have in 4.x?
Or we can have this update on 3.x?
What are Your thoughts?

**Comment by jonnywilliamson** [comment]
Poxy is supported in new version (to be released)

**Comment by irazasyed** [comment]
As @jonnywilliamson mentioned, it's already supported in `4.x` but one can also set HTTPS proxy in `3.x` by setting an env var. Guzzle supports [proxy env var](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L243-L245).

Edit: OP is already aware of env var method. They can wait for 4.x release.
