### ISSUE TITLE
editMessage method

### ISSUE THREAD

**Issue by urtvs** [irazasyed/telegram-bot-sdk#756]
Hi
I cant find method for editing message
Do you have it? 

Thanks

**Comment by KielD-01** [comment]
@urtvs You can refer to the [EditMessage Trait](https://github.com/irazasyed/telegram-bot-sdk/blob/develop/src/Methods/EditMessage.php).
It contains all the needed methods for Editing Messages.

Hope, this helps.

**Comment by irazasyed** [comment]
Thanks @KielD-01.
