### ISSUE TITLE
MultiBot work incorrect

### ISSUE THREAD

**Issue by ivanklykov** [irazasyed/telegram-bot-sdk#757]
Hello
I created 2 bots and set 2 webhooks. I registered both bots in the config. Everything works correctly, but when sending a command to a single bot, the response comes in the default bot. What might be the problem?

web.php
`Route::post('/{token}/webhook', function () {

    $update = Telegram::commandsHandler(true);
});`

**Comment by KielD-01** [comment]
@ivanklykov I advise You to have different webhook places for different bots. 
So, create a mapper for routes and create `routes/bots.php` file, where You would be able to specify different routes for different bots.

As an example:

```php5
// app/Http/Controllers/WebHookController.php

class WebHookController extends Controller {
        public function hook() {
            Telegram::commandsHandler(true);
        }
}

// app/Http/Controllers/Bots/BotAController.php
class BotAController extends WebHookController {}

// app/Http/Controllers/Bots/BotBController.php
class BotBController extends WebHookController {}
```

```php5
// routes/bot.php

Route::prefix('botA')
    ->name('botA.')
    ->group(function (Router $router) {
        $router->get('web-hook', [BotAController::class, 'hook']);
    });

Route::prefix('botB')
    ->name('botB.')
    ->group(function (Router $router) {
        $router->get('web-hook', [BotBController::class, 'hook']);
    });
```

If You have some custom logic, You can freely rewrite it in the Bot Controller.

Hope, this helps.

**Comment by irazasyed** [comment]
Try this:

```php
Route::post('/{token}/{bot}/webhook', function ($bot) {
	$update = Telegram::bot($bot)->commandsHandler(true);
});
```

Your webhook URL would look like this: `/token1234/botone/webhook`

When working with multi-bots, always make sure to provide bot name to the `bot()` method supported for all API methods.
