### ISSUE TITLE
Wrong response from the webhook: 429 Too Many Requests

### ISSUE THREAD

**Issue by michelmelo** [irazasyed/telegram-bot-sdk#759]
Wrong response from the webhook: 429 Too Many Requests ???

**Comment by KielD-01** [comment]
@michelmelo why it's the wrong response?
It says, that Your frequency of the requests is too high and You are exceeding more than 30 messages per second.
Plus, it's not about the package. It's about the [Telegram API Rates Limit](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this).

Hope, this helps

**Comment by KielD-01** [comment]
@irazasyed You can close this issue, as this one is non-related and blatant.
