### ISSUE TITLE
Is that all right with Getting Started part?

### ISSUE THREAD

**Issue by Iossar** [irazasyed/telegram-bot-sdk#760]
Hi, i just want to know is that all right with Installation part? I mean self-register  ServiceProvider and Facade does not working for me, and **php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider"** command returns **Unable to locate publishable resources.**. I`m using laravel 5.6 and  7.18.0 versions. Tried to reinstall package, but still no results.
Also tried to add providers and aliases to config/app by myself, but got _  Class 'Telegram\Bot\Laravel\Facades\TelegramServiceProvider' not found _ error.
Is that only my problems? Thanks.

**Comment by KielD-01** [comment]
@Iossar ServiceProvider, You have specified, is not available by that namespace.
The right namespace for that is:
```php5
\Telegram\Bot\Laravel\TelegramServiceProvider::class
```

Also, try to run `composer dump-autoload -o` within the root of the project.

Hope, this helps.
