### ISSUE TITLE
update guzzle requirements

### ISSUE THREAD

**Issue by vv12131415** [irazasyed/telegram-bot-sdk#761]
Since guzzle 7 is out I think it will be cool to support it here, in this package.

**Comment by KielD-01** [comment]
@vladyslavstartsev AFAIK, v7 support will be in v4 of this package.
@irazasyed can You leave a comment regarding this one?

**Comment by irazasyed** [comment]
Yes, Guzzle v7 will be supported in v4 of this SDK. Thanks!
