### ISSUE TITLE
many of other messengers in the world work like telegram bot api

### ISSUE THREAD

**Issue by saber13812002** [irazasyed/telegram-bot-sdk#764]
we have many messangers in other countries that bot apis same as telegram 

and in your best laravel we use https://api.telegram.org/api

please change your code so we can use your module in other countries as laravel module

**Comment by saber13812002** [comment]
i create a new merge request 

https://github.com/irazasyed/telegram-bot-sdk/pull/765


to solve this problem

so we can use env file to use another base url for your use


روبات بله لاراول پلاگین کتابخانه

**Comment by KielD-01** [comment]
@irazasyed AFAIK, this should be closed as per PR
