### ISSUE TITLE
Send a message with buttons, and after clicking: change the message and remove the buttons

### ISSUE THREAD

**Issue by enshtein** [irazasyed/telegram-bot-sdk#766]
Please write an example of the following code:

1) The bot asks a question to the user and offers 2 answer options in the form of buttons: Yes / No
2) User clicks on any of the buttons in this message
3) The bot receives a response, hides the buttons on the message and adds a smiley before the message text

How to do it?

Thank!

**Comment by KielD-01** [comment]
@enshtein Is this one still relevant?

**Comment by akhmadovDev** [comment]
> 
yes

**Comment by KielD-01** [comment]
@AkhmadovBehruzbek @enshtein scenario is next:
- Send a message with a keyboard
- On button press, You get message ID, on which action has occurred
- Edit message by the message ID from the conversation
