### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by raviroshanmehta** [irazasyed/telegram-bot-sdk#768]
Unable to integrate into existing laravel project

 Problem 1
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - irazasyed/telegram-bot-sdk v3.1.0 requires guzzlehttp/guzzle ^6.1 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Installation request for irazasyed/telegram-bot-sdk ^3.1 -> satisfiable by irazasyed/telegram-bot-sdk[v3.1.0].
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0) -> satisfiable by guzzlehttp/guzzle[7.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by KielD-01** [comment]
@raviroshanmehta What's the version of Laravel You do use?
If lower than 6, You need to use 2.x.

**Comment by dkwiebe** [comment]
I'm running into this with Laravel 7.

Using version ^3.1 for irazasyed/telegram-bot-sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - irazasyed/telegram-bot-sdk v3.1.0 requires guzzlehttp/guzzle ^6.1 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Installation request for irazasyed/telegram-bot-sdk ^3.1 -> satisfiable by irazasyed/telegram-bot-sdk[v3.1.0].
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0) -> satisfiable by guzzlehttp/guzzle[7.0.1].

**Comment by Yabzik** [comment]
Same on Lumen 7.2.1

- Installation request for irazasyed/telegram-bot-sdk ^3.1 -> satisfiable by irazasyed/telegram-bot-sdk[v3.1.0].
- Conclusion: remove guzzlehttp/guzzle 7.0.1
- Conclusion: don't install guzzlehttp/guzzle 7.0.1

**Comment by irazasyed** [comment]
Try the `3.3.0` release. It supports Guzzle 7.
