### ISSUE TITLE
Full keyboard dont work

### ISSUE THREAD

**Issue by dura0ok** [irazasyed/telegram-bot-sdk#769]
` <?php
        $keyboard = new Keyboard();
        $keyboard->row(Keyboard::button(['text' => 'asdasd']));

        $data = [
            'text' => $this->text,
            'chat_id' => $this->chatId,
            'keyboard' => $keyboard
        ];
    $this->telegram->sendMessage($data);`
I'm trying to pin a message to my keyboard
The message is sent, but for some reason the keyboard is not
Please, help me....

**Comment by KielD-01** [comment]
@stepan-neretin7 Here You go with the example:

```php5
class WebHookController extends Controller
{
    public function hook()
    {
        /** @var Update $update */
        $update = Telegram::commandsHandler(true);

        if ($update->getChat()->get('id')) {
            $params = [
                'keyboard' => [
                    [
                        ['text' => 'test1', 'callback_data' => 'test1'],
                        ['text' => 'test2', 'callback_data' => 'test2'],
                    ]
                ],
                'resize_keyboard' => true,
                'one_time_keyboard' => true,
            ];

            /** @var Update $response */
            Telegram::sendMessage([
                'text' => 'Test Message pinned to the Keyboard',
                'chat_id' => $update->getChat()->get('id'),
                'reply_markup' => new Keyboard($params)
            ]);
        }
    }
}
```

<img width="1035" alt="Result : Message with Kbrd" src="https://user-images.githubusercontent.com/10153164/91616050-98b6d180-e98d-11ea-8da4-8a958e78d742.png">

Hope this helps
