### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by dasturchiuz** [irazasyed/telegram-bot-sdk#770]
PHP version: PHP 7.3.19-1~deb10u1

`$  composer require irazasyed/telegram-bot-sdk ^3.1
`
`Package operations: 2 installs, 0 updates, 0 removals
  - Installing league/event (2.2.0): Loading from cache
  - Installing irazasyed/telegram-bot-sdk (v3.1.0): Loading from cache
irazasyed/telegram-bot-sdk suggests installing irazasyed/larasupport (Allows you to use any Laravel Package in Lumen by adding support!)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   TypeError 

  Argument 1 passed to Telegram\Bot\BotsManager::__construct() must be of the type array, string given, called in /var/www/works/soliq24/vendor/irazasyed/telegram-bot-sdk/src/Laravel/TelegramServiceProvider.php on line 65

  at vendor/irazasyed/telegram-bot-sdk/src/BotsManager.php:29
    25|      * TelegramManager constructor.
    26|      *
    27|      * @param array $config
    28|      */
  > 29|     public function __construct(array $config)
    30|     {
    31|         $this->config = $config;
    32|     }
    33|

      +24 vendor frames 
  25  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.`

**Comment by KielD-01** [comment]
@dasturchiuz Try clearing composer cache, removing and install a package again.
Looks like, it has some issues with the previous version of the package.
That's why You are facing such an issue.

**Comment by irazasyed** [comment]
Please try the latest release and make sure to clear config cache.
