### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'PhpOption\Option' not found in /var/www/app/vendor/illuminate/support/Env.php:100

### ISSUE THREAD

**Issue by dimasalam1982** [irazasyed/telegram-bot-sdk#775]
I write at Yii2. I installed this library and when I tried to call new Api('TOKEN')
I got an error:

PHP Fatal error:  Uncaught Error: Class 'PhpOption\Option' not found in /var/www/app/vendor/illuminate/support/Env.php:100

**Comment by KielD-01** [comment]
@dimasalam1982 Try to run one of the next commands:
```php5
# Update dependencies
composer update

# Dump Your classes to vendor autoload
composer dump-autoload

# Remove Your vendor and re-install Your dependencies
rm -rf ./vendor; composer i
```

Hope, this helps

**Comment by irazasyed** [comment]
Can you try by installing this package `vlucas/phpdotenv`?
