### ISSUE TITLE
How can i test my application ?

### ISSUE THREAD

**Issue by foremtehan** [irazasyed/telegram-bot-sdk#776]
Excuse me how can i test my application ? I mean it works for webhooks things but what about unit testing ?

**Comment by KielD-01** [comment]
@foremtehan You can use Telegram Facade and check it in a way like this:

```php5
class WebHookController extends Controller
{
    public function hook()
    {
        /** @var Update $update */
        $update = Telegram::commandsHandler(true);

        if ($update->getChat()->get('id')) {
            $response = Telegram::sendPoll([
                'chat_id' => $update->getChat()->get('id'),
                'question' => 'Test Question',
                'type' => 'quiz',
                'explanation' => 'This is the test explanation',
                'options' => [
                    '1', '2', '3', '4'
                ],
                'is_anonymous' => false,
                'correct_option_id' => '2',
                'explanation_parse_mode' => 'html',
                'quiz' => true
            ]);

            // ToDo : Check response for some info
        }
    }
}
```

but - within the test.
Plus, You need to annotate, that it throws an Exception and it would be only an issue when wrong data has been passed or any content You are trying to pass doesn't exist.

Hope, this helps.

**Comment by KielD-01** [comment]
@irazasyed I think, that this one can be closed now

**Comment by foremtehan** [comment]
@KielD-01 I dont get it, `Telegram::commandsHandler(true);` just return a empty collection, I mean how can i test my application, for example how can i mock the telegram updates ?
