### ISSUE TITLE
Poll object does not have the Explanation field

### ISSUE THREAD

**Issue by aliraghebi** [irazasyed/telegram-bot-sdk#777]
The poll object does not have the explanation field, please add it

**Comment by KielD-01** [comment]
@arsamme Actually, You can do an explanation.
But it only works for [Quiz Mode](https://core.telegram.org/bots/api#sendpoll).
Please, take a look at the code and a screenshot:

```php5
class WebHookController extends Controller
{
    public function hook()
    {
        /** @var Update $update */
        $update = Telegram::commandsHandler(true);

        Telegram::sendPoll([
            'chat_id' => $update->getChat()->id,
            'question' => 'Test Question',
            'type' => 'quiz',
            'explanation' => 'This is the test explanation',
            'options' => [
                '1', '2', '3', '4'
            ],
            'correct_option_id' => '2',
            'explanation_parse_mode' => 'html',
            'quiz' => true
        ]);
    }
}
```

<img width="694" alt="Result : Poll as a Quiz with the Explanation field" src="https://user-images.githubusercontent.com/10153164/91608668-a9138000-e97e-11ea-943d-35c54245c4ce.png">

Hope, this helps.

@irazasyed we can close this issue.
