### ISSUE TITLE
Wrong doc

### ISSUE THREAD

**Issue by ombapit** [irazasyed/telegram-bot-sdk#779]
![image](https://user-images.githubusercontent.com/2478584/91168311-a2c3a080-e6ff-11ea-8e7b-d9dd67548950.png)

wrong attribute, should be parse_mode

**Comment by KielD-01** [comment]
@irazasyed Any possibility to update the API Docs?

**Comment by irazasyed** [comment]
It seems like you are browsing v2 API docs which are obsolete. It'll most likely be taken down once v4 is released.

**Comment by irazasyed** [comment]
Also, the API doc generator seems to be removing the `_` underscore for all params, so it's not just that one param.
