### ISSUE TITLE
Error in BotsManager.php:29

### ISSUE THREAD

**Issue by AkhmedovSH** [irazasyed/telegram-bot-sdk#783]
Argument 1 passed to Telegram\Bot\BotsManager::__construct() must be of the type array, null given, called in myProjectPath\vendor\irazasyed\telegram-bot-sdk\src\Laravel\TelegramServiceProvider.php on line 65

25|      * TelegramManager constructor.
    26|      *
    27|      * @param array $config
    28|      */
  > 29|     public function __construct(array $config)
    30|     {
    31|         $this->config = $config;
    32|     }
    33| 

\vendor\irazasyed\telegram-bot-sdk\src\Laravel\TelegramServiceProvider.php:65
\vendor\laravel\framework\src\Illuminate\Container\Container.php:805

error after installation version v3.1.0

**Comment by irazasyed** [comment]
Please share more details like Laravel version and whether or not you've published the config from the package?

**Comment by Xoshbin** [comment]
Having same issue, on Laravel 7, tried v3.2.0 and v3.1.0, both of them giving the same error at installing the package.

**Comment by Xoshbin** [comment]
it's solved here #https://github.com/irazasyed/telegram-bot-sdk/issues/754#issuecomment-657583607

**Comment by irazasyed** [comment]
Try the new release and also make sure to clear config cache as recommended above. https://github.com/irazasyed/telegram-bot-sdk/releases/tag/v3.3.0
