### ISSUE TITLE
Unable to locate publishable resources using Laravel Framework 7.27.0

### ISSUE THREAD

**Issue by errand** [irazasyed/telegram-bot-sdk#784]
Hello!
I tried to add packege using Docs on your site and failed to vendor:publish on Laravel clean install. I checked package.json and didn't find "laravel": in "extra" of the package so i tried to install v3 of the package and viola. So the question is the documentation is lack of the info or the packege is broken? Because basicly ^2.0 isn't right package for laravel

**Comment by Davronjuraev** [comment]
Hey there
Last day i've this type of problem. Installed 3 rd version, now works.

**Comment by irazasyed** [comment]
We're working on `4.x` release which will have proper documentations as well as great new features until then you can use `3.x` version which although isn't documented but works fine with Laravel.

You can star and watch the project to get updates. Thanks!
