### ISSUE TITLE
Multiple bots in one project

### ISSUE THREAD

**Issue by Davronjuraev** [irazasyed/telegram-bot-sdk#785]
Hello,
How can i realize to make project with multiple bots. Project has several users and  for these users need to connect Telegram bot for their customer. Any idea how to realize it in one project? 
Configs of telegram will be in Database, but do not know how can i do that(
If any example, please share

**Comment by rubik360accounting** [comment]
As you said store bot information in database and while sending message you can query or get specific bot or use all of them 
and use like this
$telegram = new Api('your token');
$telegram->sendMessage([
                        'chat_id' => 'your chat_id, 
                        'text' => =>'test message'
                    ]);
