### ISSUE TITLE
support laravel 8

### ISSUE THREAD

**Issue by rajabit** [irazasyed/telegram-bot-sdk#787]
Problem 1
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.0.x-dev, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.1.x-dev, 6.5.x-dev].
    - irazasyed/telegram-bot-sdk v2.3.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Installation request for irazasyed/telegram-bot-sdk ^2.3.0 -> satisfiable by irazasyed/telegram-bot-sdk[v2.3.0].
    - Installation request for guzzlehttp/guzzle ^7.0.1 -> satisfiable by guzzlehttp/guzzle[7.0.1, 7.0.x-dev, 7.1.x-dev].

**Comment by irazasyed** [comment]
Please install `3.2` and try. Although there are no documentations but you can use it until `4.x` is released with documentations.
