### ISSUE TITLE
Telegram\Bot\Exceptions\CouldNotUploadInputFile File: `images_1600068177.jpg` does not exist or is not readable!

### ISSUE THREAD

**Issue by masabahmed** [irazasyed/telegram-bot-sdk#790]
if someone can solve my problem i shall be thankful

**Comment by masabahmed** [comment]
![image](https://user-images.githubusercontent.com/48594427/93056773-5b895980-f686-11ea-8d12-2ef53717c10d.png)

**Comment by irazasyed** [comment]
Share your code but it seems like you're trying to upload a file that isn't accessible or found as the error says.

Make sure you give absolute and correct path to the file, ex: `storage_path('image.jpg')` and the file is stored under `storage` dir.

**Comment by masabahmed** [comment]
public function store(Request $request)
    {
        //Validate Ad
        $this->validate($request, [
            'title' => 'required',
            'image' => 'image|nullable|max:1999',
            'pm_link' => 'required',
            'content' => 'required',
            'status' => 'required'
        ]);

        //Handle File Upload
        if($request->hasFile('image')){
            //Get filename with the extension
            $full_file_name = $request->file('image')->getClientOriginalName();
            //Get filename only without extension
            $file_name = pathinfo($full_file_name, PATHINFO_FILENAME);
            //Get file extension
            $file_extension = $request->file('image')->getClientOriginalExtension();
            //Filename to store
            $file_name_new = $file_name . '_' .time().'.'.$file_extension;
            //Upload image
            $path = $request->file('image')->storeAs('public/cover_images', $file_name_new);
        }else{
            $file_name_new = 'noimage.jpg';
        }
        //Create Ad
        $ad = new Ad;
        $ad->title = $request->input('title');
        $ad->name = 'name-will';
        $ad->image = $file_name_new;
        $ad->pm_link = $request->input('pm_link');
        $ad->content = $request->input('content');
        $ad->status = $request->input('status');
        $ad->user_id = auth()->user()->id;
        $ad->save();

        // dd($ad->image);

        Telegram::sendMessage ([
            'chat_id' => '-482323143',
            'parse_mode' => 'HTML',
            'text' => $ad->title
        ]);

        $remoteImage = $ad->image;
        $filename = 'ironman';

        Telegram::sendPhoto ([
            'chat_id' => '-482323143', 
            'photo'   => InputFile::create($remoteImage, $filename),
            'parse_mode' => 'HTML',
            'caption' => '$ad->content'
        ]);

        return redirect('/ads')->with('success', 'Ad Created');
    }

**Comment by masabahmed** [comment]
this my code , i want to send all of the $ads components to the group via my telegram bot.
is it possible?

**Comment by Maxxab** [comment]
and one thing the $file_name_new and the $remoteImage is same in the following line ?

                                'photo'   => InputFile::create($file_name_new, $filename),

**Comment by masabahmed** [comment]
i will wait for your response and i will be thankful if you can help me this is my first laravel project

**Comment by irazasyed** [comment]
You've quotes around your var `'$ad->content'` which is invalid.

You've just given file name to the `InputFile::create`, like mentioned earlier you need to give absolute path to the file. In this case, it looks like it would be `public_path('cover_images/'.$ad->image)`.

Please read Laravel docs as this is off-topic and not related to the SDK.

**Comment by masabahmed** [comment]
ok sir thanks

**Comment by masabahmed** [comment]
one thing this is the path of my image
![image](https://user-images.githubusercontent.com/48594427/93061690-58459c00-f68d-11ea-881e-fd1596aa14c3.png)

**Comment by masabahmed** [comment]
![image](https://user-images.githubusercontent.com/48594427/93061717-672c4e80-f68d-11ea-832e-b1599de676db.png)
and this is my code i change it as you said but it not works
![image](https://user-images.githubusercontent.com/48594427/93061800-81662c80-f68d-11ea-8392-3a34f82edec8.png)
and this error is showing

**Comment by masabahmed** [comment]
kindly tell me the correct path for my image
