### ISSUE TITLE
public path problem

### ISSUE THREAD

**Issue by masabahmed** [irazasyed/telegram-bot-sdk#791]
![image](https://user-images.githubusercontent.com/48594427/93096934-67910d80-f6be-11ea-9ae5-ea16c36d93c5.png)
brother can you please explain me this error?

**Comment by egin10** [comment]
Hi @Maxxab, I use version 3.4 on Laravel 8.

this is my code

    public function handle()
    {        
        $response = $this->getUpdate();
        $chat_id = $response->getChat()->getId();

        $filename = 'ubuntu.jpeg';
        $pathOrUrlOrResource = public_path('file_materi/1/' . $filename);
        $inputFile = InputFile::create($pathOrUrlOrResource, $filename);

        $response = $this->telegram->sendPhoto([
            'chat_id' => $chat_id,
            'photo' => $inputFile,
            'caption' => $filename
        ]);
    }

The result is like screenshot below

![image](https://user-images.githubusercontent.com/22806493/105628959-b328a480-5e72-11eb-8dfd-f0b087521242.png)

It works!

**Comment by JoseVale99** [comment]
@masabahmed
**Excellent friend, only you have to import `use Telegram\Bot\FileUpload\InputFile;`
this is my code:**
```php
<?php

namespace App\Http\Livewire;

use App\Models\Post;
use Livewire\Component;
use Telegram\Bot\Api;
use Telegram\Bot\FileUpload\InputFile;
class Tables extends Component
{

    // recover id for send telegram message post
    public function getMessageID($id)
    {
        $post = Post::find($id);
        $this->title = $post->title;
        $this->show_id = $id;
    }

    // send telegram message post
    public function sendMessage()
    {
        $post = Post::find($this->show_id);
        $post->status = 'send';

        $telegram = new Api(env('TELEGRAM_BOT_TOKEN'));

        $message = "$post->title\n\n$post->description\n\n$post->url_post";

        $inputFile = InputFile::create($post->image);

        $response = $telegram->sendPhoto([
            'chat_id' => env('TELEGRAM_CHAT_ID'),
            'photo' => $inputFile,
            'caption' => $message
        ]);

        $post->saveOrFail();
    }

}

```
**the result is the following:**
<a href="https://ibb.co/rdDLhbk"><img src="https://i.ibb.co/dm83vbB/Screenshot-20220330-223058-Telegram.jpg" alt="Screenshot-20220330-223058-Telegram" border="0" width="30%"></a>
