### ISSUE TITLE
Error: Call to undefined function Telegram\Bot\Commands\studly_case() in /vendor/irazasyed/telegram-bot-sdk/src/Commands/Command.php:182

### ISSUE THREAD

**Issue by vjik** [irazasyed/telegram-bot-sdk#793]
Version 2.3.0

I see, this problem already fixed in 2.0 branch.
Please release new version.

**Comment by kulakovfoto** [comment]
Also have this problem on v2.3

**Comment by Rodion15** [comment]
How do I solve the problem?

**Comment by artchudov** [comment]
Just change

` $reply_name = studly_case(substr($method, 9)); `

to

` $reply_name = substr($method, 9);`

On line 182 in in /vendor/irazasyed/telegram-bot-sdk/src/Commands/Command.php
