### ISSUE TITLE
How to get reply_to_message for sendMessage?

### ISSUE THREAD

**Issue by sanzharanarbay** [irazasyed/telegram-bot-sdk#794]
$telegram = new Api(Telegram::getAccessToken());
        $update = Telegram::getWebhookUpdates();
        $chat_id = $update->getMessage()->getChat()->getId();

        $replyMarkup = array(
            'force_reply' => true
        );
        $encodedMarkup = json_encode($replyMarkup);
		
        $response = $telegram->sendMessage([
            'chat_id' => $chat_id,
            'text' => 'Enter your name , please?',
            'reply_markup' => $encodedMarkup
        ]);

// this gives me entered command, not name
   $text = $update->getMessage()->getText();

   $this->replyWithMessage(['text' => 'Hello, ' . $text]);

**Comment by PunyFlash** [comment]
I think you are searching for `$update->getMessage()->reply_to_message` or `$update->getMessage()->replyToMessage` object, I'm not sure how it coded in the library (see [TG docs](https://core.telegram.org/bots/api#message) - reply_to_message). If you need more intuitive objects compatibility with oficiall telegram API docs, please check out [westacks/telebot](https://github.com/westacks/telebot) library.

**Comment by egin10** [comment]
Hi @sanzharanarbay you can check if ther's any 'reply_to_message' in the response from user like the code below.

      public function commandHandlerWebHook()
      {
          $updates = Telegram::commandsHandler(true);
          $chat_id = $updates->getChat()->getId();

          // get Reply_to_message
          if(array_key_exists('reply_to_message', $updates['message'])) {
            Telegram::sendMessage(['chat_id' => $chat_id, 'text' => 'Hello ' . $updates['message']['text']]);
          }

          return 'ok';
        }

you can put the code in your webhook route.
It's work fine.
