### ISSUE TITLE
$telegram->sendDice(...

### ISSUE THREAD

**Issue by APTEMOH** [irazasyed/telegram-bot-sdk#795]
Как получить значение sendDice (кинуть кости) Telegram API BOT?
Всем добра!

Не могу получить значение выпавшего после бросания костей.
Кидаем вот так:

`$response = $this->post('sendDice', $params);`

С такими параметрами:
```
$params = [
'chat_id'              => '',
'disable_notification' => '',
'reply_to_message_id'  => '',
'reply_markup'         => '',
];
```

Сервер должен вернуть вот так (в сообщении):
`"dice":{"emoji":"\ud83c\udfb2","value":3}`

НО возвращает когда отправить боту этот кубик, а если отправлять вот так $this->post('sendDice',... , то нет. Просто кидается кубик, анимация и т.д.

Помогите, пожалуйста!
Help me please!

Спасибо!

**Comment by punyflash** [comment]
Попробуй другую библиотеку - https://github.com/westacks/telebot.
```php
$message = $bot->sendDice([
    'chat_id' => '123456789'
]);
$dice_value = $message->dice->value;
```

**Comment by APTEMOH** [comment]
> Попробуй другую библиотеку - https://github.com/westacks/telebot.
> 
> ```
> $message = $bot->sendDice([
>     'chat_id' => '123456789'
> ]);
> $dice_value = $message->dice->value;
> ```

Спасибо! Проблема уже решена!
