### ISSUE TITLE
Target class [telegram] does not exist.

### ISSUE THREAD

**Issue by mravdel** [irazasyed/telegram-bot-sdk#799]
I'm using laravel 7 with this package.
Here is my dependencies:

<img width="457" alt="Screenshot 2020-10-18 at 21 50 50" src="https://user-images.githubusercontent.com/14264328/96377130-feecf300-118b-11eb-9e6c-0ac7205dd19b.png">

But when I run this code (open main page):
```
use Telegram\Bot\Laravel\Facades\Telegram;
Route::get('/', function () {
    $response = Telegram::getMe();
});
```

I got error:
`Target class [telegram] does not exist.`

What might be an issue?
I just install laravel 7 and require this package, and I publish `config/telegram.php` file

**Comment by mravdel** [comment]
For some reason this call: 
`php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider"`
show error:
`Unable to locate publishable resources.`

And I found out that TelegramServiceProvider doesn't even being registered.

Finally I found that I have to add in config/app.php to 'providers' array this service provider explicitly

**Comment by irazasyed** [comment]
Please use the `dev-develop` / `3.0@dev` branch. You're using an outdated version.

**Comment by newtmex** [comment]
How do we use the 3.0@dev branch?
