### ISSUE TITLE
Conflict: terminated by other getUpdates request

### ISSUE THREAD

**Issue by alvintheodora** [irazasyed/telegram-bot-sdk#801]
Calling getUpdates: https://telegram-bot-sdk.readme.io/reference#getupdates at the same time or on multiple browser will return 
`Conflict: terminated by other getUpdates request; make sure that only one bot instance is running {"userId":18,"exception":"[object] (Telegram\\Bot\\Exceptions\\TelegramResponseException(code: 409): Conflict: terminated by other getUpdates request; make sure that only one bot instance is running at /var/www/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php:58)`

How to resolve this one? Basically I want to get the updates on telegram upon every page load to see if any user registered to the telegram bot by typing command on their mobile app telegram

**Comment by irazasyed** [comment]
Use Webhook to get inbound messages/command and process the registration there instead of relying on getUpdates method.
