### ISSUE TITLE
Support for Bot API 5.0

### ISSUE THREAD

**Issue by foremtehan** [irazasyed/telegram-bot-sdk#802]
5.0 has been released yesterday and hope we get an update for supporting this version https://core.telegram.org/bots/api

This is just a heads up Good luck!

**Comment by jonnywilliamson** [comment]
It's already done and just awaiting to be merged in.

**Comment by irazasyed** [comment]
It's merged already! Thanks.

**Comment by foremtehan** [comment]
excuse me which branch ? where ?
