### ISSUE TITLE
How to send gif

### ISSUE THREAD

**Issue by mravdel** [irazasyed/telegram-bot-sdk#807]
Hello, there is no method sendAnimation (which is used in telegram api to send gifs).

Do I have any alternatives to send gif right now?

**Comment by roelofr** [comment]
[1]: https://core.telegram.org/bots/api

As the Telegram Bot SDK simply wraps around the [Telegram Bot API][1], you should look into that. For GIFs you're looking for media.

Don't use the issues for API-related questions, just SDK-related issues.

**Comment by mravdel** [comment]
@roelofr thanks for your answer! I know that it's just a wrap around Telegram Bot API, but I'm still trying to figure out how to send gifs more natively from SDK, maybe SDK provides a method to send anything Telegram bot API related. If it's not, I think it's a good idea for PR.

There is no place who can help me with that, except this issues, and I still think it can be valuable for other developers. I will post solution when I find one, thanks.

**Comment by roelofr** [comment]
Okay, apologies for being a bit blunt.

GIFs in Telegram are called animations, and you send them via the [`sendAnimation`][1] method.

### Creating suitable files

I faily often make gifs from screencaps so I have some experience on the dataformat used. My suggestion would be, to receive the best possible result and smallest filesize, to use soundless MPEG-4 files.

I'll illustrate with an [ffmpeg][2] command:

```bash
ffmpeg -i "My Animated File.mp4" -an -vf "scale=-1:480" -b 256k my-animation.mp4
```

Let's split this part:

- `-i "My Animated File.mp4"` - Load the given filename
- `-an` - Tell ffmpeg to drop the audio
- `-vf "scale=-1:480" - Tell ffmpeg to scale the video to 480px height, preserving aspect ratio
- `-b 512k` - Lower the file's bitrate to 256k (which is good enough for gifs)
- `my-animation.mp4` - Target file

### Sending the file

Now that we have our file, we can send it to Telegram.

```php
use Telegram\Bot\FileUpload\InputFile;

// ...

$bot->sendAnimation([
    'chat_id' => $id,
    'animation' => InputFile::create(__DIR__ . '/my-animation.mp4')

]);
```

I hope this helps you ~~RickRoll your users~~ send the gifs you want.

[1]: https://core.telegram.org/bots/api#sendanimation
[2]: https://ffmpeg.org/

**Comment by mravdel** [comment]
@roelofr thanks for detailed explanation about best gifs format, really good to know that.
I would love to have sendAnimation method, but I can't find one.

In Laravel I usually use facade **Telegram::sendMessage**
Here I'm not sure what type $bot variable is. I tried this:

```php
$telegram = new \Telegram\Bot\Api(config('telegram.bot_token'));
$telegram->sendAnimation([
    'chat_id' => $chatId,
    'animation' => new InputFile(storage_path('g.gif'))
]);
```

but it doesn't work. It doesn't throw an error either, but even if I use something random like **$telegram->sendSmthrandom** - it still doesn't throw an error.

Is your **$bot** variable was the object of **Telegram\Bot\Api** class? This class have tons of methods like sendAudio, sendLocation and so on, but no sendAnimation method

**Comment by roelofr** [comment]
Glad I could help.

In Laravel you don't need the `$bot` variable, you can just do `Telegram::sendAnimation`

**Comment by mravdel** [comment]
@roelofr 
`Telegram::sendAnimation` return false every time.
There is no sendAnimation method.
"false" being return from `__call`  method.

Did you try this method before? I have v2.0 of this **telegram-bot-sdk**

**Comment by roelofr** [comment]
Sorry for taking a while to get back to you.

I looked it up, and the `sendAnimation` command is supported since version `3.1.0` (it was added in ba1be2833fa6db8e55980288ae2e3e870a8d1c13). 

I'd recommend updating, version 2 doesn't receive feature updates anymore.

**Comment by sve-kai-itmo** [comment]
In addition to `sendAnimation`, the `sendVido` and `sendDoc` methods are suitable for sending GIFs.
