### ISSUE TITLE
How can i get user id from @userinfobot using @username of any user using API

### ISSUE THREAD

**Issue by AbdullahMateen** [irazasyed/telegram-bot-sdk#808]
Hi guys, i am having an issue to get telegram user id using his username. there are few scenarios that i want to know is that possible or not

1) if we have username of any user, can we get his/her user id from @userinfobot ?
2) can we receive messages from user using Bot ?
3) how to hide input field option from bot ?
4) how to add predefined buttons instead of input field ?
5) also, if a user add our bot can we programmatically press the join button for him ?

it will be great help if anyone can answers the questions.
Thank you.

**Comment by roelofr** [comment]
As the Telegram Bot SDK simply wraps around the [Telegram Bot API][1], you should look into that. For starters, bots cannot message bots and there is no API to get user information afaik.

[1]: https://core.telegram.org/bots/api

**Comment by roelofr** [comment]
> 1. if we have username of any user, can we get his/her user id from @userinfobot ?

As the Telegram Bot SDK simply wraps around the [Telegram Bot API][1], you should look into that. For starters, bots cannot message bots and there is no API to get user information afaik.

> 2. can we receive messages from user using Bot ?

Yes, given that the user knows your bot's handle. You can share a `https://tg.me/<bot username>` link to let
users message your bot easier.

> 3. how to hide input field option from bot ?

See [Reply Keyboard Markup][2].

> 4. how to add predefined buttons instead of input field ?

See [Reply Keyboard Markup][2].

> 5. also, if a user add our bot can we programmatically press the join button for him ?

A bot can only receive and send messages and suggest a keyboard. It cannot perform other actions
on the front-end UI. That'd be categorized as malware.

[1]: https://core.telegram.org/bots/api
[2]: https://telegram-bot-sdk.readme.io/docs/keyboards#reply-keyboard-markup
