### ISSUE TITLE
How send live location?

### ISSUE THREAD

**Issue by DenisKorablove** [irazasyed/telegram-bot-sdk#810]
How command?

**Comment by roelofr** [comment]
Sending a live location is supported since v3.0, and works in three parts:

1. Sending the initial location with a `live_period` (see [API docs][api-1] and [Telegram docs][tg-1])

   ```php
   $locationMsg = $bot->sendLocation([
       'chat_id' => $chat,
       'latitude' => $lat,
       'longitude' => $lng,
       'live_period' => 3600 // One hour
   ]);
   ```
3. Updating the location (not in API docs, see [Telegram docs][tg-2])

   ```php
   $bot->editMessageLiveLocation([
       'chat_id' => $chat,
       'message_id' => $locationMsg->messageId,
       'latitude' => $lat,
       'longitude' => $lng,
   ]);
4. (optionally) Ending the live location early  (not in API docs, see [Telegram docs][tg-3])

   ```php
   $bot->stopMessageLiveLocation([
       'chat_id' => $chat,
       'message_id' => $locationMsg->messageId
   ]);
   ```

[api-1]: https://irazasyed.github.io/telegram-bot-sdk/api/v2.0.0/Telegram/Bot/Api.html#method_sendLocation
[tg-1]: https://core.telegram.org/bots/api#sendlocation
[tg-2]: https://core.telegram.org/bots/api#editmessagelivelocation
[tg-3]: https://core.telegram.org/bots/api#stopmessagelivelocation

**Comment by DenisKorablove** [comment]
Tell me.
How to read the live location of the lat long position change sent by the user to the bot?

User -> sendLiveLocations -> Telegram bot -> how to read changes?

$this->update->getEditedMessage()

how to work this code?
