### ISSUE TITLE
Countdown timer

### ISSUE THREAD

**Issue by msadeghyan1996** [irazasyed/telegram-bot-sdk#812]
Hi.
i need show 60s countdown timer for user and if timer is 0 message delete or update.
i know how to update or delete message but i don't know how to create a countdown timer in a message of telegram.

thanks in advance

**Comment by msadeghyan1996** [comment]
i find solution.

```
      case 'accept_buy_gold':
        $message = $this->text."⏱ time : 10s‌";
        $this->edit_message($message);

        for ($i=9; $i>0; $i--) {
          sleep(2);
          $message = $this->text."⏱ $i";
          $this->edit_message($message);
        }
      break;
```

**Comment by roelofr** [comment]
Please close your issue if you've resolved the problem.

**Comment by msadeghyan1996** [comment]
@roelofr 
i resolved problem and but now i have a new problem.
when i start counter in for loop and user click to 'cancel' button in bot, my code not process user button input because for loop is not over.
any way for run loop in background?
