### ISSUE TITLE
setChatPhoto without uploading new photo in chat or group 

### ISSUE THREAD

**Issue by msadeghyan1996** [irazasyed/telegram-bot-sdk#815]
hi.
i use setChatPhoto buy any time i change group photo, telegram upload photo in group but i need setChatPhoto with file_unique_id for use that and not upload new photo in group.

```
$url = "https://api.telegram.org/bot".env('TELEGRAM_BOT_TOKEN')."/setChatPhoto";
$post_fields = [
    'chat_id'   => env('TELEGRAM_CHANNEL_ID'),
    'file_unique_id' => new \CURLFile(public_path($img))
];

$ch = curl_init(); 
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    "Content-Type:multipart/form-data"
));
curl_setopt($ch, CURLOPT_URL, $url); 
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
curl_setopt($ch, CURLOPT_POSTFIELDS, $post_fields); 
$result = curl_exec($ch);
curl_close($ch); 
```

![image](https://user-images.githubusercontent.com/47277114/100583046-71aacb80-32ff-11eb-98cc-3c2df1d5897d.png)

**Comment by qwertynik** [comment]
@msadeghyan1996 

Try changing the 'file_unique_id' to 'photo' in request params
