### ISSUE TITLE
How to upload files?

### ISSUE THREAD

**Issue by IServetnik** [irazasyed/telegram-bot-sdk#816]
You can get a file using Telegram::getFile();
And can you say how to upload it

**Comment by roelofr** [comment]
The SDK can take care of that for you.

```php
use Telegram\Bot\FileUpload\InputFile;

$file = InputFile::create('path-to-file.txt');
$bot->sendDocument([
    'chat_id' => $id,
    'document' => $file
]);
```

For more arguments of `sendDocument`, see the [API docs](https://irazasyed.github.io/telegram-bot-sdk/api/v2.0.0/Telegram/Bot/Api.html#method_sendDocument)

**Comment by IServetnik** [comment]
Thank you!
