### ISSUE TITLE
compatibility with :aravel 6.20.8

### ISSUE THREAD

**Issue by rubik360accounting** [irazasyed/telegram-bot-sdk#825]
![Capture](https://user-images.githubusercontent.com/69752114/103146475-8431ec80-4767-11eb-9112-c0c5c0b1d573.PNG)

**Comment by SergkeiM** [comment]
Hi @rubik360accounting I don't think this lib works with laravel ^6.0,

I managed to install it after manually adding `composer require guzzlehttp/guzzle ^6.3`

But no I have another error: `Call to undefined function Telegram\Bot\Commands\studly_case()`

**Comment by rubik360accounting** [comment]
Hi dear  Melingk and thank you for sharing your experience. The package has
problem with Laravel 6. I install development version also but working. at
last because I stared new project and it is easy for me to work with
Laravel 8 and the package work fine. thanks

**Comment by roelofr** [comment]
Switch to v3, it supports 5.8 - 8.0
