### ISSUE TITLE
Laravel 8.16.1

### ISSUE THREAD

**Issue by ds-ivanenko** [irazasyed/telegram-bot-sdk#827]
Hi. 
I have a problem installing this package on Laravel 8.16.1
I run the installation with this command `composer require irazasyed / telegram-bot-sdk ^ 3.2`
Since it is said that version 3.2 added support for Laravel 8 (`https://github.com/irazasyed/telegram-bot-sdk/releases/tag/v3.2.0`).
But during the installation, I get the following error:
http://joxi.ru/Q2K6WK9TvqNpYm

Could you help me sort out this problem?
Thanks!

**Comment by Spillo17** [comment]
@ds-ivanenko can be helpful for you as well I think https://github.com/telegram-bot-sdk/telegram-bot-sdk and https://github.com/telegram-bot-sdk/laravel-starter

Just add this on your composer.json in the require section and call : composer update

"telegram-bot-sdk/laravel": "^4.0@dev",
 "telegram-bot-sdk/telegram-bot-sdk": "^4.0@dev"

**Comment by Spillo17** [comment]
By the way, I tried this solution but the error is still there.... It's quite strange, I've tried to create a new fresh Laravel project (v.8) and it works... so the problem is not solved...

**Comment by foremtehan** [comment]
@Spillo17 can you explain what is different between those two package you mentioned Vs this repo ? which one is better

**Comment by Spillo17** [comment]
You can forgot the other... It was a test when this doesn't work, but I found that with a new fresh Laravel project it works also this package.

**Comment by ds-ivanenko** [comment]
@Spillo17 The problem is only in Laravel 8.16.1 version, did I get it right?

**Comment by Spillo17** [comment]
> @Spillo17 The problem is only in Laravel 8.16.1 version, did I get it right?

@ds-ivanenko No... I didn't found how... when is a fresh install (also v. 8.16.1) it works well

**Comment by ds-ivanenko** [comment]
Thanks for answers. Most likely the problem is in my code somewhere .
