### ISSUE TITLE
sendMediaGroup

### ISSUE THREAD

**Issue by marnelle1** [irazasyed/telegram-bot-sdk#828]
Hello! How can I use this method? 
$telegram->sendMediaGroup
Could you please provide an example?

**Comment by foremtehan** [comment]
It's not working on this repo you should make your own.

**Comment by MyZik** [comment]
@foremtehan I think  it's wrong :)
https://github.com/irazasyed/telegram-bot-sdk/blob/develop/src/Methods/Message.php#L430

**Comment by foremtehan** [comment]
@MyZik it have the method but it's not working did you test it ?

**Comment by YSRoot** [comment]
https://github.com/irazasyed/telegram-bot-sdk/pull/1014
fix that method in my PR
