### ISSUE TITLE
webhook issue

### ISSUE THREAD

**Issue by moein-rahimi** [irazasyed/telegram-bot-sdk#83]
hi
i'm using the standalone without laravel.
I have a page called notifer.php this is where my webhook is set to.
I have this code in it : 
require 'vendor/autoload.php';

use Telegram\Bot\Api;
$telegram = new Api('token');

$updates = $telegram->getWebhookUpdates();

var_dump($updates) ;

when i visit notifer.php in browser it returns this : object(Telegram\Bot\Objects\Update)#18 (1) { ["items":protected]=> array(0) { } }

**Comment by ihoru** [comment]
And what do you want to see there?
Telegram Bot API should call this url.
But first you have to setWebhook and pass there your URL.

**Comment by moein-rahimi** [comment]
yeah i set webhook already : https://api.telegram.org/bot<token>/setWebhook?url=https://sheltered-fortress-5013.herokuapp.com/notifier.php

**Comment by ihoru** [comment]
Then, you should send something to your bot, and this URL will be called by Telegram.
Tip: Best practices is to set secure url with unique string (for example your bot's API code)

**Comment by moein-rahimi** [comment]
ok then how to manipulate the response? how to get the chat id that telegram send to the webhook url

**Comment by ihoru** [comment]
You should manipulate with update object. More info about its structure here: https://core.telegram.org/bots/api#update

**Comment by moein-rahimi** [comment]
by update object you mean getupdate function ?

**Comment by ihoru** [comment]
No. The result of calling getWebhookUpdates

**Comment by irazasyed** [comment]
@moein-rahimi You need to refer the documentation of this library.
