### ISSUE TITLE
Not support guzzle 7+

### ISSUE THREAD

**Issue by mccarlosen** [irazasyed/telegram-bot-sdk#833]
![image](https://user-images.githubusercontent.com/8524361/104827756-5c4a1c00-582f-11eb-94db-cd84d1b86fdf.png)

I am using Laravel 8...

**Comment by zhuchunshu** [comment]
I also encountered the same problem

**Comment by viacheslavoleshko** [comment]
Use actual version 3.4 `composer require irazasyed/telegram-bot-sdk` without version

**Comment by Britaniik** [comment]
@EvoLion thanks.It helps me

**Comment by VladSavitsky** [comment]
The same problem. PHP 7.4, Laravel 8.27. Solution:
`composer require irazasyed/telegram-bot-sdk`
Please update documentation at https://telegram-bot-sdk.readme.io/docs
