### ISSUE TITLE
Not Working w/ Lumen

### ISSUE THREAD

**Issue by ItsJoeTurner** [irazasyed/telegram-bot-sdk#835]
I'm struggling to get this working with Lumen, using the latest version and ^3.4 of this SDK. 

When calling: 

`php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider"`

I get the following message: 

`Unable to locate publishable resources.`

**Comment by xdloc** [comment]
Lumen can't publish something. You need to add provider **manually**.
