### ISSUE TITLE
how to handle inline buttons response ? 

### ISSUE THREAD

**Issue by saeidtahan** [irazasyed/telegram-bot-sdk#845]
all bot commands automatically handled , except inline bot commands. 
this is my router that get telegram responses 
`			$update = Telegram::commandsHandler(true);
`

but i could not handle inline button commands .
this is my start handle function : 

      $keyboard = Keyboard::make()
                          ->inline()
                          ->row(
	                          Keyboard::inlineButton(['text' => 'x', 'callback_data' => 'accepttos']),
	                          // Keyboard::inlineButton(['text' => 'Btn 2', 'callback_data' => 'data_from_btn2'])
                      );
    
      $response = \Telegram::sendMessage([
                'chat_id' => $this->update->message->from->id, 
                'text' => $tos->tostext, 
                'reply_markup' => $keyboard
              ]);

i'm using laravel

**Comment by Kutalia** [comment]
Try out code [from this post](https://github.com/irazasyed/telegram-bot-sdk/issues/860)
