### ISSUE TITLE
What`s wrong with setWebhook method?

### ISSUE THREAD

**Issue by Iossarian** [irazasyed/telegram-bot-sdk#846]
I`m trying to set webhook at my url, but setWebhook method answer is "ErrorException: Undefined index: result in file /.../vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php on line 182". It means there is no data in response.

**Comment by shmuel-livshits** [comment]
I got the same issue. Did you get an answer?

**Comment by ob-tk** [comment]
Same issue.

**Comment by LordVersA** [comment]
same issue

**Comment by alies-dev** [comment]
@LordVersA 
@Iossarian

 - What package version do you use?
 - Can you please provide a code snippet to test it?
 - Can you please provide a body of telegram response?
