### ISSUE TITLE
Receiving messages (not commands)

### ISSUE THREAD

**Issue by danilchican** [irazasyed/telegram-bot-sdk#847]
Hi everyone!
I would like to receive and process messages instead of commands. 
How to do that? 
Because in docs I found information about adding commands.
But where I need to define hanlder for messages?

**Comment by jpgnz** [comment]
@danilchican take a look at the example from the Awesome Bots repo: https://github.com/hamzaali00001/Cryptocurrency-Telegram-Bot-Laravel/blob/master/app/Http/Controllers/TelegramController.php

Provided your bot is setup to receive all messages from a group for example you could manage it this way.
