### ISSUE TITLE
Laravel 8 Guzzle confilicts

### ISSUE THREAD

**Issue by realtebo** [irazasyed/telegram-bot-sdk#850]
When requiring package, i got 

```
 Problem 1
    - Root composer.json requires irazasyed/telegram-bot-sdk 2.0 -> satisfiable by irazasyed/telegram-bot-sdk[v2.0.0].
    - irazasyed/telegram-bot-sdk v2.0.0 requires guzzlehttp/guzzle ~6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

**Comment by L34T** [comment]
@realtebo 

1. `php artisan config:clear`
//del `./bootstrap/cache/*` if you'll got error
2. set `TELEGRAM_BOT_TOKEN` in .env
3. `composer require irazasyed/telegram-bot-sdk ^3.4.1`

ps publish conf file with
`php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider"`

**Comment by realtebo** [comment]
I will try thanks. But It was a new project, there was nothing into cache folder at that moment.

I'll try

**Comment by alexp-ka** [comment]
@L34T 

thanks, it worked for me

**Comment by pr4gmat1q** [comment]
Laravel 8.52.0

Problem
```
 Problem 1
    - Root composer.json requires irazasyed/telegram-bot-sdk ^3.4.1 -> satisfiable by irazasyed/telegram-bot-sdk[v3.4.1].
    - irazasyed/telegram-bot-sdk v3.4.1 requires guzzlehttp/psr7 ^1.3 -> found guzzlehttp/psr7[1.3.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

```
Solution 
```
composer require guzzlehttp/psr7 1.*
composer require irazasyed/telegram-bot-sdk ^3.4.1
```

**Comment by RhysLees** [comment]
> @realtebo
> 
> 1. `php artisan config:clear`
>    //del `./bootstrap/cache/*` if you'll got error
> 2. set `TELEGRAM_BOT_TOKEN` in .env
> 3. `composer require irazasyed/telegram-bot-sdk ^3.4.1`
> 
> ps publish conf file with
> `php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider"`

Needs to be updated on the docs as it still says ^2.0

**Comment by Sodiqmirzo** [comment]
> composer require irazasyed/telegram-bot-sdk ^3.4.1

thanks you bro. it's working))

**Comment by chienle** [comment]
> Laravel 8.52.0
> 
> Problem
> 
> ```
>  Problem 1
>     - Root composer.json requires irazasyed/telegram-bot-sdk ^3.4.1 -> satisfiable by irazasyed/telegram-bot-sdk[v3.4.1].
>     - irazasyed/telegram-bot-sdk v3.4.1 requires guzzlehttp/psr7 ^1.3 -> found guzzlehttp/psr7[1.3.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> ```
> 
> Solution
> 
> ```
> composer require guzzlehttp/psr7 1.*
> composer require irazasyed/telegram-bot-sdk ^3.4.1
> ```

It's working well, thank bro!

**Comment by imteajsajid12** [comment]
thanks its working

**Comment by ab11bkr** [comment]
> Laravel 8.52.0
> 
> Problem
> 
> ```
>  Problem 1
>     - Root composer.json requires irazasyed/telegram-bot-sdk ^3.4.1 -> satisfiable by irazasyed/telegram-bot-sdk[v3.4.1].
>     - irazasyed/telegram-bot-sdk v3.4.1 requires guzzlehttp/psr7 ^1.3 -> found guzzlehttp/psr7[1.3.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> ```
> 
> Solution
> 
> ```
> composer require guzzlehttp/psr7 1.*
> composer require irazasyed/telegram-bot-sdk ^3.4.1
> ```

Hi, I'm having the same issue and I've tried both solutions and they don't work. When I run `composer require guzzlehttp/psr7 1.*` It says 'zsh: no matches found: 1.*'

And the other solution by clearing the config doesn't work either. Anyone able to help me out? Thanks in advance :)

**Comment by RhysLees** [comment]
> > Laravel 8.52.0
> > Problem
> > ```
> >  Problem 1
> >     - Root composer.json requires irazasyed/telegram-bot-sdk ^3.4.1 -> satisfiable by irazasyed/telegram-bot-sdk[v3.4.1].
> >     - irazasyed/telegram-bot-sdk v3.4.1 requires guzzlehttp/psr7 ^1.3 -> found guzzlehttp/psr7[1.3.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
> > 
> > Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Solution
> > ```
> > composer require guzzlehttp/psr7 1.*
> > composer require irazasyed/telegram-bot-sdk ^3.4.1
> > ```
> 
> Hi, I'm having the same issue and I've tried both solutions and they don't work. When I run `composer require guzzlehttp/psr7 1.*` It says 'zsh: no matches found: 1.*'
> 
> And the other solution by clearing the config doesn't work either. Anyone able to help me out? Thanks in advance :)

Add this to your composer.json "require": 

```
"irazasyed/telegram-bot-sdk": "^3.4.1",
"guzzlehttp/psr7": "^1.3",
```

then run `composer update`

**Comment by ab11bkr** [comment]
Thank you very much, this worked perfectly.

**Comment by sukhrobnurali** [comment]
> Laravel 8.52.0
> 
> Problem
> 
> ```
>  Problem 1
>     - Root composer.json requires irazasyed/telegram-bot-sdk ^3.4.1 -> satisfiable by irazasyed/telegram-bot-sdk[v3.4.1].
>     - irazasyed/telegram-bot-sdk v3.4.1 requires guzzlehttp/psr7 ^1.3 -> found guzzlehttp/psr7[1.3.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> ```
> 
> Solution
> 
> ```
> composer require guzzlehttp/psr7 1.*
> composer require irazasyed/telegram-bot-sdk ^3.4.1
> ```

it worked!! thanks

**Comment by dimaodnokoz** [comment]
As mensioned in separate thread it is better to use the most actual version of sdk (documentation is not updated actually) by command without version:

composer require irazasyed/telegram-bot-sdk

**Comment by demix506** [comment]
> php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider"

Thank you, that helped.
