### ISSUE TITLE
V3 documentation

### ISSUE THREAD

**Issue by mamprogr** [irazasyed/telegram-bot-sdk#855]
I found the documentation for version 2 here: https://telegram-bot-sdk.readme.io/docs

Where can I find the documentation for version 3?

**Comment by ilyastuit** [comment]
same problem

**Comment by Xibel** [comment]
There is none. We were working on v4 documentation but it is not finished yet.

**Comment by DevRaeph** [comment]
Any new updates yet? :)

**Comment by ypylypenko** [comment]
I am ready to help with the documentation. Please tell me where to contribute

**Comment by DevRaeph** [comment]
You can make a pull request, maybe the maintainer see it :)

**Comment by ypylypenko** [comment]
> You can make a pull request, maybe the maintainer see it :)

unfortunately the documentation is not stored in current repository

**Comment by DevRaeph** [comment]
hmm... and if you create an unofficial documentation? maybe better than nothing ^^
