### ISSUE TITLE
[Question] Support Callbacks system

### ISSUE THREAD

**Issue by maffinca69** [irazasyed/telegram-bot-sdk#860]
Hi! You planned adding support callback? At this moment we have good command system, maybe create callback system  by analogy with command system? 
Example: callback_data (request, value) => name of callback class. This example have problems - url instead of callback_data and etc. BUT. Maybe have solutions?

If this is impossible or you haven't  planning added support callback, have good solutions? Below my code (temporary solution), which working in this moment, but he far from ideal and require refactoring. Thanks you
```php
// ...
if ($update->isType('callback_query')) {
     $this->handleCallback($update, $telegram);
     return;
}
// ...

/**
* @param Update $update
* @param Api $telegram
*/
private function handleCallback(Update $update, Api $telegram)
{
    $data = $update->callbackQuery->data;
    switch ($data) {
        case 'request':
            $telegram->triggerCommand('start', $update);
            break;
        case 'select':
            $telegram->triggerCommand('select', $update);
            break;
        case 'logout':
            $this->logout($telegram, $update->callbackQuery->from->id);
            break;
        default: // select month
            $telegram->triggerCommand($data, $update);
    }
}
```

**Comment by Kutalia** [comment]
If you'd like arguments support you can add the following code in your command's `handle()` method:
```
$update = $shouldUseWebhook ? $this->telegram->getWebhookUpdate() : $this->getUpdate();
$callbackData = $update->callbackQuery->data;

$args = str_replace("/{$this->name} ", '', $callbackData);
$args = explode(' ', $args);
$args = $args ?: $this->getArguments();
```

**Comment by maffinca69** [comment]
No, that se so bad...
I would like to full callback-system. All current solutions are not stable

**Comment by lamtranb** [comment]
Hi @maffinca69 
I have a question, which file should I put your code into it to make it work ? 
Example: 
I have ABC command, in this command I create 1 button with callback_data. How can I handle it with your solution?
