### ISSUE TITLE
  Argument 1 passed to Telegram\Bot\BotsManager::__construct() must be of the type array, null given, called in /Users/techarea/Documents/project/laravel-admin/vendor/irazasyed/telegram-bot-sdk/src/Laravel/TelegramServiceProvider.php on line 5

### ISSUE THREAD

**Issue by jagoanmamah** [irazasyed/telegram-bot-sdk#865]
use Laravel 8, and fresh install

<img width="937" alt="Screen Shot 2021-05-26 at 09 57 35" src="https://user-images.githubusercontent.com/25195185/119596169-e0796500-be08-11eb-9af9-2248ff3ee594.png">

**Comment by ds-ivanenko** [comment]
Hi
I have the same problem. I tried to install it in different ways. Also, tried the solution from this comment. https://github.com/irazasyed/telegram-bot-sdk/issues/754 But nothing helps. Why do I keep getting an error while installing this package?
Laravel Framework 8.43.0

**Comment by butschster** [comment]
Try to use `php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider"` command

**Comment by ds-ivanenko** [comment]
> Try to use `php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider"` command

Thank you. That helped. But not at once. I ran this command 3 times and after the last time it worked.

**Comment by codenashwan** [comment]
I have the same problem on Laravel Framework v8

![image](https://user-images.githubusercontent.com/35005761/120912056-c0f9fc00-c694-11eb-8516-5c90ac2e8189.png)

**Comment by lrmaldo** [comment]
Debe borrar su caché de configuración manualmente eliminándolo en bootstrap / cache / config.php ¡
Entonces todo funcionará!

**Comment by AhmedNabil-hub** [comment]
You need to add TELEGRAM_TOKEN="your-bot-api-token" in your .env file then run the installation command
