### ISSUE TITLE
Upload File with name containing cyrillic symbols

### ISSUE THREAD

**Issue by Min-An-Nhuien** [irazasyed/telegram-bot-sdk#872]
When I try to send file with cyrillic symbols in its name (thus, URL also contains cyrillic symbols, utf-8 encoded), I receive error "Bad Request: failed to get HTTP URL content", but there is no problem with sending files with latin names.

If I use urlencode, user will receive a file, but with urlencoded name, not with the original one. What can I do to send file with its original name that contains not latin symbols?

**Comment by HuanYangzz** [comment]
Hi i have similar issue when sending Chinese Character file name..
the file name is 招聘启事.pdf..

By using sendDocument function, it able to send out, but the file name will rename to "pdf" (without .pdf extension)
receiver are unable to open the document...
