### ISSUE TITLE
triggerCommand with input parameter

### ISSUE THREAD

**Issue by ziZily** [irazasyed/telegram-bot-sdk#878]
trigger command with argument dont work for me,I'm trying run an command from another command but when i add argument to triggerCommand It does not work,Where is my mistake?

class ChangeLanguageCommand extends Command
{
    /**
     * @var string Command Name
     */
    protected $name = 'change_language';

    /**
     * @var string Command Description
     */
    protected $description = 'Change Language,Change language of bot';

    protected $pattern = '{lang}';
    /**
     * {@inheritdoc}
     */
    public function handle()
    {
        if($this->getArguments())
        {
            $args = $this->getArguments();
            if($args['lang'])
                $lang=$args['lang'];
            else
                $lang='fa';
        }
        else
            $lang='fa';

        if($lang=='fa')
        {
            $response=$this->replyWithMessage(['text' => 'زبان ربات تغییر یافت.']);
            $this->triggerCommand('start','fa');

        }
        else
        {
            $response=$this->replyWithMessage(['text' => 'Robot language changed.']);
            $this->triggerCommand('start','en');
        }

    }
}

**Comment by ziZily** [comment]
@irazasyed

**Comment by Chouchen** [comment]
In a command, `triggerCommand` takes only 1 parameter, so it should be `$this->triggerCommand('start en');` for example.

**Comment by ojpro** [comment]
I am having the same issue, I wanna pass data when triggering a command.
any ideas?

**Comment by ojpro** [comment]
> I am having the same issue, I wanna pass data when triggering a command. any ideas?

I have figured out a solution that worked for me (so far):
```php
Telegram::triggerCommand(TargetCommand::handlTarget($value), $this->getUpdate());
```
