### ISSUE TITLE
need to help about triggerCommand(*Emergency)

### ISSUE THREAD

**Issue by ziZily** [irazasyed/telegram-bot-sdk#880]
problem with triggerCommand, this command still dont work for me, i try to run a command from controller but  this comand dont work for me, i use telegram-bot-sdk version 2.
 public function commandHandlerWebHook()
    {
        try{
            $commandsHandler=Telegram::commandsHandler(true);
            $update =Telegram::getWebhookUpdate(['timeout' => 120]);
            if ($update->isType('callback_query')) {
                $data  =$update->callbackQuery->data;
                $chatID =$update->callbackQuery->from->id;
                switch ($data) {
                    case '/change_language_fa':
                        Telegram::triggerCommand(StartCommand::class,'en');
                        Telegram::sendMessage(['chat_id' =>$chatID,'text' => 'Robot language changed.']);
                        break;
                    case '/change_language_en':
                        Telegram::triggerCommand(StartCommand::class,'fa');
                        Telegram::sendMessage(['chat_id' =>$chatID,'text' => 'زبان ربات تغییر یافت.']);
                        break;
                    case '/help':
                        Telegram::triggerCommand(HelpCommand::class);
                        break;
                }
            }
            return 'Ok';
        }catch (\Exception $e)
        {
            dd($e->getMessage());
        }

    }

**Comment by ziZily** [comment]
@irazasyed

**Comment by ziZily** [comment]
@TDarkCoder

**Comment by ziZily** [comment]
@jonnywilliamson

**Comment by ziZily** [comment]
@cjmaximal

**Comment by kklysenko** [comment]
@ziZily  Hello! You should use the command name, not the Class name
Here is an example:
```php
Telegram::triggerCommand('change_language_fa', $update);
```
