### ISSUE TITLE
How to get user location and phone number by inline button?

### ISSUE THREAD

**Issue by ziZily** [irazasyed/telegram-bot-sdk#882]
It seams inlineButton cant return user phone, do you have any solution؟

            $keyboard = Keyboard::make()
                ->inline()
                ->row(
                    Keyboard::inlineButton(['text' => 'Improve Your Account', 'callback_data' => '/improve_user_en','request_contact' => true]),
                    Keyboard::inlineButton(['text' => 'Change Language', 'callback_data' => '/change_language_en']),
                    Keyboard::inlineButton(['text' => 'Help', 'callback_data' => '/help']),
                );

            $response=$this->replyWithMessage(['text' => 'Hello, welcome to the robot of Ukelc; can I help you?', 'reply_markup' => $keyboard]);

**Comment by Omyshev** [comment]
In Telegram bot it is impossible to get a location or a phone with inline buttons, this can only be obtained on a standard keyboard
[Reply Keyboard Markup](https://core.telegram.org/bots/api#replykeyboardmarkup);

**KeyboardButton**
- text
- request_contact
- request_location
- request_poll


**InlineKeyboardButton:**
- text
- url
- login_url
- callback_data
- switch_inline_query
- switch_inline_query_current_chat
- callback_game
- pay

**Comment by ziZily** [comment]
Thank you for your answer, dear @Omyshev
