### ISSUE TITLE
installation error in last laravel version 

### ISSUE THREAD

**Issue by metif12** [irazasyed/telegram-bot-sdk#887]
Problem 1
    - irazasyed/telegram-bot-sdk[v2.0.0, ..., v2.3.0] require guzzlehttp/guzzle ~6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - Root composer.json requires irazasyed/telegram-bot-sdk ^2.0 -> satisfiable by irazasyed/telegram-bot-sdk[v2.0.0, ..., v2.3.0].

"laravel/framework": "^8.54",

**Comment by RhysLees** [comment]
Update your composer file to include this in the "require" section then run composer update.
```json
"irazasyed/telegram-bot-sdk": "^3.4.1",
``` 

This fixed it for me.

**Comment by metif12** [comment]
> Update your composer file to include this in the "require" section then run composer update.
> 
> ```json
> "irazasyed/telegram-bot-sdk": "^3.4.1",
> ```
> 
> This fixed it for me.

thanks. that fixed it for me too. would you mind update installation guide at https://telegram-bot-sdk.readme.io/docs ?!

**Comment by RhysLees** [comment]
> > Update your composer file to include this in the "require" section then run composer update.
> > ```json
> > "irazasyed/telegram-bot-sdk": "^3.4.1",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This fixed it for me.
> 
> thanks. that fixed it for me too. would you mind update installation guide at https://telegram-bot-sdk.readme.io/docs ?!

The docs haven't been updated, I'm waiting for the same thing, I would make a PR but I dno if there is a git repo for it

**Comment by RhysLees** [comment]
> > > Update your composer file to include this in the "require" section then run composer update.
> > > ```json
> > > "irazasyed/telegram-bot-sdk": "^3.4.1",
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This fixed it for me.
> > 
> > 
> > thanks. that fixed it for me too. would you mind update installation guide at https://telegram-bot-sdk.readme.io/docs ?!
> 
> The docs haven't been updated, I'm waiting for the same thing, I would make a PR but I dno if there is a git repo for it

Just seen in another issue that mentioned the v4.0 docs site is being worked on

**Comment by ynaderi1959** [comment]
```json
"irazasyed/telegram-bot-sdk": "^3.5",
```
