### ISSUE TITLE
Laravel 8.6.2 support

### ISSUE THREAD

**Issue by degorych** [irazasyed/telegram-bot-sdk#888]
Please add support for Laravel 8.6.2. Now installing plagin is impossibe. 
`irazasyed/telegram-bot-sdk v3.4.1 requires guzzlehttp/psr7 ^1.3 -> found guzzlehttp/psr7[1.3.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.`

**Comment by shaikhfoysal** [comment]
composer require guzzlehttp/psr7 1.*

composer require irazasyed/telegram-bot-sdk ^3.4.1
