### ISSUE TITLE
Sending Messages To Users ( Not a Channel ) via PHP

### ISSUE THREAD

**Issue by marcoczen** [irazasyed/telegram-bot-sdk#889]
Hi, 

I am wondering whether your software allow sending of  messages ( reminders ) to telegram users ( not a telegram channel or telegram group ) from a php application  where the users mobile numbers are already available ? 

I am confused because you used the term creating a 'bot'.

Right now, my app has the ability to send email reminders to users via pphmailer. So i am 
looking for a telegram equivalent.

Thanks.

**Comment by marechenok** [comment]
Use built in Laravel Notifications.
Just append https://github.com/laravel-notification-channels/telegram
