### ISSUE TITLE
does not send a picture

### ISSUE THREAD

**Issue by BuinovskiyAndrei** [irazasyed/telegram-bot-sdk#899]
I'm trying to send a picture from a remote server, but it's not being sent. I get either a BAD REQUEST or nothing happens at all, but if I try to make a request directly to the telegram api, then everything works. what is the reason.  
![image](https://user-images.githubusercontent.com/28735873/138068077-749474a8-f089-4655-b3dd-115eeb39fd73.png)
![image](https://user-images.githubusercontent.com/28735873/138068142-4f76c153-44dd-4716-8f07-494ee574ea7c.png)

**Comment by marechenok** [comment]
```php
if ($item->icon) {
    $this->replyWithChatAction(['action' => Actions::UPLOAD_PHOTO]);
    $file = InputFile::create(
        asset($item->getIconPath()),
        'logo.png'
    );
    $this->replyWithPhoto(['photo' => $file, 'type' => 'photo']);
}
```

where $this -- Command in my case
