### ISSUE TITLE
Unable to create custom commands

### ISSUE THREAD

**Issue by Forsakenrox** [irazasyed/telegram-bot-sdk#900]
i just write my own custom command folloving by steps in docs, and i get this error:

**Declaration of App\Telegram\Commands\TestCommand::handle($arguments) must be compatible with Telegram\Bot\Commands\Command::handle()**

It strange becouse i extend the same Command::class what and default HelpCommand.

**Comment by Xibel** [comment]
Show us your complete HelpCommand. There shouldn't be any $arguments with handle(). Your private function should look like: public function handle()

**Comment by irazasyed** [comment]
Command `handle()` method can't have arguments. Make sure you're using develop branch aka v3.

**Comment by Forsakenrox** [comment]
> Show us your complete HelpCommand. There shouldn't be any $arguments with handle(). Your private function should look like: public function handle()

Thanks for reply. I already figure out with this. Problem is in example in official documentation because in they $arguments is present in handle() method.
