### ISSUE TITLE
With  async_requests = true command telegram:webhook --setup return error

### ISSUE THREAD

**Issue by vetus-koneko** [irazasyed/telegram-bot-sdk#910]
Hello!

Error happened when i m setup param `async_requests = true` globally in `telegram.php` and try run `php artisan telegram:webhook --setup`

![image](https://user-images.githubusercontent.com/32628786/144455665-d3980c4c-c578-4e82-8a22-19a20731bc5e.png)

Ty for ur package!

**Comment by riettotek** [comment]
same for me too.
Moreover, handlecommandshandler() method doesnt works when u have async set to true. It come back with 500 error status code. Anyway i think the error is dude to the same issue.
