### ISSUE TITLE
phpDoc for Telegram facade

### ISSUE THREAD

**Issue by Nurzzzone** [irazasyed/telegram-bot-sdk#912]
could you plz add phpDocs for autocomplition for Telegram facade in laravel

**Comment by the-alex-mark** [comment]
Воспользуйся пакетом "[ide-helper](https://github.com/barryvdh/laravel-ide-helper)".

**Comment by new-user-name** [comment]
> Воспользуйся пакетом "[ide-helper](https://github.com/barryvdh/laravel-ide-helper)".

It marks many classes as "double", https://github.com/barryvdh/laravel-ide-helper/issues/592,
so I wanted to remove "method not found" from Telegram::sendMessage, it's still not found, and plenty other warnings poped up...

**Comment by alies-dev** [comment]
to avoid this issue, you can use DI and inject `BotsManager` class and then use
```php
$bot = $botManager->bot()
$bot->sendMessage([...]);
```

`Telegram` facade proxies too much methods, for this reason it's difficult to maintain such PHPDoc. But `BotsManager` methods are already added as PHPDoc: https://github.com/irazasyed/telegram-bot-sdk/blob/9466c47b6b1aba8c60010b4f281494469cdd1245/src/Laravel/Facades/Telegram.php#L11-L14
