### ISSUE TITLE
editMessage

### ISSUE THREAD

**Issue by glebkhil** [irazasyed/telegram-bot-sdk#913]
how can i editMessage? can you give sample?

**Comment by marechenok** [comment]
Most often I have to do this during callback processing. Then I use something like this:

```php
use Telegram\Bot\Objects\Update;
class CallbackHandler {
  public static function handle(Update $update){
          $message = $update->getMessage();
          $chat = $message->get('chat');
          Telegram::editMessageText([
                      'chat_id'   => $chat->get('id'),
                      'message_id'    =>  $message->get('message_id'),
                      'text'  =>  "updated text",
                  ]);
  }
}
```

**Comment by asteriskDevelop** [comment]
Next Telegram\Bot\Exceptions\TelegramResponseException: Bad Request: message text is empty in /var/www/admin/data/www/.site/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php:67
Stack trace:
#0 /var/www/admin/data/www/.site/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(101): Telegram\Bot\Exceptions\TelegramResponseException::create(Object(Telegram\Bot\TelegramResponse))
#1 /var/www/admin/data/www/.site/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(82): Telegram\Bot\TelegramResponse->makeException()
#2 /var/www/admin/data/www/.site/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(52): Telegram\Bot\TelegramResponse->decodeBody()
#3 /var/www/admin/data/www/.site/vendor/irazasyed/telegram-bot-sdk/src/TelegramClient.php(130): Telegram\Bot\TelegramResponse->__construct(Object(Telegram\Bot\TelegramRequest), Object(GuzzleHttp\Psr7\Response))
#4 /var/www/admin/data/www/.site/vendor/irazasyed/telegram-bot-sdk/src/TelegramClient.php(82): Telegram\Bot\TelegramClient->getResponse(Object(Telegram\Bot\TelegramRequest), Object(GuzzleHttp\Psr7\Response))
#5 /var/www/admin/data/www/.site/vendor/irazasyed/telegram-bot-sdk/src/Traits/Http.php(305): Telegram\Bot\TelegramClient->sendRequest(Object(Telegram\Bot\TelegramRequest))
#6 /var/www/admin/data/www/.site/vendor/irazasyed/telegram-bot-sdk/src/Traits/Http.php(198): Telegram\Bot\Api->sendRequest('POST', 'editMessageText', Array)
#7 /var/www/admin/data/www/.site/vendor/irazasyed/telegram-bot-sdk/src/Methods/EditMessage.php(52): Telegram\Bot\Api->post('editMessageText', Array)
#8 /var/www/admin/data/www/.site/bot.php(205): Telegram\Bot\Api->editMessageText(Array)
#9 {main}
  thrown in /var/www/admin/data/www/.site/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php on line 67

**Comment by SoulNaturalist** [comment]
@MaxMCP your text is empty, give code
