### ISSUE TITLE
Поддержка/Обновления/Релиз

### ISSUE THREAD

**Issue by the-alex-mark** [irazasyed/telegram-bot-sdk#915]
Подскажите пожалуйста, поддерживается ли ещё данный проект.
Стоит ли ждать релиза версии 3?

**Comment by CrazyBoy49z** [comment]
Релиз уже давно есть

 "irazasyed/telegram-bot-sdk": "^3.4",
 
 Может перепутал с 4 версией она в разработке

**Comment by the-alex-mark** [comment]
@CrazyBoy49z Версия 3 находится в ветке `develop`, подписана как `pre-release` и на сайте с документацией последняя стабильная версия указана 2.
Поэтому и интересуюсь, когда ждать 3 версию.

**Comment by CrazyBoy49z** [comment]
> @CrazyBoy49z Версия 3 находится в ветке `develop`, подписана как `pre-release` и на сайте с документацией последняя стабильная версия указана 2. Поэтому и интересуюсь, когда ждать 3 версию.

Уже около 1.5 года работаю на ветке 3. Проблем нет, потому и не скажу что `develop`
![image](https://user-images.githubusercontent.com/3448603/152678516-1214adc9-1cb2-44e9-b6ed-c5c5faffc3c4.png)


Сейчас есть 4 версия она только в разработке https://github.com/telegram-bot-sdk/telegram-bot-sdk/projects/1

А с документацией есть некоторые проблемы вот например https://telegrambotsdk.com/docs/upgrade3-4/. Так как не очень обновляется. Проще в исходниках покопаться, ну или найти ишью которое решит твой вопрос
