### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by decadence** [irazasyed/telegram-bot-sdk#923]
Can you please tag version with Laravel 9 support?
As I see [this](https://github.com/irazasyed/telegram-bot-sdk/commit/95d41acf496b95e3728dd3969721465391373182) commit has necessary changes.

**Comment by irazasyed** [comment]
Done. Released `3.5`.

Although it's not tested well, please feel free to create a new issue. Thanks.

**Comment by decadence** [comment]
@irazasyed thanks!
