### ISSUE TITLE
[Error] Alias [listcommands] conflicts with another command's alias list:

### ISSUE THREAD

**Issue by ghost** [irazasyed/telegram-bot-sdk#931]
[Error] Alias [listcommands] conflicts with another command's alias list: "Telegram\Bo
t\Commands\HelpCommand", try with another name or remove this alias from the list.

Telegram::bot($botname);

**Comment by ghost** [comment]
v3.5

**Comment by ghost** [comment]
'commands'            => [],

**Comment by andrey-helldar** [comment]
@SeibelStan, just delete the [Telegram\Bot\Commands\HelpCommand::class](https://github.com/irazasyed/telegram-bot-sdk/blob/develop/src/Laravel/config/telegram.php#L119) from `config/telegram.php` and clear cache config: `php artisan config:clear`, if you use the Laravel.
