### ISSUE TITLE
Start Command doesn't work

### ISSUE THREAD

**Issue by HenriqueValente09** [irazasyed/telegram-bot-sdk#939]
Method 'Vendor VApp\Commands \StartCommand: : handle () is not compatible with method
"Telegram\Bot \ Commands\ Command : :handle()". intelephense(1038)

please, can someone help me? I'm following this guide https://telegram-bot-sdk.readme.io/docs/commands-system#writing-commands but it shows this error above

**Comment by Chouchen** [comment]
The documentation is misleading. `handle()` shouldn't have any parameters.
