### ISSUE TITLE
Fatal error: Uncaught Telegram\Bot\Exceptions\TelegramOtherException: Unauthorized

### ISSUE THREAD

**Issue by duquesimba** [irazasyed/telegram-bot-sdk#940]
Fatal error: Uncaught Telegram\Bot\Exceptions\TelegramOtherException: Unauthorized in /home/xxxxxxx/public_html/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php:58 Stack trace: #0 /home/xxxxxxxxx/public_html/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(174): Telegram\Bot\Exceptions\TelegramResponseException::create(Object(Telegram\Bot\TelegramResponse)) #1 /home/xxxxxxxxxxxxxxxxx/public_html/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(204): Telegram\Bot\TelegramResponse->makeException() #2 /home/xxxxxxxxxxxxxx/public_html/vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(65): Telegram\Bot\TelegramResponse->decodeBody() #3 /home/xxxxxxxxxxxxxx/public_html/vendor/irazasyed/telegram-bot-sdk/src/TelegramClient.php(138): Telegram\Bot\TelegramResponse->__construct(Object(Telegram\Bot\TelegramRequest), Object(GuzzleHttp\Psr7\Response)) #4 /home/xxxxxxxxxxx/public_html/vendor/irazasyed/telegram-bot-sdk/src/TelegramClient.php(119): Telegram\Bot\TelegramClient->get in /home/xxxxxxxxxxxxxxxxx/public_html/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php on line 58

`<?php
    require '../vendor/autoload.php';
    use Telegram\Bot\Api;

$telegram = new Api('xxxxxxxxxxx');

$response = $telegram->getMe();

$botId = $response->getId();
$firstName = $response->getFirstName();
$username = $response->getUsername();
    
    echo "Bot id: ". $botId;
    
    ?>`

**Comment by Arsham-rmz** [comment]
i think your **token** isn't correct :)
