### ISSUE TITLE
Bad Request: can't parse keyboard button: KeyboardButton must be a String or an Object

### ISSUE THREAD

**Issue by maaxim-one** [irazasyed/telegram-bot-sdk#946]
Hello! I can't create a keyboard, it gives an error: Bad Request: can't parse keyboard button: KeyboardButton must be a String or an Object.

telegram-bot-sdk - 3.6
laravel - 8.83.11

```php
$keyboard = Keyboard::make()->row([
    Keyboard::button(['text' => 'asd'])
])->setResizeKeyboard(true);
```

```php
$response = TelegramCore::sendMessage([
    'chat_id' => $chatId,
    'text' => 'asd',
    'reply_markup' => $keyboard
]);
```

**Comment by colinhall17** [comment]
Hi @maksimklimenko 

Did you manage to resolve this?  Having the same issue

**Comment by alies-dev** [comment]
@maksimklimenko 
@colinhall17 
I assume you are using another composer package https://github.com/php-telegram-bot/core , this is a wrong repository to ask this question

**Comment by colinhall17** [comment]
No we are using this repository, why is this the wrong repository?

@maksimklimenko has stated the version he is using, I am also using version 3.6

**Comment by zhalil** [comment]
> Hello! I can't create a keyboard, it gives an error: Bad Request: can't parse keyboard button: KeyboardButton must be a String or an Object.
> 
> telegram-bot-sdk - 3.6 laravel - 8.83.11
> 
> ```
> $keyboard = Keyboard::make()->row([
>     Keyboard::button(['text' => 'asd'])
> ])->setResizeKeyboard(true);
> ```
> 
> ```
> $response = TelegramCore::sendMessage([
>     'chat_id' => $chatId,
>     'text' => 'asd',
>     'reply_markup' => $keyboard
> ]);
> ```

inside the "row" method, the arguments are unpacked and they are converted into an array, and you are trying to make a nested array
```
 public function row(...$buttons): self
    {
        $property = $this->isInlineKeyboard() ? 'inline_keyboard' : 'keyboard';
        $this->items[$property][] = $buttons;

        return $this;
    }
 ```
    
instead of this : 
```
$keyboard = Keyboard::make()->row([
    Keyboard::button(['text' => 'asd'])
])->setResizeKeyboard(true);
``` 
make this :
```
$keyboard = Keyboard::make()->row(
    Keyboard::button(['text' => 'btn1']), Keyboard::button(['text' => 'btn2']), Keyboard::button(['text' => 'btn3']),
)->setResizeKeyboard(true);
```
and then everything will work
