### ISSUE TITLE
WebAppInfo

### ISSUE THREAD

**Issue by APTEMOH** [irazasyed/telegram-bot-sdk#947]
Hi!

WebAppInfo worked?

Thanks!

**Comment by 3dreplicator** [comment]
I support the question!?
Make a support WebAppInfo Telegram API 6.1

**Comment by andymitrich** [comment]
Hi, guys, do you have plans to support WebAppInfo in this version of API?

**Comment by irazasyed** [comment]
PRs are most welcome.

**Comment by nevstas** [comment]
Any updates? 
How to create web app telegram bot using the SDK?
