### ISSUE TITLE
Edit telegram message

### ISSUE THREAD

**Issue by vasiliyaltunin** [irazasyed/telegram-bot-sdk#948]
Can anyone share example how edit message in v3?

I try to use:

`                $this->editMessageText([
                'chat_id' => $chatid,
                'message_id' =>$msgid,
                'text' => MenuMessages::$aboutmain_txt, 'parse_mode' => 'html', 'reply_markup' => $keyboard]);
`
but i get error:

Method [editMessageText] does not exist

**Comment by hatimalam** [comment]
Hi @vasiliyaltunin,

You can use `Telegram::editMessageText([ 'chat_id' => $chatid, 'message_id' =>$msgid, 'text' => MenuMessages::$aboutmain_txt, 'parse_mode' => 'html', 'reply_markup' => $keyboard]);`

Note: you can only edit the message sent by bot.

**Comment by vasiliyaltunin** [comment]
Thx
