### ISSUE TITLE
[TODO] Implement inline API functionality

### ISSUE THREAD

**Issue by ihoru** [irazasyed/telegram-bot-sdk#95]
Docs:
https://telegram.org/blog/inline-bots
https://core.telegram.org/bots/inline
https://core.telegram.org/bots/api#inline-mode

I'm going to implement this feature nearest days and send PR asap.

**Comment by irazasyed** [comment]
:+1:

**Comment by ihoru** [comment]
TODO:
1. Tests
2. Docs
3. Base class InlineQueryResult with children: InlineQueryResultArticle, InlineQueryResultPhoto, InlineQueryResultGif, InlineQueryResultMpeg4Gif, InlineQueryResultVideo

**Comment by ihoru** [comment]
4. Tests for ChosenInlineResult https://github.com/irazasyed/telegram-bot-sdk/pull/106
