### ISSUE TITLE
PHP 8.1 Laravel update?

### ISSUE THREAD

**Issue by gvoider** [irazasyed/telegram-bot-sdk#950]
Using dev-master in my project, which includes "illuminate/support" currently of version "7.30.6". As I understand, it's from Laravel 7, which is not fully compatible with PHP 8.1. Partly, I've got the next error messages on sendMessage:
PHP Fatal error:  During inheritance of ArrayAccess: Uncaught Exception: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice.

Is it possible to update the requirements for the compatibility? It seems that this is fixed in later Laravel versions.

**Comment by alies-dev** [comment]
latest versions work perfectly on PHP 8.1
