### ISSUE TITLE
Octane && Swoole

### ISSUE THREAD

**Issue by BilagoNet** [irazasyed/telegram-bot-sdk#957]
Sdk not working in started laravel with octane, but working start with serve

Code:
```
<?php

namespace App\Http\Controllers;

use Exception;
use Illuminate\Http\Request;
use Telegram;

class TelegramController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        try {
            $updates = Telegram::getWebhookUpdates();
            $message = $updates->getMessage();
            $chat_id = $message->getChat()->getId();
            $text = $message->getText();
            $data = [
                'chat_id' => $chat_id,
                'text' => $text,
            ];
            Telegram::sendMessage($data);
        } catch (Exception $e) {
            error_log($e->getMessage());
        }
    }
}

```
Error: `Method Illuminate\Support\Collection::getChat does not exist.`
tg bot sdk version: 3.6

**Comment by alies-dev** [comment]
@BilagoNet 
In your case, `$updates` is a list of `Update` instances. This is pretty common problem, I think it's better to implement 2 separate public methods: one will return a single `Update` (to listen webhooks), second - a list of `Update` (for polling). WDYT, @irazasyed ?

**Comment by irazasyed** [comment]
@lptn [`getWebhookUpdate`](https://github.com/irazasyed/telegram-bot-sdk/blob/develop/src/Methods/Update.php#L159-L170) already returns just one update instance (not the `s` at the end). There's also `getUpdates` method for polling.

**Comment by alies-dev** [comment]
@BilagoNet

this issue was solved by https://github.com/irazasyed/telegram-bot-sdk/pull/908 (SDK v3.5), you can pass `$request` instance:
```diff
- Telegram::getWebhookUpdates();
+ Telegram::getWebhookUpdate(true, $request);
```
PS: probably you need to convert Laravel Request into `\Psr\Http\Message\RequestInterface` instance or even better: inject request of a proper type: https://laravel.com/docs/9.x/requests#psr7-requests
