### ISSUE TITLE
Inline query

### ISSUE THREAD

**Issue by psycholyzern** [irazasyed/telegram-bot-sdk#98]
Hi. Firstly, thank you for this awesome project.

I can't make inline query works.

```
$answerInlineQuery = $telegram->answerInlineQuery([
      'inline_query_id' => $r->inline_query->id, 
      'results' => ["test"],
      'cache_time' => 0,
      'is_personal' => false,
      'next_offset' => ''
    ]);
```

I think, I write it right. It never respond to inline query.

**Comment by ihoru** [comment]
Results array is wrong formatted. There should be an array of results like
this: https://core.telegram.org/bots/api#inlinequeryresultarticle

**Comment by psycholyzern** [comment]
Sorry but there is no example in the link you gave me. Can you write an example how result should looks like? I dont know how "JSON serialized array" shouls looks like

**Comment by ihoru** [comment]
Here is how I was testing it:
```php
        $inline_query_id = $inlineQuery['id'];
        $cache_time = 0;
        $results = [];
        $results[] = [
            'type'         => 'article',
            'id'           => '1',
            'title'        => 'title',
            'message_text' => 'message_text',
            'description'  => 'description',
        ];
        $params = compact('inline_query_id', 'results', 'cache_time');
        $rs = Telegram::answerInlineQuery($params);
```

**Comment by psycholyzern** [comment]
Hi. Thanks for that example. I misunderstood about the result. I didnt use InlineQueryResult, instead I wrote the plain text directly in the result parameter. Thank you, problem solved :)

**Comment by nerestaren** [comment]
Hi,

I'm not able to work with inline queries, regardless of your comment @ihoru. Has anything changed?

        $inlineQuery = $update->getInlineQuery();
        
        $query = $inlineQuery->getQuery();
                
        $results = array();
        $results[] = array(
            'type' => 'article',
            'id' => '0',
            'title' => 'Query: ' . $query,
            //'input_message_content' => array(
                'message_text' => 'Text',
            //),
            'description' => 'description',
        );
        
        $params = array(
            'inline_query_id' => $inlineQuery->getId(),
            'results' => $results,
        );
                
        $result = $telegram->answerInlineQuery();

Thanks for your time.

**Comment by ihoru** [comment]
@nerestaren what do you get in result?

**Comment by nerestaren** [comment]
Ooops, sorry, forgot to tell.

`false`.

**Comment by ihoru** [comment]
@nerestaren it should return TelegramResponse object not bool (there is an error here: @return bool in sources).
Please debug answer into the library.

**Comment by nerestaren** [comment]
Well, this was my fault.

I was using v2.0, and answerInlineQuery() does not exist there.

Now I'm getting `Bad Request: QUERY_ID_INVALID`.

Sorry for the mess.

**Comment by igorshinal** [comment]
$inlineQuery = $update->getInlineQuery() returned {query:" "} why?

**Comment by ehs4nm** [comment]
Hi guys.
I am useing the same library v3.3. After user type inline query, nothing happens. i get a 1 response from telegram. but user cant see the list (results) in client app.
my code:

    `public function Webhook()
    {
        $update = Telegram::commandsHandler(true);
        $inlineQuery   = $update->getInlineQuery();
        $inlineQueryId = $inlineQuery->getId();

        $query = $inlineQuery->getQuery();

        $results = array();

        $results[] = array(
            'type'         => 'article',
            'id'           => 12,
            'title'        =>  'test'
        );

        return Telegram::answerInlineQuery([
            'inline_query_id' => $inlineQueryId,
            'cache_time'      => 0,
            'results'         => $results
        ]);
    }`
