### ISSUE TITLE
Custom "http_client_handler" (Error)

### ISSUE THREAD

**Issue by the-alex-mark** [irazasyed/telegram-bot-sdk#988]
- `irazasyed/telegram-bot-sdk` version: `3.4`
- PHP Version: `7.3`
- Laravel Version: `8.75`

## Description:
Использую пользовательский класс клиента `GuzzleHttpClient`, к примеру логирую в нём запросы и ответы к API Telegram.  
Получаю ошибку при кешировании конфигурации, т.к. нельзя использовать замыкания или инициализированные экземпляры классов:
```
In ConfigCacheCommand.php line 71:
Your configuration files are not serializable.
```
```
In config.php line 719:
Call to undefined method ...\GuzzleHttpClient::__set_state()
```

## Steps To Reproduce:
```php
// in "config/telegram.php"

return [

    /*
    |--------------------------------------------------------------------------
    | HTTP Client Handler [Optional]
    |--------------------------------------------------------------------------
    |
    | If you'd like to use a custom HTTP Client Handler.
    | Should be an instance of \Telegram\Bot\HttpClients\HttpClientInterface
    |
    | Default: GuzzlePHP
    |
    */

    'http_client_handler' => new GuzzleHttpClient()
];
```

Прошу помочь мне разобраться как правильно это делать или обратить внимание, если это ошибка. Просмотрев исходный код SDK наблюдаю, что из конфигурации ожидается именно инициализированный экземпляр, что уже не неверно.

**Comment by alies-dev** [comment]
@the-alex-mark 

## preamble
this is english speaking repository. For all questions in Russian please use local communities (импортозамещайтесь 😀).

## Answer

I've checked this case - it's not possible to solve your issue using [cached] config, but you can directly call `setHttpClientHandler()` in `\Telegram\Bot\Api` instance. E.g. you can define it in your Service Provider. Something like:
```php
$this->app->bind(Api::class, static function ($app) {
    $api = $app[BotsManager::class]->bot();
    $api->setHttpClientHandler(new YourHttpClient());
    return $api;
});
```
(I haven't tested this code).


>Использую пользовательский класс клиента GuzzleHttpClient, к примеру логирую в нём запросы и ответы к API Telegram.

Note, for income webhooks you can listen `\Telegram\Bot\Events\UpdateWasReceived` events (this is not Laravel event -- these events uses `league/event` v2).

PS: Привіт з України. Будь ласка, пішу на-англійську як тут прынята. #StandWithUkraine

**Comment by alies-dev** [comment]
BTW: there are a lot bugs fixed in recent versions, it's highly recommended to update to the latest version of the package
