### ISSUE TITLE
TypeError: Telegram\Bot\Api::createChatInviteLink(): Return value must be of type Telegram\Bot\Methods\ChatInviteLink, array returned

### ISSUE THREAD

**Issue by phpmac** [irazasyed/telegram-bot-sdk#989]
- `irazasyed/telegram-bot-sdk` version: #.#.#
- PHP Version: 7.2
- Laravel Version: 9

```
Telegram::createChatInviteLink(compact('chat_id'));

```

## Description:
When I create an invitation link, there is a code error. It is normal after deletion!

### Stacktrace:
```
```

**Comment by alies-dev** [comment]
this one is fixed in [3.9](https://github.com/irazasyed/telegram-bot-sdk/releases/tag/v3.9)
