### ISSUE TITLE
Telegram\Bot\Commands\CommandBus::execute(): Argument #3 ($entity) must be of type array, string given

### ISSUE THREAD

**Issue by Carla1315** [irazasyed/telegram-bot-sdk#994]
- `irazasyed/telegram-bot-sdk` version: 3.4.1
- PHP Version: 8.1.8
- Laravel Version: 8.0 (optional)

## Description:
I tried to update to the latest version but it doesn't work either.
Maybe I am sending the data wrong, so can you please give me an example of the data format that I should pass.
### Stacktrace:
```
```

**Comment by alies-dev** [comment]
@Carla1315 
can you please provide:
 - stacktrace
 - code example how you register commands
